// DEMO ONLY — all rights, party, contract, document, dispute, and clearance data
// is fabricated for workflow demonstration. It does not confirm legal ownership.

export const RIGHTS_STORAGE_KEY = "beatmondo-rights-database-v1";
export const SELECTED_RIGHTS_KEY = "beatmondo-selected-rights-record";

export const RIGHTS_STATUSES = [
  "Unreviewed",
  "Draft",
  "Documents Requested",
  "Under Review",
  "Partially Verified",
  "Master Verified",
  "Publishing Verified",
  "Fully Verified",
  "Conditional",
  "Restricted",
  "Disputed",
  "Not Licensable",
  "Review Expired",
  "Archived",
];

export const ELIGIBILITY_STATUSES = [
  "Eligible",
  "Eligible with Restrictions",
  "Conditional",
  "Manual Review Required",
  "Not Yet Eligible",
  "Blocked",
  "Expired",
  "Not Applicable",
];

export const RIGHTS_STATUS_CONTENT = {
  Unreviewed: {
    description: "Rights information has not entered human review.",
    buyerVisible: false,
    licensing: false,
    delivery: false,
    next: "Create draft record",
  },
  Draft: {
    description: "Rights data is being assembled and is not approved.",
    buyerVisible: false,
    licensing: false,
    delivery: false,
    next: "Complete required data",
  },
  "Documents Requested": {
    description: "Evidence or ownership information is still required.",
    buyerVisible: true,
    licensing: false,
    delivery: false,
    next: "Collect requested documents",
  },
  "Under Review": {
    description: "A reviewer is assessing rights evidence.",
    buyerVisible: true,
    licensing: false,
    delivery: false,
    next: "Complete review checklist",
  },
  "Partially Verified": {
    description: "One or more rights domains remain incomplete.",
    buyerVisible: true,
    licensing: "conditional",
    delivery: false,
    next: "Resolve missing domains",
  },
  "Master Verified": {
    description: "Master rights are verified; publishing remains separate.",
    buyerVisible: true,
    licensing: "conditional",
    delivery: false,
    next: "Complete publishing review",
  },
  "Publishing Verified": {
    description:
      "Publishing rights are verified; master rights remain separate.",
    buyerVisible: true,
    licensing: "conditional",
    delivery: false,
    next: "Complete master review",
  },
  "Fully Verified": {
    description:
      "Required rights domains and authority were human-reviewed for the recorded scope.",
    buyerVisible: true,
    licensing: true,
    delivery: true,
    next: "Monitor review dates",
  },
  Conditional: {
    description:
      "Licensing may proceed only with recorded approvals or scope limits.",
    buyerVisible: true,
    licensing: "conditional",
    delivery: "conditional",
    next: "Request required approvals",
  },
  Restricted: {
    description:
      "A blocking rights restriction prevents ordinary licensing or delivery.",
    buyerVisible: true,
    licensing: false,
    delivery: false,
    next: "Resolve restriction",
  },
  Disputed: {
    description: "An active ownership claim is under restricted legal review.",
    buyerVisible: true,
    licensing: false,
    delivery: false,
    next: "Legal review",
  },
  "Not Licensable": {
    description: "The track is not available for new licensing.",
    buyerVisible: true,
    licensing: false,
    delivery: false,
    next: "No buyer action",
  },
  "Review Expired": {
    description:
      "The prior rights review has expired; new licensing needs reverification.",
    buyerVisible: true,
    licensing: false,
    delivery: false,
    next: "Trigger reverification",
  },
  Archived: {
    description: "The record is retained historically and is not current.",
    buyerVisible: false,
    licensing: false,
    delivery: false,
    next: "View current version",
  },
};

export const RIGHTS_REVIEWERS = [
  {
    id: "reviewer-amelia",
    name: "Amelia Grant",
    role: "Rights and Compliance",
  },
  { id: "reviewer-jordan", name: "Jordan Lee", role: "Catalog Operations" },
  {
    id: "reviewer-maya",
    name: "Maya Thompson",
    role: "Buyer and Licensing Review",
  },
  { id: "user-preston", name: "Preston Repenning", role: "Senior Approver" },
];

export const RIGHTS_CHECKLIST = [
  "Track identity confirmed",
  "Master owner identified",
  "Master shares total 100%",
  "Master agreement reviewed",
  "Writers identified",
  "Writer shares total 100%",
  "Publishers identified",
  "Publisher shares complete",
  "PRO details reviewed",
  "ISRC confirmed",
  "ISWC reviewed where available",
  "Samples declared",
  "Sample clearance reviewed",
  "Contributor releases reviewed",
  "Territory confirmed",
  "Restrictions recorded",
  "Licensing authority confirmed",
  "Supporting documents accepted",
  "Disputes resolved",
  "Public summary approved",
  "Final eligibility decision complete",
];

export const RIGHTS_STATUS_TRANSITIONS = {
  Unreviewed: ["Draft"],
  Draft: ["Documents Requested", "Under Review"],
  "Documents Requested": ["Under Review"],
  "Under Review": [
    "Partially Verified",
    "Master Verified",
    "Publishing Verified",
    "Restricted",
    "Disputed",
  ],
  "Master Verified": [
    "Fully Verified",
    "Partially Verified",
    "Restricted",
    "Disputed",
  ],
  "Publishing Verified": [
    "Fully Verified",
    "Partially Verified",
    "Restricted",
    "Disputed",
  ],
  "Partially Verified": [
    "Fully Verified",
    "Documents Requested",
    "Restricted",
    "Disputed",
  ],
  "Fully Verified": [
    "Review Expired",
    "Disputed",
    "Restricted",
    "Under Review",
  ],
  Restricted: ["Under Review", "Disputed"],
  Disputed: ["Under Review", "Restricted"],
  "Review Expired": ["Under Review"],
  "Not Licensable": ["Under Review", "Archived"],
};

export const RIGHTS_PARTIES = [
  {
    id: "party-lennox",
    legalName: "Lennox Music LLC",
    displayName: "Lennox Music",
    partyType: "Master Owner",
    contactEmail: "rights@lennox.example",
    country: "United States",
    pro: null,
    ipiCae: null,
    verificationStatus: "Verified",
    active: true,
    documents: ["doc-golden-master"],
    internalNotes: "Prototype party record.",
  },
  {
    id: "party-lennox-writer",
    legalName: "Lennox Avery",
    displayName: "Lennox",
    partyType: "Writer",
    contactEmail: "private@lennox.example",
    country: "United States",
    pro: "ASCAP",
    ipiCae: "00123456789",
    verificationStatus: "Verified",
    active: true,
    documents: ["doc-golden-split"],
    internalNotes: "Contact hidden from buyers.",
  },
  {
    id: "party-arco-label",
    legalName: "Arco North Recordings Ltd",
    displayName: "Arco North Recordings",
    partyType: "Record Label",
    contactEmail: "legal@arconorth.example",
    country: "Canada",
    verificationStatus: "Verified",
    active: true,
    documents: ["doc-paper-master"],
    internalNotes: "North American mandate only.",
  },
  {
    id: "party-arco-writer",
    legalName: "Elias North",
    displayName: "Elias North",
    partyType: "Composer",
    contactEmail: "rights@arconorth.example",
    country: "Canada",
    pro: "SOCAN",
    ipiCae: "00234567890",
    verificationStatus: "Under Review",
    active: true,
    documents: [],
    internalNotes: "Publisher confirmation pending.",
  },
  {
    id: "party-vespera",
    legalName: "Vespera Archive Trust",
    displayName: "Vespera Archive",
    partyType: "Estate",
    contactEmail: "trust@vespera.example",
    country: "United Kingdom",
    verificationStatus: "Verified",
    active: true,
    documents: ["doc-midnight-master"],
    internalNotes: "Trust contact is legal restricted.",
  },
  {
    id: "party-hollow",
    legalName: "Hollow Skies Music Inc",
    displayName: "Hollow Skies Music",
    partyType: "Publisher",
    contactEmail: "publishing@hollowskies.example",
    country: "United States",
    pro: "BMI",
    ipiCae: "00345678901",
    verificationStatus: "Verified",
    active: true,
    documents: ["doc-glass-publishing"],
    internalNotes: "Publishing record verified.",
  },
  {
    id: "party-unknown",
    legalName: "Unidentified Contributor",
    displayName: "Ownership confirmation pending",
    partyType: "Other",
    contactEmail: "",
    country: "",
    verificationStatus: "Unverified",
    active: true,
    documents: [],
    internalNotes: "Do not expose identity speculation.",
  },
];

const document = (
  id,
  name,
  category,
  trackId,
  status = "Accepted",
  confidentiality = "Internal",
  extra = {},
) => ({
  id,
  fileName: name,
  fileType: "application/pdf",
  fileSize: "1.2 MB",
  category,
  relatedTrackId: trackId,
  relatedPartyId: null,
  version: 1,
  uploadedBy: "Catalog Operations",
  uploadedAt: "2026-06-18T10:00:00.000Z",
  reviewStatus: status,
  effectiveDate: "2026-06-01",
  expiryDate: null,
  confidentiality,
  mockStorageReference: `mock://rights/${id}`,
  notes: "Simulated document metadata only.",
  ...extra,
});

export const RIGHTS_DOCUMENTS = [
  document(
    "doc-golden-master",
    "golden-hours-master-agreement.pdf",
    "Master ownership agreement",
    1,
  ),
  document(
    "doc-golden-split",
    "golden-hours-split-sheet.pdf",
    "Split sheet",
    1,
  ),
  document(
    "doc-golden-publishing",
    "golden-hours-publishing-mandate.pdf",
    "Publishing agreement",
    1,
    "Accepted",
    "Legal Restricted",
  ),
  document(
    "doc-paper-master",
    "paper-planes-master-mandate.pdf",
    "Licensing mandate",
    2,
  ),
  document(
    "doc-paper-publisher",
    "paper-planes-publisher-confirmation.pdf",
    "Publishing agreement",
    2,
    "Replacement Requested",
  ),
  document(
    "doc-static-master",
    "all-that-remains-master-agreement.pdf",
    "Master ownership agreement",
    4,
  ),
  document(
    "doc-static-split",
    "all-that-remains-split-sheet.pdf",
    "Split sheet",
    4,
    "Replacement Requested",
  ),
  document(
    "doc-midnight-master",
    "midnight-transit-master-chain.pdf",
    "Master ownership agreement",
    3,
  ),
  document(
    "doc-midnight-sample",
    "midnight-transit-sample-request.pdf",
    "Sample clearance",
    3,
    "Pending Review",
    "Legal Restricted",
  ),
  document(
    "doc-glass-publishing",
    "glass-cathedral-publishing.pdf",
    "Publishing agreement",
    10,
  ),
  document(
    "doc-glass-dispute",
    "glass-cathedral-producer-claim.pdf",
    "Dispute evidence",
    10,
    "Pending Review",
    "Super Admin Only",
  ),
  document(
    "doc-harbor-old",
    "harbor-light-rights-review-2025.pdf",
    "Licensing mandate",
    8,
    "Expired",
  ),
];

const partyRef = (
  partyId,
  partyName,
  partyType,
  ownershipPercentage,
  evidenceDocumentIds = [],
  extra = {},
) => ({
  partyId,
  partyName,
  partyType,
  ownershipPercentage,
  controlledByBeatmondo: true,
  territory: "Worldwide",
  effectiveFrom: "2026-01-01",
  effectiveUntil: null,
  evidenceDocumentIds,
  approvalRequired: false,
  notes: "",
  ...extra,
});
const writer = (
  partyId,
  name,
  share,
  pro,
  ipiCae,
  publisherIds = [],
  extra = {},
) => ({
  partyId,
  name,
  ipiCae,
  pro,
  writerShare: share,
  publisherIds,
  territory: "Worldwide",
  evidenceDocumentIds: [],
  ...extra,
});
const publisher = (partyId, name, share, pro, ipiCae, extra = {}) => ({
  partyId,
  name,
  publisherShare: share,
  pro,
  ipiCae,
  administrator: "",
  controlledByBeatmondo: true,
  territory: "Worldwide",
  approvalRequired: false,
  evidenceDocumentIds: [],
  ...extra,
});
const fullChecklist = () =>
  Object.fromEntries(RIGHTS_CHECKLIST.map((item) => [item, true]));
const activity = (
  id,
  trackId,
  action,
  description,
  timestamp,
  visibility = "Internal",
) => ({
  id,
  actor: "Amelia Grant",
  trackId,
  rightsRecordId: `rights-${trackId}`,
  version: 1,
  timestamp,
  action,
  description,
  before: null,
  after: null,
  reason: "Scheduled rights review",
  source: "Rights Database",
  visibility,
});

const baseRecord = {
  version: 1,
  samples: [],
  contributors: [],
  contracts: [],
  restrictions: [],
  approvalRequirements: [],
  disputes: [],
  territories: { included: ["Worldwide"], excluded: [], conflicts: [] },
  declarations: {
    noUndeclaredSamples: true,
    informationAccurate: true,
    authorityConfirmed: true,
  },
  internalNotes: [],
  linkedLicences: [],
  createdAt: "2026-06-01T09:00:00.000Z",
  createdBy: "Catalog Operations",
  updatedAt: "2026-06-20T12:00:00.000Z",
  updatedBy: "Amelia Grant",
  effectiveFrom: "2026-06-20T12:00:00.000Z",
  effectiveUntil: null,
  supersededBy: null,
};

export const DEFAULT_RIGHTS_RECORDS = [
  {
    ...baseRecord,
    id: "rights-1",
    trackId: 1,
    trackTitle: "Golden Hours",
    scenarioLabel: "Fully verified and licensable",
    artist: "Lennox",
    isrc: "BM-GH-2026-001",
    status: "Fully Verified",
    licensingEligibility: "Eligible",
    assignedReviewerId: "reviewer-amelia",
    priority: "Standard",
    masterRights: {
      status: "Verified",
      owners: [
        partyRef("party-lennox", "Lennox Music LLC", "Master Owner", 100, [
          "doc-golden-master",
        ]),
      ],
      totalOwnership: 100,
      exclusiveRepresentative: "beatmondo",
      licensingAuthority: "Worldwide synchronization mandate",
      masterUseAllowed: true,
      restrictions: [],
      verifiedAt: "2026-06-20",
      verifiedBy: "Amelia Grant",
    },
    compositionRights: {
      status: "Verified",
      workTitle: "Golden Hours",
      alternateTitles: [],
      iswc: "T-345.678.901-2",
      writers: [
        writer(
          "party-lennox-writer",
          "Lennox Avery",
          100,
          "ASCAP",
          "00123456789",
          ["party-lennox-publishing"],
          { evidenceDocumentIds: ["doc-golden-split"] },
        ),
      ],
      writerShareTotal: 100,
      controlledShare: 100,
      uncontrolledShare: 0,
      restrictions: [],
      verifiedAt: "2026-06-20",
      verifiedBy: "Amelia Grant",
    },
    publishingRights: {
      status: "Verified",
      publishers: [
        publisher(
          "party-lennox",
          "Lennox Music LLC",
          100,
          "ASCAP",
          "00456789012",
          { evidenceDocumentIds: ["doc-golden-publishing"] },
        ),
      ],
      publisherShareTotal: 100,
      controlledShare: 100,
      uncontrolledShare: 0,
      synchronizationAuthority: "Direct",
      restrictions: [],
      verifiedAt: "2026-06-20",
      verifiedBy: "Amelia Grant",
    },
    contributors: [
      {
        id: "contrib-gh-1",
        name: "Lennox",
        role: "Featured Artist",
        contractStatus: "Accepted",
        releaseStatus: "Accepted",
        approvalRequired: false,
        revenueParticipation: "Artist agreement",
        territory: "Worldwide",
        evidenceDocumentIds: ["doc-golden-master"],
        notes: "Participation is not treated as ownership.",
      },
    ],
    contracts: [
      {
        id: "contract-gh-1",
        type: "Master representation agreement",
        parties: ["Lennox Music LLC", "beatmondo"],
        effectiveDate: "2026-06-01",
        expiryDate: "2028-06-01",
        territory: "Worldwide",
        exclusivity: "Non-exclusive",
        licensingAuthority: true,
        sublicensingAuthority: true,
        approvalRequirements: [],
        revenueSplit: "Confidential",
        renewalTerms: "Annual review",
        restrictions: [],
        documentId: "doc-golden-master",
        verificationState: "Verified",
      },
    ],
    documents: [
      "doc-golden-master",
      "doc-golden-split",
      "doc-golden-publishing",
    ],
    review: {
      workflowStage: "Approved",
      checklist: fullChecklist(),
      lastReviewedAt: "2026-06-20",
      nextReviewAt: "2027-06-20",
      expiryStatus: "Current",
      dueDate: null,
      collaborators: [],
    },
    completeness: {
      percentage: 100,
      missingSections: [],
      blockingIssues: [],
      warnings: [],
    },
    publicSummary: {
      approved: true,
      status: "Rights Verified",
      territory: "Worldwide",
      wording:
        "Master and publishing rights have been human-reviewed for worldwide licensing.",
    },
    buyerSummary: {
      status: "Available for licensing",
      master: "Cleared",
      publishing: "Cleared",
      approvals: "Not required",
      stems: "Available subject to project approval",
      delivery: "Master, instrumental, and stems may be approved",
    },
    internalNotes: [
      {
        id: "note-gh-1",
        author: "Amelia Grant",
        createdAt: "2026-06-20",
        visibility: "Internal",
        content:
          "Evidence reviewed for the recorded scope; not a legal guarantee.",
      },
    ],
    versions: [
      {
        version: 1,
        effectiveDate: "2026-06-20",
        createdBy: "Amelia Grant",
        reason: "Initial verification",
        summary: "Master and publishing verified.",
        before: null,
        after: { status: "Fully Verified", eligibility: "Eligible" },
        linkedDocuments: ["doc-golden-master", "doc-golden-split"],
        current: true,
      },
    ],
    activity: [
      activity(
        "rights-act-gh-1",
        1,
        "Track fully verified",
        "Master, publishing, territory, and authority review completed.",
        "2026-06-20T12:00:00.000Z",
      ),
    ],
  },
  {
    ...baseRecord,
    id: "rights-2",
    trackId: 2,
    trackTitle: "Paper Planes",
    scenarioLabel: "Partially verified",
    artist: "Arco North",
    isrc: "BM-PP-2026-002",
    status: "Partially Verified",
    licensingEligibility: "Conditional",
    assignedReviewerId: "reviewer-jordan",
    priority: "High",
    masterRights: {
      status: "Verified",
      owners: [
        partyRef(
          "party-arco-label",
          "Arco North Recordings Ltd",
          "Record Label",
          100,
          ["doc-paper-master"],
          { territory: "United States and Canada" },
        ),
      ],
      totalOwnership: 100,
      exclusiveRepresentative: "beatmondo",
      licensingAuthority: "United States and Canada only",
      masterUseAllowed: true,
      restrictions: ["United States and Canada only"],
      verifiedAt: "2026-07-10",
      verifiedBy: "Jordan Lee",
    },
    compositionRights: {
      status: "Under Review",
      workTitle: "Paper Planes",
      alternateTitles: [],
      iswc: null,
      writers: [
        writer(
          "party-arco-writer",
          "Elias North",
          100,
          "SOCAN",
          "",
          ["party-arco-publisher"],
          { territory: "United States and Canada" },
        ),
      ],
      writerShareTotal: 100,
      controlledShare: 75,
      uncontrolledShare: 25,
      restrictions: [],
      verifiedAt: null,
      verifiedBy: null,
    },
    publishingRights: {
      status: "Under Review",
      publishers: [
        publisher(
          "party-arco-publisher",
          "North Paper Publishing",
          100,
          "SOCAN",
          "",
          {
            territory: "United States and Canada",
            approvalRequired: true,
            evidenceDocumentIds: ["doc-paper-publisher"],
          },
        ),
      ],
      publisherShareTotal: 100,
      controlledShare: 75,
      uncontrolledShare: 25,
      synchronizationAuthority: "Publisher approval required",
      restrictions: ["Publisher confirmation pending"],
      verifiedAt: null,
      verifiedBy: null,
    },
    approvalRequirements: [
      {
        id: "approval-pp-1",
        type: "Publisher approval",
        required: true,
        approver: "North Paper Publishing",
        triggerConditions: "Every synchronization request",
        territory: "United States and Canada",
        usageType: "All media",
        responseStatus: "Not Requested",
        dueDate: null,
        notes: "Buyer sees approval requirement, not contact details.",
      },
    ],
    restrictions: [
      {
        id: "restriction-pp-1",
        type: "Territory Restriction",
        description:
          "Current control is limited to the United States and Canada.",
        appliesTo: "Licensing",
        territory: "United States and Canada",
        effectiveFrom: "2026-07-10",
        effectiveUntil: null,
        approvalPath: "Manual publisher approval",
        publicVisibility: "Buyer Visible",
        buyerWording:
          "Available in the United States and Canada; publisher approval is required.",
        internalRationale: "Publisher mandate evidence remains incomplete.",
      },
    ],
    documents: ["doc-paper-master", "doc-paper-publisher"],
    review: {
      workflowStage: "Publishing Review",
      checklist: {
        ...fullChecklist(),
        "Publishers identified": false,
        "Publisher shares complete": false,
        "PRO details reviewed": false,
        "Supporting documents accepted": false,
        "Final eligibility decision complete": false,
      },
      lastReviewedAt: "2026-07-10",
      nextReviewAt: null,
      expiryStatus: "Current",
      dueDate: "2026-07-24",
      collaborators: [],
    },
    completeness: {
      percentage: 82,
      missingSections: ["Publisher confirmation", "Writer IPI or CAE", "ISWC"],
      blockingIssues: [],
      warnings: ["Publisher IPI number missing", "Stems not cleared"],
    },
    publicSummary: {
      approved: true,
      status: "Conditionally Available",
      territory: "United States and Canada",
      wording:
        "Available in the United States and Canada. Publisher approval is required before final clearance.",
    },
    buyerSummary: {
      status: "Conditional",
      master: "Cleared",
      publishing: "Under review",
      approvals: "Publisher approval required",
      stems: "Not available",
      delivery: "Master may be approved after manual review",
    },
    internalNotes: [
      {
        id: "note-pp-1",
        author: "Jordan Lee",
        createdAt: "2026-07-10",
        visibility: "Internal",
        content:
          "Publisher confirmation and writer identifier remain outstanding.",
      },
    ],
    versions: [
      {
        version: 1,
        effectiveDate: "2026-07-10",
        createdBy: "Jordan Lee",
        reason: "Initial partial review",
        summary: "Master verified; publishing conditional.",
        before: null,
        after: { status: "Partially Verified", eligibility: "Conditional" },
        linkedDocuments: ["doc-paper-master"],
        current: true,
      },
    ],
    activity: [
      activity(
        "rights-act-pp-1",
        2,
        "Publishing evidence requested",
        "Publisher confirmation and writer identifier requested.",
        "2026-07-10T10:00:00.000Z",
      ),
    ],
  },
  {
    ...baseRecord,
    id: "rights-4",
    trackId: 4,
    trackTitle: "All That Remains",
    scenarioLabel: "Ownership split incomplete",
    artist: "Hollow Skies",
    isrc: "BM-AR-2026-004",
    status: "Documents Requested",
    licensingEligibility: "Not Yet Eligible",
    assignedReviewerId: "reviewer-amelia",
    priority: "Urgent",
    masterRights: {
      status: "Verified",
      owners: [
        partyRef(
          "party-hollow",
          "Hollow Skies Music Inc",
          "Master Owner",
          100,
          ["doc-static-master"],
        ),
      ],
      totalOwnership: 100,
      exclusiveRepresentative: "beatmondo",
      licensingAuthority: "Pending complete composition",
      masterUseAllowed: false,
      restrictions: [],
      verifiedAt: "2026-07-02",
      verifiedBy: "Amelia Grant",
    },
    compositionRights: {
      status: "Incomplete",
      workTitle: "All That Remains",
      alternateTitles: [],
      iswc: null,
      writers: [
        writer("party-hollow", "Rowan Vale", 50, "BMI", "00567890123", [
          "party-hollow",
        ]),
        writer(
          "party-unknown",
          "Ownership confirmation pending",
          35,
          null,
          "",
          [],
        ),
      ],
      writerShareTotal: 85,
      controlledShare: 50,
      uncontrolledShare: 35,
      restrictions: [],
      verifiedAt: null,
      verifiedBy: null,
    },
    publishingRights: {
      status: "Incomplete",
      publishers: [
        publisher(
          "party-hollow",
          "Hollow Skies Music Inc",
          50,
          "BMI",
          "00345678901",
        ),
      ],
      publisherShareTotal: 50,
      controlledShare: 50,
      uncontrolledShare: 35,
      synchronizationAuthority: "Incomplete",
      restrictions: [],
      verifiedAt: null,
      verifiedBy: null,
    },
    documents: ["doc-static-master", "doc-static-split"],
    review: {
      workflowStage: "Documents Requested",
      checklist: {
        ...fullChecklist(),
        "Writer shares total 100%": false,
        "Publisher shares complete": false,
        "Supporting documents accepted": false,
        "Final eligibility decision complete": false,
      },
      lastReviewedAt: "2026-07-03",
      nextReviewAt: null,
      expiryStatus: "Current",
      dueDate: "2026-07-22",
      collaborators: ["reviewer-jordan"],
    },
    completeness: {
      percentage: 64,
      missingSections: [
        "Remaining writer",
        "15% writer share",
        "Complete split sheet",
        "Publisher allocation",
      ],
      blockingIssues: ["Missing 15% writer share", "Split sheet not accepted"],
      warnings: ["ISWC not supplied"],
    },
    publicSummary: {
      approved: true,
      status: "Rights Review Required",
      territory: "Pending",
      wording:
        "This track is not yet available for licensing while ownership information is completed.",
    },
    buyerSummary: {
      status: "Not Yet Eligible",
      master: "Reviewed",
      publishing: "Incomplete",
      approvals: "Not available",
      stems: "Blocked",
      delivery: "Disabled",
    },
    internalNotes: [
      {
        id: "note-ar-1",
        author: "Amelia Grant",
        createdAt: "2026-07-03",
        visibility: "Internal",
        content: "Do not infer or normalize the missing 15% share.",
      },
    ],
    versions: [
      {
        version: 1,
        effectiveDate: "2026-07-03",
        createdBy: "Amelia Grant",
        reason: "Ownership gap detected",
        summary: "Writer shares total 85%.",
        before: null,
        after: {
          status: "Documents Requested",
          eligibility: "Not Yet Eligible",
        },
        linkedDocuments: ["doc-static-split"],
        current: true,
      },
    ],
    activity: [
      activity(
        "rights-act-ar-1",
        4,
        "Ownership gap detected",
        "Writer shares total 85%; 15% remains unconfirmed.",
        "2026-07-03T10:00:00.000Z",
      ),
    ],
  },
  {
    ...baseRecord,
    id: "rights-3",
    trackId: 3,
    trackTitle: "Midnight Transit",
    scenarioLabel: "Sample clearance required",
    artist: "Vespera",
    isrc: "BM-MT-2026-003",
    status: "Restricted",
    licensingEligibility: "Blocked",
    assignedReviewerId: "reviewer-amelia",
    priority: "Urgent",
    masterRights: {
      status: "Verified",
      owners: [
        partyRef("party-vespera", "Vespera Archive Trust", "Estate", 100, [
          "doc-midnight-master",
        ]),
      ],
      totalOwnership: 100,
      exclusiveRepresentative: "beatmondo",
      licensingAuthority: "Subject to sample clearance",
      masterUseAllowed: false,
      restrictions: ["No commercial licensing until sample clearance"],
      verifiedAt: "2026-06-25",
      verifiedBy: "Amelia Grant",
    },
    compositionRights: {
      status: "Verified",
      workTitle: "Midnight Transit",
      alternateTitles: [],
      iswc: "T-456.789.012-3",
      writers: [
        writer("party-vespera", "Vespera Archive", 100, "PRS", "00678901234"),
      ],
      writerShareTotal: 100,
      controlledShare: 100,
      uncontrolledShare: 0,
      restrictions: [],
      verifiedAt: "2026-06-25",
      verifiedBy: "Amelia Grant",
    },
    publishingRights: {
      status: "Verified",
      publishers: [
        publisher(
          "party-vespera",
          "Vespera Archive Trust",
          100,
          "PRS",
          "00678901234",
        ),
      ],
      publisherShareTotal: 100,
      controlledShare: 100,
      uncontrolledShare: 0,
      synchronizationAuthority: "Blocked pending sample clearance",
      restrictions: [],
      verifiedAt: "2026-06-25",
      verifiedBy: "Amelia Grant",
    },
    samples: [
      {
        id: "sample-mt-1",
        declared: true,
        type: "Master and composition sample",
        sourceTrack: "Vintage soul recording",
        sourceArtist: "Confidential third party",
        sourceMasterOwner: "Third-party label",
        sourcePublisher: "Third-party publisher",
        portionUsed: "Short vocal phrase",
        clearanceRequired: true,
        masterClearance: "Clearance Requested",
        publishingClearance: "Research Required",
        territory: "Worldwide",
        restrictions: ["No commercial licensing until both sides are cleared"],
        clearanceFee: "Confidential placeholder",
        evidenceDocumentIds: ["doc-midnight-sample"],
        status: "Clearance Requested",
        reviewerId: "reviewer-amelia",
      },
    ],
    restrictions: [
      {
        id: "restriction-mt-1",
        type: "No Advertising",
        description:
          "No commercial licensing while sample clearance is incomplete.",
        appliesTo: "All commercial licensing and delivery",
        territory: "Worldwide",
        effectiveFrom: "2026-06-25",
        effectiveUntil: null,
        approvalPath: "Sample-owner and publisher clearance",
        publicVisibility: "Buyer Visible",
        buyerWording:
          "Manual rights review is required. Commercial licensing and secure delivery are currently unavailable.",
        internalRationale:
          "Sample source identities and negotiations are confidential.",
      },
    ],
    approvalRequirements: [
      {
        id: "approval-mt-1",
        type: "Sample-owner approval",
        required: true,
        approver: "Confidential third party",
        triggerConditions: "All commercial use",
        territory: "Worldwide",
        usageType: "All media",
        responseStatus: "Pending",
        dueDate: null,
        notes: "Legal restricted.",
      },
    ],
    documents: ["doc-midnight-master", "doc-midnight-sample"],
    review: {
      workflowStage: "Sample Review",
      checklist: {
        ...fullChecklist(),
        "Sample clearance reviewed": false,
        "Supporting documents accepted": false,
        "Final eligibility decision complete": false,
      },
      lastReviewedAt: "2026-06-25",
      nextReviewAt: null,
      expiryStatus: "Current",
      dueDate: "2026-07-30",
      collaborators: ["user-preston"],
    },
    completeness: {
      percentage: 86,
      missingSections: [
        "Sample master clearance",
        "Sample publishing clearance",
      ],
      blockingIssues: ["Sample clearance incomplete"],
      warnings: [],
    },
    publicSummary: {
      approved: true,
      status: "Manual Rights Review",
      territory: "Worldwide",
      wording:
        "Commercial licensing and secure delivery are unavailable while a third-party clearance is reviewed.",
    },
    buyerSummary: {
      status: "Restricted",
      master: "Not deliverable",
      publishing: "Reviewed",
      approvals: "Third-party approval required",
      stems: "Blocked",
      delivery: "Disabled",
    },
    internalNotes: [
      {
        id: "note-mt-1",
        author: "Amelia Grant",
        createdAt: "2026-06-25",
        visibility: "Legal Restricted",
        content:
          "Confidential sample-source negotiation details are not buyer visible.",
      },
    ],
    versions: [
      {
        version: 1,
        effectiveDate: "2026-06-25",
        createdBy: "Amelia Grant",
        reason: "Sample declared",
        summary: "Licensing blocked pending third-party sample clearance.",
        before: null,
        after: { status: "Restricted", eligibility: "Blocked" },
        linkedDocuments: ["doc-midnight-sample"],
        current: true,
      },
    ],
    activity: [
      activity(
        "rights-act-mt-1",
        3,
        "Sample clearance required",
        "Commercial licensing and delivery blocked.",
        "2026-06-25T10:00:00.000Z",
        "Legal Restricted",
      ),
    ],
  },
  {
    ...baseRecord,
    id: "rights-10",
    trackId: 10,
    trackTitle: "Glass Cathedral",
    scenarioLabel: "Disputed ownership",
    artist: "Hollow Skies",
    isrc: "BM-GC-2026-010",
    status: "Disputed",
    licensingEligibility: "Blocked",
    assignedReviewerId: "user-preston",
    priority: "Critical",
    masterRights: {
      status: "Disputed",
      owners: [
        partyRef(
          "party-hollow",
          "Hollow Skies Music Inc",
          "Master Owner",
          100,
          [],
          {
            notes:
              "Former producer separately claims 25%; totals are not normalized.",
          },
        ),
      ],
      totalOwnership: 100,
      exclusiveRepresentative: "Unclear during dispute",
      licensingAuthority: "Suspended",
      masterUseAllowed: false,
      restrictions: ["Active ownership dispute"],
      verifiedAt: null,
      verifiedBy: null,
    },
    compositionRights: {
      status: "Verified",
      workTitle: "Glass Cathedral",
      alternateTitles: [],
      iswc: "T-567.890.123-4",
      writers: [
        writer("party-hollow", "Rowan Vale", 100, "BMI", "00567890123"),
      ],
      writerShareTotal: 100,
      controlledShare: 100,
      uncontrolledShare: 0,
      restrictions: [],
      verifiedAt: "2026-06-12",
      verifiedBy: "Amelia Grant",
    },
    publishingRights: {
      status: "Verified",
      publishers: [
        publisher(
          "party-hollow",
          "Hollow Skies Music Inc",
          100,
          "BMI",
          "00345678901",
          { evidenceDocumentIds: ["doc-glass-publishing"] },
        ),
      ],
      publisherShareTotal: 100,
      controlledShare: 100,
      uncontrolledShare: 0,
      synchronizationAuthority: "Direct publishing only",
      restrictions: [],
      verifiedAt: "2026-06-12",
      verifiedBy: "Amelia Grant",
    },
    disputes: [
      {
        id: "dispute-gc-1",
        reference: "BM-RD-2026-0004",
        claimant: "Former producer",
        claimType: "Master ownership",
        claimedPercentage: 25,
        rightsDomain: "Master",
        dateRaised: "2026-07-06",
        evidenceDocumentIds: ["doc-glass-dispute"],
        internalOwner: "Amelia Grant",
        legalReviewer: "Preston Repenning",
        status: "Under Legal Review",
        buyerImpact: "Licensing and secure delivery blocked",
        publicImpact: "Track availability may be hidden",
        resolution: null,
        closedDate: null,
      },
    ],
    documents: ["doc-glass-publishing", "doc-glass-dispute"],
    review: {
      workflowStage: "Legal Review",
      checklist: {
        ...fullChecklist(),
        "Master agreement reviewed": false,
        "Disputes resolved": false,
        "Final eligibility decision complete": false,
      },
      lastReviewedAt: "2026-07-06",
      nextReviewAt: null,
      expiryStatus: "Current",
      dueDate: "2026-07-20",
      collaborators: ["reviewer-amelia"],
    },
    completeness: {
      percentage: 78,
      missingSections: ["Dispute resolution", "Confirmed master authority"],
      blockingIssues: ["Active 25% master ownership claim"],
      warnings: ["Public preview is admin-controlled"],
    },
    publicSummary: {
      approved: true,
      status: "Unavailable for Licensing",
      territory: "Not published",
      wording: "This track is not currently available for licensing.",
    },
    buyerSummary: {
      status: "Blocked",
      master: "Unavailable",
      publishing: "Reviewed",
      approvals: "Legal review required",
      stems: "Blocked",
      delivery: "Disabled",
    },
    internalNotes: [
      {
        id: "note-gc-1",
        author: "Preston Repenning",
        createdAt: "2026-07-06",
        visibility: "Super Admin Only",
        content:
          "Former producer claim and correspondence must remain restricted.",
      },
    ],
    versions: [
      {
        version: 1,
        effectiveDate: "2026-07-06",
        createdBy: "Preston Repenning",
        reason: "Dispute opened",
        summary: "Active master ownership claim blocks licensing.",
        before: { status: "Under Review" },
        after: { status: "Disputed", eligibility: "Blocked" },
        linkedDocuments: ["doc-glass-dispute"],
        current: true,
      },
    ],
    activity: [
      activity(
        "rights-act-gc-1",
        10,
        "Dispute opened",
        "Master ownership claim escalated to legal review.",
        "2026-07-06T10:00:00.000Z",
        "Super Admin Only",
      ),
    ],
  },
  {
    ...baseRecord,
    id: "rights-8",
    trackId: 8,
    trackTitle: "Harbor Light",
    scenarioLabel: "Rights review expired",
    artist: "Arco North",
    isrc: "BM-HL-2025-008",
    status: "Review Expired",
    previousStatus: "Fully Verified",
    licensingEligibility: "Manual Review Required",
    assignedReviewerId: "reviewer-jordan",
    priority: "High",
    masterRights: {
      status: "Expired",
      owners: [
        partyRef(
          "party-arco-label",
          "Arco North Recordings Ltd",
          "Record Label",
          100,
          ["doc-harbor-old"],
          { effectiveUntil: "2026-05-05" },
        ),
      ],
      totalOwnership: 100,
      exclusiveRepresentative: "Expired",
      licensingAuthority: "Review required",
      masterUseAllowed: false,
      restrictions: ["Representation authority expired"],
      verifiedAt: "2025-05-05",
      verifiedBy: "Jordan Lee",
    },
    compositionRights: {
      status: "Expired",
      workTitle: "Harbor Light",
      alternateTitles: [],
      iswc: "T-678.901.234-5",
      writers: [
        writer("party-arco-writer", "Elias North", 100, "SOCAN", "00234567890"),
      ],
      writerShareTotal: 100,
      controlledShare: 100,
      uncontrolledShare: 0,
      restrictions: [],
      verifiedAt: "2025-05-05",
      verifiedBy: "Jordan Lee",
    },
    publishingRights: {
      status: "Expired",
      publishers: [
        publisher(
          "party-arco-label",
          "Arco North Publishing",
          100,
          "SOCAN",
          "00789012345",
        ),
      ],
      publisherShareTotal: 100,
      controlledShare: 100,
      uncontrolledShare: 0,
      synchronizationAuthority: "Expired pending reverification",
      restrictions: [],
      verifiedAt: "2025-05-05",
      verifiedBy: "Jordan Lee",
    },
    documents: ["doc-harbor-old"],
    review: {
      workflowStage: "Reverification Started",
      checklist: {},
      lastReviewedAt: "2025-05-05",
      nextReviewAt: "2026-05-05",
      expiryStatus: "Expired",
      dueDate: "2026-07-25",
      collaborators: [],
    },
    completeness: {
      percentage: 92,
      missingSections: ["Current representation evidence"],
      blockingIssues: ["Rights review expired"],
      warnings: ["Existing licences remain valid; new licences are blocked"],
    },
    publicSummary: {
      approved: true,
      status: "Manual Review Required",
      territory: "Previously Worldwide",
      wording: "New licensing requests require a current rights review.",
    },
    buyerSummary: {
      status: "Manual Review Required",
      master: "Review expired",
      publishing: "Review expired",
      approvals: "Fresh rights review required",
      stems: "Blocked for new requests",
      delivery: "Existing licensed delivery remains governed by its licence",
    },
    internalNotes: [
      {
        id: "note-hl-1",
        author: "Jordan Lee",
        createdAt: "2026-05-05",
        visibility: "Internal",
        content:
          "Prior licences retain rights version 1; renewals require version 2.",
      },
    ],
    linkedLicences: [
      {
        id: "licence-hl-2025-1",
        rightsRecordId: "rights-8",
        rightsVersion: 1,
        eligibilityResult: "Eligible",
        restrictions: [],
        approvalEvidence: ["doc-harbor-old"],
        decisionDate: "2025-08-01",
        warning:
          "Current rights are expired; historical licence remains unchanged.",
      },
    ],
    versions: [
      {
        version: 1,
        effectiveDate: "2025-05-05",
        createdBy: "Jordan Lee",
        reason: "Annual verification",
        summary: "Worldwide master and publishing reviewed.",
        before: null,
        after: { status: "Fully Verified", eligibility: "Eligible" },
        linkedDocuments: ["doc-harbor-old"],
        current: true,
      },
    ],
    activity: [
      activity(
        "rights-act-hl-1",
        8,
        "Review expired",
        "New licences blocked until reverification.",
        "2026-05-05T10:00:00.000Z",
      ),
    ],
  },
  {
    ...baseRecord,
    id: "rights-15",
    trackId: 15,
    trackTitle: "The End of Jason Todd",
    scenarioLabel: "Protected source material — documentation pending",
    artist: "The SMYRK",
    isrc: null,
    status: "Unreviewed",
    licensingEligibility: "Not Yet Eligible",
    assignedReviewerId: "reviewer-amelia",
    priority: "High",
    masterRights: {
      status: "Unreviewed",
      owners: [],
      totalOwnership: 0,
      exclusiveRepresentative: null,
      licensingAuthority: "Not established",
      masterUseAllowed: false,
      restrictions: ["Original protected master locked"],
      verifiedAt: null,
      verifiedBy: null,
    },
    compositionRights: {
      status: "Unreviewed",
      workTitle: "The End of Jason Todd",
      alternateTitles: [],
      iswc: null,
      writers: [],
      writerShareTotal: 0,
      controlledShare: 0,
      uncontrolledShare: 100,
      restrictions: [],
      verifiedAt: null,
      verifiedBy: null,
    },
    publishingRights: {
      status: "Unreviewed",
      publishers: [],
      publisherShareTotal: 0,
      controlledShare: 0,
      uncontrolledShare: 100,
      synchronizationAuthority: "Not established",
      restrictions: [],
      verifiedAt: null,
      verifiedBy: null,
    },
    documents: [],
    review: {
      workflowStage: "Draft",
      checklist: {},
      lastReviewedAt: null,
      nextReviewAt: null,
      expiryStatus: "Current",
      dueDate: null,
      collaborators: [],
    },
    completeness: {
      percentage: 15,
      missingSections: [
        "Master ownership",
        "Writers",
        "Publishers",
        "PRO details",
        "Contracts",
        "Territories",
        "Licensing authority",
      ],
      blockingIssues: [
        "Rights documentation not supplied",
        "Licensing authority not established",
      ],
      warnings: ["Only the derived browser preview is available"],
    },
    publicSummary: {
      approved: true,
      status: "Rights Review Required",
      territory: "Not confirmed",
      wording:
        "This protected preview is not currently available for licensing or delivery.",
    },
    buyerSummary: {
      status: "Not Yet Eligible",
      master: "Protected and locked",
      publishing: "Not reviewed",
      approvals: "Rights review required",
      stems: "Not available",
      delivery: "Disabled",
    },
    internalNotes: [
      {
        id: "note-smyrk-1",
        author: "Catalog Operations",
        createdAt: "2026-07-15",
        visibility: "Internal",
        content:
          "Do not invent ownership, publishing, personnel, PRO registration, or licensing eligibility.",
      },
    ],
    versions: [
      {
        version: 1,
        effectiveDate: "2026-07-15",
        createdBy: "Catalog Operations",
        reason: "Protected source received",
        summary: "Preview created; rights documentation remains pending.",
        before: null,
        after: { status: "Unreviewed", eligibility: "Not Yet Eligible" },
        linkedDocuments: [],
        current: true,
      },
    ],
    activity: [
      activity(
        "rights-act-smyrk-1",
        15,
        "Protected source received",
        "Derived browser preview created; source master remains locked.",
        "2026-07-15T10:00:00.000Z",
      ),
    ],
  },
];

export const DEFAULT_RIGHTS_STATE = {
  version: 1,
  records: DEFAULT_RIGHTS_RECORDS,
  parties: RIGHTS_PARTIES,
  documents: RIGHTS_DOCUMENTS,
  reports: [],
  globalActivity: [],
};
