export const EXPIRING_ACCESS_STORAGE_KEY = "beatmondo-expiring-access-v1";
export const SELECTED_ACCESS_KEY = "beatmondo-selected-expiring-access";
export const ACTIVE_TOKEN_SESSION_PREFIX = "beatmondo-active-temp-token:";

export const ACCESS_STATUSES = {
  Draft: {
    allowed: false,
    refresh: false,
    extension: false,
    next: ["Active", "Cancelled"],
  },
  Active: {
    allowed: true,
    refresh: true,
    extension: true,
    next: ["Used", "Consumed", "Expired", "Revoked", "Suspended", "Cancelled"],
  },
  Used: {
    allowed: true,
    refresh: true,
    extension: true,
    next: ["Consumed", "Expired", "Revoked"],
  },
  Consumed: {
    allowed: false,
    refresh: true,
    extension: false,
    next: ["Superseded", "Archived"],
  },
  Expired: {
    allowed: false,
    refresh: true,
    extension: true,
    next: ["Superseded", "Archived"],
  },
  Revoked: {
    allowed: false,
    refresh: false,
    extension: false,
    next: ["Archived"],
  },
  Suspended: {
    allowed: false,
    refresh: false,
    extension: false,
    next: ["Active", "Revoked"],
  },
  Failed: {
    allowed: false,
    refresh: true,
    extension: false,
    next: ["Superseded", "Archived"],
  },
  Cancelled: {
    allowed: false,
    refresh: false,
    extension: false,
    next: ["Archived"],
  },
  "Access Denied": {
    allowed: false,
    refresh: false,
    extension: false,
    next: ["Archived"],
  },
  Superseded: {
    allowed: false,
    refresh: false,
    extension: false,
    next: ["Archived"],
  },
  Archived: { allowed: false, refresh: false, extension: false, next: [] },
};

const policy = (
  id,
  name,
  resourceType,
  action,
  duration,
  maxUses,
  overrides = {},
) => ({
  id,
  name,
  resourceType,
  action,
  defaultDurationMinutes: duration,
  minimumDurationMinutes:
    overrides.minimumDurationMinutes || Math.min(5, duration),
  maximumDurationMinutes:
    overrides.maximumDurationMinutes || Math.max(duration, 60),
  maxUses,
  refreshAllowed: overrides.refreshAllowed ?? true,
  extensionAllowed: overrides.extensionAllowed ?? true,
  deviceBinding: overrides.deviceBinding || "None",
  userBinding: overrides.userBinding || "When authenticated",
  organizationBinding:
    overrides.organizationBinding || "When organization-scoped",
  requiresApprovalAboveMinutes:
    overrides.requiresApprovalAboveMinutes || duration,
  active: true,
  version: 1,
  previousVersionId: null,
  decisionPriority: overrides.decisionPriority || 6,
  createdAt: "2026-07-15T10:00:00.000Z",
  createdBy: "Preston Repenning",
});

export const DEFAULT_ACCESS_POLICIES = [
  policy(
    "policy-public-preview",
    "Public protected preview",
    "Protected preview",
    "STREAM",
    30,
    1,
    {
      minimumDurationMinutes: 15,
      maximumDurationMinutes: 30,
      userBinding: "Anonymous session",
      organizationBinding: "None",
    },
  ),
  policy(
    "policy-professional-preview",
    "Professional preview",
    "Professional preview",
    "STREAM",
    30,
    1,
  ),
  policy("policy-vip-preview", "VIP preview", "VIP preview", "STREAM", 20, 1, {
    deviceBinding: "Current browser session",
  }),
  policy(
    "policy-buyer-preview",
    "Buyer-specific preview",
    "Buyer-specific preview",
    "STREAM",
    15,
    1,
    { maximumDurationMinutes: 1440 },
  ),
  policy(
    "policy-master-download",
    "Master download",
    "Secure delivery asset",
    "DOWNLOAD",
    10,
    1,
    {
      maximumDurationMinutes: 15,
      deviceBinding: "Current browser session",
      extensionAllowed: false,
    },
  ),
  policy(
    "policy-stem-download",
    "Stem download",
    "Secure delivery stems",
    "DOWNLOAD",
    5,
    1,
    {
      maximumDurationMinutes: 10,
      deviceBinding: "Current browser session",
      extensionAllowed: false,
    },
  ),
  policy(
    "policy-licence-document",
    "Licence document",
    "Licence document",
    "VIEW",
    45,
    5,
    { maximumDurationMinutes: 60 },
  ),
  policy(
    "policy-delivery-manifest",
    "Delivery package or manifest",
    "Delivery manifest",
    "VIEW",
    30,
    3,
    { maximumDurationMinutes: 60 },
  ),
  policy(
    "policy-contract-document",
    "Signed contract",
    "Signed contract",
    "VIEW",
    30,
    5,
    { maximumDurationMinutes: 60 },
  ),
  policy(
    "policy-financial-document",
    "Invoice or receipt",
    "Financial document",
    "VIEW",
    45,
    5,
    { maximumDurationMinutes: 60 },
  ),
  policy(
    "policy-rights-document",
    "Internal rights document",
    "Rights document",
    "VIEW",
    10,
    2,
    {
      maximumDurationMinutes: 15,
      userBinding: "Required",
      organizationBinding: "Internal only",
    },
  ),
  policy(
    "policy-upload",
    "Temporary upload",
    "Temporary upload",
    "UPLOAD",
    15,
    1,
    { maximumDurationMinutes: 30, extensionAllowed: false },
  ),
  policy(
    "policy-signature",
    "Signature page token",
    "Signature invitation",
    "SIGN",
    15,
    1,
    { maximumDurationMinutes: 30, userBinding: "Required" },
  ),
];

const record = (
  id,
  reference,
  resourceType,
  resourceLabel,
  action,
  status,
  overrides = {},
) => ({
  id,
  reference,
  resourceType,
  resourceLabel,
  resourceId: overrides.resourceId || id.replace("access-", "resource-"),
  relatedAssetId: overrides.relatedAssetId || null,
  relatedPreviewId: overrides.relatedPreviewId || null,
  relatedDeliveryId: overrides.relatedDeliveryId || null,
  relatedLicenceId: overrides.relatedLicenceId || null,
  relatedContractId: overrides.relatedContractId || null,
  relatedInvoiceId: overrides.relatedInvoiceId || null,
  action,
  status,
  tokenHashPlaceholder: overrides.tokenHashPlaceholder || `demo-hash-${id}`,
  tokenDisplaySuffix: overrides.tokenDisplaySuffix || id.slice(-6),
  generatedForUserId: overrides.generatedForUserId ?? null,
  generatedForOrganizationId: overrides.generatedForOrganizationId ?? null,
  generatedForSessionId: overrides.generatedForSessionId || null,
  anonymousSessionId: overrides.anonymousSessionId || null,
  requiredPermissions: overrides.requiredPermissions || [],
  requiredEntitlements: overrides.requiredEntitlements || [],
  allowedMethods:
    overrides.allowedMethods || (action === "VIEW" ? ["VIEW"] : [action]),
  maxUses: overrides.maxUses ?? 1,
  useCount: overrides.useCount || 0,
  validFrom: overrides.validFrom || "2026-07-16T12:00:00.000Z",
  expiresAt: overrides.expiresAt || "2026-07-16T18:00:00.000Z",
  firstUsedAt: overrides.firstUsedAt || null,
  lastUsedAt: overrides.lastUsedAt || null,
  consumedAt: overrides.consumedAt || null,
  revokedAt: overrides.revokedAt || null,
  revocationReason: overrides.revocationReason || null,
  deviceBinding: overrides.deviceBinding || "None",
  approximateRegionRestriction:
    overrides.approximateRegionRestriction || "None",
  refreshPolicy: overrides.refreshPolicy || {
    allowed: true,
    supersedeOld: true,
    requiresCurrentEntitlement: true,
  },
  policyId: overrides.policyId || "policy-master-download",
  policyVersion: overrides.policyVersion || 1,
  metadata: {
    resourceHidden: true,
    refreshAvailable: overrides.refreshAvailable ?? true,
    securityReviewRequired: overrides.securityReviewRequired || false,
    consumptionPolicy:
      overrides.consumptionPolicy ||
      (action === "DOWNLOAD" ? "Completed download" : "Successful exchange"),
    ...overrides.metadata,
  },
  createdAt: overrides.createdAt || "2026-07-16T13:00:00.000Z",
  createdBy: overrides.createdBy || "Temporary access service",
  lastValidatedAt: overrides.lastValidatedAt || null,
});

export const DEFAULT_ACCESS_RECORDS = [
  record(
    "access-101",
    "BM-URL-2026-0101",
    "Protected preview",
    "Afterglow Drive public watermarked preview",
    "STREAM",
    "Active",
    {
      relatedPreviewId: "preview-afterglow-public",
      anonymousSessionId: "anon-preview-session-101",
      maxUses: 1,
      policyId: "policy-public-preview",
      expiresAt: "2026-07-16T18:00:00.000Z",
      createdBy: "Preview access service",
    },
  ),
  record(
    "access-102",
    "BM-URL-2026-0102",
    "VIP preview",
    "Afterglow Drive VIP preview",
    "STREAM",
    "Active",
    {
      relatedPreviewId: "preview-afterglow-vip",
      generatedForUserId: "user-olivia",
      generatedForOrganizationId: "org-northstar",
      generatedForSessionId: "session-olivia",
      deviceBinding: "Current browser session",
      policyId: "policy-vip-preview",
      expiresAt: "2026-07-16T17:50:00.000Z",
      createdBy: "Olivia Bennett",
    },
  ),
  record(
    "access-103",
    "BM-URL-2026-0103",
    "Secure delivery asset",
    "Afterglow Drive WAV master",
    "DOWNLOAD",
    "Active",
    {
      resourceId: "delivery-entry-master-16",
      relatedAssetId: "asset-master-1",
      relatedDeliveryId: "delivery-package-16",
      relatedLicenceId: "licence-18",
      generatedForUserId: "user-olivia",
      generatedForOrganizationId: "org-northstar",
      requiredEntitlements: ["entitlement-master-16"],
      deviceBinding: "Current browser session",
      policyId: "policy-master-download",
      expiresAt: "2026-07-16T17:40:00.000Z",
      createdBy: "Olivia Bennett",
    },
  ),
  record(
    "access-104",
    "BM-URL-2026-0104",
    "Secure delivery stems",
    "Afterglow Drive stems package",
    "DOWNLOAD",
    "Expired",
    {
      resourceId: "delivery-entry-stems-16",
      relatedAssetId: "asset-stems-1",
      relatedDeliveryId: "delivery-package-16",
      relatedLicenceId: "licence-18",
      generatedForUserId: "user-olivia",
      generatedForOrganizationId: "org-northstar",
      requiredEntitlements: ["entitlement-stems-16"],
      deviceBinding: "Current browser session",
      policyId: "policy-stem-download",
      expiresAt: "2026-07-16T13:35:00.000Z",
      createdBy: "Olivia Bennett",
    },
  ),
  record(
    "access-105",
    "BM-URL-2026-0105",
    "Secure delivery asset",
    "Midnight Signal master",
    "DOWNLOAD",
    "Revoked",
    {
      resourceId: "delivery-entry-midnight-master",
      relatedAssetId: "asset-midnight-signal-master",
      relatedDeliveryId: "delivery-package-19",
      relatedLicenceId: "licence-conditional-23",
      generatedForUserId: "user-rachel",
      generatedForOrganizationId: "org-orbit",
      policyId: "policy-master-download",
      revokedAt: "2026-07-16T13:20:00.000Z",
      revocationReason: "Delivery suspended after rights review reopened",
      refreshAvailable: false,
      createdBy: "Amelia Grant",
    },
  ),
  record(
    "access-106",
    "BM-URL-2026-0106",
    "Secure delivery asset",
    "Northern Lines WAV master",
    "DOWNLOAD",
    "Consumed",
    {
      resourceId: "delivery-entry-northern-master",
      relatedAssetId: "asset-northern-lines-master",
      relatedDeliveryId: "delivery-package-8",
      relatedLicenceId: "licence-87",
      generatedForUserId: "user-olivia",
      generatedForOrganizationId: "org-northstar",
      policyId: "policy-master-download",
      maxUses: 1,
      useCount: 1,
      firstUsedAt: "2026-07-01T10:00:00.000Z",
      lastUsedAt: "2026-07-01T10:00:00.000Z",
      consumedAt: "2026-07-01T10:00:00.000Z",
      expiresAt: "2026-07-01T10:10:00.000Z",
      createdBy: "Olivia Bennett",
    },
  ),
  record(
    "access-107",
    "BM-URL-2026-0107",
    "Buyer-specific preview",
    "Private buyer preview",
    "STREAM",
    "Access Denied",
    {
      generatedForOrganizationId: "org-northstar",
      policyId: "policy-buyer-preview",
      expiresAt: "2026-07-16T17:00:00.000Z",
      metadata: {
        resourceHidden: true,
        denialCode: "ORGANIZATION_MISMATCH",
        attemptedOrganizationId: "org-brightframe",
        refreshAvailable: false,
      },
      createdBy: "Preview access service",
    },
  ),
  record(
    "access-108",
    "BM-URL-2026-0108",
    "Licence document",
    "BM-LIC-2026-0018 licence document",
    "VIEW",
    "Active",
    {
      resourceId: "asset-licence-1",
      relatedAssetId: "asset-licence-1",
      relatedLicenceId: "licence-18",
      generatedForUserId: "user-olivia",
      generatedForOrganizationId: "org-northstar",
      allowedMethods: ["VIEW", "DOWNLOAD"],
      maxUses: 5,
      policyId: "policy-licence-document",
      expiresAt: "2026-07-16T18:15:00.000Z",
      createdBy: "Olivia Bennett",
    },
  ),
  record(
    "access-109",
    "BM-URL-2026-0109",
    "Signed contract",
    "BM-C-2026-0021 signed contract",
    "VIEW",
    "Active",
    {
      resourceId: "signed-contract-contract-21-v2",
      relatedContractId: "contract-21",
      generatedForOrganizationId: "org-northstar",
      allowedMethods: ["VIEW", "DOWNLOAD"],
      maxUses: 5,
      policyId: "policy-contract-document",
      expiresAt: "2026-07-16T18:00:00.000Z",
      createdBy: "Olivia Bennett",
    },
  ),
  record(
    "access-110",
    "BM-URL-2026-0110",
    "Rights document",
    "Split sheet for Afterglow Drive",
    "VIEW",
    "Active",
    {
      resourceId: "asset-rights-1",
      relatedAssetId: "asset-rights-1",
      generatedForUserId: "user-amelia",
      generatedForOrganizationId: "org-beatmondo",
      requiredPermissions: ["rights.manage_documents"],
      allowedMethods: ["VIEW", "DOWNLOAD"],
      maxUses: 2,
      policyId: "policy-rights-document",
      expiresAt: "2026-07-16T17:38:00.000Z",
      createdBy: "Amelia Grant",
    },
  ),
  record(
    "access-111",
    "BM-URL-2026-0111",
    "Temporary upload",
    "Replacement instrumental upload",
    "UPLOAD",
    "Active",
    {
      resourceId: "ingestion-1-replacement-instrumental",
      generatedForUserId: "user-marcus",
      generatedForOrganizationId: "org-smyrk",
      requiredPermissions: ["ingestion.upload_assets"],
      policyId: "policy-upload",
      expiresAt: "2026-07-16T17:45:00.000Z",
      metadata: {
        resourceHidden: true,
        acceptedFormats: ["WAV", "AIFF"],
        maximumSizeBytes: 500000000,
        workflowId: "BM-ING-2026-0001",
        refreshAvailable: true,
      },
      createdBy: "Noah Pierce",
    },
  ),
  record(
    "access-112",
    "BM-URL-2026-0112",
    "Secure delivery stems",
    "High-value stems package",
    "DOWNLOAD",
    "Suspended",
    {
      resourceId: "delivery-entry-stems-16",
      relatedAssetId: "asset-stems-1",
      relatedDeliveryId: "delivery-package-16",
      relatedLicenceId: "licence-18",
      generatedForUserId: "user-olivia",
      generatedForOrganizationId: "org-northstar",
      policyId: "policy-stem-download",
      securityReviewRequired: true,
      refreshAvailable: false,
      metadata: {
        resourceHidden: true,
        refreshAvailable: false,
        securityReviewRequired: true,
        buyerMessage:
          "Temporary access is unavailable. Please contact beatmondo support.",
      },
      createdBy: "Security simulation",
    },
  ),
];

export const DEFAULT_EXPIRING_ACCESS_STATE = {
  version: 1,
  policies: DEFAULT_ACCESS_POLICIES,
  policyVersions: [],
  records: DEFAULT_ACCESS_RECORDS,
  attempts: [
    {
      id: "attempt-org-mismatch-1",
      accessId: "access-107",
      reference: "BM-URL-2026-0107",
      userId: "user-ethan",
      organizationId: "org-brightframe",
      resourceType: "Buyer-specific preview",
      action: "STREAM",
      timestamp: "2026-07-16T13:15:00.000Z",
      result: "Denied",
      reasonCode: "ORGANIZATION_MISMATCH",
      safeMessage:
        "This temporary access is not available for the current workspace.",
      approximateDevice: "Current browser · Simulated",
      approximateRegion: "North America",
      visibility: "Internal",
    },
  ],
  refreshRecords: [],
  extensionRequests: [],
  revocations: [
    {
      id: "revocation-access-105",
      accessId: "access-105",
      scope: "Individual",
      reason: "Delivery suspended after rights review reopened",
      createdAt: "2026-07-16T13:20:00.000Z",
      createdBy: "Amelia Grant",
    },
  ],
  securityReviews: [
    {
      id: "security-review-112",
      accessId: "access-112",
      status: "Open",
      severity: "High",
      reason: "Unusual repeated generation requests",
      indicators: [
        "Six generation requests in ten minutes",
        "High-value stems resource",
      ],
      buyerMessage:
        "Temporary access is unavailable. Please contact beatmondo support.",
      internalNotes:
        "Review buyer session history and package entitlement before resolution.",
      createdAt: "2026-07-16T13:25:00.000Z",
      createdBy: "Security simulation",
      resolvedAt: null,
      resolvedBy: null,
    },
  ],
  sessionExchanges: [],
  uploadUses: [],
  activity: [],
  notifications: [],
  analyticsEvents: [],
  generationWindows: {},
  lastNumbers: { access: 112, policy: 12 },
  settings: {
    generationWindowMinutes: 10,
    generationLimit: 5,
    securityReviewThreshold: 6,
    tokenDisplaySeconds: 90,
    supportEmail: "access@beatmondo.example",
  },
};
