export const QUOTE_STORAGE_KEY = "beatmondo-quote-calculation-v1";
export const SELECTED_QUOTE_KEY = "beatmondo-selected-quote";
export const SELECTED_CALCULATION_KEY = "beatmondo-selected-quote-calculation";

export const QUOTE_STATUSES = {
  Draft: {
    buyerLabel: "Preparing",
    description: "Internal draft quote.",
    actions: ["Calculate", "Edit", "Request Approval"],
    buyerVisible: false,
    acceptanceEligible: false,
    next: ["Calculation Incomplete", "Internal Review", "Blocked"],
  },
  "Calculation Incomplete": {
    buyerLabel: "Information pending",
    description: "Required pricing inputs are missing.",
    actions: ["Edit", "Request Information"],
    buyerVisible: false,
    acceptanceEligible: false,
    next: ["Information Required", "Draft", "Blocked"],
  },
  "Information Required": {
    buyerLabel: "Information required",
    description: "Buyer clarification is required.",
    actions: ["Provide Information", "Recalculate"],
    buyerVisible: true,
    acceptanceEligible: false,
    next: ["Draft", "Withdrawn"],
  },
  "Internal Review": {
    buyerLabel: "Under review",
    description: "Licensing review is in progress.",
    actions: [
      "Request Rights Approval",
      "Request Finance Approval",
      "Request Senior Approval",
    ],
    buyerVisible: false,
    acceptanceEligible: false,
    next: [
      "Rights Review Required",
      "Finance Review Required",
      "Senior Approval Required",
      "Approved Internally",
      "Blocked",
    ],
  },
  "Rights Review Required": {
    buyerLabel: "Rights review",
    description: "Rights approval is required.",
    actions: ["Approve Rights", "Block"],
    buyerVisible: false,
    acceptanceEligible: false,
    next: ["Internal Review", "Blocked"],
  },
  "Finance Review Required": {
    buyerLabel: "Pricing review",
    description: "Finance approval is required.",
    actions: ["Approve Finance", "Request Changes"],
    buyerVisible: false,
    acceptanceEligible: false,
    next: ["Internal Review", "Approved Internally"],
  },
  "Senior Approval Required": {
    buyerLabel: "Senior review",
    description: "High-value or exceptional terms require senior approval.",
    actions: ["Approve Senior", "Reject"],
    buyerVisible: false,
    acceptanceEligible: false,
    next: ["Approved Internally", "Internal Review", "Blocked"],
  },
  "Approved Internally": {
    buyerLabel: "Approved",
    description: "All required internal approvals are complete.",
    actions: ["Prepare Send"],
    buyerVisible: false,
    acceptanceEligible: false,
    next: ["Ready to Send"],
  },
  "Ready to Send": {
    buyerLabel: "Ready",
    description: "Buyer-safe terms are ready to send.",
    actions: ["Send"],
    buyerVisible: false,
    acceptanceEligible: false,
    next: ["Sent", "Withdrawn"],
  },
  Sent: {
    buyerLabel: "Available",
    description: "Quote was sent to the buyer.",
    actions: ["View", "Accept", "Request Changes", "Decline"],
    buyerVisible: true,
    acceptanceEligible: true,
    next: [
      "Viewed",
      "Buyer Revision Requested",
      "Accepted",
      "Declined",
      "Expired",
      "Withdrawn",
    ],
  },
  Viewed: {
    buyerLabel: "Viewed",
    description: "Buyer viewed the current quote.",
    actions: ["Accept", "Request Changes", "Decline"],
    buyerVisible: true,
    acceptanceEligible: true,
    next: [
      "Buyer Revision Requested",
      "Accepted",
      "Declined",
      "Expired",
      "Withdrawn",
    ],
  },
  "Buyer Revision Requested": {
    buyerLabel: "Changes requested",
    description: "Buyer requested revised commercial terms.",
    actions: ["Open Negotiation"],
    buyerVisible: true,
    acceptanceEligible: false,
    next: ["Negotiation", "Withdrawn"],
  },
  Negotiation: {
    buyerLabel: "In discussion",
    description: "Structured negotiation is active.",
    actions: ["Counterproposal", "Revise"],
    buyerVisible: true,
    acceptanceEligible: false,
    next: ["Revised", "Withdrawn"],
  },
  Revised: {
    buyerLabel: "Revised",
    description: "A new quote version was prepared.",
    actions: ["Send"],
    buyerVisible: true,
    acceptanceEligible: false,
    next: ["Sent", "Superseded"],
  },
  Accepted: {
    buyerLabel: "Accepted",
    description:
      "Buyer accepted the quoted terms; contract and payment remain required.",
    actions: ["Prepare Contract"],
    buyerVisible: true,
    acceptanceEligible: false,
    next: ["Converted to Contract"],
  },
  Declined: {
    buyerLabel: "Declined",
    description: "Buyer declined this quote.",
    actions: ["Follow Up", "Revise"],
    buyerVisible: true,
    acceptanceEligible: false,
    next: ["Revised", "Archived"],
  },
  Expired: {
    buyerLabel: "Expired",
    description: "The validity period ended.",
    actions: ["Renew", "Extend"],
    buyerVisible: true,
    acceptanceEligible: false,
    next: ["Revised", "Sent", "Archived"],
  },
  Withdrawn: {
    buyerLabel: "Withdrawn",
    description: "Beatmondo withdrew the quote.",
    actions: ["Create Replacement"],
    buyerVisible: true,
    acceptanceEligible: false,
    next: ["Revised", "Archived"],
  },
  Blocked: {
    buyerLabel: "Pricing unavailable",
    description: "Rights or policy prevents buyer-facing pricing.",
    actions: ["Rights Review", "Archive"],
    buyerVisible: true,
    acceptanceEligible: false,
    next: ["Internal Review", "Archived"],
  },
  "Converted to Contract": {
    buyerLabel: "Contract preparation",
    description: "Accepted quote is linked to later contract readiness.",
    actions: ["View Contract"],
    buyerVisible: true,
    acceptanceEligible: false,
    next: ["Archived"],
  },
  Superseded: {
    buyerLabel: "Superseded",
    description: "A newer quote version is current.",
    actions: ["Compare"],
    buyerVisible: false,
    acceptanceEligible: false,
    next: ["Archived"],
  },
  Archived: {
    buyerLabel: "Archived",
    description: "Historical quote record.",
    actions: ["View"],
    buyerVisible: false,
    acceptanceEligible: false,
    next: [],
  },
};

export const LINE_ITEM_TYPES = [
  "Master Licence Fee",
  "Publishing Licence Fee",
  "Territory Fee",
  "Media Fee",
  "Term Fee",
  "Exclusivity Fee",
  "Prominence Fee",
  "Paid Media Fee",
  "Audience Scale Fee",
  "Rush Fee",
  "Stem Preparation",
  "Custom Edit",
  "Instrumental Preparation",
  "Clean Version Preparation",
  "Additional Approval Fee",
  "Administrative Fee",
  "Renewal Fee",
  "Amendment Fee",
  "Discount",
  "Credit",
  "Tax",
  "Other",
];

const currentRules = {
  baseRates: {
    "Independent short film": [100000, 300000],
    Documentary: [200000, 600000],
    "Television episode": [300000, 1000000],
    "Streaming series": [400000, 1200000],
    Trailer: [800000, 2500000],
    "Advertising campaign": [600000, 3000000],
    "Global brand campaign": [2000000, 7500000],
    "Video game": [500000, 2000000],
    "Corporate production": [150000, 500000],
    "Social-only campaign": [100000, 600000],
    "Feature film": [1000000, 5000000],
    Other: null,
  },
  projectTypeMultipliers: {
    "Independent short film": 1,
    Documentary: 1,
    "Television episode": 1,
    "Streaming series": 1.1,
    Trailer: 1.2,
    "Advertising campaign": 1.15,
    "Global brand campaign": 1.35,
    "Video game": 1.1,
    "Corporate production": 1,
    "Social-only campaign": 0.9,
    "Feature film": 1.25,
    Other: 1,
  },
  mediaMultipliers: {
    Television: 1.25,
    Cinema: 1.4,
    Streaming: 1.2,
    "Online Video": 1,
    "Social Media": 1,
    "Paid Social": 1.3,
    Radio: 1.15,
    Podcast: 0.8,
    "In-Store": 1,
    "Out-of-Home": 1.2,
    Game: 1.3,
    "Internal Corporate": 0.7,
    "All Media": 2.2,
    Other: 1.15,
  },
  territoryMultipliers: {
    "Single Country": 1,
    "Multiple Countries": 1.25,
    "North America": 1.25,
    "United Kingdom": 1.05,
    "European Union": 1.3,
    "Australia and New Zealand": 1.15,
    "Latin America": 1.2,
    "Asia-Pacific": 1.35,
    Worldwide: 2,
    "Custom Territory": 1.5,
  },
  termMultipliers: {
    "1 month": 0.4,
    "3 months": 0.6,
    "6 months": 0.8,
    "12 months": 1,
    "24 months": 1.35,
    "36 months": 1.6,
    "5 years": 2,
    Perpetuity: 2.75,
    Custom: 1.4,
  },
  exclusivityMultipliers: {
    "Non-exclusive": 1,
    "Category exclusive": 1.5,
    "Territory exclusive": 1.7,
    "Media exclusive": 1.6,
    "Full exclusive": 3,
    Unknown: 1.5,
  },
  prominenceMultipliers: {
    Background: 0.8,
    "Featured background": 1.1,
    "Visual vocal": 1.3,
    "Main-title use": 1.7,
    "End-title use": 1.5,
    "Trailer focal use": 1.8,
    "Theme use": 2,
    "Logo or sonic-brand use": 2.5,
    Unknown: 1.35,
  },
  scaleMultipliers: {
    Small: 0.75,
    Standard: 1,
    Large: 1.35,
    Major: 1.75,
    Global: 2.25,
    Unknown: 1.4,
  },
  rushPercent: {
    Standard: 0,
    "5 business days": 0,
    "3 business days": 0.1,
    "48 hours": 0.15,
    "24 hours": 0.25,
    "Same day": 0.35,
  },
  assetFees: {
    "Preview only": 0,
    "WAV master": 0,
    Instrumental: 25000,
    "Clean version": 25000,
    Acapella: 35000,
    Stems: 50000,
    "Custom edit": 50000,
    "15-second cut": 20000,
    "30-second cut": 25000,
    "60-second cut": 30000,
    "Alternate mix": 35000,
  },
  buyerDiscountRules: {
    VIP: 0.05,
    Professional: 0,
    "Strategic partner": 0.1,
    "Volume buyer": 0.1,
    "Founding buyer": 0.1,
  },
  minimumFees: {
    Professional: 100000,
    "VIP preparation": 25000,
    Rush: 25000,
    Stems: 50000,
  },
  approvalThresholds: {
    licensingOnlyBelow: 500000,
    financeFrom: 500000,
    seniorAbove: 2000000,
    seniorDiscountAbove: 0.15,
    fullExclusivity: true,
    conditionalRights: true,
  },
  manualReviewThresholds: {
    majorProjectTypes: ["Global brand campaign", "Feature film"],
    prominence: ["Logo or sonic-brand use"],
    terms: ["Perpetuity"],
    exclusivity: ["Full exclusive", "Unknown"],
    rush: ["Same day"],
    scale: ["Global", "Unknown"],
  },
};

export const DEFAULT_PRICING_MODELS = [
  {
    id: "pricing-model-v1",
    version: 1,
    name: "Historical Demo Pricing",
    effectiveFrom: "2026-01-01",
    effectiveUntil: "2026-06-30",
    currency: "USD",
    active: false,
    rules: {
      ...currentRules,
      baseRates: {
        ...currentRules.baseRates,
        "Advertising campaign": [500000, 2500000],
        Trailer: [700000, 2200000],
      },
    },
  },
  {
    id: "pricing-model-v2",
    version: 2,
    name: "Current Demo Pricing",
    effectiveFrom: "2026-07-01",
    effectiveUntil: null,
    currency: "USD",
    active: true,
    rules: currentRules,
  },
];

const line = (type, total, description, overrides = {}) => ({
  id: `line-${Math.random().toString(36).slice(2, 8)}`,
  type,
  name: type,
  description,
  quantity: 1,
  unitAmount: total,
  total,
  buyerVisible: overrides.buyerVisible ?? true,
  taxable: overrides.taxable ?? true,
  optional: overrides.optional ?? false,
  required: overrides.required ?? true,
  sourceRule: overrides.sourceRule || "Seeded quote",
  manualOverride: overrides.manualOverride || false,
});
const approvals = (items) =>
  items.map(([type, status, approver, note]) => ({
    id: `approval-${type.toLowerCase()}-${Math.random().toString(36).slice(2, 7)}`,
    type,
    status,
    approver,
    approverId: null,
    note,
    date: status === "Approved" ? "2026-07-16T10:00:00.000Z" : null,
    history: [],
  }));
const quote = (
  id,
  reference,
  buyer,
  organization,
  project,
  trackId,
  trackTitle,
  artist,
  quoteType,
  status,
  overrides = {},
) => ({
  id,
  reference,
  calculationId: overrides.calculationId || `calc-${id}`,
  licensingRequestId: overrides.licensingRequestId || `request-${id}`,
  projectId: overrides.projectId || `project-${id}`,
  project,
  buyerId: buyer.id,
  buyer: buyer.name,
  organizationId: organization.id,
  organization: organization.name,
  trackId,
  trackTitle,
  artist,
  quoteType,
  status,
  version: overrides.version || 1,
  current: overrides.current ?? true,
  currency: overrides.currency || "USD",
  lineItems: overrides.lineItems || [],
  subtotal: overrides.subtotal ?? 0,
  discounts: overrides.discounts ?? 0,
  tax: overrides.tax ?? 0,
  total: overrides.total ?? 0,
  minimum: overrides.minimum ?? null,
  maximum: overrides.maximum ?? null,
  terms: overrides.terms || {
    media: ["Online Video"],
    territory: "North America",
    term: "12 months",
    exclusivity: "Non-exclusive",
    prominence: "Featured background",
    usageDurationSeconds: 30,
    scale: "Standard",
    assets: ["WAV master"],
    rush: "Standard",
    deposit: "25%",
    paymentTerms: "Due before delivery",
  },
  conditions: overrides.conditions || [],
  exclusions: overrides.exclusions || [
    "No transfer of ownership",
    "No unapproved media or territory expansion",
  ],
  rightsSummary: overrides.rightsSummary || {
    eligibility: "Eligible",
    rightsVersion: 1,
    masterControlledShare: 100,
    publishingControlledShare: 100,
    uncontrolledShare: 0,
    thirdPartyApproval: false,
  },
  usageSummary:
    overrides.usageSummary ||
    "One synchronized use in the approved project and media.",
  approvalStatus: overrides.approvalStatus || "Pending",
  approvers: overrides.approvers || [],
  validFrom: overrides.validFrom || "2026-07-16T00:00:00.000Z",
  validUntil: overrides.validUntil || "2026-08-06T23:59:59.000Z",
  sentAt: overrides.sentAt || null,
  viewedAt: overrides.viewedAt || null,
  lastViewedAt: overrides.lastViewedAt || null,
  acceptedAt: overrides.acceptedAt || null,
  acceptedBy: overrides.acceptedBy || null,
  declinedAt: overrides.declinedAt || null,
  expiredAt: overrides.expiredAt || null,
  buyerMessage:
    overrides.buyerMessage ||
    "Prepared by beatmondo for your project review. Final usage rights require contract completion and any required payment.",
  internalNotes: overrides.internalNotes || [],
  previousVersionId: overrides.previousVersionId || null,
  supersededBy: overrides.supersededBy || null,
  changeSummary: overrides.changeSummary || null,
  createdAt: overrides.createdAt || "2026-07-16T09:00:00.000Z",
  createdBy: overrides.createdBy || "Jordan Lee",
  updatedAt: overrides.updatedAt || "2026-07-16T10:00:00.000Z",
  quoteOwner: overrides.quoteOwner || "Jordan Lee",
  negotiation: overrides.negotiation || [],
  buyerResponses: overrides.buyerResponses || [],
  futureWorkflow: overrides.futureWorkflow || {
    contractReadiness: "Not Ready",
    invoiceReadiness: "Not Ready",
  },
  pricingModelVersion: overrides.pricingModelVersion || 2,
  calculationSnapshot: overrides.calculationSnapshot || null,
});

export const DEFAULT_QUOTES = [
  quote(
    "quote-41",
    "BM-Q-2026-0041",
    { id: "user-olivia", name: "Olivia Bennett" },
    { id: "org-northstar", name: "Northstar Pictures" },
    "Premium Hotel Launch Film",
    1,
    "Golden Hours",
    "Lennox",
    "Fixed",
    "Accepted",
    {
      projectId: "project-premium-hotel",
      lineItems: [
        line("Master Licence Fee", 500000, "Master synchronization rights"),
        line(
          "Publishing Licence Fee",
          500000,
          "Publishing synchronization rights",
        ),
        line("Rush Fee", 75000, "Priority processing"),
        line("Stem Preparation", 50000, "Approved stem preparation"),
        line("Discount", -75000, "Configured VIP service discount"),
      ],
      subtotal: 1125000,
      discounts: -75000,
      total: 1050000,
      approvalStatus: "Completed",
      approvers: approvals([
        ["Licensing", "Approved", "Jordan Lee", "Commercial terms confirmed"],
        ["Rights", "Approved", "Amelia Grant", "Controlled rights confirmed"],
        ["Finance", "Approved", "Finance Team", "Amount and discount approved"],
      ]),
      acceptedAt: "2026-07-17T12:00:00.000Z",
      acceptedBy: "Olivia Bennett",
      sentAt: "2026-07-16T12:00:00.000Z",
      viewedAt: "2026-07-16T13:00:00.000Z",
      validUntil: "2026-07-31T23:59:59.000Z",
      futureWorkflow: {
        contractReadiness: "Ready",
        invoiceReadiness: "Pending contract",
      },
    },
  ),
  quote(
    "quote-42",
    "BM-Q-2026-0042",
    { id: "user-ethan", name: "Ethan Cole" },
    { id: "org-brightframe", name: "BrightFrame Agency" },
    "Launch Forward Campaign",
    2,
    "Paper Planes",
    "Arco North",
    "Suggested Range",
    "Internal Review",
    {
      minimum: 450000,
      maximum: 750000,
      rightsSummary: {
        eligibility: "Conditional",
        rightsVersion: 1,
        masterControlledShare: 100,
        publishingControlledShare: 75,
        uncontrolledShare: 25,
        thirdPartyApproval: true,
      },
      conditions: ["Publisher confirmation pending"],
      approvalStatus: "Pending",
      approvers: approvals([
        ["Licensing", "Pending", "Jordan Lee", ""],
        ["Rights", "Pending", "Amelia Grant", ""],
      ]),
      validUntil: "2026-07-30T23:59:59.000Z",
      internalNotes: ["Buyer verification remains under review; do not send."],
    },
  ),
  quote(
    "quote-43",
    "BM-Q-2026-0043",
    { id: "user-sofia", name: "Sofia Martinez" },
    { id: "org-lighthouse", name: "Lighthouse Creative" },
    "Quiet City Documentary",
    3,
    "Midnight Transit",
    "Soren",
    "Suggested Range",
    "Information Required",
    {
      minimum: null,
      maximum: null,
      conditions: [
        "Confirmed production budget required",
        "Final territory required",
        "Music-use duration required",
      ],
      buyerMessage:
        "Please provide the missing project information before pricing can be prepared.",
      validUntil: null,
      approvalStatus: "Not Started",
    },
  ),
  quote(
    "quote-44",
    "BM-Q-2026-0044",
    { id: "user-rachel", name: "Rachel Kim" },
    { id: "org-orbit", name: "Orbit Trailers" },
    "Midnight Run Trailer",
    4,
    "All That Remains",
    "Vespera",
    "Conditional Range",
    "Sent",
    {
      minimum: 1500000,
      maximum: 2200000,
      conditions: [
        "Sample clearance required",
        "No final contract until third-party approval",
      ],
      rightsSummary: {
        eligibility: "Conditional",
        rightsVersion: 1,
        masterControlledShare: 100,
        publishingControlledShare: 80,
        uncontrolledShare: 20,
        thirdPartyApproval: true,
      },
      sentAt: "2026-07-15T10:00:00.000Z",
      validUntil: "2026-08-05T23:59:59.000Z",
      approvalStatus: "Completed",
      approvers: approvals([
        ["Licensing", "Approved", "Jordan Lee", ""],
        ["Rights", "Approved", "Amelia Grant", "Conditional range only"],
        ["Finance", "Approved", "Finance Team", ""],
      ]),
    },
  ),
  quote(
    "quote-45",
    "BM-Q-2026-0045",
    { id: "user-olivia", name: "Olivia Bennett" },
    { id: "org-northstar", name: "Northstar Pictures" },
    "Aurora Motors Campaign",
    9,
    "Meridian",
    "Atlas Collective",
    "Fixed",
    "Buyer Revision Requested",
    {
      total: 1800000,
      subtotal: 1800000,
      sentAt: "2026-07-14T10:00:00.000Z",
      viewedAt: "2026-07-14T11:00:00.000Z",
      negotiation: [
        {
          id: "neg-45-1",
          author: "Olivia Bennett",
          role: "Buyer",
          date: "2026-07-15T09:00:00.000Z",
          message: "Please revise to a 12-month term without cinema.",
          proposedAmount: 1400000,
          proposedTerm: "12 months",
          proposedTerritory: "Worldwide",
          proposedMedia: ["Online Video", "Paid Social"],
          attachments: [],
          internal: false,
        },
      ],
      buyerResponses: [
        {
          type: "Change Request",
          requestedBudget: 1400000,
          term: "12 months",
          media: ["Online Video", "Paid Social"],
          message: "Remove cinema and reduce term.",
          createdAt: "2026-07-15T09:00:00.000Z",
        },
      ],
    },
  ),
  quote(
    "quote-37",
    "BM-Q-2026-0037",
    { id: "user-ethan", name: "Ethan Cole" },
    { id: "org-brightframe", name: "BrightFrame Agency" },
    "Independent Channel Package",
    16,
    "Northern Lines",
    "Arco North",
    "Renewal",
    "Expired",
    {
      total: 250000,
      subtotal: 250000,
      validUntil: "2026-07-01T23:59:59.000Z",
      expiredAt: "2026-07-02T00:00:00.000Z",
      conditions: ["Renewed buyer and rights review required"],
    },
  ),
  quote(
    "quote-39",
    "BM-Q-2026-0039",
    { id: "user-rachel", name: "Rachel Kim" },
    { id: "org-orbit", name: "Orbit Trailers" },
    "Global Fashion Campaign",
    19,
    "Velvet Warning",
    "Jade Montague",
    "Fixed",
    "Declined",
    {
      total: 4200000,
      subtotal: 4200000,
      declinedAt: "2026-07-12T12:00:00.000Z",
      buyerResponses: [
        {
          type: "Decline",
          reason: "Budget too high",
          createdAt: "2026-07-12T12:00:00.000Z",
        },
      ],
      internalNotes: [
        "Offer a narrower territory and shorter term if the project reopens.",
      ],
    },
  ),
  quote(
    "quote-46",
    "BM-Q-2026-0046",
    { id: "buyer-major-studio", name: "Major Studio Review" },
    { id: "org-major-studio", name: "Major Studio" },
    "Feature Film End Credits",
    15,
    "The End of Jason Todd",
    "The SMYRK",
    "Manual",
    "Blocked",
    {
      minimum: null,
      maximum: null,
      total: 0,
      rightsSummary: {
        eligibility: "Blocked",
        rightsVersion: 1,
        masterControlledShare: 0,
        publishingControlledShare: 0,
        uncontrolledShare: 100,
        thirdPartyApproval: true,
      },
      conditions: [
        "Pricing unavailable while licensing eligibility is under review",
      ],
      buyerMessage:
        "Pricing is unavailable while licensing eligibility is under review.",
      internalNotes: [
        "Do not invent or infer ownership, publishing, or commercial eligibility for The SMYRK.",
      ],
    },
  ),
  quote(
    "quote-47",
    "BM-Q-2026-0047",
    { id: "user-olivia", name: "Olivia Bennett" },
    { id: "org-northstar", name: "Northstar Pictures" },
    "Luxury Auto Campaign - Fall 2026",
    1,
    "Golden Hours",
    "Lennox",
    "Fixed",
    "Sent",
    {
      projectId: "project-luxury-auto",
      total: 2200000,
      subtotal: 2300000,
      discounts: -100000,
      lineItems: [
        line("Master Licence Fee", 1050000, "Master synchronization rights"),
        line(
          "Publishing Licence Fee",
          1050000,
          "Publishing synchronization rights",
        ),
        line("Stem Preparation", 50000, "Stem package preparation"),
        line("Rush Fee", 150000, "48-hour processing"),
        line("Discount", -100000, "Configured VIP service discount"),
      ],
      approvalStatus: "Completed",
      approvers: approvals([
        ["Licensing", "Approved", "Jordan Lee", ""],
        ["Rights", "Approved", "Amelia Grant", ""],
        ["Finance", "Approved", "Finance Team", ""],
        ["Senior", "Approved", "Preston Repenning", "High-value VIP approval"],
      ]),
      sentAt: "2026-07-16T10:00:00.000Z",
      validUntil: "2026-08-06T23:59:59.000Z",
      terms: {
        media: ["Online Video", "Paid Social"],
        territory: "Worldwide",
        term: "12 months",
        exclusivity: "Non-exclusive",
        prominence: "Featured background",
        usageDurationSeconds: 45,
        scale: "Major",
        assets: ["WAV master", "Stems"],
        rush: "48 hours",
        deposit: "25%",
        paymentTerms: "Due before delivery",
      },
    },
  ),
  quote(
    "quote-48",
    "BM-Q-2026-0048",
    { id: "user-olivia", name: "Olivia Bennett" },
    { id: "org-northstar", name: "Northstar Pictures" },
    "Northstar Streaming Ident",
    1,
    "Golden Hours",
    "Lennox",
    "Fixed",
    "Accepted",
    {
      projectId: "project-streaming-ident",
      total: 1250000,
      subtotal: 1250000,
      lineItems: [
        line("Master Licence Fee", 625000, "Master synchronization rights"),
        line(
          "Publishing Licence Fee",
          625000,
          "Publishing synchronization rights",
        ),
      ],
      approvalStatus: "Completed",
      approvers: approvals([
        ["Licensing", "Approved", "Jordan Lee", ""],
        ["Rights", "Approved", "Amelia Grant", ""],
        ["Finance", "Approved", "Nadia Foster", ""],
      ]),
      sentAt: "2026-07-16T10:00:00.000Z",
      viewedAt: "2026-07-16T11:00:00.000Z",
      acceptedAt: "2026-07-16T12:00:00.000Z",
      acceptedBy: "Olivia Bennett",
      validUntil: "2026-08-06T23:59:59.000Z",
      terms: {
        media: ["Online Video", "Paid Social"],
        territory: "North America",
        term: "12 months",
        exclusivity: "Non-exclusive",
        prominence: "Featured background",
        usageDurationSeconds: 30,
        scale: "Standard",
        assets: ["WAV master"],
        rush: "Standard",
        deposit: "25%",
        paymentTerms: "25% deposit; balance due before approved delivery",
      },
      futureWorkflow: {
        contractReadiness: "Ready",
        invoiceReadiness: "Pending contract",
      },
    },
  ),
  quote(
    "quote-49",
    "BM-Q-2026-0049",
    { id: "user-olivia", name: "Olivia Bennett" },
    { id: "org-northstar", name: "Northstar Pictures" },
    "Northstar Brand Film",
    1,
    "Golden Hours",
    "Lennox",
    "Fixed",
    "Accepted",
    {
      projectId: "project-brand-film",
      total: 1600000,
      subtotal: 1600000,
      lineItems: [
        line("Master Licence Fee", 800000, "Master synchronization rights"),
        line("Publishing Licence Fee", 800000, "Publishing synchronization rights"),
      ],
      approvalStatus: "Completed",
      approvers: approvals([
        ["Licensing", "Approved", "Jordan Lee", ""],
        ["Rights", "Approved", "Amelia Grant", ""],
        ["Finance", "Approved", "Nadia Foster", ""],
      ]),
      acceptedAt: "2026-07-15T12:00:00.000Z",
      acceptedBy: "Olivia Bennett",
      validUntil: "2026-08-06T23:59:59.000Z",
      terms: {
        media: ["Online Video", "Paid Social"],
        territory: "Worldwide",
        term: "12 months",
        exclusivity: "Non-exclusive",
        prominence: "Featured background",
        usageDurationSeconds: 30,
        scale: "Standard",
        assets: ["WAV master", "Instrumental"],
        rush: "Standard",
        deposit: "100%",
        paymentTerms: "Paid in full before licence generation",
      },
    },
  ),
];

export const DEFAULT_CALCULATIONS = DEFAULT_QUOTES.filter(
  (item) => !["Information Required", "Blocked"].includes(item.status),
).map((item) => ({
  id: item.calculationId,
  licensingRequestId: item.licensingRequestId,
  projectId: item.projectId,
  buyerId: item.buyerId,
  organizationId: item.organizationId,
  trackId: item.trackId,
  rightsVersion: item.rightsSummary.rightsVersion,
  pricingModelVersion: item.pricingModelVersion,
  currency: item.currency,
  inputs: {
    projectType: item.project.includes("Trailer")
      ? "Trailer"
      : item.project.includes("Documentary")
        ? "Documentary"
        : "Advertising campaign",
    media: item.terms.media,
    territory: item.terms.territory,
    term: item.terms.term,
    exclusivity: item.terms.exclusivity,
    prominence: item.terms.prominence,
    scale: item.terms.scale,
    assets: item.terms.assets,
    rush: item.terms.rush,
  },
  baseRates: {
    minimum: item.minimum || Math.round(item.total * 0.45),
    maximum: item.maximum || Math.round(item.total * 0.65),
  },
  multipliers: [],
  additions: [],
  discounts: item.discounts
    ? [{ name: "Configured discount", amount: item.discounts }]
    : [],
  taxes: [],
  suggestedMinimum: item.minimum,
  suggestedMaximum: item.maximum,
  recommendedAmount: item.total,
  confidence: item.quoteType === "Manual" ? "Manual" : "Medium",
  manualReviewRequired: ["Manual", "Conditional Range"].includes(
    item.quoteType,
  ),
  blockingIssues: [],
  warnings: item.conditions,
  calculationNotes: ["Fictional demo pricing guidance only."],
  createdAt: item.createdAt,
  createdBy: item.createdBy,
  updatedAt: item.updatedAt,
}));

export const DEFAULT_QUOTE_STATE = {
  version: 1,
  pricingModels: DEFAULT_PRICING_MODELS,
  calculations: DEFAULT_CALCULATIONS,
  quotes: DEFAULT_QUOTES,
  quoteVersions: [],
  approvals: [],
  negotiations: [],
  analyticsEvents: [],
  activity: [],
  notifications: [],
  pricingRuleVersions: [],
  projects: [
    {
      id: "project-luxury-auto",
      name: "Luxury Auto Campaign - Fall 2026",
      organizationId: "org-northstar",
      status: "Quote Sent",
      quoteId: "quote-47",
    },
    {
      id: "project-premium-hotel",
      name: "Premium Hotel Launch Film",
      organizationId: "org-northstar",
      status: "Quote Accepted",
      quoteId: "quote-41",
    },
    {
      id: "project-aurora",
      name: "Aurora Motors Campaign",
      organizationId: "org-northstar",
      status: "Negotiation",
      quoteId: "quote-45",
    },
    {
      id: "project-streaming-ident",
      name: "Northstar Streaming Ident",
      organizationId: "org-northstar",
      status: "Quote Accepted",
      quoteId: "quote-48",
    },
    {
      id: "project-brand-film",
      name: "Northstar Brand Film",
      organizationId: "org-northstar",
      status: "Quote Accepted",
      quoteId: "quote-49",
    },
  ],
  licensingRequests: [
    {
      id: "request-quote-42",
      projectId: "project-quote-42",
      status: "Quote Needed",
      quoteId: "quote-42",
    },
  ],
  contractReadiness: [],
  invoiceReadiness: [],
};
