// DEMO ONLY — membership, billing, tax, invoice, and payment data in this file
// is fabricated for the frontend prototype. Production billing must be server-side.

export const MEMBERSHIP_STORAGE_KEY = "beatmondo-membership-billing-v1";
export const CHECKOUT_STORAGE_KEY = "beatmondo-membership-checkout-v1";
export const SELECTED_MEMBERSHIP_KEY = "beatmondo-selected-membership";
export const SELECTED_INVOICE_KEY = "beatmondo-selected-invoice";

export const MEMBERSHIP_STATUSES = [
  "Free",
  "Trialing",
  "Active",
  "Complimentary",
  "Pending Verification",
  "Pending Approval",
  "Past Due",
  "Grace Period",
  "Payment Failed",
  "Paused",
  "Cancelling",
  "Cancelled",
  "Expired",
  "Suspended",
  "Incomplete",
];

export const MEMBERSHIP_STATUS_CONTENT = {
  Free: {
    description: "Discovery access is active with no recurring charge.",
    access: "Discovery entitlements",
    actions: ["Upgrade"],
  },
  Trialing: {
    description:
      "Time-limited plan access is active, subject to buyer verification.",
    access: "Plan entitlements while eligible",
    actions: ["Upgrade", "Cancel trial"],
  },
  Active: {
    description: "Billing is current and the membership is active.",
    access: "Plan entitlements subject to verification",
    actions: ["Change plan", "Cancel"],
  },
  Complimentary: {
    description: "Access was granted without a recurring payment requirement.",
    access: "Granted entitlements until review",
    actions: ["Contact support"],
  },
  "Pending Verification": {
    description:
      "Payment is complete, but professional access awaits buyer verification.",
    access: "Discovery entitlements",
    actions: ["Complete verification"],
  },
  "Pending Approval": {
    description:
      "A senior review is required before this membership can activate.",
    access: "Current membership entitlements",
    actions: ["View request"],
  },
  "Past Due": {
    description: "A scheduled payment was not successful.",
    access: "Temporary restricted access",
    actions: ["Update payment", "Retry"],
  },
  "Grace Period": {
    description: "Payment resolution is required before the grace period ends.",
    access: "Existing projects visible; premium actions restricted",
    actions: ["Resolve payment"],
  },
  "Payment Failed": {
    description: "The most recent payment attempt failed.",
    access: "Discovery entitlements",
    actions: ["Update payment", "Retry"],
  },
  Paused: {
    description:
      "Paid membership access is paused until the scheduled resume date.",
    access: "Discovery entitlements",
    actions: ["Resume"],
  },
  Cancelling: {
    description:
      "Auto-renewal is disabled; current access remains until period end.",
    access: "Current entitlements until end date",
    actions: ["Reactivate"],
  },
  Cancelled: {
    description: "The membership has ended.",
    access: "Discovery entitlements",
    actions: ["Choose a plan"],
  },
  Expired: {
    description: "The membership period has expired.",
    access: "Discovery entitlements",
    actions: ["Choose a plan"],
  },
  Suspended: {
    description:
      "Paid access is suspended while an account or payment issue is resolved.",
    access: "Discovery entitlements",
    actions: ["Contact support"],
  },
  Incomplete: {
    description: "Checkout was not completed.",
    access: "Existing entitlements",
    actions: ["Resume checkout"],
  },
};

const discoveryEntitlements = [
  "catalog.discovery",
  "previews.protected",
  "tracks.save",
  "collections.basic",
  "verification.apply",
  "profile.limited",
  "projects.draft_one",
];
const professionalEntitlements = [
  ...discoveryEntitlements,
  "catalog.professional",
  "projects.create",
  "projects.limit_ten",
  "licensing.request",
  "quotes.view",
  "contracts.view",
  "payments.view",
  "licences.view",
  "delivery.secure",
  "concierge.standard",
  "team.members",
  "analytics.buyer",
];
const vipEntitlements = [
  ...professionalEntitlements.filter((item) => item !== "projects.limit_ten"),
  "catalog.vip",
  "projects.unlimited",
  "delivery.masters",
  "delivery.stems",
  "concierge.vip",
  "terms.preapproved",
  "priority.review",
  "workspace.premium",
];

export const MEMBERSHIP_PLANS = [
  {
    id: "plan-discovery",
    slug: "discovery",
    name: "Discovery Access",
    audience: "Approved early-stage buyers and registered users",
    description:
      "Selective music discovery with protected previews while professional eligibility is established.",
    monthlyPriceCents: 0,
    annualPriceCents: 0,
    currency: "USD",
    entitlements: discoveryEntitlements,
    features: [
      "Public and Discovery music",
      "Protected previews",
      "Save tracks",
      "Basic collections",
      "Buyer verification application",
    ],
    eligibility: "Registered account",
    verificationRequirement: "No professional verification required",
    trialAvailable: false,
    public: true,
    recommended: false,
    requiresVerification: false,
    requiresSeniorApproval: false,
    supportsTeamMembers: false,
    maxSeats: 1,
    sortOrder: 1,
  },
  {
    id: "plan-professional",
    slug: "professional",
    name: "Professional Buyer",
    audience: "Music supervisors, producers, agencies, brands, and studios",
    description:
      "Professional project, licensing, quote, contract, and approved secure-delivery workflows.",
    monthlyPriceCents: 9900,
    annualPriceCents: 99000,
    currency: "USD",
    entitlements: professionalEntitlements,
    features: [
      "Expanded professional music",
      "Up to 10 active projects",
      "Licensing requests",
      "Quote and contract workflow",
      "Approved secure delivery",
      "Standard licensing assistance",
    ],
    eligibility: "Approved Professional Buyer verification",
    verificationRequirement:
      "Payment may complete before verification; professional tools activate only after approval.",
    trialAvailable: true,
    public: true,
    recommended: true,
    requiresVerification: true,
    requiresSeniorApproval: false,
    supportsTeamMembers: true,
    maxSeats: 5,
    sortOrder: 2,
  },
  {
    id: "plan-vip",
    slug: "vip",
    name: "VIP Sync Access",
    audience: "High-volume, deadline-sensitive and premium sync teams",
    description:
      "Priority review, private selections, concierge support, premium workflows, and controlled asset delivery.",
    monthlyPriceCents: 29900,
    annualPriceCents: 299000,
    currency: "USD",
    entitlements: vipEntitlements,
    features: [
      "Everything in Professional Buyer",
      "VIP-only selections",
      "Priority and fast-track review",
      "Concierge support",
      "Premium project workspace",
      "Approved WAV master and stem delivery",
      "Pre-approved terms where granted",
    ],
    eligibility: "Approved VIP Buyer verification and senior approval",
    verificationRequirement:
      "Purchasing or requesting VIP never grants VIP verification automatically.",
    trialAvailable: false,
    public: true,
    recommended: false,
    requiresVerification: true,
    requiresSeniorApproval: true,
    supportsTeamMembers: true,
    maxSeats: 12,
    sortOrder: 3,
  },
  {
    id: "plan-enterprise",
    slug: "enterprise",
    name: "Enterprise / Strategic Partner",
    audience:
      "Studios, networks, trailer houses, agencies, and streaming platforms",
    description:
      "Custom seats, central billing, account management, delivery policies, catalog access, and consolidated invoicing.",
    monthlyPriceCents: null,
    annualPriceCents: null,
    currency: "USD",
    entitlements: vipEntitlements,
    features: [
      "Custom seats",
      "Central organization billing",
      "Dedicated account manager",
      "Custom terms",
      "Consolidated invoices",
      "Custom delivery policy",
    ],
    eligibility: "Manual organization review and agreement",
    verificationRequirement:
      "Enterprise access is configured by beatmondo after organizational review.",
    trialAvailable: false,
    public: true,
    recommended: false,
    requiresVerification: true,
    requiresSeniorApproval: true,
    supportsTeamMembers: true,
    maxSeats: null,
    sortOrder: 4,
  },
];

export const DISCOUNT_CODES = [
  {
    code: "FOUNDING10",
    type: "percent",
    value: 10,
    plans: ["plan-professional", "plan-vip"],
    intervals: ["Monthly", "Annual"],
    active: true,
    expiresAt: "2027-12-31",
    maxUses: 100,
    uses: 14,
  },
  {
    code: "VIP20",
    type: "percent",
    value: 20,
    plans: ["plan-vip"],
    intervals: ["Monthly", "Annual"],
    active: true,
    expiresAt: "2026-12-31",
    maxUses: 20,
    uses: 4,
    requiresVip: true,
    firstPeriodOnly: true,
  },
  {
    code: "ANNUAL100",
    type: "fixed",
    valueCents: 10000,
    plans: ["plan-professional"],
    intervals: ["Annual"],
    active: true,
    expiresAt: "2026-12-31",
    maxUses: 50,
    uses: 9,
  },
  {
    code: "PARTNER100",
    type: "percent",
    value: 100,
    plans: ["plan-professional", "plan-vip"],
    intervals: ["Monthly", "Annual"],
    active: true,
    expiresAt: "2027-12-31",
    maxUses: 10,
    uses: 1,
    adminOnly: true,
  },
  {
    code: "EXPIRED25",
    type: "percent",
    value: 25,
    plans: ["plan-professional"],
    intervals: ["Annual"],
    active: false,
    expiresAt: "2026-01-01",
    maxUses: 10,
    uses: 10,
  },
];

const billingAddress = (name, company, email, country = "United States") => ({
  name,
  company,
  email,
  country,
  address1: "100 Production Avenue",
  address2: "",
  city: "Los Angeles",
  region: "CA",
  postalCode: "90028",
  taxId: "",
  purchaseOrder: "",
});

export const DEFAULT_MEMBERSHIP_BILLING_STATE = {
  version: 1,
  lastInvoiceNumber: 48,
  plans: MEMBERSHIP_PLANS,
  discounts: DISCOUNT_CODES,
  memberships: [
    {
      id: "membership-olivia",
      ownerType: "Organization",
      ownerId: "org-northstar",
      userId: "user-olivia",
      organizationId: "org-northstar",
      planId: "plan-vip",
      planName: "VIP Sync Access",
      billingInterval: "Annual",
      status: "Active",
      currency: "USD",
      listPriceCents: 299000,
      subtotalCents: 299000,
      discount: { code: "FOUNDING10", amountCents: 29900 },
      taxCents: 0,
      totalCents: 269100,
      startedAt: "2026-06-18T00:00:00.000Z",
      currentPeriodStart: "2026-06-18T00:00:00.000Z",
      currentPeriodEnd: "2027-06-18T00:00:00.000Z",
      cancelAtPeriodEnd: false,
      autoRenew: true,
      paymentMethodId: "pm-olivia-visa",
      billingContact: billingAddress(
        "Olivia Bennett",
        "Northstar Pictures",
        "billing@northstarpictures.com",
      ),
      verificationRequirement: "VIP Approved",
      entitlements: vipEntitlements,
      restrictions: [],
      nextInvoiceAt: "2027-06-18T00:00:00.000Z",
      nextInvoiceAmountCents: 269100,
      seats: 8,
      usedSeats: 5,
      metadata: { discountLabel: "Founding Buyer 10%" },
    },
    {
      id: "membership-ethan",
      ownerType: "Organization",
      ownerId: "org-brightframe",
      userId: "user-ethan",
      organizationId: "org-brightframe",
      planId: "plan-discovery",
      planName: "Discovery Access",
      billingInterval: "None",
      status: "Free",
      currency: "USD",
      listPriceCents: 0,
      subtotalCents: 0,
      discount: null,
      taxCents: 0,
      totalCents: 0,
      startedAt: "2026-07-10T00:00:00.000Z",
      currentPeriodStart: null,
      currentPeriodEnd: null,
      cancelAtPeriodEnd: false,
      autoRenew: false,
      paymentMethodId: null,
      billingContact: billingAddress(
        "Ethan Cole",
        "BrightFrame Agency",
        "ethan@brightframeagency.com",
      ),
      verificationRequirement: "Under Review",
      entitlements: discoveryEntitlements,
      restrictions: ["Professional features available after verification"],
      seats: 1,
      usedSeats: 1,
    },
    {
      id: "membership-sofia",
      ownerType: "Individual",
      ownerId: "user-sofia",
      userId: "user-sofia",
      organizationId: "org-lighthouse",
      planId: "plan-professional",
      planName: "Professional Buyer",
      billingInterval: "Monthly",
      status: "Active",
      currency: "USD",
      listPriceCents: 9900,
      subtotalCents: 9900,
      discount: null,
      taxCents: 0,
      totalCents: 9900,
      startedAt: "2026-07-01T00:00:00.000Z",
      currentPeriodStart: "2026-07-01T00:00:00.000Z",
      currentPeriodEnd: "2026-08-01T00:00:00.000Z",
      cancelAtPeriodEnd: false,
      autoRenew: true,
      paymentMethodId: "pm-sofia-mastercard",
      billingContact: billingAddress(
        "Sofia Martinez",
        "Lighthouse Creative",
        "sofia@lighthousecreative.co",
      ),
      verificationRequirement: "Additional Information Required",
      entitlements: professionalEntitlements,
      restrictions: [
        "Professional entitlements temporarily limited until verification is completed",
      ],
      nextInvoiceAt: "2026-08-01T00:00:00.000Z",
      nextInvoiceAmountCents: 9900,
      seats: 1,
      usedSeats: 1,
    },
    {
      id: "membership-rachel",
      ownerType: "Organization",
      ownerId: "org-orbit",
      userId: "user-rachel",
      organizationId: "org-orbit",
      planId: "plan-professional",
      planName: "Professional Buyer",
      billingInterval: "Monthly",
      status: "Past Due",
      currency: "USD",
      listPriceCents: 9900,
      subtotalCents: 9900,
      discount: null,
      taxCents: 0,
      totalCents: 9900,
      startedAt: "2026-05-12T00:00:00.000Z",
      currentPeriodStart: "2026-07-12T00:00:00.000Z",
      currentPeriodEnd: "2026-08-12T00:00:00.000Z",
      cancelAtPeriodEnd: false,
      autoRenew: true,
      paymentMethodId: "pm-rachel-expired",
      billingContact: billingAddress(
        "Rachel Kim",
        "Orbit Trailers",
        "rachel@orbittrailers.com",
      ),
      verificationRequirement: "Suspended / Reverification Required",
      entitlements: professionalEntitlements,
      restrictions: [
        "Secure delivery disabled",
        "Discovery access only while verification is suspended",
      ],
      failedPaymentAt: "2026-07-12T00:00:00.000Z",
      nextPaymentAttemptAt: "2026-07-18T00:00:00.000Z",
      gracePeriodEndsAt: "2026-07-22T00:00:00.000Z",
      outstandingBalanceCents: 9900,
      seats: 4,
      usedSeats: 3,
    },
    {
      id: "membership-daniel",
      ownerType: "Individual",
      ownerId: "user-daniel",
      userId: "user-daniel",
      organizationId: "org-independent",
      planId: "plan-professional",
      planName: "Professional Buyer",
      billingInterval: "Monthly",
      status: "Cancelling",
      currency: "USD",
      listPriceCents: 9900,
      subtotalCents: 9900,
      discount: null,
      taxCents: 0,
      totalCents: 9900,
      startedAt: "2026-06-30T00:00:00.000Z",
      currentPeriodStart: "2026-06-30T00:00:00.000Z",
      currentPeriodEnd: "2026-07-31T00:00:00.000Z",
      cancelAtPeriodEnd: true,
      cancelledAt: "2026-07-14T00:00:00.000Z",
      autoRenew: false,
      paymentMethodId: "pm-daniel-visa",
      billingContact: billingAddress(
        "Daniel Brooks",
        "Self-employed",
        "daniel@independentmail.com",
      ),
      verificationRequirement: "Rejected",
      entitlements: professionalEntitlements,
      restrictions: [
        "Effective access is Discovery only due to verification decision",
      ],
      cancellationReason: "Verification issue",
      seats: 1,
      usedSeats: 1,
    },
    {
      id: "membership-partner",
      ownerType: "Organization",
      ownerId: "org-partner-demo",
      userId: null,
      organizationId: "org-partner-demo",
      planId: "plan-vip",
      planName: "VIP Sync Access",
      billingInterval: "Annual review",
      status: "Complimentary",
      currency: "USD",
      listPriceCents: 0,
      subtotalCents: 0,
      discount: { code: "PARTNER100", amountCents: 299000 },
      taxCents: 0,
      totalCents: 0,
      startedAt: "2026-07-01T00:00:00.000Z",
      currentPeriodStart: "2026-07-01T00:00:00.000Z",
      currentPeriodEnd: "2027-01-01T00:00:00.000Z",
      cancelAtPeriodEnd: false,
      autoRenew: false,
      paymentMethodId: null,
      billingContact: billingAddress(
        "Strategic Partner Team",
        "Internal Demo Strategic Partner",
        "partner@example.com",
      ),
      verificationRequirement: "Senior-approved strategic partner",
      entitlements: vipEntitlements,
      restrictions: ["Review required January 2027"],
      complimentaryReason: "Strategic Partner Access",
      grantedBy: "Preston Repenning",
      nextReviewAt: "2027-01-01T00:00:00.000Z",
      seats: 10,
      usedSeats: 6,
    },
  ],
  paymentMethods: [
    {
      id: "pm-olivia-visa",
      userId: "user-olivia",
      organizationId: "org-northstar",
      brand: "Visa",
      last4: "4242",
      expiryMonth: 12,
      expiryYear: 2029,
      cardholderName: "Olivia Bennett",
      token: "pm_demo_olivia_4242",
      default: true,
      status: "Valid",
      billingPostalCode: "90028",
    },
    {
      id: "pm-sofia-mastercard",
      userId: "user-sofia",
      organizationId: "org-lighthouse",
      brand: "Mastercard",
      last4: "5100",
      expiryMonth: 9,
      expiryYear: 2028,
      cardholderName: "Sofia Martinez",
      token: "pm_demo_sofia_5100",
      default: true,
      status: "Valid",
      billingPostalCode: "10001",
    },
    {
      id: "pm-rachel-expired",
      userId: "user-rachel",
      organizationId: "org-orbit",
      brand: "Visa",
      last4: "1111",
      expiryMonth: 3,
      expiryYear: 2026,
      cardholderName: "Rachel Kim",
      token: "pm_demo_rachel_1111",
      default: true,
      status: "Expired",
      billingPostalCode: "10012",
    },
    {
      id: "pm-daniel-visa",
      userId: "user-daniel",
      organizationId: "org-independent",
      brand: "Visa",
      last4: "4242",
      expiryMonth: 8,
      expiryYear: 2028,
      cardholderName: "Daniel Brooks",
      token: "pm_demo_daniel_4242",
      default: true,
      status: "Valid",
      billingPostalCode: "60601",
    },
  ],
  invoices: [
    {
      id: "invoice-olivia",
      number: "BM-INV-2026-0042",
      membershipId: "membership-olivia",
      userId: "user-olivia",
      organizationId: "org-northstar",
      planName: "VIP Sync Access",
      invoiceDate: "2026-06-18T00:00:00.000Z",
      dueDate: "2026-06-18T00:00:00.000Z",
      currency: "USD",
      lineItems: [
        {
          description: "VIP Sync Access — annual membership",
          quantity: 1,
          amountCents: 299000,
        },
      ],
      subtotalCents: 299000,
      discountCents: 29900,
      taxCents: 0,
      totalCents: 269100,
      amountPaidCents: 269100,
      balanceDueCents: 0,
      status: "Paid",
      paymentMethodId: "pm-olivia-visa",
      transactionReference: "BM-TXN-0042",
      billingSnapshot: billingAddress(
        "Olivia Bennett",
        "Northstar Pictures",
        "billing@northstarpictures.com",
      ),
      notes: "Membership fees do not include track licence fees.",
    },
    {
      id: "invoice-sofia",
      number: "BM-INV-2026-0045",
      membershipId: "membership-sofia",
      userId: "user-sofia",
      organizationId: "org-lighthouse",
      planName: "Professional Buyer",
      invoiceDate: "2026-07-01T00:00:00.000Z",
      dueDate: "2026-07-01T00:00:00.000Z",
      currency: "USD",
      lineItems: [
        {
          description: "Professional Buyer — monthly membership",
          quantity: 1,
          amountCents: 9900,
        },
      ],
      subtotalCents: 9900,
      discountCents: 0,
      taxCents: 0,
      totalCents: 9900,
      amountPaidCents: 9900,
      balanceDueCents: 0,
      status: "Paid",
      paymentMethodId: "pm-sofia-mastercard",
      transactionReference: "BM-TXN-0045",
      billingSnapshot: billingAddress(
        "Sofia Martinez",
        "Lighthouse Creative",
        "sofia@lighthousecreative.co",
      ),
      notes: "Professional access remains subject to buyer verification.",
    },
    {
      id: "invoice-rachel",
      number: "BM-INV-2026-0048",
      membershipId: "membership-rachel",
      userId: "user-rachel",
      organizationId: "org-orbit",
      planName: "Professional Buyer",
      invoiceDate: "2026-07-12T00:00:00.000Z",
      dueDate: "2026-07-12T00:00:00.000Z",
      currency: "USD",
      lineItems: [
        {
          description: "Professional Buyer — monthly renewal",
          quantity: 1,
          amountCents: 9900,
        },
      ],
      subtotalCents: 9900,
      discountCents: 0,
      taxCents: 0,
      totalCents: 9900,
      amountPaidCents: 0,
      balanceDueCents: 9900,
      status: "Past Due",
      paymentMethodId: "pm-rachel-expired",
      transactionReference: "BM-TXN-0048",
      billingSnapshot: billingAddress(
        "Rachel Kim",
        "Orbit Trailers",
        "rachel@orbittrailers.com",
      ),
      notes: "Payment retry scheduled for 18 July 2026.",
    },
    {
      id: "invoice-daniel",
      number: "BM-INV-2026-0046",
      membershipId: "membership-daniel",
      userId: "user-daniel",
      organizationId: "org-independent",
      planName: "Professional Buyer",
      invoiceDate: "2026-06-30T00:00:00.000Z",
      dueDate: "2026-06-30T00:00:00.000Z",
      currency: "USD",
      lineItems: [
        {
          description: "Professional Buyer — monthly membership",
          quantity: 1,
          amountCents: 9900,
        },
      ],
      subtotalCents: 9900,
      discountCents: 0,
      taxCents: 0,
      totalCents: 9900,
      amountPaidCents: 9900,
      balanceDueCents: 0,
      status: "Paid",
      paymentMethodId: "pm-daniel-visa",
      transactionReference: "BM-TXN-0046",
      billingSnapshot: billingAddress(
        "Daniel Brooks",
        "Self-employed",
        "daniel@independentmail.com",
      ),
      notes: "Cancellation scheduled at period end.",
    },
  ],
  transactions: [
    {
      id: "txn-olivia",
      membershipId: "membership-olivia",
      invoiceId: "invoice-olivia",
      userId: "user-olivia",
      organizationId: "org-northstar",
      type: "Charge",
      amountCents: 269100,
      currency: "USD",
      status: "Succeeded",
      paymentMethodId: "pm-olivia-visa",
      createdAt: "2026-06-18T00:00:00.000Z",
      processedAt: "2026-06-18T00:00:05.000Z",
      metadata: { reference: "BM-TXN-0042" },
    },
    {
      id: "txn-sofia",
      membershipId: "membership-sofia",
      invoiceId: "invoice-sofia",
      userId: "user-sofia",
      organizationId: "org-lighthouse",
      type: "Charge",
      amountCents: 9900,
      currency: "USD",
      status: "Succeeded",
      paymentMethodId: "pm-sofia-mastercard",
      createdAt: "2026-07-01T00:00:00.000Z",
      processedAt: "2026-07-01T00:00:03.000Z",
      metadata: { reference: "BM-TXN-0045" },
    },
    {
      id: "txn-rachel",
      membershipId: "membership-rachel",
      invoiceId: "invoice-rachel",
      userId: "user-rachel",
      organizationId: "org-orbit",
      type: "Charge",
      amountCents: 9900,
      currency: "USD",
      status: "Failed",
      paymentMethodId: "pm-rachel-expired",
      createdAt: "2026-07-12T00:00:00.000Z",
      processedAt: "2026-07-12T00:00:02.000Z",
      failureCode: "expired_card",
      failureMessage: "The saved payment method has expired.",
      metadata: { reference: "BM-TXN-0048" },
    },
  ],
  enterpriseInquiries: [],
  refunds: [],
  checkoutSessions: [],
  audit: [
    {
      id: "billing-audit-1",
      membershipId: "membership-rachel",
      userId: "user-rachel",
      organizationId: "org-orbit",
      actor: "Billing simulation",
      timestamp: "2026-07-12T00:00:02.000Z",
      action: "Payment failed",
      description: "Renewal payment failed because the saved card expired.",
      before: "Active",
      after: "Past Due",
      source: "Mock renewal",
      status: "Failed",
    },
    {
      id: "billing-audit-2",
      membershipId: "membership-daniel",
      userId: "user-daniel",
      organizationId: "org-independent",
      actor: "Daniel Brooks",
      timestamp: "2026-07-14T12:00:00.000Z",
      action: "Cancellation scheduled",
      description: "Membership will end at the current period close.",
      before: "Active",
      after: "Cancelling",
      source: "Buyer billing portal",
      status: "Succeeded",
    },
  ],
};

export const BILLING_FAQS = [
  [
    "Does membership include music licence fees?",
    "No. Membership controls platform access and service level. Every track licence is quoted separately.",
  ],
  [
    "Can I cancel at any time?",
    "Yes. Standard cancellations take effect at the current billing-period end, unless authorized support applies another arrangement.",
  ],
  [
    "Is VIP access automatically approved?",
    "No. VIP requires eligible buyer verification and senior approval.",
  ],
  [
    "What happens if buyer verification is pending?",
    "Billing can be active while professional tools remain limited to Discovery access until verification is approved.",
  ],
  [
    "Can I change plans later?",
    "Yes. Upgrades may apply immediately with simulated proration; downgrades normally apply at period end.",
  ],
  [
    "Are masters and stems included?",
    "Delivery eligibility depends on membership, buyer approval, project approval, rights review, and licence conditions.",
  ],
  [
    "Can my company pay by invoice?",
    "Enterprise and approved organization accounts can request manual invoicing.",
  ],
  [
    "What happens after a failed payment?",
    "A grace period may preserve limited visibility while premium actions and secure delivery are restricted.",
  ],
  [
    "Can I receive a refund?",
    "Refunds are reviewed by authorized billing staff and do not automatically cancel a membership.",
  ],
  [
    "Can multiple team members share a membership?",
    "Eligible organization plans support controlled seats; credentials must never be shared.",
  ],
];
