export const PRIVACY_STORAGE_KEY = "beatmondo-compliance-privacy-v1";
export const SELECTED_PRIVACY_REQUEST_KEY =
  "beatmondo-selected-privacy-request";
export const PRIVACY_CODE = "739184";

export const DATA_CATEGORIES = [
  "Identity",
  "Contact",
  "Account",
  "Authentication",
  "Organization",
  "Buyer Verification",
  "Artist Profile",
  "Contributor",
  "Project",
  "Catalog",
  "Rights and Ownership",
  "Contractual",
  "Financial",
  "Payment",
  "Licence",
  "Delivery",
  "Usage and Activity",
  "Search",
  "Preview",
  "Communication",
  "Device and Session",
  "Security",
  "Audit",
  "Support",
  "Marketing Preference",
  "Uploaded Document",
  "Analytics",
];
export const SENSITIVITY_LEVELS = [
  "Public",
  "Internal",
  "Confidential",
  "Highly Confidential",
  "Restricted",
];
export const LEGAL_BASIS_PLACEHOLDERS = [
  "Consent",
  "Contractual Necessity",
  "Legal Obligation Placeholder",
  "Legitimate Interest Placeholder",
  "Vital Interest Placeholder",
  "Public Interest Placeholder",
  "Not Applicable",
  "Requires Legal Review",
];

const classification = (category, sensitivity, overrides = {}) => ({
  id: `classification-${category.toLowerCase().replaceAll(" ", "-")}`,
  key: category.toLowerCase().replaceAll(" ", "_"),
  name: category,
  description: `${category} data used by represented beatmondo workflows.`,
  category,
  sensitivity,
  personalData: !["Catalog"].includes(category),
  confidential: !["Catalog"].includes(category),
  financial: ["Financial", "Payment"].includes(category),
  legal: ["Contractual", "Licence", "Rights and Ownership"].includes(category),
  security: [
    "Authentication",
    "Security",
    "Audit",
    "Device and Session",
  ].includes(category),
  retentionClass:
    overrides.retentionClass ||
    (sensitivity === "Restricted"
      ? "Long-term restricted"
      : "Standard operational"),
  defaultPurposeIds: overrides.purposes || [],
  allowedRoles: overrides.allowedRoles || [
    "privacy_administrator",
    "super_administrator",
  ],
  exportable: overrides.exportable ?? !["Security", "Audit"].includes(category),
  correctable:
    overrides.correctable ??
    [
      "Identity",
      "Contact",
      "Account",
      "Organization",
      "Artist Profile",
      "Contributor",
    ].includes(category),
  deletable:
    overrides.deletable ??
    ["Marketing Preference", "Search", "Preview", "Analytics"].includes(
      category,
    ),
  anonymizable: overrides.anonymizable ?? true,
  requiresLegalReview:
    overrides.requiresLegalReview ??
    [
      "Rights and Ownership",
      "Contractual",
      "Financial",
      "Payment",
      "Licence",
      "Audit",
    ].includes(category),
  active: true,
});

export const DEFAULT_CLASSIFICATIONS = DATA_CATEGORIES.map((category) =>
  classification(
    category,
    [
      "Identity",
      "Buyer Verification",
      "Rights and Ownership",
      "Payment",
      "Security",
      "Audit",
      "Uploaded Document",
    ].includes(category)
      ? "Highly Confidential"
      : [
            "Authentication",
            "Contractual",
            "Financial",
            "Licence",
            "Device and Session",
          ].includes(category)
        ? "Restricted"
        : category === "Catalog"
          ? "Public"
          : "Confidential",
  ),
);

const inventory = (
  fieldKey,
  displayName,
  dataCategory,
  sourceModule,
  sensitivity,
  deletionBehavior,
  retentionRuleId,
  overrides = {},
) => ({
  id: `inventory-${fieldKey.replaceAll(".", "-")}`,
  dataCategory,
  fieldKey,
  displayName,
  sourceModule,
  sourceEntityType: overrides.sourceEntityType || sourceModule,
  purposeIds: overrides.purposeIds || [],
  legalBasisIds: overrides.legalBasisIds || ["Requires Legal Review"],
  sensitivity,
  personalData: true,
  userVisible: overrides.userVisible ?? true,
  exportable: overrides.exportable ?? true,
  correctable: overrides.correctable ?? false,
  deletionBehavior,
  retentionRuleId,
  sharedWithVendorIds: overrides.sharedWithVendorIds || [],
  notes: overrides.notes || "Prototype inventory mapping.",
});

export const DEFAULT_DATA_INVENTORY = [
  inventory(
    "user.name",
    "Name",
    "Identity",
    "Authentication",
    "Confidential",
    "Correct or anonymize",
    "retention-account",
    { correctable: true },
  ),
  inventory(
    "user.email",
    "Email",
    "Contact",
    "Authentication",
    "Confidential",
    "Correct or anonymize",
    "retention-account",
    { correctable: true },
  ),
  inventory(
    "user.phone",
    "Phone",
    "Contact",
    "Profile",
    "Confidential",
    "Delete when nonessential",
    "retention-account",
    { correctable: true },
  ),
  inventory(
    "user.loginHistory",
    "Login history",
    "Authentication",
    "Authentication",
    "Restricted",
    "Retain security summary",
    "retention-security",
    { exportable: true },
  ),
  inventory(
    "verification.documents",
    "Verification documents",
    "Buyer Verification",
    "Buyer Verification",
    "Highly Confidential",
    "Retain pending legal review",
    "retention-verification",
    { sharedWithVendorIds: ["vendor-identity"] },
  ),
  inventory(
    "artist.legalName",
    "Artist legal name",
    "Artist Profile",
    "Track Ingestion",
    "Highly Confidential",
    "Rights review required",
    "retention-rights",
    { correctable: true },
  ),
  inventory(
    "rights.ownership",
    "Contributor and ownership splits",
    "Rights and Ownership",
    "Rights Database",
    "Highly Confidential",
    "Retain ownership history",
    "retention-rights",
    { correctable: true },
  ),
  inventory(
    "project.name",
    "Buyer project name",
    "Project",
    "Buyer Projects",
    "Confidential",
    "Retain while commercially active",
    "retention-contractual",
  ),
  inventory(
    "contract.signer",
    "Signer identity",
    "Contractual",
    "Contracts",
    "Highly Confidential",
    "Retain contract version",
    "retention-contractual",
    { correctable: true },
  ),
  inventory(
    "contract.signature",
    "Signature evidence",
    "Contractual",
    "Contracts",
    "Restricted",
    "Retain; raw asset excluded",
    "retention-contractual",
    { exportable: false },
  ),
  inventory(
    "payment.billingContact",
    "Billing contact",
    "Financial",
    "Payments",
    "Highly Confidential",
    "Correct; retain invoice history",
    "retention-financial",
    { correctable: true },
  ),
  inventory(
    "payment.methodMetadata",
    "Payment method metadata",
    "Payment",
    "Payments",
    "Restricted",
    "Retain redacted metadata",
    "retention-financial",
    { exportable: false, sharedWithVendorIds: ["vendor-payment"] },
  ),
  inventory(
    "licence.parties",
    "Licence parties",
    "Licence",
    "Licence Generation",
    "Highly Confidential",
    "Retain original parties",
    "retention-contractual",
  ),
  inventory(
    "delivery.downloadHistory",
    "Download history",
    "Delivery",
    "Secure Delivery",
    "Confidential",
    "Retain safe access history",
    "retention-security",
  ),
  inventory(
    "search.history",
    "Search history",
    "Search",
    "Search Infrastructure",
    "Confidential",
    "Delete after operational period",
    "retention-activity",
  ),
  inventory(
    "preview.history",
    "Preview history",
    "Preview",
    "Watermarked Previews",
    "Confidential",
    "Delete after operational period",
    "retention-activity",
  ),
  inventory(
    "email.messages",
    "Notification history",
    "Communication",
    "Email Notifications",
    "Confidential",
    "Archive after operational period",
    "retention-email",
  ),
  inventory(
    "audit.events",
    "Audit activity",
    "Audit",
    "Audit Logging",
    "Restricted",
    "Preserve by event class",
    "retention-audit",
    { exportable: false },
  ),
  inventory(
    "analytics.events",
    "Optional analytics events",
    "Analytics",
    "Analytics & Reporting",
    "Confidential",
    "Anonymize or aggregate",
    "retention-activity",
  ),
];

const purposeNames = [
  ["account-auth", "Account creation and authentication", true, false, true],
  ["buyer-verification", "Buyer verification", true, false, true],
  ["artist-onboarding", "Artist onboarding", true, false, true],
  ["catalog-publication", "Catalog publication", true, false, true],
  ["rights-verification", "Rights verification", true, false, true],
  ["licensing-requests", "Licensing-request management", true, false, true],
  ["quote-preparation", "Quote preparation", true, false, true],
  ["contract-execution", "Contract execution", true, false, true],
  ["payment-processing", "Payment processing", true, false, true],
  ["licence-issuance", "Licence issuance", true, false, true],
  ["secure-delivery", "Secure asset delivery", true, false, true],
  ["customer-support", "Customer support", true, false, false],
  ["security-monitoring", "Security monitoring", true, false, false],
  ["audit-logging", "Audit logging", true, false, false],
  ["operational-analytics", "Operational analytics", true, false, false],
  ["product-updates", "Optional product updates", false, true, false],
  [
    "marketing-communication",
    "Optional marketing communication",
    false,
    true,
    false,
  ],
  ["renewal-reminders", "Licence-renewal reminders", true, false, true],
  [
    "fraud-prevention",
    "Fraud and abuse prevention simulation",
    true,
    false,
    false,
  ],
  ["legal-preservation", "Legal-claim preservation", true, false, false],
];
export const DEFAULT_PROCESSING_PURPOSES = purposeNames.map(
  ([key, name, required, consentRequired, contractual], index) => ({
    id: `purpose-${key}`,
    key,
    name,
    description: `Prototype processing purpose for ${name.toLowerCase()}.`,
    category: index < 5 ? "Platform" : "Operations",
    required,
    consentRequired,
    contractual,
    legalObligationPlaceholder: key === "legal-preservation",
    legitimateInterestPlaceholder: [
      "security-monitoring",
      "operational-analytics",
      "fraud-prevention",
    ].includes(key),
    dataCategories: [],
    retentionRuleIds: [],
    status: "Active",
    version: 1,
    legalBasis: consentRequired
      ? "Consent"
      : contractual
        ? "Contractual Necessity"
        : "Requires Legal Review",
  }),
);

const noticeTypes = [
  "General Privacy Notice",
  "Buyer Privacy Notice",
  "Artist Privacy Notice",
  "Verification Privacy Notice",
  "Payment Privacy Notice",
  "Cookie and Analytics Notice",
  "Email Communication Notice",
  "Signature and Contract Notice",
  "Secure Delivery Notice",
  "Internal Workforce Privacy Notice",
];
export const DEFAULT_PRIVACY_NOTICES = noticeTypes.map((name, index) => ({
  id: `notice-${index + 1}`,
  key: name.toLowerCase().replaceAll(" ", "-"),
  name,
  audience:
    index === 2
      ? "Artists"
      : index === 9
        ? "Internal workforce"
        : index === 1
          ? "Buyers"
          : "All relevant users",
  version: index === 0 ? 2 : 1,
  status: "Active",
  effectiveFrom: "2026-07-01T00:00:00.000Z",
  effectiveTo: null,
  content: `${name} explains the categories, purposes, choices, retention placeholders, and contact routes represented by this prototype. It does not provide jurisdiction-specific legal advice.`,
  summary: `Plain-language summary of ${name.toLowerCase()}.`,
  processingPurposeIds: DEFAULT_PROCESSING_PURPOSES.slice(0, 6).map(
    (item) => item.id,
  ),
  requiredAcknowledgment: index < 5,
  languages: ["English"],
  createdAt: "2026-06-15T09:00:00.000Z",
  createdBy: "Priya Nair",
  approvedAt: "2026-06-25T09:00:00.000Z",
  approvedBy: "Eleanor Shaw",
}));

const consent = (id, userId, purposeId, status, overrides = {}) => ({
  id,
  userId,
  organizationId: overrides.organizationId || null,
  purposeId,
  consentType: overrides.consentType || "Optional preference",
  status,
  noticeId: overrides.noticeId || "notice-6",
  noticeVersion: 1,
  grantedAt: status === "Granted" ? "2026-07-01T10:00:00.000Z" : null,
  withdrawnAt: status === "Withdrawn" ? "2026-07-10T10:00:00.000Z" : null,
  expiresAt: null,
  source: "Privacy settings",
  evidence: { method: "Explicit toggle", prototype: true },
  metadata: { essential: false },
  ...overrides,
});
export const DEFAULT_CONSENTS = [
  consent(
    "consent-olivia-analytics",
    "user-olivia",
    "purpose-operational-analytics",
    "Granted",
    { organizationId: "org-northstar", consentType: "Optional analytics" },
  ),
  consent(
    "consent-olivia-updates",
    "user-olivia",
    "purpose-product-updates",
    "Granted",
    { organizationId: "org-northstar", consentType: "Product updates" },
  ),
  consent(
    "consent-olivia-marketing",
    "user-olivia",
    "purpose-marketing-communication",
    "Withdrawn",
    {
      organizationId: "org-northstar",
      consentType: "Optional marketing email",
    },
  ),
  consent(
    "consent-marcus-analytics",
    "user-marcus",
    "purpose-operational-analytics",
    "Granted",
    { organizationId: "org-smyrk", consentType: "Optional analytics" },
  ),
  consent(
    "consent-sofia-marketing",
    "user-sofia",
    "purpose-marketing-communication",
    "Withdrawn",
    {
      organizationId: "org-lighthouse",
      consentType: "Optional marketing email",
    },
  ),
];

const request = (
  id,
  reference,
  requestType,
  userId,
  status,
  overrides = {},
) => ({
  id,
  reference,
  requestType,
  requesterUserId: userId,
  requesterOrganizationId: overrides.organizationId || null,
  subjectUserId: overrides.subjectUserId || userId,
  status,
  priority: overrides.priority || "Normal",
  submittedAt: overrides.submittedAt || "2026-07-01T10:00:00.000Z",
  dueAt: overrides.dueAt || "2026-07-31T23:59:59.000Z",
  identityVerificationStatus:
    overrides.identityVerificationStatus || "Verified",
  scope: overrides.scope || ["Personal data"],
  requestedDetails: overrides.requestedDetails || requestType,
  relatedEntityIds: overrides.relatedEntityIds || [],
  assignedTo: overrides.assignedTo || "Privacy Administrator",
  reviewers: overrides.reviewers || [],
  blockers: overrides.blockers || [],
  decisions: overrides.decisions || [],
  exportId: overrides.exportId || null,
  deletionPlanId: overrides.deletionPlanId || null,
  resolutionSummary: overrides.resolutionSummary || null,
  completedAt: overrides.completedAt || null,
  closedAt: null,
  metadata: { legalDeadlineDisclaimer: true },
  ...overrides,
});
export const DEFAULT_PRIVACY_REQUESTS = [
  request(
    "privacy-request-1",
    "BM-PRIV-2026-0001",
    "Access Request",
    "user-olivia",
    "Completed",
    {
      organizationId: "org-northstar",
      exportId: "privacy-export-1",
      completedAt: "2026-07-12T12:00:00.000Z",
      resolutionSummary:
        "Personal and commercial records included; restricted security investigation details excluded.",
    },
  ),
  request(
    "privacy-request-2",
    "BM-PRIV-2026-0002",
    "Correction Request",
    "user-marcus",
    "Under Review",
    {
      requestedDetails: "Correct legal surname on contributor record",
      scope: ["Contributor", "Rights and Ownership"],
      assignedTo: "Rights Manager",
      blockers: ["Rights-manager approval required"],
    },
  ),
  request(
    "privacy-request-3",
    "BM-PRIV-2026-0003",
    "Deletion Request",
    "user-daniel",
    "Partially Approved",
    {
      deletionPlanId: "deletion-plan-1",
      blockers: [
        "Financial-retention placeholder",
        "Contractual-retention placeholder",
        "Audit-retention requirement",
      ],
      resolutionSummary:
        "Optional preferences and saved searches eligible; invoices, payment, contract, licence, and audit history retained.",
    },
  ),
  request(
    "privacy-request-4",
    "BM-PRIV-2026-0004",
    "Marketing Opt-Out",
    "user-sofia",
    "Completed",
    {
      completedAt: "2026-07-10T10:00:00.000Z",
      resolutionSummary:
        "Optional marketing withdrawn; transactional communication remains active.",
    },
  ),
  request(
    "privacy-request-5",
    "BM-PRIV-2026-0005",
    "Restriction Request",
    "user-rachel",
    "Legal Review Required",
    {
      scope: ["Optional analytics", "Recommendation profiling"],
      blockers: ["Rights-disputed project", "Payment issue"],
      assignedTo: "Legal Reviewer",
    },
  ),
  request(
    "privacy-request-6",
    "BM-PRIV-2026-0006",
    "Data Export",
    "user-olivia",
    "Ready for Approval",
    {
      organizationId: "org-northstar",
      scope: [
        "Organization projects",
        "Quotes",
        "Contracts",
        "Licences",
        "Invoices",
        "Deliveries",
      ],
      identityVerificationStatus: "Verified",
      blockers: ["Internal-only notes excluded"],
    },
  ),
  request(
    "privacy-request-7",
    "BM-PRIV-2026-0007",
    "Account Closure",
    "user-dummy",
    "Identity Verification Required",
    {
      identityVerificationStatus: "Required",
      blockers: ["Identity must be verified before deletion review"],
    },
  ),
  request(
    "privacy-request-8",
    "BM-PRIV-2026-0008",
    "Privacy Complaint",
    "user-marcus",
    "Security Review Required",
    {
      relatedEntityIds: ["privacy-incident-1"],
      assignedTo: "Security Administrator",
      priority: "High",
      requestedDetails:
        "Artist profile contact field appeared unexpectedly in an internal workflow.",
    },
  ),
];

export const DEFAULT_RETENTION_RULES = [
  [
    "retention-account",
    "User account",
    "Account closure",
    24,
    "Months",
    "Review Required",
  ],
  [
    "retention-verification",
    "Buyer verification",
    "Account closure",
    5,
    "Years",
    "Review Required",
  ],
  [
    "retention-contractual",
    "Contracts and licences",
    "Contract completion",
    10,
    "Years Placeholder",
    "Retain",
  ],
  [
    "retention-financial",
    "Financial records",
    "Transaction completion",
    7,
    "Years Placeholder",
    "Archive",
  ],
  [
    "retention-activity",
    "Search and preview activity",
    "Activity recorded",
    12,
    "Months",
    "Delete",
  ],
  [
    "retention-security",
    "Temporary access and security",
    "Access expiry",
    12,
    "Months",
    "Archive",
  ],
  [
    "retention-email",
    "Email notification logs",
    "Message completed",
    24,
    "Months",
    "Archive",
  ],
  [
    "retention-audit",
    "Audit records",
    "Event class trigger",
    3,
    "Years Placeholder",
    "Review Required",
  ],
  [
    "retention-rights",
    "Rights and ownership records",
    "Rights relationship ended",
    10,
    "Years Placeholder",
    "Retain",
  ],
].map(([id, name, triggerEvent, duration, durationUnit, actionAtExpiry]) => ({
  id,
  key: id,
  name,
  description: `Prototype retention rule for ${name.toLowerCase()}.`,
  dataCategories: [name],
  sourceModules: [name],
  triggerEvent,
  duration,
  durationUnit,
  actionAtExpiry,
  legalReviewRequired: ["Review Required", "Retain"].includes(actionAtExpiry),
  legalHoldAware: true,
  status: "Active",
  version: 1,
  disclaimer:
    "Prototype configuration — requires jurisdiction-specific legal review.",
}));

export const DEFAULT_LEGAL_HOLDS = [
  {
    id: "legal-hold-1",
    reference: "BM-HOLD-2026-0001",
    name: "Rights dispute preservation",
    reason:
      "Preserve rights, contract, payment, and audit evidence for an active simulated dispute.",
    status: "Active",
    relatedCaseReference: "CASE-RIGHTS-009",
    subjectUserIds: ["user-rachel"],
    organizationIds: ["org-orbit"],
    entityScopes: ["rights-disputed-project"],
    dataCategories: [
      "Rights and Ownership",
      "Contractual",
      "Financial",
      "Audit",
    ],
    createdAt: "2026-07-05T10:00:00.000Z",
    createdBy: "Eleanor Shaw",
    approvedBy: "Preston Repenning",
    reviewDate: "2026-08-05",
    releasedAt: null,
    releaseReason: null,
  },
  {
    id: "legal-hold-2",
    reference: "BM-HOLD-2026-0002",
    name: "Incident evidence review",
    reason: "Preserve restricted delivery-access evidence.",
    status: "Under Review",
    relatedCaseReference: "INC-DELIVERY-004",
    subjectUserIds: [],
    organizationIds: ["org-northstar"],
    entityScopes: ["delivery-access"],
    dataCategories: ["Security", "Delivery", "Audit"],
    createdAt: "2026-07-14T10:00:00.000Z",
    createdBy: "Aman Verma",
    approvedBy: "Eleanor Shaw",
    reviewDate: "2026-07-28",
    releasedAt: null,
    releaseReason: null,
  },
];

const vendorNames = [
  ["vendor-payment", "Payment Processing Provider Placeholder", "Payment"],
  ["vendor-email", "Email Delivery Provider Placeholder", "Email"],
  ["vendor-storage", "Cloud Storage Provider Placeholder", "Storage"],
  [
    "vendor-identity",
    "Identity Verification Provider Placeholder",
    "Identity verification",
  ],
  ["vendor-signature", "E-Signature Provider Placeholder", "Signature"],
  ["vendor-analytics", "Analytics Provider Placeholder", "Analytics"],
  ["vendor-support", "Customer Support Provider Placeholder", "Support"],
];
export const DEFAULT_VENDORS = vendorNames.map(
  ([id, name, category], index) => ({
    id,
    name,
    category,
    status: index === 5 ? "Under Review" : "Active",
    purposeIds: [],
    dataCategories: [category],
    regions:
      index % 2 ? ["European Union"] : ["United States", "Global Placeholder"],
    contractStatus: index === 5 ? "Under Review" : "Prototype terms recorded",
    securityReviewStatus: index === 5 ? "Due" : "Reviewed",
    privacyReviewStatus: index === 5 ? "Due" : "Reviewed",
    retentionNotes: "Prototype retention mapping",
    transferMechanismPlaceholder: "Requires Legal Review",
    owner: index === 5 ? "Privacy Administrator" : "Operations Owner",
    reviewDate: index === 5 ? "2026-07-25" : "2027-01-15",
    metadata: { simulated: true },
  }),
);

export const DEFAULT_PRIVACY_INCIDENTS = [
  {
    id: "privacy-incident-1",
    reference: "BM-INC-PRIV-2026-0001",
    title: "Incorrect internal field visibility",
    description:
      "Artist contact field appeared in an internal catalog table for an unauthorized support role.",
    status: "Resolved",
    severity: "Moderate",
    detectedAt: "2026-07-08T10:00:00.000Z",
    reportedBy: "Marcus Hale",
    affectedModules: ["Catalog"],
    affectedDataCategories: ["Contact"],
    affectedUserIds: ["user-marcus"],
    affectedOrganizationIds: ["org-smyrk"],
    approximateRecordCount: 1,
    containmentActions: [
      "Field-level permission corrected",
      "Access reviewed",
      "Audit events checked",
    ],
    investigationNotes: "Restricted internal note",
    notificationsRequiredPlaceholder: "Requires Legal Review",
    owner: "Aman Verma",
    reviewers: ["Priya Nair"],
    resolvedAt: "2026-07-10T12:00:00.000Z",
    postIncidentReview: "Completed",
  },
  {
    id: "privacy-incident-2",
    reference: "BM-INC-PRIV-2026-0002",
    title: "Repeated unauthorized delivery access",
    description:
      "Multiple organization-mismatch attempts against expiring delivery access.",
    status: "Investigating",
    severity: "High",
    detectedAt: "2026-07-15T10:00:00.000Z",
    reportedBy: "Security Monitoring",
    affectedModules: ["Expiring URLs", "Secure Delivery"],
    affectedDataCategories: ["Security", "Delivery"],
    affectedUserIds: [],
    affectedOrganizationIds: ["org-northstar"],
    approximateRecordCount: 5,
    containmentActions: ["Session review started"],
    investigationNotes: "Restricted",
    notificationsRequiredPlaceholder: "Requires Legal Review",
    owner: "Aman Verma",
    reviewers: ["Priya Nair"],
    resolvedAt: null,
    postIncidentReview: null,
  },
  {
    id: "privacy-incident-3",
    reference: "BM-INC-PRIV-2026-0003",
    title: "Email recipient error simulation",
    description:
      "Internal test notification resolved an inactive recipient; no real email was sent.",
    status: "Contained",
    severity: "Moderate",
    detectedAt: "2026-07-13T10:00:00.000Z",
    reportedBy: "Email Queue",
    affectedModules: ["Email Notifications"],
    affectedDataCategories: ["Communication"],
    affectedUserIds: [],
    affectedOrganizationIds: [],
    approximateRecordCount: 1,
    containmentActions: ["Queue paused", "Recipient rule corrected"],
    investigationNotes: "Prototype only",
    notificationsRequiredPlaceholder: "Not Applicable",
    owner: "Priya Nair",
    reviewers: ["Aman Verma"],
    resolvedAt: null,
    postIncidentReview: null,
  },
  {
    id: "privacy-incident-4",
    reference: "BM-INC-PRIV-2026-0004",
    title: "Lost browser-persisted session simulation",
    description:
      "No production data involved; used to exercise incident workflow.",
    status: "Closed",
    severity: "Low",
    detectedAt: "2026-07-01T10:00:00.000Z",
    reportedBy: "Demo Automation",
    affectedModules: ["Authentication"],
    affectedDataCategories: ["Device and Session"],
    affectedUserIds: [],
    affectedOrganizationIds: [],
    approximateRecordCount: 0,
    containmentActions: ["Demo session cleared"],
    investigationNotes: "Simulation",
    notificationsRequiredPlaceholder: "Not Applicable",
    owner: "Aman Verma",
    reviewers: [],
    resolvedAt: "2026-07-01T11:00:00.000Z",
    postIncidentReview: "Completed",
  },
];

export const DEFAULT_ASSESSMENTS = [
  {
    id: "assessment-1",
    reference: "BM-PIA-2026-0001",
    title: "Buyer engagement indicator review",
    assessmentType: "New analytics use",
    owner: "Priya Nair",
    status: "Mitigation Required",
    processingPurposes: ["purpose-operational-analytics"],
    dataCategories: ["Analytics", "Usage and Activity"],
    subjects: ["Buyers"],
    risks: ["Overinterpretation of limited demo signals"],
    mitigations: ["Operational indicator label", "No high-stakes automation"],
    residualRisk: "Moderate",
    approvals: [],
    createdAt: "2026-07-10T10:00:00.000Z",
    completedAt: null,
  },
  {
    id: "assessment-2",
    reference: "BM-PIA-2026-0002",
    title: "Identity verification placeholder review",
    assessmentType: "New identity-verification workflow",
    owner: "Priya Nair",
    status: "Approved",
    processingPurposes: ["purpose-buyer-verification"],
    dataCategories: ["Identity", "Uploaded Document"],
    subjects: ["Buyers"],
    risks: ["Highly confidential documents"],
    mitigations: ["Restricted access", "Redacted exports"],
    residualRisk: "Moderate",
    approvals: ["Legal Reviewer", "Security Administrator"],
    createdAt: "2026-06-20T10:00:00.000Z",
    completedAt: "2026-07-01T10:00:00.000Z",
  },
  {
    id: "assessment-3",
    reference: "BM-PIA-2026-0003",
    title: "Analytics vendor placeholder review",
    assessmentType: "New vendor review",
    owner: "Priya Nair",
    status: "In Review",
    processingPurposes: ["purpose-operational-analytics"],
    dataCategories: ["Analytics"],
    subjects: ["Platform users"],
    risks: ["Region and transfer review required"],
    mitigations: ["No real vendor integration"],
    residualRisk: "High",
    approvals: [],
    createdAt: "2026-07-14T10:00:00.000Z",
    completedAt: null,
  },
];

export const DEFAULT_PRIVACY_REPORTS = [
  "Privacy Request Status",
  "Privacy Request Due Dates",
  "Consent and Withdrawal",
  "Marketing Opt-Out",
  "Data Inventory Coverage",
  "Missing Data Classification",
  "Retention Review",
  "Legal Hold Summary",
  "Privacy Incident Summary",
  "Vendor Review Status",
  "High-Risk Processing Assessments",
  "Data Export History",
  "Deletion and Anonymization Outcomes",
  "Restricted Processing",
  "Privacy Notice Acknowledgment",
].map((name, index) => ({
  id: `privacy-report-${index + 1}`,
  name,
  status: "Active",
  version: 1,
  permissionKey: "privacy.analytics.view",
  confidentiality: ["Legal Hold Summary", "Privacy Incident Summary"].includes(
    name,
  )
    ? "Restricted"
    : "Internal",
  description: `Permission-aware ${name.toLowerCase()} prototype report.`,
  createdAt: "2026-07-01T09:00:00.000Z",
}));

export const DEFAULT_PRIVACY_STATE = {
  version: 1,
  classifications: DEFAULT_CLASSIFICATIONS,
  dataInventory: DEFAULT_DATA_INVENTORY,
  processingPurposes: DEFAULT_PROCESSING_PURPOSES,
  legalBasisPlaceholders: LEGAL_BASIS_PLACEHOLDERS,
  privacyNotices: DEFAULT_PRIVACY_NOTICES,
  noticeVersions: [],
  acknowledgments: [
    {
      id: "ack-olivia-general",
      userId: "user-olivia",
      organizationId: "org-northstar",
      noticeId: "notice-1",
      noticeVersion: 2,
      acknowledgmentType: "Acknowledged",
      acknowledgedAt: "2026-07-01T10:00:00.000Z",
      declinedAt: null,
      source: "Login",
      sessionId: "user-olivia-current",
      required: true,
      metadata: { prototype: true },
    },
  ],
  consents: DEFAULT_CONSENTS,
  requests: DEFAULT_PRIVACY_REQUESTS,
  identityVerifications: [],
  discoveryResults: {},
  exports: [
    {
      id: "privacy-export-1",
      reference: "BM-PRIV-EXP-2026-0001",
      requestId: "privacy-request-1",
      subjectUserId: "user-olivia",
      organizationId: "org-northstar",
      format: "ZIP package simulation",
      status: "Ready",
      dataCategories: [
        "Account",
        "Projects",
        "Contracts",
        "Financial",
        "Licence",
        "Delivery",
      ],
      includedModules: [
        "Account",
        "Projects",
        "Quotes",
        "Contracts",
        "Payments",
        "Licences",
        "Deliveries",
      ],
      excludedModules: ["Security investigations", "Internal legal advice"],
      redactions: [
        "Other users",
        "Payment credentials",
        "Internal pricing logic",
        "Raw signature assets",
      ],
      recordCount: 34,
      generatedAt: "2026-07-11T10:00:00.000Z",
      expiresAt: "2026-07-18T10:00:00.000Z",
      fileAssetId: "privacy-export-asset-1",
      downloadedAt: null,
      revokedAt: null,
      accessReference: "BM-URL-PRIV-0001",
    },
  ],
  correctionDecisions: [],
  deletionPlans: [
    {
      id: "deletion-plan-1",
      requestId: "privacy-request-3",
      subjectUserId: "user-daniel",
      actions: [
        "Delete optional preferences",
        "Anonymize saved searches",
        "Retain contractual records",
      ],
      retainedRecords: [
        "Invoices",
        "Payments",
        "Expired licence",
        "Contracts",
        "Audit events",
      ],
      anonymizedRecords: ["Search history", "Optional profile fields"],
      deletedRecords: ["Marketing preferences"],
      detachedRecords: [],
      accountAction: "Deactivate login after approval",
      scheduledAt: null,
      approvalStatus: "Partially Approved",
      createdBy: "user-privacy",
      approvedBy: "user-legal",
      executedAt: null,
      rollbackAllowed: false,
      notes: "Commercial and financial retention placeholders apply.",
    },
  ],
  restrictions: [
    {
      id: "restriction-1",
      subjectUserId: "user-rachel",
      organizationId: "org-orbit",
      categories: ["Optional analytics", "Recommendation profiling"],
      reason: "Request under legal review",
      status: "Partially Active",
      validFrom: "2026-07-12T10:00:00.000Z",
      expiresAt: null,
      imposedBy: "Priya Nair",
      approvedBy: "Eleanor Shaw",
      exceptions: [
        "Contractual processing",
        "Payment processing",
        "Security logging",
        "Rights records",
      ],
      metadata: { prototype: true },
    },
  ],
  retentionRules: DEFAULT_RETENTION_RULES,
  retentionReviews: [
    {
      id: "retention-review-1",
      category: "Search activity",
      module: "Search Infrastructure",
      subject: "Closed discovery account",
      ruleId: "retention-activity",
      triggerDate: "2025-06-01",
      eligibleDate: "2026-06-01",
      legalHold: false,
      recommendedAction: "Delete",
      reviewer: "Privacy Administrator",
      status: "Review Due",
    },
    {
      id: "retention-review-2",
      category: "Rights ownership",
      module: "Rights Database",
      subject: "The SMYRK contributor record",
      ruleId: "retention-rights",
      triggerDate: "2026-01-01",
      eligibleDate: "Requires legal review",
      legalHold: false,
      recommendedAction: "Retain",
      reviewer: "Rights Manager",
      status: "On Track",
    },
  ],
  legalHolds: DEFAULT_LEGAL_HOLDS,
  vendors: DEFAULT_VENDORS,
  incidents: DEFAULT_PRIVACY_INCIDENTS,
  assessments: DEFAULT_ASSESSMENTS,
  cookiePreferences: [
    {
      userId: "user-olivia",
      anonymousSessionId: null,
      noticeVersion: 1,
      essential: true,
      functional: true,
      analytics: true,
      personalization: true,
      marketing: false,
      updatedAt: "2026-07-10T10:00:00.000Z",
      source: "Privacy settings",
    },
    {
      userId: "user-marcus",
      anonymousSessionId: null,
      noticeVersion: 1,
      essential: true,
      functional: true,
      analytics: true,
      personalization: false,
      marketing: false,
      updatedAt: "2026-07-10T10:00:00.000Z",
      source: "Privacy settings",
    },
  ],
  privacyNotifications: [],
  activity: [],
  lastNumbers: { request: 8, export: 1, hold: 2, incident: 4, assessment: 3 },
  privacyReports: DEFAULT_PRIVACY_REPORTS,
};
