export const AUDIT_STORAGE_KEY = "beatmondo-audit-logging-v1";
export const SELECTED_AUDIT_KEY = "beatmondo-selected-audit-event";

export const AUDIT_RESULTS = [
  "Success",
  "Failure",
  "Denied",
  "Blocked",
  "Warning",
  "Pending",
  "Cancelled",
  "Expired",
  "Revoked",
  "Completed with Warning",
];
export const AUDIT_SEVERITIES = [
  "Informational",
  "Low",
  "Medium",
  "High",
  "Critical",
];
export const AUDIT_VISIBILITIES = [
  "Public Activity",
  "Buyer Visible",
  "Artist Visible",
  "Organization Visible",
  "Internal",
  "Finance Restricted",
  "Rights Restricted",
  "Legal Restricted",
  "Security Restricted",
  "Super Admin Only",
];
export const RETENTION_POLICIES = [
  {
    id: "retention-short",
    name: "Short Operational",
    duration: "12 months",
    behavior: "Archive eligible low-value operational events",
    legalPlaceholder: true,
    active: true,
  },
  {
    id: "retention-standard",
    name: "Standard",
    duration: "24 months",
    behavior: "General prototype activity",
    legalPlaceholder: true,
    active: true,
  },
  {
    id: "retention-financial",
    name: "Financial",
    duration: "7 years placeholder",
    behavior: "Financial events remain protected from cleanup",
    legalPlaceholder: true,
    active: true,
  },
  {
    id: "retention-contractual",
    name: "Contractual",
    duration: "Long-term",
    behavior: "Contract and licence events remain protected",
    legalPlaceholder: true,
    active: true,
  },
  {
    id: "retention-rights",
    name: "Rights and Legal",
    duration: "Long-term",
    behavior: "Rights disputes and legal records remain protected",
    legalPlaceholder: true,
    active: true,
  },
  {
    id: "retention-security",
    name: "Security",
    duration: "3 years placeholder",
    behavior: "Security events remain restricted",
    legalPlaceholder: true,
    active: true,
  },
  {
    id: "retention-history",
    name: "Permanent Historical",
    duration: "Indefinite prototype history",
    behavior: "Seeded milestone evidence",
    legalPlaceholder: true,
    active: true,
  },
];

const actors = {
  olivia: {
    actorType: "Buyer",
    userId: "user-olivia",
    displayName: "Olivia Bennett",
    role: "VIP Buyer",
    organizationId: "org-northstar",
    organizationName: "Northstar Pictures",
    systemName: null,
    impersonatedBy: null,
    authenticationMethod: "Password",
  },
  marcus: {
    actorType: "Artist",
    userId: "user-marcus",
    displayName: "Marcus Hale",
    role: "Artist / Rightsholder",
    organizationId: "org-smyrk",
    organizationName: "The SMYRK",
    systemName: null,
    impersonatedBy: null,
    authenticationMethod: "Password + MFA",
  },
  jordan: {
    actorType: "Internal User",
    userId: "user-jordan",
    displayName: "Jordan Lee",
    role: "Catalog Manager",
    organizationId: "org-beatmondo",
    organizationName: "beatmondo",
    systemName: null,
    impersonatedBy: null,
    authenticationMethod: "Password",
  },
  amelia: {
    actorType: "Internal User",
    userId: "user-amelia",
    displayName: "Amelia Grant",
    role: "Rights Manager",
    organizationId: "org-beatmondo",
    organizationName: "beatmondo",
    systemName: null,
    impersonatedBy: null,
    authenticationMethod: "Password",
  },
  noah: {
    actorType: "Internal User",
    userId: "user-noah",
    displayName: "Noah Pierce",
    role: "Media Operations",
    organizationId: "org-beatmondo",
    organizationName: "beatmondo",
    systemName: null,
    impersonatedBy: null,
    authenticationMethod: "Password",
  },
  finance: {
    actorType: "Internal User",
    userId: "user-finance",
    displayName: "Nadia Foster",
    role: "Finance Manager",
    organizationId: "org-beatmondo",
    organizationName: "beatmondo",
    systemName: null,
    impersonatedBy: null,
    authenticationMethod: "Password + MFA",
  },
  preston: {
    actorType: "Administrator",
    userId: "user-preston",
    displayName: "Preston Repenning",
    role: "Super Administrator",
    organizationId: "org-beatmondo",
    organizationName: "beatmondo",
    systemName: null,
    impersonatedBy: null,
    authenticationMethod: "Password + MFA",
  },
  system: {
    actorType: "Automated Process",
    userId: null,
    displayName: "Beatmondo Demo Automation",
    role: null,
    organizationId: "org-beatmondo",
    organizationName: "beatmondo",
    systemName: "Beatmondo Demo Automation",
    impersonatedBy: null,
    authenticationMethod: null,
  },
  anonymous: {
    actorType: "Anonymous Visitor",
    userId: null,
    displayName: "Anonymous visitor",
    role: null,
    organizationId: null,
    organizationName: null,
    systemName: null,
    impersonatedBy: null,
    authenticationMethod: null,
  },
};

const specs = [
  [
    "Authentication",
    "Authentication",
    "Login succeeded",
    "Success",
    "Informational",
    "olivia",
    "User",
    "user-olivia",
    "Olivia Bennett",
    "Organization Visible",
    "Standard",
    "Authenticated VIP workspace session created",
  ],
  [
    "Authentication",
    "Security",
    "MFA challenge failed",
    "Failure",
    "High",
    "preston",
    "User",
    "user-preston",
    "Super administrator",
    "Security Restricted",
    "Restricted",
    "Incorrect MFA code; supplied value redacted",
  ],
  [
    "Authentication",
    "Authentication",
    "Logout completed",
    "Success",
    "Informational",
    "olivia",
    "User",
    "user-olivia",
    "Olivia Bennett",
    "Organization Visible",
    "Standard",
    "Browser session ended",
  ],
  [
    "Buyer Verification",
    "Buyer Verification",
    "Buyer verification approved",
    "Success",
    "Medium",
    "preston",
    "Buyer Organization",
    "org-northstar",
    "Northstar Pictures",
    "Internal",
    "Confidential",
    "VIP secure-delivery eligibility approved",
  ],
  [
    "Buyer Verification",
    "Buyer Verification",
    "Verification suspended",
    "Success",
    "High",
    "amelia",
    "Buyer Organization",
    "org-orbit",
    "Orbit Trailers",
    "Rights Restricted",
    "Confidential",
    "Reverification required after company-domain change",
  ],
  [
    "Membership Billing",
    "Membership Billing",
    "Membership upgraded",
    "Success",
    "Medium",
    "olivia",
    "Membership",
    "membership-olivia",
    "VIP Sync Access",
    "Organization Visible",
    "Standard",
    "Professional Buyer upgraded to VIP Sync Access",
  ],
  [
    "Membership Billing",
    "Membership Billing",
    "Membership payment failed",
    "Failure",
    "Medium",
    "system",
    "Invoice",
    "membership-invoice-failed",
    "Membership invoice",
    "Finance Restricted",
    "Confidential",
    "Simulated card authorization failed",
  ],
  [
    "Rights Database",
    "Rights",
    "Rights dispute opened",
    "Blocked",
    "High",
    "amelia",
    "Rights Record",
    "rights-8",
    "The Long Arrival rights",
    "Rights Restricted",
    "Highly Confidential",
    "Active claim blocks commercial licensing and delivery",
  ],
  [
    "Rights Database",
    "Rights",
    "Rights document viewed",
    "Success",
    "Medium",
    "amelia",
    "Rights Document",
    "asset-rights-1",
    "Afterglow Drive split sheet",
    "Rights Restricted",
    "Highly Confidential",
    "Short-lived internal document access",
  ],
  [
    "Rights Database",
    "Rights",
    "Territory restriction added",
    "Success",
    "Medium",
    "amelia",
    "Rights Record",
    "rights-1",
    "Golden Hours rights",
    "Rights Restricted",
    "Confidential",
    "Restriction added for controlled commercial use",
  ],
  [
    "Search Infrastructure",
    "Search",
    "Search index rebuilt",
    "Success",
    "Informational",
    "system",
    "System Configuration",
    "search-index",
    "Music search index",
    "Internal",
    "Standard",
    "Catalog search index synchronized",
  ],
  [
    "Search Infrastructure",
    "Search",
    "Buyer search performed",
    "Success",
    "Informational",
    "olivia",
    "Search Index Record",
    "search-query-olivia",
    "Cinematic trailer search",
    "Organization Visible",
    "Standard",
    "Protected discovery query executed",
  ],
  [
    "Track Ingestion",
    "Track Ingestion",
    "Track published",
    "Success",
    "Medium",
    "jordan",
    "Ingestion Record",
    "ingestion-1",
    "Golden Hours",
    "Internal",
    "Standard",
    "Technical, catalog, rights, and search gates completed",
  ],
  [
    "Track Ingestion",
    "Track Ingestion",
    "Track master replaced",
    "Success",
    "High",
    "noah",
    "Asset",
    "asset-instrumental-1-v2",
    "Golden Hours instrumental V2",
    "Internal",
    "Confidential",
    "Corrected end fade approved as a new immutable asset version",
  ],
  [
    "Track Ingestion",
    "Track Ingestion",
    "File validation failed",
    "Failure",
    "Medium",
    "noah",
    "Asset",
    "asset-failed-20",
    "The Long Arrival source master",
    "Internal",
    "Confidential",
    "Invalid or unreadable audio header",
  ],
  [
    "File Storage and Streaming",
    "Storage",
    "Master-access attempt denied",
    "Denied",
    "High",
    "anonymous",
    "Asset",
    "asset-master-1",
    "Protected master audio",
    "Security Restricted",
    "Restricted",
    "Delivery entitlement required",
  ],
  [
    "File Storage and Streaming",
    "Streaming",
    "Preview streamed",
    "Success",
    "Informational",
    "olivia",
    "Preview",
    "preview-afterglow-vip",
    "Afterglow Drive VIP preview",
    "Organization Visible",
    "Standard",
    "Short-lived protected streaming session created",
  ],
  [
    "File Storage and Streaming",
    "Storage",
    "Asset integrity warning",
    "Warning",
    "Medium",
    "system",
    "Asset",
    "asset-art-20",
    "The Long Arrival artwork",
    "Internal",
    "Confidential",
    "Publication approval remains pending",
  ],
  [
    "Watermarked Previews",
    "Preview Protection",
    "Watermarked preview approved",
    "Success",
    "Medium",
    "jordan",
    "Preview",
    "preview-afterglow-vip",
    "Afterglow Drive VIP preview",
    "Internal",
    "Standard",
    "Policy and watermark review completed",
  ],
  [
    "Watermarked Previews",
    "Preview Protection",
    "Preview revoked",
    "Revoked",
    "High",
    "jordan",
    "Preview",
    "preview-revoked",
    "Chasing the Light preview",
    "Internal",
    "Confidential",
    "Protected access disabled and active sessions revoked",
  ],
  [
    "Quote Calculation",
    "Quote",
    "Quote sent",
    "Success",
    "Informational",
    "jordan",
    "Quote",
    "quote-41",
    "BM-Q-2026-0041",
    "Internal",
    "Standard",
    "Commercial quote sent to Northstar Pictures",
  ],
  [
    "Quote Calculation",
    "Quote",
    "Quote accepted",
    "Success",
    "Medium",
    "olivia",
    "Quote",
    "quote-41",
    "BM-Q-2026-0041",
    "Organization Visible",
    "Standard",
    "Buyer accepted version 1",
  ],
  [
    "Quote Calculation",
    "Quote",
    "Manual pricing override used",
    "Completed with Warning",
    "High",
    "jordan",
    "Quote",
    "quote-44",
    "BM-Q-2026-0044",
    "Internal",
    "Confidential",
    "Override reason recorded and approval required",
  ],
  [
    "Contracts and E-Signature",
    "Contract",
    "Contract generated",
    "Success",
    "Medium",
    "jordan",
    "Contract",
    "contract-21",
    "BM-C-2026-0021",
    "Internal",
    "Confidential",
    "Contract generated from accepted quote version",
  ],
  [
    "Contracts and E-Signature",
    "Signature",
    "Signature completed",
    "Success",
    "Medium",
    "olivia",
    "Signature",
    "signature-21-buyer",
    "BM-C-2026-0021 buyer signature",
    "Organization Visible",
    "Confidential",
    "Typed signature record created; raw signature image not logged",
  ],
  [
    "Contracts and E-Signature",
    "Contract",
    "Contract became effective",
    "Success",
    "High",
    "preston",
    "Contract",
    "contract-21",
    "BM-C-2026-0021",
    "Legal Restricted",
    "Highly Confidential",
    "Required signatures and countersignature completed",
  ],
  [
    "Payments",
    "Payment",
    "Payment failed",
    "Failure",
    "Medium",
    "olivia",
    "Payment",
    "payment-failed-demo",
    "Licence payment attempt",
    "Finance Restricted",
    "Confidential",
    "Processor simulation declined payment; card •••• 4242",
  ],
  [
    "Payments",
    "Payment",
    "Payment succeeded",
    "Success",
    "High",
    "olivia",
    "Payment",
    "payment-61",
    "BM-PAY-2026-0061",
    "Finance Restricted",
    "Confidential",
    "Deposit captured; payment credentials redacted",
  ],
  [
    "Payments",
    "Payment",
    "Refund approved",
    "Success",
    "High",
    "finance",
    "Payment",
    "payment-refund-demo",
    "Licence payment refund",
    "Finance Restricted",
    "Highly Confidential",
    "Finance review approved simulated refund",
  ],
  [
    "Licence Generation",
    "Licence",
    "Licence issued",
    "Success",
    "High",
    "jordan",
    "Licence",
    "licence-18",
    "BM-LIC-2026-0018",
    "Legal Restricted",
    "Highly Confidential",
    "Versioned commercial licence document issued",
  ],
  [
    "Licence Generation",
    "Licence",
    "Licence suspended",
    "Revoked",
    "Critical",
    "amelia",
    "Licence",
    "licence-suspended-demo",
    "Suspended licence",
    "Legal Restricted",
    "Restricted",
    "Rights review reopened; new use disabled",
  ],
  [
    "Licence Generation",
    "Licence",
    "Licence restored",
    "Success",
    "High",
    "preston",
    "Licence",
    "licence-restored-demo",
    "Restored licence",
    "Legal Restricted",
    "Highly Confidential",
    "Rights, payment, and eligibility revalidated",
  ],
  [
    "Secure Delivery",
    "Delivery",
    "Delivery activated",
    "Success",
    "High",
    "jordan",
    "Delivery Package",
    "delivery-package-16",
    "BM-DEL-2026-0016",
    "Internal",
    "Confidential",
    "Asset versions locked, manifest generated, entitlements created",
  ],
  [
    "Secure Delivery",
    "Delivery",
    "Master download completed",
    "Success",
    "Medium",
    "olivia",
    "Asset",
    "delivery-entry-master-16",
    "Afterglow Drive WAV master",
    "Organization Visible",
    "Confidential",
    "Simulated transfer completed; one entitlement use recorded",
  ],
  [
    "Secure Delivery",
    "Authorization",
    "Stem download denied",
    "Denied",
    "High",
    "anonymous",
    "Asset",
    "delivery-entry-stems-16",
    "Protected stems package",
    "Security Restricted",
    "Restricted",
    "Named-user delivery entitlement required",
  ],
  [
    "Secure Delivery",
    "Delivery",
    "Manual delivery-limit override",
    "Completed with Warning",
    "Critical",
    "preston",
    "Delivery Package",
    "delivery-package-20",
    "BM-DEL-2026-0020",
    "Super Admin Only",
    "Restricted",
    "One additional download approved after senior review",
  ],
  [
    "Temporary Access",
    "Temporary Access",
    "Temporary URL expired",
    "Expired",
    "Informational",
    "system",
    "Temporary URL",
    "access-104",
    "BM-URL-2026-0104",
    "Internal",
    "Standard",
    "Unused stems URL expired independently of active entitlement",
  ],
  [
    "Temporary Access",
    "Security",
    "Organization mismatch",
    "Denied",
    "High",
    "anonymous",
    "Temporary URL",
    "access-107",
    "BM-URL-2026-0107",
    "Security Restricted",
    "Restricted",
    "Temporary access was attempted from a different organization",
  ],
  [
    "Temporary Access",
    "Security",
    "Bulk URL revocation",
    "Revoked",
    "Critical",
    "preston",
    "Delivery Package",
    "delivery-package-16",
    "BM-DEL-2026-0016",
    "Security Restricted",
    "Restricted",
    "Delivery-wide temporary access revoked",
  ],
  [
    "Temporary Access",
    "Security",
    "Security review opened",
    "Pending",
    "High",
    "system",
    "Temporary URL",
    "access-112",
    "High-value stems access",
    "Security Restricted",
    "Restricted",
    "Repeated generation requests triggered manual review",
  ],
  [
    "Administration",
    "User Management",
    "Role permission changed",
    "Success",
    "Critical",
    "preston",
    "Permission",
    "permission-audit-security",
    "Audit security access",
    "Super Admin Only",
    "Restricted",
    "Security audit permission assigned with approval",
  ],
  [
    "Administration",
    "Administration",
    "Administrator impersonation started",
    "Completed with Warning",
    "Critical",
    "preston",
    "User",
    "user-olivia",
    "Olivia Bennett",
    "Security Restricted",
    "Restricted",
    "Support simulation; true administrator identity preserved",
  ],
  [
    "Administration",
    "Configuration",
    "Retention policy changed",
    "Success",
    "High",
    "preston",
    "System Configuration",
    "retention-security",
    "Security retention",
    "Super Admin Only",
    "Restricted",
    "Prototype retention placeholder updated",
  ],
  [
    "Administration",
    "Administration",
    "Demo data reset",
    "Success",
    "Medium",
    "system",
    "System Configuration",
    "demo-reset",
    "Prototype data",
    "Internal",
    "Standard",
    "Seeded browser data restored; production records are unaffected",
  ],
  [
    "Notification",
    "Notification",
    "Buyer notification created",
    "Success",
    "Informational",
    "system",
    "Notification",
    "notification-delivery-ready",
    "Secure delivery ready",
    "Internal",
    "Standard",
    "Buyer-safe delivery notification queued",
  ],
  [
    "System",
    "System",
    "Audit persistence recovered",
    "Success",
    "Medium",
    "system",
    "System Configuration",
    "audit-service",
    "Audit persistence",
    "Super Admin Only",
    "Restricted",
    "Fallback queue recorded after simulated recovery",
  ],
];

const categoryToRetention = (category) =>
  category === "Payment"
    ? "Financial"
    : ["Contract", "Signature", "Licence"].includes(category)
      ? "Contractual"
      : category === "Rights"
        ? "Rights and Legal"
        : category === "Security"
          ? "Security"
          : "Standard";
const seeded = specs.map((spec, index) => {
  const [
    module,
    category,
    action,
    result,
    severity,
    actorKey,
    entityType,
    entityId,
    displayName,
    visibility,
    confidentiality,
    description,
  ] = spec;
  const correlationId =
    index >= 20 && index <= 34
      ? "BM-CORR-2026-0041"
      : `BM-CORR-2026-${String(Math.floor(index / 4) + 1).padStart(4, "0")}`;
  const before = action.includes("upgraded")
    ? { tier: "Professional Buyer" }
    : action.includes("suspended")
      ? { status: "Active" }
      : action.includes("restored")
        ? { status: "Suspended" }
        : null;
  const after = action.includes("upgraded")
    ? { tier: "VIP Sync Access" }
    : action.includes("suspended")
      ? { status: "Suspended" }
      : action.includes("restored")
        ? { status: "Active" }
        : null;
  return {
    id: `audit-seed-${index + 1}`,
    reference: `BM-AUD-2026-${String(index + 1).padStart(6, "0")}`,
    occurredAt: new Date(
      Date.UTC(
        2026,
        6,
        10 + Math.floor(index / 8),
        8 + (index % 8),
        index % 60,
      ),
    ).toISOString(),
    recordedAt: new Date(
      Date.UTC(
        2026,
        6,
        10 + Math.floor(index / 8),
        8 + (index % 8),
        index % 60,
        5,
      ),
    ).toISOString(),
    module,
    category,
    eventType: action,
    action,
    result,
    severity,
    actor: actors[actorKey],
    subject: {
      entityType,
      entityId,
      reference: displayName.startsWith("BM-") ? displayName : null,
      displayName,
      secondaryEntityType: null,
      secondaryEntityId: null,
      secondaryReference: null,
    },
    organizationId: actors[actorKey].organizationId,
    projectId: entityType === "Delivery Package" ? "project-horizon-run" : null,
    parentEventId: null,
    correlationId,
    sessionId: index < 3 ? `session-seed-${index + 1}` : null,
    requestId: `request-seed-${index + 1}`,
    source:
      actorKey === "system" ? "Scheduled Simulation" : "Imported Demo Data",
    description,
    reason:
      action.includes("override") ||
      action.includes("denied") ||
      action.includes("suspended")
        ? description
        : null,
    before,
    after,
    changes:
      before && after
        ? Object.keys(after).map((field) => ({
            field,
            label: field[0].toUpperCase() + field.slice(1),
            before: before[field],
            after: after[field],
            redacted: false,
            dataType: "string",
          }))
        : [],
    metadata: {
      seeded: true,
      sourceEventKey: `seed:${index + 1}`,
      approximateDevice:
        actorKey === "system" ? "Automated process" : "Codex Browser",
      approximateRegion:
        actors[actorKey].organizationId === "org-beatmondo"
          ? "India"
          : "United States",
      overrideUsed: action.toLowerCase().includes("override"),
      integrityHashPlaceholder: `demo-integrity-audit-${index + 1}`,
    },
    visibility,
    confidentiality,
    redactedFields: action.includes("MFA")
      ? ["mfaCode"]
      : action.includes("Payment") || category === "Payment"
        ? ["cardNumber", "cvc", "processorToken"]
        : [],
    reviewStatus: ["High", "Critical"].includes(severity)
      ? "Not Reviewed"
      : "Reviewed",
    reviewedBy: ["High", "Critical"].includes(severity)
      ? null
      : "Beatmondo Demo Automation",
    reviewedAt: ["High", "Critical"].includes(severity)
      ? null
      : "2026-07-16T10:00:00.000Z",
    assignedTo: ["High", "Critical"].includes(severity) ? "user-jordan" : null,
    retentionClass: categoryToRetention(category),
    retentionStatus: "Active",
    legalHoldId: null,
    environment: "Prototype",
    immutable: true,
    archivedAt: null,
  };
});

export const DEFAULT_AUDIT_STATE = {
  version: 1,
  events: seeded,
  sequence: seeded.length,
  correlationSequence: 12,
  sourceEventKeys: seeded.map((item) => item.metadata.sourceEventKey),
  reviews: [],
  exports: [],
  exportFiles: [],
  retentionPolicies: RETENTION_POLICIES,
  legalHolds: [],
  archiveActions: [],
  fallbackQueue: [],
  health: {
    auditService: "Operational",
    eventPersistence: "Operational",
    exportService: "Operational",
    retentionProcess: "Operational",
    securityQueue: "Operational",
  },
  notifications: [],
  activity: [],
  lastResetAt: null,
};
