export const ANALYTICS_STORAGE_KEY = "beatmondo-analytics-reporting-v1";
export const SELECTED_REPORT_KEY = "beatmondo-selected-report";

export const FIXED_FX_RATES = {
  version: "BM-FX-PROTOTYPE-2026.07",
  base: "USD",
  rates: { USD: 1, GBP: 1.29, EUR: 1.09, AUD: 0.66 },
  effectiveAt: "2026-07-01T00:00:00.000Z",
  disclaimer:
    "Converted using fixed prototype rates. Not live foreign-exchange data.",
};

const metric = (
  key,
  name,
  category,
  format,
  permissionKey,
  overrides = {},
) => ({
  id: `metric-${key.replaceAll(".", "-")}`,
  key,
  name,
  description:
    overrides.description ||
    `${name} derived from visible prototype source records.`,
  category,
  format,
  aggregation: overrides.aggregation || "Calculated",
  sourceEntities: overrides.sourceEntities || [category],
  dateField: overrides.dateField || "occurredAt",
  filters: overrides.filters || ["dateRange", "organization", "currency"],
  permissionKey,
  confidentiality: overrides.confidentiality || "Internal",
  calculationVersion: overrides.calculationVersion || "1.0",
  effectiveAt: "2026-07-01T00:00:00.000Z",
  simulated: Boolean(overrides.simulated),
  dataQuality: overrides.dataQuality || "Complete",
  active: true,
});

export const DEFAULT_METRIC_DEFINITIONS = [
  metric(
    "catalog.total_tracks",
    "Total catalog tracks",
    "Catalog",
    "Number",
    "analytics.catalog.view",
  ),
  metric(
    "catalog.ready_tracks",
    "Commercially ready tracks",
    "Catalog",
    "Number",
    "analytics.catalog.view",
  ),
  metric(
    "catalog.readiness_rate",
    "Catalog readiness rate",
    "Catalog",
    "Percentage",
    "analytics.catalog.view",
  ),
  metric(
    "catalog.new_tracks",
    "New tracks this period",
    "Catalog",
    "Number",
    "analytics.catalog.view",
    { dataQuality: "Mostly Complete" },
  ),
  metric(
    "catalog.demand_score",
    "Average track demand",
    "Catalog",
    "Score",
    "analytics.catalog.view",
    { simulated: true, dataQuality: "Estimated" },
  ),
  metric(
    "search.searches",
    "Searches",
    "Search",
    "Number",
    "analytics.search.view",
  ),
  metric(
    "search.unique_searchers",
    "Unique searchers",
    "Search",
    "Number",
    "analytics.search.view",
  ),
  metric(
    "search.zero_result_rate",
    "Zero-result rate",
    "Search",
    "Percentage",
    "analytics.search.view",
  ),
  metric(
    "search.click_rate",
    "Search-result click rate",
    "Search",
    "Percentage",
    "analytics.search.view",
    { dataQuality: "Mostly Complete" },
  ),
  metric(
    "preview.starts",
    "Preview starts",
    "Preview",
    "Number",
    "analytics.catalog.view",
  ),
  metric(
    "preview.unique_listeners",
    "Unique listeners",
    "Preview",
    "Number",
    "analytics.catalog.view",
  ),
  metric(
    "preview.completion_rate",
    "Preview completion rate",
    "Preview",
    "Percentage",
    "analytics.catalog.view",
  ),
  metric(
    "buyers.active_organizations",
    "Active buyer organizations",
    "Buyer Engagement",
    "Number",
    "analytics.buyers.view",
  ),
  metric(
    "buyers.active_projects",
    "Active buyer projects",
    "Projects",
    "Number",
    "analytics.buyers.view",
  ),
  metric(
    "buyers.engagement_score",
    "Buyer engagement indicator",
    "Buyer Engagement",
    "Score",
    "analytics.buyers.view",
    { simulated: true, dataQuality: "Estimated" },
  ),
  metric(
    "commercial.requests",
    "Licensing requests",
    "Commercial",
    "Number",
    "analytics.commercial.view",
  ),
  metric(
    "commercial.quotes_sent",
    "Quotes sent",
    "Quotes",
    "Number",
    "analytics.commercial.view",
  ),
  metric(
    "commercial.quotes_accepted",
    "Quotes accepted",
    "Quotes",
    "Number",
    "analytics.commercial.view",
  ),
  metric(
    "commercial.quote_acceptance_rate",
    "Quote acceptance rate",
    "Quotes",
    "Percentage",
    "analytics.commercial.view",
  ),
  metric(
    "commercial.average_quote",
    "Average quote value",
    "Quotes",
    "Currency",
    "analytics.commercial.view",
    { confidentiality: "Confidential" },
  ),
  metric(
    "commercial.contracted_value",
    "Contracted value",
    "Contracts",
    "Currency",
    "analytics.commercial.view",
    { confidentiality: "Confidential" },
  ),
  metric(
    "commercial.average_cycle",
    "Average licensing cycle",
    "Commercial",
    "Duration",
    "analytics.commercial.view",
    { dataQuality: "Partial" },
  ),
  metric(
    "finance.invoiced_value",
    "Invoiced value",
    "Financial",
    "Currency",
    "analytics.finance.view",
    { confidentiality: "Finance Restricted" },
  ),
  metric(
    "finance.collected_value",
    "Collected licensing value",
    "Financial",
    "Currency",
    "analytics.finance.view",
    { confidentiality: "Finance Restricted" },
  ),
  metric(
    "finance.refunded_value",
    "Refunded value",
    "Financial",
    "Currency",
    "analytics.finance.view",
    { confidentiality: "Finance Restricted" },
  ),
  metric(
    "finance.net_collected",
    "Net collected value",
    "Financial",
    "Currency",
    "analytics.finance.view",
    { confidentiality: "Finance Restricted" },
  ),
  metric(
    "finance.outstanding_value",
    "Outstanding licensing value",
    "Financial",
    "Currency",
    "analytics.finance.view",
    { confidentiality: "Finance Restricted" },
  ),
  metric(
    "finance.payment_success_rate",
    "Payment success rate",
    "Financial",
    "Percentage",
    "analytics.finance.view",
    { confidentiality: "Finance Restricted" },
  ),
  metric(
    "membership.active_subscriptions",
    "Active subscriptions",
    "Membership",
    "Number",
    "analytics.finance.view",
  ),
  metric(
    "membership.recurring_revenue",
    "Membership recurring revenue simulation",
    "Membership",
    "Currency",
    "analytics.finance.view",
    { simulated: true, dataQuality: "Estimated" },
  ),
  metric(
    "contracts.sent",
    "Contracts sent",
    "Contracts",
    "Number",
    "analytics.commercial.view",
  ),
  metric(
    "contracts.completion_rate",
    "Contract completion rate",
    "Contracts",
    "Percentage",
    "analytics.commercial.view",
  ),
  metric(
    "licences.issued",
    "Licences issued",
    "Licences",
    "Number",
    "analytics.commercial.view",
  ),
  metric(
    "licences.active",
    "Active licences",
    "Licences",
    "Number",
    "analytics.commercial.view",
  ),
  metric(
    "licences.expiring",
    "Expiring licences",
    "Licences",
    "Number",
    "analytics.commercial.view",
  ),
  metric(
    "licences.conversion_rate",
    "Licence conversion rate",
    "Licences",
    "Percentage",
    "analytics.commercial.view",
  ),
  metric(
    "delivery.completed",
    "Deliveries completed",
    "Delivery",
    "Number",
    "analytics.operations.view",
  ),
  metric(
    "delivery.completion_rate",
    "Delivery completion rate",
    "Delivery",
    "Percentage",
    "analytics.operations.view",
  ),
  metric(
    "rights.verified_tracks",
    "Fully verified tracks",
    "Rights",
    "Number",
    "analytics.rights.view",
  ),
  metric(
    "rights.blocked_opportunities",
    "Rights-blocked opportunities",
    "Rights",
    "Number",
    "analytics.rights.view",
  ),
  metric(
    "rights.affected_value",
    "Potential opportunity value affected",
    "Rights",
    "Currency",
    "analytics.rights.view",
    {
      simulated: true,
      confidentiality: "Rights Restricted",
      dataQuality: "Estimated",
    },
  ),
  metric(
    "verification.queue",
    "Verification queue backlog",
    "Verification",
    "Number",
    "analytics.operations.view",
  ),
  metric(
    "operations.overdue",
    "Overdue operational items",
    "Operations",
    "Number",
    "analytics.operations.view",
    { simulated: true, dataQuality: "Mostly Complete" },
  ),
  metric(
    "security.critical_events",
    "Critical security events",
    "Security",
    "Number",
    "analytics.security.view",
    { confidentiality: "Security Restricted" },
  ),
  metric(
    "security.access_denials",
    "Access denials",
    "Security",
    "Number",
    "analytics.security.view",
    { confidentiality: "Security Restricted" },
  ),
  metric(
    "email.delivered",
    "Delivered message simulations",
    "Email",
    "Number",
    "analytics.email.view",
    { simulated: true },
  ),
  metric(
    "email.failure_rate",
    "Email failure rate",
    "Email",
    "Percentage",
    "analytics.email.view",
    { simulated: true },
  ),
  metric(
    "permissions.temporary_elevations",
    "Temporary elevations",
    "Permissions",
    "Number",
    "analytics.permissions.view",
    { confidentiality: "Security Restricted" },
  ),
  metric(
    "permissions.open_conflicts",
    "Open permission conflicts",
    "Permissions",
    "Number",
    "analytics.permissions.view",
    { confidentiality: "Security Restricted" },
  ),
  metric(
    "executive.weighted_pipeline",
    "Weighted pipeline value",
    "Executive",
    "Currency",
    "analytics.executive.view",
    {
      simulated: true,
      confidentiality: "Confidential",
      dataQuality: "Estimated",
    },
  ),
];

const reportNames = [
  [
    "executive-business-review",
    "Executive Business Review",
    "Executive",
    "analytics.executive.view",
    true,
  ],
  [
    "licensing-pipeline",
    "Licensing Pipeline",
    "Commercial",
    "analytics.commercial.view",
  ],
  [
    "quote-performance",
    "Quote Performance",
    "Commercial",
    "analytics.commercial.view",
  ],
  [
    "revenue-collection",
    "Revenue Collection",
    "Financial",
    "analytics.finance.view",
    true,
  ],
  [
    "outstanding-payments",
    "Outstanding Payments",
    "Financial",
    "analytics.finance.view",
    true,
  ],
  [
    "catalog-readiness",
    "Catalog Readiness",
    "Catalog",
    "analytics.catalog.view",
  ],
  ["track-demand", "Track Demand", "Catalog", "analytics.catalog.view"],
  ["search-demand", "Search Demand", "Search", "analytics.search.view"],
  [
    "zero-result-searches",
    "Zero-Result Searches",
    "Search",
    "analytics.search.view",
  ],
  [
    "preview-engagement",
    "Preview Engagement",
    "Preview",
    "analytics.catalog.view",
  ],
  [
    "buyer-organization-activity",
    "Buyer Organization Activity",
    "Buyers",
    "analytics.buyers.view",
  ],
  [
    "artist-catalog-performance",
    "Artist Catalog Performance",
    "Artists",
    "analytics.artists.view",
  ],
  ["rights-health", "Rights Health", "Rights", "analytics.rights.view", true],
  [
    "rights-blocked-opportunities",
    "Rights-Blocked Opportunities",
    "Rights",
    "analytics.rights.view",
    true,
  ],
  [
    "contract-status",
    "Contract Status",
    "Contracts",
    "analytics.commercial.view",
  ],
  ["licence-expiry", "Licence Expiry", "Licences", "analytics.commercial.view"],
  [
    "delivery-completion",
    "Delivery Completion",
    "Delivery",
    "analytics.operations.view",
  ],
  [
    "operational-queue-health",
    "Operational Queue Health",
    "Operations",
    "analytics.operations.view",
  ],
  [
    "security-events",
    "Security Events",
    "Security",
    "analytics.security.view",
    true,
  ],
  [
    "email-delivery-simulation",
    "Email Delivery Simulation",
    "Email",
    "analytics.email.view",
  ],
  [
    "privileged-access-review",
    "Privileged Access Review",
    "Permissions",
    "analytics.permissions.view",
    true,
  ],
  [
    "membership-overview",
    "Membership Overview",
    "Membership",
    "analytics.finance.view",
  ],
  [
    "verification-queue",
    "Verification Queue",
    "Verification",
    "analytics.operations.view",
  ],
  [
    "renewal-opportunities",
    "Renewal Opportunities",
    "Licences",
    "analytics.commercial.view",
  ],
];

const reportMetricCategories = {
  Buyers: ["Buyer Engagement", "Projects", "Commercial"],
  Artists: ["Catalog", "Preview"],
  Delivery: ["Delivery"],
};

export const DEFAULT_REPORTS = reportNames.map(
  ([key, name, category, permissionKey, restricted], index) => ({
    id: `report-${String(index + 1).padStart(2, "0")}`,
    key,
    name,
    description: `${name} with permission-aware prototype metrics and record-level drill-down.`,
    category,
    owner: "Beatmondo Reporting",
    ownerId: "user-preston",
    status: "Active",
    version: 1,
    dataSources: [category],
    metrics: DEFAULT_METRIC_DEFINITIONS.filter(
      (item) =>
        item.category === category ||
        reportMetricCategories[category]?.includes(item.category) ||
        index === 0,
    )
      .slice(0, index === 0 ? 12 : 6)
      .map((item) => item.key),
    dimensions: ["Date", category],
    defaultFilters: {
      dateRange: "Last 30 days",
      comparison: "Previous equivalent period",
    },
    availableFilters: ["Date", "Organization", "Artist", "Track", "Currency"],
    columns: ["Metric", "Current", "Previous", "Change", "Data quality"],
    chartDefinitions: [
      { type: index === 1 ? "Funnel" : "Bar chart", title: name },
    ],
    permissionKey,
    confidentiality: restricted ? "Restricted" : "Internal",
    exportFormats: ["CSV", "JSON", "PDF-style print"],
    scheduledDeliveryAllowed: true,
    sharedRoleIds: [],
    createdAt: "2026-07-01T09:00:00.000Z",
    updatedAt: "2026-07-16T10:00:00.000Z",
  }),
);

export const DEFAULT_ANALYTICS_EVENTS = [
  [
    "Search performed",
    "Search",
    "user-olivia",
    "org-northstar",
    1,
    "2026-07-15T10:10:00.000Z",
    { query: "dark cinematic trailer", results: 5 },
  ],
  [
    "Preview started",
    "Preview",
    "user-olivia",
    "org-northstar",
    1,
    "2026-07-15T10:12:00.000Z",
    { tier: "VIP" },
  ],
  [
    "Preview completed",
    "Preview",
    "user-olivia",
    "org-northstar",
    1,
    "2026-07-15T10:14:00.000Z",
    { completion: 100 },
  ],
  [
    "Track saved",
    "Catalog",
    "user-olivia",
    "org-northstar",
    1,
    "2026-07-15T10:15:00.000Z",
    {},
  ],
  [
    "Added to project",
    "Projects",
    "user-olivia",
    "org-northstar",
    1,
    "2026-07-15T10:20:00.000Z",
    { projectType: "Trailer" },
  ],
  [
    "Licensing request created",
    "Commercial",
    "user-olivia",
    "org-northstar",
    1,
    "2026-07-15T11:00:00.000Z",
    { projectType: "Trailer" },
  ],
  [
    "Quote sent",
    "Quotes",
    "user-jordan",
    "org-northstar",
    1,
    "2026-07-16T09:00:00.000Z",
    { value: 12500, currency: "USD" },
  ],
  [
    "Quote accepted",
    "Quotes",
    "user-olivia",
    "org-northstar",
    1,
    "2026-07-17T09:00:00.000Z",
    { value: 12500, currency: "USD" },
  ],
  [
    "Contract signed",
    "Contracts",
    "user-olivia",
    "org-northstar",
    1,
    "2026-07-18T09:00:00.000Z",
    {},
  ],
  [
    "Payment completed",
    "Payments",
    "user-olivia",
    "org-northstar",
    1,
    "2026-07-18T12:00:00.000Z",
    { value: 12500, currency: "USD" },
  ],
  [
    "Licence issued",
    "Licences",
    "user-jordan",
    "org-northstar",
    1,
    "2026-07-18T16:00:00.000Z",
    {},
  ],
  [
    "Delivery completed",
    "Delivery",
    "user-olivia",
    "org-northstar",
    1,
    "2026-07-19T09:00:00.000Z",
    {},
  ],
  [
    "Search performed",
    "Search",
    "user-ethan",
    "org-independent",
    7,
    "2026-07-12T08:00:00.000Z",
    { query: "vintage surf noir", results: 0 },
  ],
  [
    "Search performed",
    "Search",
    "user-olivia",
    "org-northstar",
    19,
    "2026-07-13T08:00:00.000Z",
    { query: "luxury female vocal", results: 2 },
  ],
  [
    "Preview started",
    "Preview",
    "user-olivia",
    "org-northstar",
    19,
    "2026-07-13T08:05:00.000Z",
    { tier: "VIP" },
  ],
].map(
  (
    [eventType, module, userId, organizationId, trackId, occurredAt, metadata],
    index,
  ) => ({
    id: `analytics-event-${index + 1}`,
    eventType,
    module,
    category: module,
    occurredAt,
    userId,
    organizationId,
    artistId: trackId === 1 ? "org-smyrk" : null,
    projectId:
      organizationId === "org-northstar" ? "project-horizon-run" : null,
    trackId,
    relatedEntityType: module,
    relatedEntityId: `${module.toLowerCase()}-${index + 1}`,
    value: metadata.value || null,
    currency: metadata.currency || null,
    dimensions: {
      tier: metadata.tier || null,
      projectType: metadata.projectType || null,
    },
    metadata,
    source: "Prototype event stream",
    simulated: true,
  }),
);

export const DEFAULT_PIPELINE = [
  ["New Request", 5, 22000, 10, 2],
  ["Rights Review", 4, 41000, 20, 1],
  ["Quote Preparation", 6, 78000, 35, 2],
  ["Quote Sent", 4, 62000, 50, 1],
  ["Negotiation", 3, 54000, 65, 1],
  ["Contract Review", 2, 37000, 75, 0],
  ["Signature", 2, 28500, 85, 0],
  ["Payment", 2, 24000, 95, 1],
  ["Licence Generation", 1, 12500, 100, 0],
].map(([stage, count, value, probability, overdue], index) => ({
  id: `pipeline-${index + 1}`,
  stage,
  count,
  value,
  currency: "USD",
  probability,
  weightedValue: Math.round((value * probability) / 100),
  averageAgeDays: index + 2,
  overdue,
  owner: index % 2 ? "Jordan Lee" : "Licensing Team",
  blocker: overdue ? "Next action overdue" : "None",
}));

export const DEFAULT_ZERO_RESULT_TERMS = [
  {
    query: "vintage surf noir",
    searchCount: 9,
    buyerTier: "Professional",
    filters: "Instrumental · 1960s",
    lastSearched: "2026-07-15",
    similar: "surf rock, noir",
    opportunity: "Catalog acquisition",
    recommendation: "Map ‘surf noir’ to dark surf rock",
  },
  {
    query: "Bollywood minimal tension",
    searchCount: 6,
    buyerTier: "VIP",
    filters: "India · Instrumental",
    lastSearched: "2026-07-14",
    similar: "minimal tension",
    opportunity: "Territory demand",
    recommendation: "Curate South Asian tension",
  },
  {
    query: "clean hyperpop anthem",
    searchCount: 4,
    buyerTier: "Professional",
    filters: "Clean version",
    lastSearched: "2026-07-12",
    similar: "electropop anthem",
    opportunity: "Missing clean version",
    recommendation: "Commission clean edits",
  },
];

export const DEFAULT_TRACK_PERFORMANCE = [
  {
    trackId: 1,
    track: "The End of Jason Todd",
    artist: "The SMYRK",
    genre: "Alternative Rock",
    mood: "Dark",
    readiness: "Rights Review",
    rightsStatus: "Conditional",
    impressions: 186,
    views: 72,
    previewStarts: 41,
    previewCompletions: 24,
    saves: 16,
    projectAdditions: 7,
    requests: 4,
    quotes: 2,
    acceptedQuotes: 1,
    licences: 1,
    collectedValue: 12500,
  },
  {
    trackId: 19,
    track: "Velvet Empire",
    artist: "Mara Vale",
    genre: "Electronic",
    mood: "Luxury",
    readiness: "Ready",
    rightsStatus: "Verified",
    impressions: 214,
    views: 94,
    previewStarts: 58,
    previewCompletions: 39,
    saves: 21,
    projectAdditions: 9,
    requests: 5,
    quotes: 3,
    acceptedQuotes: 2,
    licences: 2,
    collectedValue: 28500,
  },
  {
    trackId: 14,
    track: "Open Road Hearts",
    artist: "Westward",
    genre: "Indie",
    mood: "Uplifting",
    readiness: "Ready",
    rightsStatus: "Verified",
    impressions: 168,
    views: 69,
    previewStarts: 37,
    previewCompletions: 25,
    saves: 14,
    projectAdditions: 6,
    requests: 3,
    quotes: 2,
    acceptedQuotes: 1,
    licences: 1,
    collectedValue: 9800,
  },
  {
    trackId: 7,
    track: "After Midnight",
    artist: "Noir Avenue",
    genre: "Alternative",
    mood: "Tension",
    readiness: "Restricted",
    rightsStatus: "Restricted",
    impressions: 121,
    views: 48,
    previewStarts: 23,
    previewCompletions: 11,
    saves: 8,
    projectAdditions: 3,
    requests: 2,
    quotes: 0,
    acceptedQuotes: 0,
    licences: 0,
    collectedValue: 0,
  },
];

export const DEFAULT_QUEUES = [
  ["Buyer verification", 4, 1, 22, "Approaching Due"],
  ["Track technical review", 6, 2, 31, "Overdue"],
  ["Rights review", 7, 3, 68, "Overdue"],
  ["Quote preparation", 6, 2, 39, "Overdue"],
  ["Contract review", 3, 0, 18, "On Track"],
  ["Payment reconciliation", 2, 1, 27, "Approaching Due"],
  ["Licence generation", 2, 0, 9, "On Track"],
  ["Asset preparation", 5, 1, 35, "Approaching Due"],
  ["Delivery approval", 3, 0, 12, "On Track"],
  ["Security review", 2, 1, 16, "Overdue"],
  ["Email failures", 3, 1, 7, "Approaching Due"],
  ["Access requests", 1, 0, 5, "On Track"],
].map(([queue, open, overdue, averageAgeHours, status], index) => ({
  id: `queue-${index + 1}`,
  queue,
  open,
  overdue,
  averageAgeHours,
  oldestItemHours: averageAgeHours + 18,
  owners: index % 2 ? ["Jordan Lee"] : ["Operations Team"],
  status,
  target: index === 2 ? "5 business days" : "2 business days",
  blocked: false,
  trend: index % 3 === 0 ? "Up" : "Stable",
}));

export const DEFAULT_ANALYTICS_STATE = {
  version: 1,
  metricDefinitions: DEFAULT_METRIC_DEFINITIONS,
  metricVersions: DEFAULT_METRIC_DEFINITIONS.map((item) => ({
    metricId: item.id,
    version: item.calculationVersion,
    effectiveAt: item.effectiveAt,
    description: item.description,
  })),
  reports: DEFAULT_REPORTS,
  reportVersions: [],
  customReports: [],
  dashboardLayouts: {},
  schedules: [
    {
      id: "schedule-1",
      reportId: "report-01",
      ownerId: "user-preston",
      recipients: ["admin@beatmondo.com"],
      frequency: "Monthly",
      day: "1",
      time: "09:00",
      timezone: "Europe/London",
      format: "PDF-style print",
      filters: { dateRange: "Previous month" },
      enabled: true,
      nextRun: "2026-08-01T08:00:00.000Z",
      expiryDays: 7,
      confidentiality: "Restricted",
      deliveryChannel: "Email simulation",
      status: "Scheduled",
    },
  ],
  exports: [
    {
      id: "export-1",
      reference: "BM-RPT-EXP-2026-0001",
      reportId: "report-04",
      reportVersion: 1,
      format: "CSV",
      requestedBy: "user-finance",
      filters: { dateRange: "Last 30 days" },
      status: "Ready",
      rowCount: 18,
      confidentiality: "Restricted",
      approvalRequired: true,
      approvedBy: "user-preston",
      createdAt: "2026-07-15T09:00:00.000Z",
      completedAt: "2026-07-15T09:04:00.000Z",
      expiresAt: "2026-07-22T09:04:00.000Z",
      fileAssetId: "analytics-export-1",
      accessReference: "BM-URL-RPT-0001",
    },
  ],
  snapshots: [
    {
      id: "snapshot-1",
      reference: "BM-RPT-SNAP-2026-0001",
      reportId: "report-01",
      reportVersion: 1,
      filters: { dateRange: "Previous month" },
      generatedAt: "2026-07-01T09:00:00.000Z",
      generatedBy: "Preston Repenning",
      metricValues: {
        "finance.collected_value": 42800,
        "catalog.readiness_rate": 68,
      },
      rowData: [],
      simulated: true,
      immutable: true,
    },
  ],
  alerts: [
    {
      id: "alert-1",
      name: "Rights review backlog",
      metricKey: "operations.overdue",
      condition: "Greater than",
      threshold: 10,
      comparison: "Current value",
      status: "Active",
      recipients: ["user-amelia"],
      severity: "High",
      lastEvaluatedAt: null,
      lastTriggeredAt: null,
      cooldownHours: 24,
      enabled: true,
    },
    {
      id: "alert-2",
      name: "Email failure rate",
      metricKey: "email.failure_rate",
      condition: "Greater than",
      threshold: 10,
      comparison: "Current value",
      status: "Active",
      recipients: ["user-preston"],
      severity: "Medium",
      lastEvaluatedAt: null,
      lastTriggeredAt: null,
      cooldownHours: 12,
      enabled: true,
    },
  ],
  alertEvents: [],
  annotations: [
    {
      id: "annotation-1",
      reportId: "report-01",
      date: "2026-07-10",
      title: "Pricing model updated",
      note: "Prototype enterprise pricing weights were revised.",
      createdBy: "Preston Repenning",
      createdAt: "2026-07-10T10:00:00.000Z",
    },
  ],
  cache: {},
  userPreferences: {},
  events: DEFAULT_ANALYTICS_EVENTS,
  pipeline: DEFAULT_PIPELINE,
  zeroResultTerms: DEFAULT_ZERO_RESULT_TERMS,
  trackPerformance: DEFAULT_TRACK_PERFORMANCE,
  queues: DEFAULT_QUEUES,
  fx: FIXED_FX_RATES,
  lastNumbers: { report: 24, export: 1, snapshot: 1, schedule: 1, alert: 2 },
};
