export const CONTRACT_STORAGE_KEY = "beatmondo-contracts-esignature-v1";
export const SELECTED_CONTRACT_KEY = "beatmondo-selected-contract";
export const SIGNATURE_CODE = "864209";

export const CONTRACT_STATUSES = {
  Draft: {
    buyerLabel: "Preparing",
    buyerVisible: false,
    signatureEligible: false,
    paymentReady: false,
    licenceReady: false,
    deliveryReady: false,
    next: ["Data Incomplete", "Internal Review", "Cancelled"],
  },
  "Data Incomplete": {
    buyerLabel: "Information required",
    buyerVisible: false,
    signatureEligible: false,
    paymentReady: false,
    licenceReady: false,
    deliveryReady: false,
    next: ["Draft", "Cancelled"],
  },
  "Internal Review": {
    buyerLabel: "Under review",
    buyerVisible: false,
    signatureEligible: false,
    paymentReady: false,
    licenceReady: false,
    deliveryReady: false,
    next: [
      "Legal Review",
      "Rights Review",
      "Finance Review",
      "Changes Requested",
      "Approved Internally",
      "Cancelled",
    ],
  },
  "Legal Review": {
    buyerLabel: "Legal review",
    buyerVisible: false,
    signatureEligible: false,
    paymentReady: false,
    licenceReady: false,
    deliveryReady: false,
    next: ["Changes Requested", "Approved Internally", "Cancelled"],
  },
  "Rights Review": {
    buyerLabel: "Rights review",
    buyerVisible: false,
    signatureEligible: false,
    paymentReady: false,
    licenceReady: false,
    deliveryReady: false,
    next: ["Changes Requested", "Approved Internally", "Cancelled"],
  },
  "Finance Review": {
    buyerLabel: "Commercial review",
    buyerVisible: false,
    signatureEligible: false,
    paymentReady: false,
    licenceReady: false,
    deliveryReady: false,
    next: ["Changes Requested", "Approved Internally", "Cancelled"],
  },
  "Changes Requested": {
    buyerLabel: "Revision in progress",
    buyerVisible: false,
    signatureEligible: false,
    paymentReady: false,
    licenceReady: false,
    deliveryReady: false,
    next: ["Draft", "Cancelled"],
  },
  "Approved Internally": {
    buyerLabel: "Approved",
    buyerVisible: false,
    signatureEligible: false,
    paymentReady: false,
    licenceReady: false,
    deliveryReady: false,
    next: ["Ready to Send", "Cancelled"],
  },
  "Ready to Send": {
    buyerLabel: "Ready",
    buyerVisible: false,
    signatureEligible: true,
    paymentReady: false,
    licenceReady: false,
    deliveryReady: false,
    next: ["Sent", "Awaiting Buyer Signature", "Cancelled"],
  },
  Sent: {
    buyerLabel: "Ready for review",
    buyerVisible: true,
    signatureEligible: true,
    paymentReady: false,
    licenceReady: false,
    deliveryReady: false,
    next: [
      "Viewed",
      "Awaiting Buyer Signature",
      "Buyer Changes Requested",
      "Cancelled",
    ],
  },
  Viewed: {
    buyerLabel: "Reviewed",
    buyerVisible: true,
    signatureEligible: true,
    paymentReady: false,
    licenceReady: false,
    deliveryReady: false,
    next: ["Awaiting Buyer Signature", "Buyer Changes Requested", "Cancelled"],
  },
  "Awaiting Buyer Signature": {
    buyerLabel: "Signature required",
    buyerVisible: true,
    signatureEligible: true,
    paymentReady: false,
    licenceReady: false,
    deliveryReady: false,
    next: [
      "Partially Signed",
      "Buyer Changes Requested",
      "Signature Declined",
      "Signature Expired",
      "Cancelled",
    ],
  },
  "Awaiting Beatmondo Signature": {
    buyerLabel: "Awaiting beatmondo",
    buyerVisible: true,
    signatureEligible: true,
    paymentReady: false,
    licenceReady: false,
    deliveryReady: false,
    next: ["Countersigned", "Signature Expired", "Cancelled"],
  },
  "Awaiting Additional Signer": {
    buyerLabel: "Awaiting others",
    buyerVisible: true,
    signatureEligible: true,
    paymentReady: false,
    licenceReady: false,
    deliveryReady: false,
    next: [
      "Fully Signed",
      "Signature Declined",
      "Signature Expired",
      "Cancelled",
    ],
  },
  "Partially Signed": {
    buyerLabel: "Partially signed",
    buyerVisible: true,
    signatureEligible: true,
    paymentReady: false,
    licenceReady: false,
    deliveryReady: false,
    next: ["Awaiting Additional Signer", "Fully Signed", "Cancelled"],
  },
  "Buyer Changes Requested": {
    buyerLabel: "Changes requested",
    buyerVisible: true,
    signatureEligible: false,
    paymentReady: false,
    licenceReady: false,
    deliveryReady: false,
    next: ["Draft", "Cancelled"],
  },
  "Signature Declined": {
    buyerLabel: "Signature declined",
    buyerVisible: true,
    signatureEligible: false,
    paymentReady: false,
    licenceReady: false,
    deliveryReady: false,
    next: ["Draft", "Cancelled", "Archived"],
  },
  "Signature Expired": {
    buyerLabel: "Signature expired",
    buyerVisible: true,
    signatureEligible: false,
    paymentReady: false,
    licenceReady: false,
    deliveryReady: false,
    next: ["Ready to Send", "Cancelled", "Archived"],
  },
  "Fully Signed": {
    buyerLabel: "Fully signed",
    buyerVisible: true,
    signatureEligible: false,
    paymentReady: true,
    licenceReady: false,
    deliveryReady: false,
    next: ["Countersigned", "Effective"],
  },
  Countersigned: {
    buyerLabel: "Countersigned",
    buyerVisible: true,
    signatureEligible: false,
    paymentReady: true,
    licenceReady: false,
    deliveryReady: false,
    next: ["Effective"],
  },
  Effective: {
    buyerLabel: "Effective",
    buyerVisible: true,
    signatureEligible: false,
    paymentReady: true,
    licenceReady: true,
    deliveryReady: false,
    next: ["Completed", "Terminated"],
  },
  Completed: {
    buyerLabel: "Completed",
    buyerVisible: true,
    signatureEligible: false,
    paymentReady: true,
    licenceReady: true,
    deliveryReady: true,
    next: ["Archived"],
  },
  Cancelled: {
    buyerLabel: "Cancelled",
    buyerVisible: true,
    signatureEligible: false,
    paymentReady: false,
    licenceReady: false,
    deliveryReady: false,
    next: ["Archived"],
  },
  Terminated: {
    buyerLabel: "Terminated",
    buyerVisible: true,
    signatureEligible: false,
    paymentReady: false,
    licenceReady: false,
    deliveryReady: false,
    next: ["Archived"],
  },
  Superseded: {
    buyerLabel: "Superseded",
    buyerVisible: true,
    signatureEligible: false,
    paymentReady: false,
    licenceReady: false,
    deliveryReady: false,
    next: ["Archived"],
  },
  Archived: {
    buyerLabel: "Archived",
    buyerVisible: false,
    signatureEligible: false,
    paymentReady: false,
    licenceReady: false,
    deliveryReady: false,
    next: [],
  },
};

const clause = (
  id,
  title,
  category,
  body,
  types = ["Standard synchronization licence agreement"],
  required = true,
) => ({
  id,
  title,
  category,
  body,
  version: 1,
  required,
  buyerVisible: true,
  internalGuidance:
    "Prototype clause for approved legal-template review; not legal advice.",
  applicableContractTypes: types,
  approvalRequirements: ["Legal"],
  updatedAt: "2026-07-01T09:00:00.000Z",
});
export const DEFAULT_CLAUSES = [
  clause(
    "clause-grant",
    "Grant of Rights",
    "Grant of rights",
    "Subject to this Agreement, {{LICENSOR_NAME}} grants {{LICENSEE_NAME}} a limited {{EXCLUSIVITY}} synchronization licence for {{TRACK_TITLE}} solely for {{PROJECT_NAME}} in the approved media, territory and term.",
  ),
  clause(
    "clause-use",
    "Permitted Usage",
    "Permitted usage",
    "The approved use is {{USAGE_DESCRIPTION}}. No use outside {{MEDIA}} is authorized.",
  ),
  clause(
    "clause-territory",
    "Territory",
    "Territory",
    "The licence is limited to {{TERRITORY}}.",
  ),
  clause(
    "clause-term",
    "Term",
    "Term",
    "The permitted term is {{TERM}}, beginning on the effective date unless otherwise stated.",
  ),
  clause(
    "clause-fee",
    "Licence Fee",
    "Fee",
    "The licence fee is {{LICENCE_FEE}} {{CURRENCY}}, payable under the agreed terms: {{PAYMENT_TERMS}}.",
  ),
  clause(
    "clause-tax",
    "Taxes",
    "Taxes",
    "Applicable taxes, if any, are determined outside this prototype and are not calculated by beatmondo.",
  ),
  clause(
    "clause-delivery",
    "Delivery",
    "Delivery",
    "Approved assets are {{ASSETS_INCLUDED}}. Contract execution does not itself authorize delivery; payment and other dependencies may remain.",
  ),
  clause(
    "clause-credit",
    "Credits",
    "Credits",
    "Approved credit: {{CREDIT_REQUIREMENT}}.",
  ),
  clause(
    "clause-restrictions",
    "Restrictions",
    "Restrictions",
    "The licensee must observe: {{RESTRICTIONS}}.",
  ),
  clause(
    "clause-editing",
    "Editing and Modification",
    "Editing and modification",
    "Edits may be made only to fit the approved production. No lyrical alteration, isolated distribution, or standalone audio exploitation is permitted.",
  ),
  clause(
    "clause-warranty",
    "Representations",
    "Representations",
    "Each party represents that its named signatory is authorized to enter this agreement, subject to the documented rights scope.",
  ),
  clause(
    "clause-confidentiality",
    "Confidentiality",
    "Confidentiality",
    "Confidential project materials and private catalog access must not be disclosed except as required for the approved production.",
  ),
  clause(
    "clause-termination",
    "Termination",
    "Termination",
    "Termination and its effect require human legal review under the applicable agreement terms.",
  ),
  clause(
    "clause-notices",
    "Notices",
    "Notices",
    "Notices must be sent to the designated contacts recorded for each party.",
  ),
  clause(
    "clause-law",
    "Governing Law",
    "Governing law",
    "The governing-law placeholder is England and Wales, subject to approved jurisdiction-specific legal review.",
  ),
  clause(
    "clause-entire",
    "Entire Agreement",
    "Entire agreement",
    "This Agreement and its schedules constitute the entire agreement for the licensed use.",
  ),
  clause(
    "clause-esign",
    "Electronic Signatures",
    "Electronic signatures",
    "The parties consent to simulated electronic execution in this prototype. Production execution requires an approved e-signature provider and legal process.",
  ),
  clause(
    "clause-assignment",
    "Assignment",
    "Assignment",
    "The licence may not be assigned or sublicensed without prior written approval.",
  ),
  clause(
    "clause-cues",
    "Cue Sheets",
    "Cue sheets",
    "The licensee will provide accurate cue-sheet information where applicable.",
  ),
  clause(
    "clause-ml",
    "Machine Learning",
    "Other",
    "The recording and composition may not be used for machine-learning training or model development.",
  ),
];

const template = (id, name, type, clauseIds, overrides = {}) => ({
  id,
  name,
  contractType: type,
  description:
    overrides.description ||
    "Approved prototype template with versioned clauses.",
  version: 1,
  active: true,
  jurisdiction: "England and Wales placeholder",
  language: "English",
  clauseIds,
  variables: [
    "CONTRACT_REFERENCE",
    "EFFECTIVE_DATE",
    "LICENSOR_NAME",
    "LICENSEE_NAME",
    "BUYER_SIGNER_NAME",
    "PROJECT_NAME",
    "TRACK_TITLE",
    "ARTIST_NAME",
    "QUOTE_REFERENCE",
    "LICENCE_FEE",
    "CURRENCY",
    "MEDIA",
    "TERRITORY",
    "TERM",
    "EXCLUSIVITY",
    "USAGE_DESCRIPTION",
    "ASSETS_INCLUDED",
    "CREDIT_REQUIREMENT",
    "RESTRICTIONS",
    "PAYMENT_TERMS",
    "SIGNATURE_DEADLINE",
  ],
  requiredApprovals: overrides.requiredApprovals || [
    "Licensing",
    "Rights",
    "Finance",
    "Legal",
  ],
  requiredSigners: overrides.requiredSigners || [
    "Buyer signatory",
    "Beatmondo senior signatory",
  ],
  supportedProjectTypes: overrides.supportedProjectTypes || [
    "Film",
    "Television",
    "Advertising",
    "Trailer",
    "Branded content",
  ],
  createdAt: "2026-06-01T09:00:00.000Z",
  updatedAt: "2026-07-01T09:00:00.000Z",
});
const standardClauses = DEFAULT_CLAUSES.map((x) => x.id);
export const DEFAULT_TEMPLATES = [
  template(
    "template-standard",
    "Standard Sync Licence",
    "Combined Master and Publishing Agreement",
    standardClauses,
  ),
  template(
    "template-conditional",
    "Conditional Sync Licence",
    "Conditional Licence Agreement",
    standardClauses,
    {
      requiredApprovals: ["Licensing", "Rights", "Finance", "Legal", "Senior"],
    },
  ),
  template(
    "template-advertising",
    "Advertising and Brand Campaign Licence",
    "Standard synchronization licence agreement",
    standardClauses,
    {
      supportedProjectTypes: [
        "Advertising",
        "Branded content",
        "Sonic branding",
      ],
    },
  ),
  template(
    "template-trailer",
    "Trailer Licence Agreement",
    "Combined Master and Publishing Agreement",
    standardClauses,
    { supportedProjectTypes: ["Trailer", "Cinema", "Online trailer"] },
  ),
  template(
    "template-amendment",
    "Amendment and Renewal Agreement",
    "Amendment Agreement",
    [
      "clause-use",
      "clause-territory",
      "clause-term",
      "clause-fee",
      "clause-restrictions",
      "clause-esign",
      "clause-entire",
    ],
    { requiredApprovals: ["Licensing", "Rights", "Finance", "Legal"] },
  ),
];

const signer = (
  id,
  name,
  email,
  organization,
  title,
  role,
  order,
  status,
  overrides = {},
) => ({
  id,
  userId: overrides.userId || null,
  name,
  email,
  organization,
  title,
  role,
  signingOrder: order,
  required: overrides.required ?? true,
  status,
  invitedAt: overrides.invitedAt || null,
  viewedAt: overrides.viewedAt || null,
  signedAt: overrides.signedAt || null,
  declinedAt: null,
  expiresAt: overrides.expiresAt || "2026-08-03T23:59:59.000Z",
  signatureMethod: overrides.signatureMethod || null,
  signatureRecordId: overrides.signatureRecordId || null,
  reassignedFrom: null,
});
const approval = (type, status, approver, note = "") => ({
  id: `approval-${type.toLowerCase()}-${Math.random().toString(36).slice(2, 7)}`,
  type,
  status,
  approver,
  note,
  date: status === "Approved" ? "2026-07-17T10:00:00.000Z" : null,
  history: [],
});
const baseClauses = DEFAULT_CLAUSES.map((c) => ({
  ...c,
  clauseVersion: c.version,
  resolvedBody: c.body,
}));
const contract = (id, reference, status, overrides = {}) => ({
  id,
  reference,
  contractType:
    overrides.contractType || "Combined Master and Publishing Agreement",
  status,
  version: overrides.version || 1,
  current: true,
  quoteId: overrides.quoteId || "quote-41",
  quoteReference: overrides.quoteReference || "BM-Q-2026-0041",
  quoteVersion: overrides.quoteVersion || 1,
  licensingRequestId: overrides.licensingRequestId || "request-quote-41",
  projectId: overrides.projectId || "project-premium-hotel",
  project: overrides.project || "Premium Hotel Launch Film",
  buyerId: overrides.buyerId || "user-olivia",
  buyer: overrides.buyer || "Olivia Bennett",
  organizationId: overrides.organizationId || "org-northstar",
  organization: overrides.organization || "Northstar Pictures",
  trackIds: overrides.trackIds || [1],
  trackTitle: overrides.trackTitle || "Golden Hours",
  artist: overrides.artist || "Lennox",
  rightsRecordIds: overrides.rightsRecordIds || ["rights-1"],
  rightsVersions: overrides.rightsVersions || [1],
  templateId: overrides.templateId || "template-standard",
  templateVersion: 1,
  title:
    overrides.title ||
    `${overrides.project || "Premium Hotel Launch Film"} — Music Licence`,
  effectiveDate: overrides.effectiveDate || null,
  expiryDate: overrides.expiryDate || null,
  signatureDeadline: overrides.signatureDeadline || "2026-08-03T23:59:59.000Z",
  licensor: {
    legalName: "Beatmondo Licensing Ltd (prototype placeholder)",
    tradingName: "beatmondo",
    address: "Legal address pending production configuration",
    authorizedSignatory: "Preston Repenning",
    title: "Authorized Signatory",
    email: "admin@beatmondo.com",
  },
  licensee: {
    legalName: overrides.organization || "Northstar Pictures",
    address:
      overrides.licenseeAddress || "Buyer legal address on approved account",
    companyNumber: "",
    authorizedSignatory: overrides.buyer || "Olivia Bennett",
    title: overrides.buyerTitle || "Senior Music Supervisor",
    email: overrides.buyerEmail || "olivia@northstarpictures.com",
    billingContact: overrides.billingContact || "billing@northstarpictures.com",
  },
  usage: overrides.usage || "One synchronized use in the approved project.",
  media: overrides.media || ["Online Video", "Paid Social"],
  territory: overrides.territory || "Worldwide",
  term: overrides.term || "12 months",
  exclusivity: overrides.exclusivity || "Non-exclusive",
  fees: overrides.fees || {
    licenceFee: 1050000,
    currency: "USD",
    deposit: 262500,
    balance: 787500,
    taxTreatment: "Not calculated in prototype",
    preparationFees: 0,
  },
  paymentTerms:
    overrides.paymentTerms ||
    "25% deposit; balance due before approved delivery",
  assets: overrides.assets || ["WAV master"],
  restrictions: overrides.restrictions || [
    "No sublicensing",
    "No standalone audio distribution",
    "No machine-learning training",
  ],
  approvals: overrides.approvals || [],
  credits:
    overrides.credits ||
    `“${overrides.trackTitle || "Golden Hours"}” performed by ${overrides.artist || "Lennox"}\nLicensed courtesy of beatmondo`,
  clauses: overrides.clauses || baseClauses,
  schedules: overrides.schedules || [
    {
      id: `schedule-${id}-track`,
      title: "Track and Usage Schedule",
      items: [
        overrides.trackTitle || "Golden Hours",
        overrides.project || "Premium Hotel Launch Film",
      ],
    },
    {
      id: `schedule-${id}-assets`,
      title: "Approved Assets",
      items: overrides.assets || ["WAV master"],
    },
  ],
  signers: overrides.signers || [],
  signatures: overrides.signatures || [],
  comments: overrides.comments || [],
  internalNotes: overrides.internalNotes || [],
  buyerMessages: overrides.buyerMessages || [],
  previousVersionId: overrides.previousVersionId || null,
  supersededBy: null,
  generatedDocumentAssetId:
    overrides.generatedDocumentAssetId || `contract-document-${id}-v1`,
  signedDocumentAssetId: overrides.signedDocumentAssetId || null,
  createdAt: overrides.createdAt || "2026-07-16T09:00:00.000Z",
  createdBy: overrides.createdBy || "Jordan Lee",
  updatedAt: overrides.updatedAt || "2026-07-18T10:00:00.000Z",
  sentAt: overrides.sentAt || null,
  fullySignedAt: overrides.fullySignedAt || null,
  countersignedAt: overrides.countersignedAt || null,
  cancelledAt: overrides.cancelledAt || null,
  contractOwner: overrides.contractOwner || "Jordan Lee",
  dependencies: overrides.dependencies || {
    fullSignature: false,
    countersignature: false,
    payment: false,
    rightsApproval: true,
    buyerVerification: true,
    membership: true,
    deliveryAuthorized: false,
  },
  paymentStatus: overrides.paymentStatus || "Not Ready",
  licenceGeneration: overrides.licenceGeneration || "Not Ready",
  deliveryStatus: overrides.deliveryStatus || "Not authorized",
  signingOrder: overrides.signingOrder || "Buyer first",
});

export const DEFAULT_CONTRACTS = [
  contract("contract-21", "BM-C-2026-0021", "Effective", {
    project: "Premium Hotel Launch Film",
    effectiveDate: "2026-07-18T16:00:00.000Z",
    signatureDeadline: "2026-07-31T23:59:59.000Z",
    media: ["Online Video", "Cinema", "Trailer"],
    approvals: [
      approval("Licensing", "Approved", "Jordan Lee"),
      approval("Rights", "Approved", "Amelia Grant"),
      approval("Finance", "Approved", "Nadia Foster"),
      approval(
        "Legal",
        "Approved",
        "Preston Repenning",
        "Simulated review only",
      ),
    ],
    signers: [
      signer(
        "signer-21-buyer",
        "Olivia Bennett",
        "olivia@northstarpictures.com",
        "Northstar Pictures",
        "Senior Music Supervisor",
        "Buyer signatory",
        1,
        "Signed",
        {
          userId: "user-olivia",
          signedAt: "2026-07-18T15:30:00.000Z",
          signatureMethod: "Typed signature",
          signatureRecordId: "signature-21-buyer",
        },
      ),
      signer(
        "signer-21-bm",
        "Preston Repenning",
        "admin@beatmondo.com",
        "beatmondo",
        "Authorized Signatory",
        "Beatmondo senior signatory",
        2,
        "Signed",
        {
          userId: "user-preston",
          signedAt: "2026-07-18T16:00:00.000Z",
          signatureMethod: "Approved stored signature",
          signatureRecordId: "signature-21-bm",
        },
      ),
    ],
    signatures: [
      {
        id: "signature-21-buyer",
        contractVersion: 1,
        signerId: "signer-21-buyer",
        signerName: "Olivia Bennett",
        signatureMethod: "Typed signature",
        signatureDisplay: "Olivia Bennett",
        consentVersion: "prototype-consent-v1",
        signedAt: "2026-07-18T15:30:00.000Z",
        mockIp: "203.0.113.42",
        device: "Codex Browser",
        verificationMethod: "Authenticated account + code",
        status: "Recorded",
      },
      {
        id: "signature-21-bm",
        contractVersion: 1,
        signerId: "signer-21-bm",
        signerName: "Preston Repenning",
        signatureMethod: "Approved stored signature",
        signatureDisplay: "Preston Repenning — simulated",
        consentVersion: "prototype-consent-v1",
        signedAt: "2026-07-18T16:00:00.000Z",
        mockIp: "203.0.113.42",
        device: "Codex Browser",
        verificationMethod: "Internal authorization",
        status: "Recorded",
      },
    ],
    fullySignedAt: "2026-07-18T16:00:00.000Z",
    countersignedAt: "2026-07-18T16:00:00.000Z",
    signedDocumentAssetId: "asset-contract-1",
    dependencies: {
      fullSignature: true,
      countersignature: true,
      payment: false,
      rightsApproval: true,
      buyerVerification: true,
      membership: true,
      deliveryAuthorized: false,
    },
    paymentStatus: "Pending",
    licenceGeneration: "Pending payment",
    deliveryStatus: "Not authorized",
  }),
  contract("contract-22", "BM-C-2026-0022", "Awaiting Buyer Signature", {
    quoteId: "quote-47",
    quoteReference: "BM-Q-2026-0047",
    projectId: "project-luxury-auto",
    project: "Luxury Auto Campaign - Fall 2026",
    fees: {
      licenceFee: 2200000,
      currency: "USD",
      deposit: 550000,
      balance: 1650000,
      taxTreatment: "Not calculated in prototype",
      preparationFees: 200000,
    },
    assets: ["WAV master", "Stems"],
    sentAt: "2026-07-20T10:00:00.000Z",
    approvals: [
      approval("Licensing", "Approved", "Jordan Lee"),
      approval("Rights", "Approved", "Amelia Grant"),
      approval("Finance", "Approved", "Nadia Foster"),
      approval("Legal", "Approved", "Preston Repenning"),
    ],
    signers: [
      signer(
        "signer-22-buyer",
        "Olivia Bennett",
        "olivia@northstarpictures.com",
        "Northstar Pictures",
        "Senior Music Supervisor",
        "Buyer signatory",
        1,
        "Viewed",
        {
          userId: "user-olivia",
          invitedAt: "2026-07-20T10:00:00.000Z",
          viewedAt: "2026-07-20T12:00:00.000Z",
        },
      ),
      signer(
        "signer-22-bm",
        "Preston Repenning",
        "admin@beatmondo.com",
        "beatmondo",
        "Authorized Signatory",
        "Beatmondo senior signatory",
        2,
        "Not Invited",
        { userId: "user-preston" },
      ),
    ],
  }),
  contract("contract-23", "BM-C-2026-0023", "Buyer Changes Requested", {
    quoteId: "quote-44",
    quoteReference: "BM-Q-2026-0044",
    project: "Midnight Run Trailer",
    buyerId: "user-rachel",
    buyer: "Rachel Kim",
    organizationId: "org-orbit",
    organization: "Orbit Trailers",
    trackIds: [4],
    trackTitle: "All That Remains",
    artist: "Vespera",
    contractType: "Conditional Licence Agreement",
    templateId: "template-conditional",
    fees: {
      licenceFee: 1850000,
      currency: "USD",
      deposit: 0,
      balance: 1850000,
      taxTreatment: "Not calculated",
      preparationFees: 0,
    },
    restrictions: [
      "Sample clearance required",
      "Cinema usage requires confirmation",
      "No sublicensing",
    ],
    comments: [
      {
        id: "comment-23-buyer",
        author: "Rachel Kim",
        role: "Buyer",
        date: "2026-07-21T09:00:00.000Z",
        section: "Restrictions and payment",
        selectedText: "Sample clearance required",
        comment:
          "Please clarify the sample-clearance condition, payment timing, and whether cinema usage is included.",
        visibility: "Buyer Visible",
        status: "Buyer Response Required",
        assignee: "Jordan Lee",
      },
    ],
    signers: [
      signer(
        "signer-23-buyer",
        "Rachel Kim",
        "rachel@orbittrailers.com",
        "Orbit Trailers",
        "Music Coordinator",
        "Buyer signatory",
        1,
        "Not Invited",
        { userId: "user-rachel" },
      ),
    ],
    dependencies: {
      fullSignature: false,
      countersignature: false,
      payment: false,
      rightsApproval: false,
      buyerVerification: false,
      membership: false,
      deliveryAuthorized: false,
    },
  }),
  contract("contract-24", "BM-C-2026-0024", "Legal Review", {
    quoteId: "quote-42",
    quoteReference: "BM-Q-2026-0042",
    project: "Launch Forward Campaign",
    buyerId: "user-ethan",
    buyer: "Ethan Cole",
    organizationId: "org-brightframe",
    organization: "BrightFrame Agency",
    trackIds: [2],
    trackTitle: "Paper Planes",
    artist: "Arco North",
    contractType: "Conditional Licence Agreement",
    templateId: "template-conditional",
    fees: {
      licenceFee: 600000,
      currency: "USD",
      deposit: 150000,
      balance: 450000,
      taxTreatment: "Not calculated",
      preparationFees: 0,
    },
    restrictions: [
      "Publisher confirmation pending",
      "No delivery until approval",
    ],
    approvals: [
      approval("Licensing", "Approved", "Jordan Lee"),
      approval("Rights", "Pending", "Amelia Grant"),
      approval("Finance", "Pending", "Nadia Foster"),
      approval("Legal", "Pending", "Preston Repenning"),
    ],
    internalNotes: [
      "Publishing approval remains pending. Buyer visibility is disabled.",
    ],
    dependencies: {
      fullSignature: false,
      countersignature: false,
      payment: false,
      rightsApproval: false,
      buyerVerification: false,
      membership: false,
      deliveryAuthorized: false,
    },
  }),
  contract("contract-25", "BM-C-2026-0025", "Partially Signed", {
    quoteId: "quote-39",
    quoteReference: "BM-Q-2026-0039",
    project: "Feature Film End Credits",
    buyerId: "buyer-enterprise",
    buyer: "Enterprise Studio Legal",
    organizationId: "org-enterprise",
    organization: "Enterprise Studio Group",
    trackIds: [19],
    trackTitle: "Velvet Warning",
    artist: "Jade Montague",
    contractType: "Enterprise or Framework Agreement",
    fees: {
      licenceFee: 4200000,
      currency: "USD",
      deposit: 1050000,
      balance: 3150000,
      taxTreatment: "Not calculated",
      preparationFees: 0,
    },
    signingOrder: "Parallel",
    signers: [
      signer(
        "signer-25-legal",
        "Alex Morgan",
        "legal@enterprisestudio.example",
        "Enterprise Studio Group",
        "Legal Representative",
        "Buyer signatory",
        1,
        "Signed",
        {
          signedAt: "2026-07-19T12:00:00.000Z",
          signatureMethod: "Typed signature",
          signatureRecordId: "signature-25-legal",
        },
      ),
      signer(
        "signer-25-finance",
        "Taylor Reed",
        "finance@enterprisestudio.example",
        "Enterprise Studio Group",
        "Finance Representative",
        "Buyer finance approver",
        1,
        "Viewed",
      ),
      signer(
        "signer-25-bm",
        "Jordan Lee",
        "jordan@beatmondo.com",
        "beatmondo",
        "Licensing Manager",
        "Beatmondo licensing signatory",
        1,
        "Signed",
        {
          userId: "user-jordan",
          signedAt: "2026-07-19T13:00:00.000Z",
          signatureMethod: "Approved stored signature",
          signatureRecordId: "signature-25-bm",
        },
      ),
      signer(
        "signer-25-rights",
        "Rights Owner Representative",
        "rights-owner@example.test",
        "Represented Rightsholder",
        "Authorized Representative",
        "Rights-owner signatory",
        1,
        "Invited",
      ),
    ],
  }),
  contract("contract-26", "BM-C-2026-0026", "Effective", {
    quoteId: "quote-49",
    quoteReference: "BM-Q-2026-0049",
    projectId: "project-brand-film",
    project: "Northstar Brand Film",
    fees: {
      licenceFee: 1600000,
      currency: "USD",
      deposit: 1600000,
      balance: 0,
      taxTreatment: "Not calculated in prototype",
      preparationFees: 0,
    },
    assets: ["WAV master", "Instrumental"],
    approvals: [
      approval("Licensing", "Approved", "Jordan Lee"),
      approval("Rights", "Approved", "Amelia Grant"),
      approval("Finance", "Approved", "Nadia Foster"),
      approval("Legal", "Approved", "Preston Repenning"),
    ],
    signers: [
      signer(
        "signer-26-buyer",
        "Olivia Bennett",
        "olivia@northstarpictures.com",
        "Northstar Pictures",
        "Senior Music Supervisor",
        "Buyer signatory",
        1,
        "Signed",
        {
          userId: "user-olivia",
          signedAt: "2026-07-15T15:00:00.000Z",
          signatureMethod: "Typed signature",
          signatureRecordId: "signature-26-buyer",
        },
      ),
      signer(
        "signer-26-bm",
        "Preston Repenning",
        "admin@beatmondo.com",
        "beatmondo",
        "Authorized Signatory",
        "Beatmondo senior signatory",
        2,
        "Signed",
        {
          userId: "user-preston",
          signedAt: "2026-07-15T16:00:00.000Z",
          signatureMethod: "Approved stored signature",
          signatureRecordId: "signature-26-bm",
        },
      ),
    ],
    fullySignedAt: "2026-07-15T16:00:00.000Z",
    countersignedAt: "2026-07-15T16:00:00.000Z",
    effectiveDate: "2026-07-15T16:00:00.000Z",
    signedDocumentAssetId: "signed-contract-contract-26-v1",
    dependencies: {
      fullSignature: true,
      countersignature: true,
      payment: true,
      rightsApproval: true,
      buyerVerification: true,
      membership: true,
      deliveryAuthorized: false,
    },
    paymentStatus: "Payment Complete",
    licenceGeneration: "Ready",
    deliveryStatus: "Not authorized — licence required",
  }),
  contract("contract-18", "BM-C-2026-0018", "Signature Expired", {
    quoteId: "quote-37",
    quoteReference: "BM-Q-2026-0037",
    project: "Independent Channel Package",
    buyerId: "user-daniel",
    buyer: "Daniel Brooks",
    organizationId: "org-independent",
    organization: "Self-employed",
    trackIds: [16],
    trackTitle: "Northern Lines",
    artist: "Arco North",
    sentAt: "2026-06-10T10:00:00.000Z",
    signatureDeadline: "2026-06-24T23:59:59.000Z",
    signers: [
      signer(
        "signer-18-buyer",
        "Daniel Brooks",
        "daniel@independentmail.com",
        "Self-employed",
        "Content Creator",
        "Buyer signatory",
        1,
        "Expired",
        { userId: "user-daniel", expiresAt: "2026-06-24T23:59:59.000Z" },
      ),
    ],
    dependencies: {
      fullSignature: false,
      countersignature: false,
      payment: false,
      rightsApproval: false,
      buyerVerification: false,
      membership: false,
      deliveryAuthorized: false,
    },
  }),
  contract("contract-19", "BM-C-2026-0019", "Cancelled", {
    quoteId: "quote-43",
    quoteReference: "BM-Q-2026-0043",
    project: "Quiet City Documentary",
    buyerId: "user-sofia",
    buyer: "Sofia Martinez",
    organizationId: "org-lighthouse",
    organization: "Lighthouse Creative",
    trackIds: [3],
    trackTitle: "Midnight Transit",
    artist: "Soren",
    cancelledAt: "2026-07-12T12:00:00.000Z",
    buyerMessages: [
      "Contract cancelled because rights information remained incomplete.",
    ],
    internalNotes: ["Internal record retained."],
    dependencies: {
      fullSignature: false,
      countersignature: false,
      payment: false,
      rightsApproval: false,
      buyerVerification: false,
      membership: false,
      deliveryAuthorized: false,
    },
  }),
  contract("amendment-3", "BM-A-2026-0003", "Draft", {
    contractType: "Amendment Agreement",
    templateId: "template-amendment",
    quoteId: "quote-51",
    quoteReference: "BM-Q-2026-0051",
    project: "Northstar Territory and Media Extension",
    title: "Amendment to BM-C-2026-0012",
    previousVersionId: "contract-original-12",
    term: "24 months",
    territory: "Worldwide",
    media: ["Online Video", "Paid Social"],
    buyerMessages: [
      "Original agreement remains effective until this amendment is executed.",
    ],
    restrictions: [
      "Adds paid social only",
      "All unchanged original restrictions remain",
    ],
  }),
];

export const DEFAULT_CONTRACT_STATE = {
  version: 1,
  templates: DEFAULT_TEMPLATES,
  templateVersions: [],
  clauses: DEFAULT_CLAUSES,
  clauseVersions: [],
  contracts: DEFAULT_CONTRACTS,
  contractVersions: [],
  signatureRecords: DEFAULT_CONTRACTS.flatMap((c) => c.signatures),
  consentRecords: [],
  signedDocuments: [
    {
      id: "signed-document-21",
      contractId: "contract-21",
      contractVersion: 1,
      assetId: "asset-contract-1",
      immutable: true,
      createdAt: "2026-07-18T16:01:00.000Z",
      certificateLabel:
        "Prototype signature record — not a certified e-signature-provider certificate.",
    },
  ],
  activity: [],
  analyticsEvents: [],
  notifications: [],
  amendments: ["amendment-3"],
  renewals: [],
};
