export const SECURE_DELIVERY_STORAGE_KEY = "beatmondo-secure-delivery-v1";
export const SELECTED_DELIVERY_KEY = "beatmondo-selected-secure-delivery";

export const DELIVERY_STATUSES = {
  Draft: { buyerLabel: "Preparing", download: false, renewal: false, replacement: false, next: ["Readiness Incomplete", "Pending Approval", "Cancelled"] },
  "Readiness Incomplete": { buyerLabel: "Requirements pending", download: false, renewal: false, replacement: false, next: ["Pending Asset Preparation", "Pending Approval", "Cancelled"] },
  "Pending Approval": { buyerLabel: "Final review", download: false, renewal: false, replacement: false, next: ["Ready to Activate", "Readiness Incomplete", "Cancelled"] },
  "Pending Asset Preparation": { buyerLabel: "Assets being prepared", download: false, renewal: false, replacement: false, next: ["Pending Approval", "Cancelled"] },
  "Ready to Activate": { buyerLabel: "Ready", download: false, renewal: false, replacement: false, next: ["Active", "Cancelled"] },
  Active: { buyerLabel: "Available", download: true, renewal: true, replacement: true, next: ["Partially Downloaded", "Completed", "Expiring Soon", "Download Limit Reached", "Suspended", "Replacement Ready", "Revoked"] },
  "Partially Downloaded": { buyerLabel: "Available", download: true, renewal: true, replacement: true, next: ["Completed", "Expiring Soon", "Download Limit Reached", "Suspended", "Replacement Ready", "Revoked"] },
  Completed: { buyerLabel: "Delivered", download: true, renewal: true, replacement: true, next: ["Expiring Soon", "Expired", "Replacement Ready", "Revoked"] },
  "Download Limit Reached": { buyerLabel: "Download limit reached", download: false, renewal: true, replacement: true, next: ["Active", "Suspended", "Revoked"] },
  "Expiring Soon": { buyerLabel: "Expiring soon", download: true, renewal: true, replacement: true, next: ["Expired", "Suspended", "Revoked"] },
  Expired: { buyerLabel: "Access expired", download: false, renewal: true, replacement: true, next: ["Active", "Archived"] },
  Suspended: { buyerLabel: "Temporarily unavailable", download: false, renewal: false, replacement: false, next: ["Active", "Revoked"] },
  "Replacement Ready": { buyerLabel: "Updated package ready", download: true, renewal: true, replacement: true, next: ["Partially Downloaded", "Completed", "Superseded", "Revoked"] },
  Revoked: { buyerLabel: "Access revoked", download: false, renewal: false, replacement: false, next: ["Archived"] },
  Superseded: { buyerLabel: "Replaced", download: false, renewal: false, replacement: false, next: ["Archived"] },
  Cancelled: { buyerLabel: "Cancelled", download: false, renewal: false, replacement: false, next: ["Archived"] },
  Archived: { buyerLabel: "Archived", download: false, renewal: false, replacement: false, next: [] },
};

const entry = (id, packageId, assetId, assetType, displayName, fileName, sizeBytes, overrides = {}) => ({
  id, deliveryPackageId: packageId, assetId, assetVersion: overrides.assetVersion || 1, assetType, displayName, fileName, sizeBytes,
  checksumPlaceholder: overrides.checksumPlaceholder || `demo-sha256-${assetId}-v${overrides.assetVersion || 1}`,
  status: overrides.status || "Ready", required: overrides.required ?? true, downloadLimit: overrides.downloadLimit ?? 3,
  downloadCount: overrides.downloadCount || 0, firstDownloadedAt: overrides.firstDownloadedAt || null, lastDownloadedAt: overrides.lastDownloadedAt || null,
  expiresAt: overrides.expiresAt || "2026-07-25T23:59:59.000Z", replacedBy: overrides.replacedBy || null, notes: overrides.notes || [],
  format: fileName.split(".").pop().toUpperCase(), approvalDate: overrides.approvalDate || "2026-07-18T12:00:00.000Z",
});

const approval = (type, status = "Approved", approver = null) => ({ id: `delivery-approval-${type.toLowerCase().replaceAll(" ", "-")}-${Math.random().toString(36).slice(2, 6)}`, type, status, approver: approver || ({ Licensing: "Jordan Lee", Media: "Noah Pierce", Rights: "Amelia Grant", Finance: "Nadia Foster", Senior: "Preston Repenning" }[type]), note: "Reviewed against locked delivery dependencies.", date: status === "Approved" ? "2026-07-18T12:30:00.000Z" : null });

const pack = (id, reference, status, overrides = {}) => ({
  id, reference, authorizationId: overrides.authorizationId || "delivery-auth-18", licenceId: overrides.licenceId || "licence-18", licenceReference: overrides.licenceReference || "BM-LIC-2026-0018", licenceVersion: overrides.licenceVersion || 1,
  buyerId: overrides.buyerId || "user-olivia", buyer: overrides.buyer || "Olivia Bennett", organizationId: overrides.organizationId || "org-northstar", organization: overrides.organization || "Northstar Pictures",
  projectId: overrides.projectId || "project-horizon-run", project: overrides.project || "Horizon Run Trailer", trackId: overrides.trackId || 1, trackTitle: overrides.trackTitle || "Afterglow Drive", artist: overrides.artist || "Lennox",
  version: overrides.version || 1, status, packageType: overrides.packageType || "Secure download package", assetEntries: overrides.assetEntries || [], documentEntries: overrides.documentEntries || [],
  recipient: overrides.recipient || { userId: overrides.buyerId || "user-olivia", name: overrides.buyer || "Olivia Bennett", email: overrides.recipientEmail || "olivia@northstarpictures.com" },
  watermarkIdentifier: overrides.watermarkIdentifier || `${reference || "BM-DEL-DRAFT"} · ${overrides.buyerId || "user-olivia"}`,
  linkVersion: overrides.linkVersion || 1, linkRegeneratedAt: overrides.linkRegeneratedAt || null,
  termsAcceptance: overrides.termsAcceptance || { status: ["Active", "Partially Downloaded", "Completed", "Expiring Soon", "Replacement Ready"].includes(status) ? "Accepted" : "Pending", version: "Delivery Terms v1.0", acceptedAt: ["Active", "Partially Downloaded", "Completed", "Expiring Soon", "Replacement Ready"].includes(status) ? "2026-07-18T16:20:00.000Z" : null, acceptedBy: ["Active", "Partially Downloaded", "Completed", "Expiring Soon", "Replacement Ready"].includes(status) ? (overrides.buyer || "Olivia Bennett") : null },
  deliveryConfirmation: overrides.deliveryConfirmation || { status: status === "Completed" ? "Confirmed" : "Pending", confirmedAt: status === "Completed" ? overrides.completedAt || "2026-07-19T09:20:00.000Z" : null },
  deliveryNotes: overrides.deliveryNotes || { buyer: "Please use the approved credit wording included in this package. Contact beatmondo before requesting alternate assets.", internal: "VIP delivery reviewed against licence and authorization." },
  manifest: overrides.manifest || null, validFrom: overrides.validFrom === undefined ? "2026-07-18T16:30:00.000Z" : overrides.validFrom, expiresAt: overrides.expiresAt === undefined ? "2026-07-25T23:59:59.000Z" : overrides.expiresAt, activatedAt: overrides.activatedAt === undefined ? "2026-07-18T16:30:00.000Z" : overrides.activatedAt, completedAt: overrides.completedAt || null,
  supersededBy: overrides.supersededBy || null, previousVersionId: overrides.previousVersionId || null, changeSummary: overrides.changeSummary || null,
  access: overrides.access || { namedUserIds: ["user-olivia"], organizationWide: false, organizationAdminUserId: "user-olivia", maxActiveSessions: 2, maxDevices: 3, maxDownloadsPerAsset: 3, maxTotalDownloads: 12, territoryRestrictions: [], additionalApprovalRequired: false },
  approvals: overrides.approvals || [approval("Licensing"), approval("Media"), approval("Rights"), approval("Finance"), approval("Senior")], restrictions: overrides.restrictions || ["Access is limited to the licensed project team", "No onward distribution", "Access expires automatically"],
  owner: overrides.owner || "Jordan Lee", createdAt: overrides.createdAt || "2026-07-18T15:00:00.000Z", createdBy: overrides.createdBy || "Jordan Lee", updatedAt: overrides.updatedAt || "2026-07-18T16:30:00.000Z",
  paymentState: overrides.paymentState || "Paid in Full",
});

const d1 = "delivery-package-16";
const d2 = "delivery-package-17";
const d3 = "delivery-package-18";
const d4 = "delivery-package-19";
const d5 = "delivery-package-8";
const d6 = "delivery-package-20";
const d7 = "delivery-package-16-v2";
const d8 = "delivery-package-11";

export const DEFAULT_DELIVERY_AUTHORIZATIONS = [
  { id: "delivery-auth-18", licenceId: "licence-18", licenceVersion: 1, buyerId: "user-olivia", organizationId: "org-northstar", projectId: "project-horizon-run", trackId: 1, status: "Approved", approvedAssetTypes: ["WAV master", "Instrumental", "Clean version", "Stems package", "Licence document", "Cue-sheet information"], approvedAssetIds: ["asset-master-1", "asset-instrumental-1", "asset-clean-1", "asset-stems-1", "asset-licence-1", "asset-cue-sheet-1"], namedUserIds: ["user-olivia"], organizationWide: false, maxDownloadsPerAsset: 3, maxTotalDownloads: 12, validFrom: "2026-07-18T00:00:00.000Z", expiresAt: "2026-08-01T23:59:59.000Z", territoryRestrictions: [], additionalApprovalRequired: false, restrictions: ["Licensed project use only"], createdAt: "2026-07-18T12:00:00.000Z", createdBy: "Jordan Lee", revokedAt: null, revocationReason: null, metadata: { policy: "VIP buyer delivery", source: "Licence issuance" } },
  { id: "delivery-auth-aurora", licenceId: "licence-amended-11", licenceVersion: 2, buyerId: "user-olivia", organizationId: "org-northstar", projectId: "project-aurora", trackId: 9, status: "Approved", approvedAssetTypes: ["WAV master", "Instrumental", "30-second custom edit"], approvedAssetIds: ["asset-aurora-master", "asset-aurora-instrumental", "asset-aurora-edit-30"], namedUserIds: ["user-olivia"], organizationWide: false, maxDownloadsPerAsset: 3, maxTotalDownloads: 9, validFrom: "2026-07-15T00:00:00.000Z", expiresAt: "2026-08-01T23:59:59.000Z", territoryRestrictions: [], additionalApprovalRequired: false, restrictions: [], createdAt: "2026-07-15T10:00:00.000Z", createdBy: "Jordan Lee" },
  { id: "delivery-auth-sofia", licenceId: "licence-sofia-generated", licenceVersion: 1, buyerId: "user-sofia", organizationId: "org-lighthouse", projectId: "project-quiet-city", trackId: 3, status: "Payment Blocked", approvedAssetTypes: ["WAV master"], approvedAssetIds: ["asset-static-hearts-master"], namedUserIds: ["user-sofia"], organizationWide: false, maxDownloadsPerAsset: 2, maxTotalDownloads: 2, validFrom: null, expiresAt: null, restrictions: ["Final balance required"], createdAt: "2026-07-12T10:00:00.000Z", createdBy: "Jordan Lee" },
  { id: "delivery-auth-rachel", licenceId: "licence-conditional-23", licenceVersion: 1, buyerId: "user-rachel", organizationId: "org-orbit", projectId: "project-midnight-run", trackId: 4, status: "Suspended", approvedAssetTypes: ["WAV master"], approvedAssetIds: ["asset-midnight-signal-master"], namedUserIds: ["user-rachel"], organizationWide: false, maxDownloadsPerAsset: 2, maxTotalDownloads: 2, validFrom: "2026-06-20T00:00:00.000Z", expiresAt: "2026-07-30T23:59:59.000Z", restrictions: ["Sample clearance review reopened"], createdAt: "2026-06-20T10:00:00.000Z", createdBy: "Amelia Grant" },
  { id: "delivery-auth-enterprise", licenceId: "licence-19", licenceVersion: 1, buyerId: "buyer-enterprise", organizationId: "org-enterprise", projectId: "project-enterprise-film", trackId: 19, status: "Approved", approvedAssetTypes: ["WAV master", "Instrumental"], approvedAssetIds: ["asset-velvet-warning-master", "asset-velvet-warning-instrumental"], namedUserIds: ["buyer-enterprise"], organizationWide: true, maxDownloadsPerAsset: 3, maxTotalDownloads: 6, validFrom: "2026-07-20T00:00:00.000Z", expiresAt: "2026-08-20T23:59:59.000Z", restrictions: [], createdAt: "2026-07-20T10:00:00.000Z", createdBy: "Jordan Lee" },
  { id: "delivery-auth-revoked", licenceId: "licence-9", licenceVersion: 1, buyerId: "buyer-dummy", organizationId: "org-dummy", projectId: "project-cancelled-brand", trackId: 10, status: "Revoked", approvedAssetTypes: [], approvedAssetIds: [], namedUserIds: [], organizationWide: false, maxDownloadsPerAsset: 0, maxTotalDownloads: 0, validFrom: "2026-06-01T00:00:00.000Z", expiresAt: null, restrictions: ["Licence terminated"], createdAt: "2026-06-01T10:00:00.000Z", createdBy: "Jordan Lee", revokedAt: "2026-07-14T00:00:00.000Z", revocationReason: "Licence terminated" },
];

export const DEFAULT_DELIVERY_PACKAGES = [
  pack(d1, "BM-DEL-2026-0016", "Active", { assetEntries: [
    entry("delivery-entry-master-16", d1, "asset-master-1", "WAV master", "Afterglow Drive — WAV master", "afterglow-drive-master-v1.wav", 86400000, { downloadCount: 1, firstDownloadedAt: "2026-07-19T09:10:00.000Z", lastDownloadedAt: "2026-07-19T09:10:00.000Z" }),
    entry("delivery-entry-inst-16", d1, "asset-instrumental-1", "Instrumental", "Afterglow Drive — Instrumental", "afterglow-drive-instrumental-v1.wav", 85800000),
    entry("delivery-entry-clean-16", d1, "asset-clean-1", "Clean version", "Afterglow Drive — Clean", "afterglow-drive-clean-v1.wav", 86100000, { downloadCount: 1, firstDownloadedAt: "2026-07-19T09:15:00.000Z", lastDownloadedAt: "2026-07-19T09:15:00.000Z" }),
    entry("delivery-entry-stems-16", d1, "asset-stems-1", "Stems package", "Afterglow Drive — Stems", "afterglow-drive-stems-v1.zip", 2450000000),
  ], documentEntries: [{ id: "doc-licence-16", type: "Licence document", displayName: "Executed music licence", assetId: "asset-licence-1", version: 1 }, { id: "doc-cue-16", type: "Cue-sheet information", displayName: "Cue-sheet metadata", assetId: "asset-cue-sheet-1", version: 1 }], manifest: { id: "manifest-16", reference: "BM-MAN-2026-0016", version: 1, generatedAt: "2026-07-18T16:25:00.000Z", generatedBy: "Jordan Lee", current: true } }),
  pack(d2, null, "Pending Asset Preparation", { authorizationId: "delivery-auth-aurora", licenceId: "licence-amended-11", licenceReference: "BM-LIC-AMD-2026-0003", projectId: "project-aurora", project: "Aurora Motors Campaign", trackId: 9, trackTitle: "Golden Static", artist: "Atlas Collective", activatedAt: null, validFrom: null, expiresAt: null, assetEntries: [entry("delivery-entry-aurora-master", d2, "asset-aurora-master", "WAV master", "Golden Static — WAV master", "golden-static-master.wav", 91000000), entry("delivery-entry-aurora-inst", d2, "asset-aurora-instrumental", "Instrumental", "Golden Static — Instrumental", "golden-static-instrumental.wav", 90500000), entry("delivery-entry-aurora-edit", d2, "asset-aurora-edit-30", "30-second custom edit", "Golden Static — 30-second edit", "golden-static-30-edit.wav", 28000000, { status: "Preparing" })], approvals: [approval("Licensing"), approval("Media", "Pending"), approval("Rights"), approval("Finance")] }),
  pack(d3, null, "Readiness Incomplete", { authorizationId: "delivery-auth-sofia", licenceId: "licence-sofia-generated", licenceReference: "BM-LIC-2026-0021", buyerId: "user-sofia", buyer: "Sofia Martinez", organizationId: "org-lighthouse", organization: "Lighthouse Creative", projectId: "project-quiet-city", project: "Quiet City Documentary", trackId: 3, trackTitle: "Static Hearts", artist: "Vespera", activatedAt: null, validFrom: null, expiresAt: null, paymentState: "Final balance unpaid", assetEntries: [entry("delivery-entry-static-master", d3, "asset-static-hearts-master", "WAV master", "Static Hearts — WAV master", "static-hearts-master.wav", 94000000)], approvals: [approval("Licensing", "Pending"), approval("Media"), approval("Rights"), approval("Finance", "Pending")], deliveryNotes: { buyer: "The package is ready for review but cannot be released until the final licence balance is paid.", internal: "Payment blocker must not be overridden by asset readiness." } }),
  pack(d4, "BM-DEL-2026-0019", "Suspended", { authorizationId: "delivery-auth-rachel", licenceId: "licence-conditional-23", licenceReference: "BM-LIC-2026-0023", buyerId: "user-rachel", buyer: "Rachel Kim", organizationId: "org-orbit", organization: "Orbit Trailers", projectId: "project-midnight-run", project: "Midnight Run Trailer", trackId: 4, trackTitle: "Midnight Signal", artist: "Vespera", assetEntries: [entry("delivery-entry-midnight-master", d4, "asset-midnight-signal-master", "WAV master", "Midnight Signal — WAV master", "midnight-signal-master.wav", 92000000, { downloadCount: 1 })], deliveryNotes: { buyer: "Delivery access is temporarily unavailable while licensing conditions are reviewed.", internal: "Sample-clearance review reopened. Preserve completed download history." } }),
  pack(d5, "BM-DEL-2026-0008", "Expired", { licenceId: "licence-87", licenceReference: "BM-LIC-2025-0087", projectId: "project-legacy-campaign", project: "Legacy Campaign", trackId: 16, trackTitle: "Northern Lines", artist: "Arco North", expiresAt: "2026-07-01T23:59:59.000Z", assetEntries: [entry("delivery-entry-northern-master", d5, "asset-northern-lines-master", "WAV master", "Northern Lines — WAV master", "northern-lines-master.wav", 92000000, { downloadCount: 1, expiresAt: "2026-07-01T23:59:59.000Z" })] }),
  pack(d6, "BM-DEL-2026-0020", "Download Limit Reached", { authorizationId: "delivery-auth-enterprise", licenceId: "licence-19", licenceReference: "BM-LIC-2026-0019", buyerId: "buyer-enterprise", buyer: "Enterprise Studio Legal", organizationId: "org-enterprise", organization: "Enterprise Studio Group", projectId: "project-enterprise-film", project: "Feature Film End Credits", trackId: 19, trackTitle: "Velvet Warning", artist: "Jade Montague", packageType: "Enterprise delivery room", assetEntries: [entry("delivery-entry-velvet-master", d6, "asset-velvet-warning-master", "WAV master", "Velvet Warning — WAV master", "velvet-warning-master.wav", 102000000, { downloadCount: 3, status: "Download Limit Reached" }), entry("delivery-entry-velvet-inst", d6, "asset-velvet-warning-instrumental", "Instrumental", "Velvet Warning — Instrumental", "velvet-warning-instrumental.wav", 100000000)] }),
  pack(d7, "BM-DEL-2026-0016-V2", "Replacement Ready", { version: 2, previousVersionId: d1, projectId: "project-horizon-run", project: "Horizon Run Trailer", trackTitle: "Afterglow Drive", assetEntries: [entry("delivery-entry-inst-16-v2", d7, "asset-instrumental-1-v2", "Instrumental", "Afterglow Drive — Instrumental V2", "afterglow-drive-instrumental-v2.wav", 85900000, { assetVersion: 2, downloadLimit: 2, notes: ["Corrected end fade"] })], previousVersionId: d1, changeSummary: "Instrumental V1 replaced after an incorrect fade at the end was confirmed.", expiresAt: "2026-07-29T23:59:59.000Z", packageType: "Replacement delivery" }),
  pack(d8, "BM-DEL-2026-0011", "Revoked", { authorizationId: "delivery-auth-revoked", licenceId: "licence-9", licenceReference: "BM-LIC-2026-0009", buyerId: "buyer-dummy", buyer: "Dummy Buyer", organizationId: "org-dummy", organization: "Dummy Buyer Organization", projectId: "project-cancelled-brand", project: "Cancelled Brand Campaign", trackId: 10, trackTitle: "Glass Horizon", artist: "Lennox", assetEntries: [entry("delivery-entry-glass-master", d8, "asset-glass-horizon-master", "WAV master", "Glass Horizon — WAV master", "glass-horizon-master.wav", 88000000, { status: "Revoked", downloadCount: 1 })], restrictions: ["Licence terminated"], deliveryNotes: { buyer: "This delivery is no longer available.", internal: "Licence terminated. All active sessions revoked; historical events preserved." } }),
];

export const DEFAULT_SECURE_DELIVERY_STATE = {
  version: 1, authorizations: DEFAULT_DELIVERY_AUTHORIZATIONS, packages: DEFAULT_DELIVERY_PACKAGES,
  packageVersions: [{ id: "package-version-16-v1", packageId: d1, version: 1, current: false, supersededBy: d7, snapshotAt: "2026-07-20T10:00:00.000Z" }, { id: "package-version-16-v2", packageId: d7, version: 2, current: true, previousVersionId: d1, snapshotAt: "2026-07-20T10:00:00.000Z" }],
  manifests: [{ id: "manifest-16", packageId: d1, reference: "BM-MAN-2026-0016", version: 1, generatedAt: "2026-07-18T16:25:00.000Z", current: true }],
  entitlements: [
    { id: "entitlement-master-16", deliveryPackageId: d1, assetEntryId: "delivery-entry-master-16", userId: "user-olivia", organizationId: "org-northstar", status: "Partially Used", downloadLimit: 3, downloadCount: 1, validFrom: "2026-07-18T16:30:00.000Z", expiresAt: "2026-07-25T23:59:59.000Z", lastAccessedAt: "2026-07-19T09:10:00.000Z", revokedAt: null, revocationReason: null, metadata: { devices: 1 } },
    { id: "entitlement-inst-16", deliveryPackageId: d1, assetEntryId: "delivery-entry-inst-16", userId: "user-olivia", organizationId: "org-northstar", status: "Active", downloadLimit: 3, downloadCount: 0, validFrom: "2026-07-18T16:30:00.000Z", expiresAt: "2026-07-25T23:59:59.000Z", lastAccessedAt: null, revokedAt: null, revocationReason: null, metadata: { devices: 0 } },
    { id: "entitlement-clean-16", deliveryPackageId: d1, assetEntryId: "delivery-entry-clean-16", userId: "user-olivia", organizationId: "org-northstar", status: "Partially Used", downloadLimit: 3, downloadCount: 1, validFrom: "2026-07-18T16:30:00.000Z", expiresAt: "2026-07-25T23:59:59.000Z", lastAccessedAt: "2026-07-19T09:15:00.000Z", revokedAt: null, revocationReason: null, metadata: { devices: 1 } },
    { id: "entitlement-stems-16", deliveryPackageId: d1, assetEntryId: "delivery-entry-stems-16", userId: "user-olivia", organizationId: "org-northstar", status: "Active", downloadLimit: 3, downloadCount: 0, validFrom: "2026-07-18T16:30:00.000Z", expiresAt: "2026-07-25T23:59:59.000Z", lastAccessedAt: null, revokedAt: null, revocationReason: null, metadata: { sensitive: true, devices: 0 } },
  ],
  sessions: [{ id: "download-session-master-16", deliveryPackageId: d1, assetEntryId: "delivery-entry-master-16", userId: "user-olivia", organizationId: "org-northstar", token: "bm_download_demo_used", status: "Completed", createdAt: "2026-07-19T09:09:50.000Z", startedAt: "2026-07-19T09:09:55.000Z", completedAt: "2026-07-19T09:10:20.000Z", failedAt: null, expiresAt: "2026-07-19T09:14:50.000Z", bytesTransferred: 86400000, failureCode: null, device: "MacBook Pro · Safari", ipAddress: "203.0.113.42 · simulated", approximateLocation: "Los Angeles, US" }],
  extensionRequests: [], replacementRecords: [{ id: "replacement-16-v2", packageId: d1, replacementPackageId: d7, assetEntryId: "delivery-entry-inst-16", replacementAssetEntryId: "delivery-entry-inst-16-v2", reason: "Incorrect fade", status: "Replacement Ready", createdAt: "2026-07-20T10:00:00.000Z", createdBy: "Noah Pierce" }],
  suspensions: [{ id: "suspension-19", packageId: d4, reason: "Sample-clearance review reopened", status: "Active", createdAt: "2026-07-10T12:00:00.000Z", createdBy: "Amelia Grant" }],
  revocations: [{ id: "revocation-11", packageId: d8, reason: "Licence terminated", createdAt: "2026-07-14T00:00:00.000Z", createdBy: "Jordan Lee" }],
  activity: [{ id: "delivery-event-seed-1", actor: "Olivia Bennett", userId: "user-olivia", buyer: "Olivia Bennett", organization: "Northstar Pictures", project: "Horizon Run Trailer", licence: "BM-LIC-2026-0018", delivery: "BM-DEL-2026-0016", asset: "Afterglow Drive — WAV master", timestamp: "2026-07-19T09:10:20.000Z", action: "Download completed", description: "Simulated download completed and one entitlement use was recorded.", before: { downloadCount: 0 }, after: { downloadCount: 1 }, source: "Secure Delivery", visibility: "Organization" }],
  notifications: [], analyticsEvents: [], lastNumbers: { delivery: 20, manifest: 16 }, settings: { countOn: "Completed", tokenMinutes: 5, supportEmail: "delivery@beatmondo.example", reminderHours: [72, 24, 6] },
};
