export const STORAGE_KEY = "beatmondo-file-storage-streaming-v1";
export const SELECTED_ASSET_KEY = "beatmondo-selected-storage-asset";

export const STORAGE_CLASSES = {
  PUBLIC_MEDIA: { visibility: "Public", streamAllowed: false, downloadPolicy: "Public display variants only", retention: "Retain while published; archive after removal", audit: "Standard" },
  PROTECTED_PREVIEW: { visibility: "Protected", streamAllowed: true, downloadPolicy: "No download", retention: "Retain while the preview policy is active", audit: "Every session" },
  PRIVATE_MASTER: { visibility: "Private", streamAllowed: false, downloadPolicy: "Approved delivery only", retention: "Contractual and legal obligations", audit: "Every attempt" },
  PRIVATE_STEMS: { visibility: "Highly Restricted", streamAllowed: false, downloadPolicy: "VIP approved delivery only", retention: "Contractual and legal obligations", audit: "Every attempt" },
  RIGHTS_DOCUMENT: { visibility: "Confidential", streamAllowed: false, downloadPolicy: "Permission controlled", retention: "Long-term legal retention", audit: "Every attempt" },
  COMMERCIAL_DOCUMENT: { visibility: "Organization Restricted", streamAllowed: false, downloadPolicy: "Related organization and staff", retention: "Licence and financial-record policy", audit: "Every attempt" },
  TEMPORARY_PROCESSING: { visibility: "Internal Only", streamAllowed: false, downloadPolicy: "No download", retention: "7–30 day cleanup policy", audit: "Operational" },
  ARCHIVE: { visibility: "Internal Only", streamAllowed: false, downloadPolicy: "Restore before use", retention: "Preserve metadata and audit history", audit: "Every action" },
};

export const FILE_STATUSES = ["Pending Upload", "Uploading", "Uploaded", "Processing", "Ready", "Ready with Warning", "Failed", "Restricted", "Quarantined", "Expired", "Superseded", "Archived", "Deleted"];

const policy = (overrides = {}) => ({ requiresAuthentication: false, allowedRoles: [], requiredPermissions: [], requiredEntitlements: [], requiredVerificationStatus: [], requiredMembershipStatus: [], requiredRightsEligibility: [], requiredProjectId: null, requiredLicenceId: null, requiredDeliveryId: null, streamAllowed: false, downloadAllowed: false, maxDownloads: 0, expiresAt: null, territoryRestrictions: [], organizationRestrictions: [], ...overrides });
const asset = (id, trackId, storageClass, assetType, fileName, sizeBytes, status = "Ready", overrides = {}) => ({ id, ownerType: "Track", ownerId: trackId ? `track-${trackId}` : null, relatedTrackId: trackId, relatedArtistId: overrides.relatedArtistId || null, relatedRightsRecordId: overrides.relatedRightsRecordId || null, relatedContractId: overrides.relatedContractId || null, relatedLicenceId: overrides.relatedLicenceId || null, relatedInvoiceId: overrides.relatedInvoiceId || null, storageClass, assetType, fileName, displayName: overrides.displayName || assetType, fileExtension: fileName.split(".").pop().toLowerCase(), mimeType: overrides.mimeType || "application/octet-stream", sizeBytes, durationSeconds: overrides.durationSeconds || null, checksum: `demo-sha256-${id}`, version: overrides.version || 1, status, visibility: overrides.visibility || STORAGE_CLASSES[storageClass].visibility, confidentiality: overrides.confidentiality || "Standard", storageReference: `storage://${storageClass.toLowerCase().replace(/_/g,"-")}/${id}`, sourceAssetId: overrides.sourceAssetId || null, derivedFromAssetId: overrides.derivedFromAssetId || null, uploadedBy: overrides.uploadedBy || "beatmondo operations", uploadedAt: overrides.uploadedAt || "2026-06-18T10:00:00.000Z", processedAt: overrides.processedAt || "2026-06-18T10:20:00.000Z", expiresAt: overrides.expiresAt || null, archivedAt: null, environment: "Prototype", lastAccessedAt: overrides.lastAccessedAt || null, usageCount: overrides.usageCount || 0, current: overrides.current ?? true, metadata: { trackTitle: overrides.trackTitle || "", artistName: overrides.artistName || "", width: overrides.width || null, height: overrides.height || null, bitrate: overrides.bitrate || null, sampleRate: overrides.sampleRate || null, bitDepth: overrides.bitDepth || null, channels: overrides.channels || null, previewVariant: overrides.previewVariant || null, watermark: overrides.watermark || false, trackPublished: overrides.trackPublished ?? true, integrityStatus: overrides.integrityStatus || "Verified", lastIntegrityCheck: "2026-07-15T10:00:00.000Z", ...overrides.metadata }, accessPolicy: policy(overrides.accessPolicy), processingInfo: { status: status === "Processing" ? "Processing" : status === "Failed" ? "Failed" : "Completed", warnings: overrides.warnings || [], failure: overrides.failure || null }, versions: overrides.versions || [], notes: overrides.notes || [] });

export const DEFAULT_ASSETS = [
  asset("asset-public-1-art",1,"PUBLIC_MEDIA","Artwork","golden-hours-artwork-medium.webp",820000,"Ready",{trackTitle:"Golden Hours",artistName:"Lennox",relatedArtistId:"artist-lennox",width:1600,height:1600,mimeType:"image/webp",usageCount:84}),
  asset("asset-preview-1-standard",1,"PROTECTED_PREVIEW","Preview MP3","golden-hours-preview-v2.mp3",5400000,"Ready",{trackTitle:"Golden Hours",artistName:"Lennox",durationSeconds:94,mimeType:"audio/mpeg",bitrate:"192 kbps",previewVariant:"Professional preview",usageCount:67,accessPolicy:{streamAllowed:true,requiredEntitlements:["catalog.professional"]},versions:[{version:1,fileName:"golden-hours-preview-v1.mp3",status:"Superseded",supersededAt:"2026-06-20T10:00:00.000Z"}]}),
  asset("asset-preview-1-watermarked",1,"PROTECTED_PREVIEW","Watermarked Preview","golden-hours-watermarked-preview.aac",4600000,"Ready",{trackTitle:"Golden Hours",artistName:"Lennox",durationSeconds:94,mimeType:"audio/aac",previewVariant:"VIP preview",watermark:true,usageCount:102,accessPolicy:{requiresAuthentication:true,streamAllowed:true,requiredEntitlements:["catalog.vip"]}}),
  asset("asset-waveform-1",1,"PROTECTED_PREVIEW","Waveform Data","golden-hours-waveform.json",4800,"Ready",{trackTitle:"Golden Hours",artistName:"Lennox",mimeType:"application/json",accessPolicy:{streamAllowed:false}}),
  asset("asset-master-1",1,"PRIVATE_MASTER","WAV Master","golden-hours-master-v1.wav",86400000,"Ready",{trackTitle:"Golden Hours",artistName:"Lennox",mimeType:"audio/wav",sampleRate:"48 kHz",bitDepth:"24-bit",channels:"Stereo",accessPolicy:{requiresAuthentication:true,requiredPermissions:["storage.view_masters"],downloadAllowed:true,requiredRightsEligibility:["Eligible","Eligible with Restrictions"],requiredDeliveryId:"delivery-northstar-1"}}),
  asset("asset-instrumental-1",1,"PRIVATE_MASTER","Instrumental","golden-hours-instrumental.wav",85800000,"Ready",{trackTitle:"Golden Hours",artistName:"Lennox",mimeType:"audio/wav",accessPolicy:{requiresAuthentication:true,requiredPermissions:["storage.view_masters"],downloadAllowed:true,requiredDeliveryId:"delivery-northstar-1"}}),
  asset("asset-instrumental-1-v2",1,"PRIVATE_MASTER","Instrumental","golden-hours-instrumental-v2.wav",85900000,"Ready",{trackTitle:"Golden Hours",artistName:"Lennox",mimeType:"audio/wav",version:2,sourceAssetId:"asset-instrumental-1",accessPolicy:{requiresAuthentication:true,requiredPermissions:["storage.view_masters"],downloadAllowed:true,requiredDeliveryId:"delivery-northstar-1"},notes:["Replacement version with corrected end fade. The previous delivery event remains historical."]}),
  asset("asset-clean-1",1,"PRIVATE_MASTER","Clean Version","golden-hours-clean-v1.wav",86100000,"Ready",{trackTitle:"Golden Hours",artistName:"Lennox",mimeType:"audio/wav",accessPolicy:{requiresAuthentication:true,requiredPermissions:["storage.view_masters"],downloadAllowed:true,requiredDeliveryId:"delivery-northstar-1"}}),
  asset("asset-stems-1",1,"PRIVATE_STEMS","Stem Package","golden-hours-stems-v1.zip",682000000,"Ready",{trackTitle:"Golden Hours",artistName:"Lennox",mimeType:"application/zip",accessPolicy:{requiresAuthentication:true,requiredPermissions:["storage.view_stems"],requiredEntitlements:["delivery.stems"],requiredVerificationStatus:["Approved","Approved with Restrictions"],requiredMembershipStatus:["Active","Complimentary"],requiredLicenceId:"licence-northstar-1",requiredDeliveryId:"delivery-northstar-1",downloadAllowed:true}}),
  asset("asset-lyrics-1",1,"RIGHTS_DOCUMENT","Lyrics","golden-hours-lyrics.pdf",240000,"Ready",{trackTitle:"Golden Hours",artistName:"Lennox",mimeType:"application/pdf",confidentiality:"Internal",accessPolicy:{requiresAuthentication:true,requiredPermissions:["storage.view_documents"],downloadAllowed:true}}),
  asset("asset-rights-1",1,"RIGHTS_DOCUMENT","Split Sheet","golden-hours-split-sheet.pdf",420000,"Ready",{trackTitle:"Golden Hours",artistName:"Lennox",relatedRightsRecordId:"rights-1",mimeType:"application/pdf",confidentiality:"Legal Restricted",accessPolicy:{requiresAuthentication:true,requiredPermissions:["rights.view_legal_notes","storage.view_documents"],downloadAllowed:true}}),
  asset("asset-public-15-art",15,"PUBLIC_MEDIA","Artwork","the-end-of-jason-todd-card.webp",780000,"Ready",{trackTitle:"The End of Jason Todd",artistName:"The SMYRK",relatedArtistId:"artist-smyrk",width:1600,height:1600,mimeType:"image/webp",usageCount:91}),
  asset("asset-preview-15-aac",15,"PROTECTED_PREVIEW","Preview AAC","the-end-of-jason-todd-protected-preview.m4a",3100000,"Ready",{trackTitle:"The End of Jason Todd",artistName:"The SMYRK",relatedArtistId:"artist-smyrk",durationSeconds:84,mimeType:"audio/mp4",previewVariant:"Protected excerpt",watermark:true,usageCount:128,metadata:{protectedEditorialPreview:true},accessPolicy:{streamAllowed:true}}),
  asset("asset-master-15",15,"PRIVATE_MASTER","WAV Master","the-end-of-jason-todd-protected-source.wav",102000000,"Restricted",{trackTitle:"The End of Jason Todd",artistName:"The SMYRK",relatedArtistId:"artist-smyrk",relatedRightsRecordId:"rights-15",mimeType:"audio/wav",sampleRate:"44.1 kHz",bitDepth:"24-bit",channels:"Stereo",accessPolicy:{requiresAuthentication:true,requiredPermissions:["storage.view_masters"],requiredRightsEligibility:["Eligible"],downloadAllowed:false},notes:["Original protected source master remains locked while rights documentation is incomplete."]}),
  asset("asset-rights-15-draft",15,"RIGHTS_DOCUMENT","Rights Agreement","the-end-of-jason-todd-rights-evidence-pending.pdf",380000,"Restricted",{trackTitle:"The End of Jason Todd",artistName:"The SMYRK",relatedArtistId:"artist-smyrk",relatedRightsRecordId:"rights-15",mimeType:"application/pdf",confidentiality:"Legal Restricted",accessPolicy:{requiresAuthentication:true,requiredPermissions:["rights.view_legal_notes","storage.view_documents"],downloadAllowed:false}}),
  asset("asset-temp-16-master",16,"TEMPORARY_PROCESSING","WAV Master","northern-lines-upload-source.wav",92000000,"Processing",{trackTitle:"Northern Lines",artistName:"Arco North",relatedArtistId:"artist-arco",mimeType:"audio/wav",trackPublished:false,expiresAt:"2026-07-23T10:00:00.000Z",accessPolicy:{requiresAuthentication:true,requiredPermissions:["storage.manage_processing"]}}),
  asset("asset-temp-16-preview",16,"TEMPORARY_PROCESSING","Preview MP3","northern-lines-preview-output.mp3",5200000,"Processing",{trackTitle:"Northern Lines",artistName:"Arco North",relatedArtistId:"artist-arco",mimeType:"audio/mpeg",trackPublished:false,expiresAt:"2026-07-23T10:00:00.000Z",derivedFromAssetId:"asset-temp-16-master",accessPolicy:{requiresAuthentication:true,requiredPermissions:["storage.manage_processing"]}}),
  asset("asset-public-16-art",16,"TEMPORARY_PROCESSING","Artwork","northern-lines-artwork-source.jpg",1900000,"Uploaded",{trackTitle:"Northern Lines",artistName:"Arco North",relatedArtistId:"artist-arco",mimeType:"image/jpeg",trackPublished:false,expiresAt:"2026-07-30T10:00:00.000Z",width:2000,height:2000,accessPolicy:{requiresAuthentication:true,requiredPermissions:["storage.manage_processing"]}}),
  asset("asset-failed-20",20,"TEMPORARY_PROCESSING","WAV Master","long-arrival-corrupted.wav",400000,"Quarantined",{trackTitle:"The Long Arrival",artistName:"Vespera",relatedArtistId:"artist-vespera",mimeType:"audio/wav",trackPublished:false,expiresAt:"2026-08-15T10:00:00.000Z",failure:"Invalid or unreadable audio header",integrityStatus:"Mismatch",accessPolicy:{requiresAuthentication:true,requiredPermissions:["storage.manage_processing"]},notes:["Quarantine simulation only; no malware scan was performed."]}),
  asset("asset-replacement-20",20,"TEMPORARY_PROCESSING","WAV Master","long-arrival-replacement-draft.wav",88000000,"Uploaded",{trackTitle:"The Long Arrival",artistName:"Vespera",relatedArtistId:"artist-vespera",mimeType:"audio/wav",trackPublished:false,sourceAssetId:"asset-failed-20",version:2,expiresAt:"2026-07-30T10:00:00.000Z",accessPolicy:{requiresAuthentication:true,requiredPermissions:["storage.manage_processing"]}}),
  asset("asset-art-20",20,"TEMPORARY_PROCESSING","Artwork","long-arrival-artwork.jpg",1800000,"Ready with Warning",{trackTitle:"The Long Arrival",artistName:"Vespera",relatedArtistId:"artist-vespera",mimeType:"image/jpeg",trackPublished:false,width:2200,height:2200,expiresAt:"2026-07-30T10:00:00.000Z",warnings:["Pending publication approval"],accessPolicy:{requiresAuthentication:true,requiredPermissions:["storage.manage_processing"]}}),
  asset("asset-dispute-20",20,"RIGHTS_DOCUMENT","Other","long-arrival-dispute-evidence.pdf",720000,"Restricted",{trackTitle:"The Long Arrival",artistName:"Vespera",relatedRightsRecordId:"rights-8",mimeType:"application/pdf",trackPublished:false,confidentiality:"Legal Restricted",accessPolicy:{requiresAuthentication:true,requiredPermissions:["rights.view_legal_notes","storage.view_documents"],downloadAllowed:false}}),
  asset("asset-contract-1",1,"COMMERCIAL_DOCUMENT","Signed Contract","northstar-golden-hours-signed-contract.pdf",680000,"Ready",{trackTitle:"Golden Hours",artistName:"Lennox",relatedContractId:"contract-northstar-1",relatedLicenceId:"licence-northstar-1",mimeType:"application/pdf",accessPolicy:{requiresAuthentication:true,organizationRestrictions:["org-northstar"],downloadAllowed:true}}),
  asset("asset-licence-1",1,"COMMERCIAL_DOCUMENT","Licence PDF","northstar-golden-hours-licence.pdf",540000,"Ready",{trackTitle:"Golden Hours",artistName:"Lennox",relatedLicenceId:"licence-northstar-1",mimeType:"application/pdf",accessPolicy:{requiresAuthentication:true,organizationRestrictions:["org-northstar"],downloadAllowed:true}}),
  asset("asset-invoice-1",1,"COMMERCIAL_DOCUMENT","Invoice PDF","BM-INV-2026-1042.pdf",320000,"Ready",{trackTitle:"Golden Hours",artistName:"Lennox",relatedInvoiceId:"invoice-1042",mimeType:"application/pdf",accessPolicy:{requiresAuthentication:true,organizationRestrictions:["org-northstar"],downloadAllowed:true}}),
  asset("asset-delivery-1",1,"COMMERCIAL_DOCUMENT","Delivery Manifest","northstar-golden-hours-delivery-manifest.pdf",260000,"Ready",{trackTitle:"Golden Hours",artistName:"Lennox",relatedLicenceId:"licence-northstar-1",mimeType:"application/pdf",accessPolicy:{requiresAuthentication:true,organizationRestrictions:["org-northstar"],downloadAllowed:true}}),
  asset("asset-cue-sheet-1",1,"COMMERCIAL_DOCUMENT","Cue-sheet Information","northstar-golden-hours-cue-sheet.pdf",180000,"Ready",{trackTitle:"Golden Hours",artistName:"Lennox",relatedLicenceId:"licence-northstar-1",mimeType:"application/pdf",accessPolicy:{requiresAuthentication:true,organizationRestrictions:["org-northstar"],downloadAllowed:true}}),
  asset("asset-archived-preview",8,"ARCHIVE","Preview MP3","harbor-light-preview-v1.mp3",4900000,"Archived",{trackTitle:"Harbor Light",artistName:"Emilia Shore",mimeType:"audio/mpeg",current:false,archivedAt:"2026-07-01T10:00:00.000Z",accessPolicy:{requiresAuthentication:true,requiredPermissions:["storage.restore_assets"]}}),
];

export const DEFAULT_STORAGE_STATE = { version:1, assets:DEFAULT_ASSETS, sessions:[], signedAccess:[], accessLogs:[], playbackHistory:{}, activity:[], notifications:[], health:{ publicMedia:"Operational", previewStreaming:"Operational", privateAssets:"Operational", processingStorage:"Operational", documentStorage:"Operational" }, retentionPolicies:Object.fromEntries(Object.entries(STORAGE_CLASSES).map(([key,value])=>[key,value.retention])), cms:{ previewUnavailable:"This protected preview is temporarily unavailable.", streamingAccess:"Preview playback uses a short-lived simulated session. No master file is delivered.", securityExplanation:"This prototype represents access controls but does not provide real cloud security.", artistGuidance:"Only your own submitted assets and review states are visible.", acceptedFormats:"WAV/AIFF masters, MP3/AAC/M4A previews, ZIP stems, JPG/PNG/WEBP artwork, and approved documents.", replacementInstructions:"A replacement creates a new version; the current asset remains active until approval.", expiryMessage:"This access has expired. Start a new approved session or request access.", support:"support@beatmondo.example" } };
