import { buyerVerificationService } from "../verification/buyerVerificationService.js";
import { calculateEffectiveAccess, membershipService } from "../membership/membershipService.js";
import { rightsService } from "../rights/rightsService.js";
import { DEFAULT_STORAGE_STATE, FILE_STATUSES, STORAGE_CLASSES, STORAGE_KEY } from "./storageData.js";
import { watermarkedPreviewService } from "../previews/watermarkedPreviewService.js";

const clone=(value)=>JSON.parse(JSON.stringify(value));
const now=()=>new Date().toISOString();
const uid=(prefix)=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;
const has=(user,permission)=>Boolean(user?.permissions?.includes("*")||user?.permissions?.includes(permission));
const internal=(user)=>user?.userType==="internal"||user?.permissions?.includes("*");

export function formatFileSize(bytes=0){if(bytes<1024)return `${bytes} B`;const units=["KB","MB","GB","TB"];let value=bytes/1024,index=0;while(value>=1024&&index<units.length-1){value/=1024;index+=1;}return `${value>=10?value.toFixed(1):value.toFixed(2)} ${units[index]}`;}

export function readStorageState(){try{const parsed=JSON.parse(window.localStorage.getItem(STORAGE_KEY));if(parsed?.version&&Array.isArray(parsed.assets)&&Array.isArray(parsed.sessions))return parsed;}catch{}const seeded=clone(DEFAULT_STORAGE_STATE);try{window.localStorage.setItem(STORAGE_KEY,JSON.stringify(seeded));}catch{}return seeded;}
function writeState(state){try{window.localStorage.setItem(STORAGE_KEY,JSON.stringify(state));return true;}catch{return false;}}
function update(mutator){const state=readStorageState();const result=mutator(state);if(!writeState(state))return{ok:false,message:"The storage change could not be persisted."};return result;}
function log(state,asset,context,action,result,reason,request={}){const entry={id:uid("access"),assetId:asset?.id||null,asset:asset?.displayName||"Unknown asset",trackId:asset?.relatedTrackId||null,track:asset?.metadata?.trackTitle||"",userId:context.user?.id||null,user:context.user?.name||"Anonymous visitor",organizationId:context.user?.organizationId||null,organization:context.user?.organization||"Public",action,result,reason,timestamp:now(),device:"Codex Browser · Desktop",approximateLocation:"India · 203.0.113.42",ipPlaceholder:"203.0.113.42",accessTier:context.accessTier,projectId:request.projectId||null,licenceId:request.licenceId||null};state.accessLogs.unshift(entry);state.accessLogs=state.accessLogs.slice(0,300);return entry;}
function activity(state,asset,actor,action,description){const event={id:uid("activity"),assetId:asset?.id||null,asset:asset?.displayName||"",trackId:asset?.relatedTrackId||null,actor:actor?.name||"System",actorId:actor?.id||null,action,description,timestamp:now(),source:"File Storage and Streaming",visibility:"Internal"};state.activity.unshift(event);return event;}

export function buildAssetContext(user){const verification=user?.userType==="buyer"?buyerVerificationService.getByUser(user.id):null;const membership=user?.userType==="buyer"?membershipService.getCurrentMembership(user.id):null;const access=internal(user)?{has:()=>true,effectivePlan:"Internal",reasons:[]}:calculateEffectiveAccess(user,verification,membership);const accessTier=internal(user)?"Internal":access.effectivePlan?.includes("VIP")?"VIP":access.effectivePlan?.includes("Professional")?"Professional":user?"Discovery":"Public";return{user,verification,membership,access,accessTier,internal:internal(user)};}

export function canAccessAsset(asset,userContext,requestContext={action:"View metadata"}){
  if(!asset)return{allowed:false,action:requestContext.action,reason:"Asset not found.",code:"ASSET_FAILED",restrictions:[],requiresAdditionalApproval:false};
  const action=requestContext.action||"View metadata";const policy=asset.accessPolicy||{};const deny=(code,reason,additional=false)=>({allowed:false,action,reason,code,restrictions:[],requiresAdditionalApproval:additional});
  if(["Failed","Quarantined","Deleted"].includes(asset.status))return deny("ASSET_FAILED",asset.status==="Quarantined"?"This file is isolated for authorized operational review.":"This asset is unavailable because processing failed.");
  if(asset.status==="Expired")return deny("ASSET_EXPIRED","This asset has expired.");
  if(["Archived","Superseded"].includes(asset.status)&&!userContext.internal)return deny("PERMISSION_DENIED","This asset version is not active.");
  if(["Processing","Uploading","Pending Upload","Uploaded"].includes(asset.status)&&["Stream","Download"].includes(action))return deny("ASSET_PROCESSING","This asset is still being prepared.");
  if(policy.requiresAuthentication&&!userContext.user)return deny("AUTHENTICATION_REQUIRED","Sign in to access this protected asset.");
  if(!userContext.user?.emailVerified&&userContext.user)return deny("EMAIL_VERIFICATION_REQUIRED","Verify your email before accessing protected media.");
  if(asset.storageClass==="PUBLIC_MEDIA")return{allowed:true,action,reason:"Approved public display asset.",code:"ALLOWED",restrictions:[],requiresAdditionalApproval:false};
  if(userContext.user?.userType==="artist"&&asset.relatedArtistId&&asset.relatedArtistId===`artist-${userContext.user.organization?.toLowerCase().replace(/[^a-z0-9]+/g,"-")}`){if(["RIGHTS_DOCUMENT","COMMERCIAL_DOCUMENT"].includes(asset.storageClass))return deny("PERMISSION_DENIED","This restricted document is not available in the artist file view.");return{allowed:true,action,reason:"Own submitted asset metadata.",code:"ALLOWED",restrictions:["Storage reference hidden"],requiresAdditionalApproval:false};}
  if(userContext.user?.role==="artist"&&asset.metadata?.artistName===userContext.user.organization&&!['RIGHTS_DOCUMENT','COMMERCIAL_DOCUMENT'].includes(asset.storageClass))return{allowed:true,action,reason:"Own submitted asset.",code:"ALLOWED",restrictions:["Storage reference hidden"],requiresAdditionalApproval:false};
  if(policy.requiredPermissions?.length&&!policy.requiredPermissions.some((permission)=>has(userContext.user,permission)))return deny("PERMISSION_DENIED","You do not have permission for this asset action.");
  if(policy.organizationRestrictions?.length&&!userContext.internal&&!policy.organizationRestrictions.includes(userContext.user?.organizationId))return deny("PERMISSION_DENIED","This commercial document belongs to another organization.");
  if(asset.storageClass==="PROTECTED_PREVIEW"){
    if(!asset.metadata?.trackPublished)return deny("TRACK_UNPUBLISHED","This track is not published for preview access.");
    const rights=rightsService.getBuyerSummary(asset.relatedTrackId);
    if(["Disputed","Restricted"].includes(rightsService.getByTrack(asset.relatedTrackId)?.status))return deny("RIGHTS_RESTRICTED","Preview access is unavailable while rights are under restricted review.",true);
    if(policy.requiredEntitlements?.length&&!policy.requiredEntitlements.every((entitlement)=>userContext.access.has(entitlement)))return deny(policy.requiredEntitlements.includes("catalog.vip")?"VIP_ACCESS_REQUIRED":"MEMBERSHIP_REQUIRED","Your current verified membership does not include this preview variant.",true);
    if(!policy.streamAllowed&&action==="Stream")return deny("PERMISSION_DENIED","This asset is not streamable.");
    if(action==="Download")return deny("PERMISSION_DENIED","Protected previews are streamed, not downloaded.");
    return{allowed:true,action,reason:"Protected preview session permitted.",code:"ALLOWED",restrictions:[asset.metadata.watermark?"Watermarked preview":"Preview only"],requiresAdditionalApproval:false};
  }
  if(asset.storageClass==="PRIVATE_STEMS"){
    if(!userContext.internal){if(!userContext.user)return deny("AUTHENTICATION_REQUIRED","Sign in to request stem access.");if(!["Approved","Approved with Restrictions","Reinstated"].includes(userContext.verification?.status))return deny("BUYER_VERIFICATION_REQUIRED","Approved buyer verification is required for stems.",true);if(!userContext.access.has("delivery.stems"))return deny("VIP_ACCESS_REQUIRED","Stem access is available only through an approved licensing and delivery workflow.",true);if(!requestContext.projectId)return deny("PROJECT_APPROVAL_REQUIRED","An approved project is required for stem access.",true);if(!requestContext.licenceId)return deny("LICENCE_REQUIRED","A signed licence is required for stem access.",true);if(!requestContext.deliveryId)return deny("DELIVERY_REQUIRED","An active secure-delivery package is required for stem access.",true);}
  }
  if(asset.storageClass==="PRIVATE_MASTER"&&!userContext.internal){if(!requestContext.deliveryId)return deny("DELIVERY_REQUIRED","The protected master is available only through an approved delivery workflow.",true);const rights=rightsService.getBuyerSummary(asset.relatedTrackId);if(!rights?.licensable)return deny("RIGHTS_RESTRICTED","Rights approval is required before master delivery.",true);}
  if(asset.storageClass==="RIGHTS_DOCUMENT"&&!has(userContext.user,"storage.view_documents"))return deny("PERMISSION_DENIED","Rights evidence is restricted to authorized review roles.");
  if(action==="Stream"&&!STORAGE_CLASSES[asset.storageClass]?.streamAllowed)return deny("PERMISSION_DENIED","Private masters, stems, and documents cannot play through the preview player.");
  if(action==="Download"&&!policy.downloadAllowed)return deny("PERMISSION_DENIED","Download authorization is not available for this asset.",true);
  return{allowed:true,action,reason:"Authorized asset operation.",code:"ALLOWED",restrictions:[],requiresAdditionalApproval:false};
}

function syncIngestionAssets(state){try{const ingestion=JSON.parse(window.localStorage.getItem("beatmondo-track-ingestion-v1"));for(const record of [...(ingestion?.records||[]),...(ingestion?.drafts||[])])for(const item of record.assets||[]){const id=`storage-ingestion-${item.id}`;if(state.assets.some((asset)=>asset.id===id))continue;const storageClass=item.processingStatus==="Completed"&&item.qualityStatus==="Approved"?(item.assetType.includes("Artwork")?"PUBLIC_MEDIA":item.assetType.includes("Master")?"PRIVATE_MASTER":"TEMPORARY_PROCESSING"):"TEMPORARY_PROCESSING";state.assets.push({id,ownerType:"Ingestion",ownerId:record.id,relatedTrackId:record.trackId,relatedArtistId:record.artistId,relatedRightsRecordId:record.rightsReadiness?.rightsRecordId||null,storageClass,assetType:item.assetType,fileName:item.fileName,displayName:item.assetType,fileExtension:item.fileType?.toLowerCase()||item.fileName.split('.').pop(),mimeType:item.assetType.includes("Artwork")?"image/webp":item.assetType.includes("Master")?"audio/wav":"application/octet-stream",sizeBytes:Math.round((item.sizeMb||parseFloat(item.fileSize)||1)*1024*1024),durationSeconds:null,checksum:item.checksum||`demo-${item.id}`,version:item.version||1,status:item.processingStatus==="Failed"?"Failed":item.qualityStatus==="Warning"?"Ready with Warning":item.processingStatus==="Completed"?"Ready":"Processing",visibility:STORAGE_CLASSES[storageClass].visibility,confidentiality:"Internal",storageReference:`storage://${storageClass.toLowerCase().replace(/_/g,'-')}/${id}`,sourceAssetId:null,derivedFromAssetId:null,uploadedBy:item.uploadedBy,uploadedAt:item.uploadedAt,processedAt:null,expiresAt:storageClass==="TEMPORARY_PROCESSING"?new Date(Date.now()+7*86400000).toISOString():null,archivedAt:null,environment:"Prototype",lastAccessedAt:null,usageCount:0,current:item.current!==false,metadata:{trackTitle:record.trackTitle,artistName:record.artistName,trackPublished:record.status==="Published",integrityStatus:"Not Checked"},accessPolicy:{requiresAuthentication:true,requiredPermissions:["storage.manage_processing"],requiredEntitlements:[],streamAllowed:false,downloadAllowed:false,organizationRestrictions:[]},processingInfo:{status:item.processingStatus,warnings:item.warnings||[],failure:null},versions:[],notes:[]});}}
  catch{}
}

export function calculateStorageUsage(assets){return assets.filter((asset)=>asset.status!=="Deleted").reduce((sum,asset)=>sum+(asset.sizeBytes||0),0);}
export function calculateStorageByClass(assets){return Object.fromEntries(Object.keys(STORAGE_CLASSES).map((key)=>[key,assets.filter((asset)=>asset.storageClass===key&&asset.status!=="Deleted").reduce((sum,asset)=>sum+(asset.sizeBytes||0),0)]));}

export const storageService={
  getState:readStorageState,
  getAssets(filters={},user){const state=readStorageState();syncIngestionAssets(state);writeState(state);let assets=state.assets;const context=buildAssetContext(user);if(context.internal){assets=assets.filter((asset)=>asset.storageClass!=="RIGHTS_DOCUMENT"||has(user,"storage.view_documents")).filter((asset)=>asset.storageClass!=="PRIVATE_MASTER"||has(user,"storage.view_masters")).filter((asset)=>asset.storageClass!=="PRIVATE_STEMS"||has(user,"storage.view_stems")).filter((asset)=>asset.storageClass!=="TEMPORARY_PROCESSING"||has(user,"storage.manage_processing"));}else if(user?.role==="artist")assets=assets.filter((asset)=>asset.metadata?.artistName===user.organization&&!['RIGHTS_DOCUMENT','COMMERCIAL_DOCUMENT'].includes(asset.storageClass));else assets=assets.filter((asset)=>asset.storageClass==="PUBLIC_MEDIA"||asset.storageClass==="PROTECTED_PREVIEW"||asset.storageClass==="COMMERCIAL_DOCUMENT"&&asset.accessPolicy.organizationRestrictions?.includes(user?.organizationId));const query=String(filters.query||"").toLowerCase();if(query)assets=assets.filter((asset)=>`${asset.fileName} ${asset.displayName} ${asset.id} ${asset.metadata?.trackTitle||""} ${asset.metadata?.artistName||""} ${asset.relatedInvoiceId||""}`.toLowerCase().includes(query));for(const key of ["storageClass","assetType","status","visibility","confidentiality","fileExtension"]){if(filters[key]&&!String(filters[key]).startsWith("All"))assets=assets.filter((asset)=>asset[key]===filters[key]);}if(filters.expiring)assets=assets.filter((asset)=>asset.expiresAt);if(filters.archived)assets=assets.filter((asset)=>asset.status==="Archived");if(filters.superseded)assets=assets.filter((asset)=>asset.status==="Superseded");return clone(assets);},
  getAsset(id,user){const asset=readStorageState().assets.find((item)=>item.id===id);if(!asset)return null;const context=buildAssetContext(user);if(!context.internal&&user?.role==="artist"&&asset.metadata?.artistName!==user.organization)return null;if(!context.internal&&['PRIVATE_MASTER','PRIVATE_STEMS','RIGHTS_DOCUMENT','TEMPORARY_PROCESSING','ARCHIVE'].includes(asset.storageClass))return null;return clone(asset);},
  getInternalAsset(id){return clone(readStorageState().assets.find((item)=>item.id===id)||null);},
  getPlayablePreviewAsset(trackId,user){const state=readStorageState();const context=buildAssetContext(user);const protectedSelection=watermarkedPreviewService.getPlayablePreviewAsset(trackId,user);if(protectedSelection.asset)return{asset:clone(protectedSelection.asset),decision:{allowed:true,code:"ALLOWED",reason:protectedSelection.decision.message,restrictions:protectedSelection.decision.restrictions||["Protected preview only"]},watermarkedPreview:protectedSelection.preview};if(protectedSelection.hasRecords)return{asset:null,decision:{allowed:false,code:protectedSelection.decision.reasonCode,reason:protectedSelection.decision.message}};const priority={"Buyer-Specific Preview":5,"Watermarked Preview":4,"Preview AAC":3,"Preview MP3":2,"Public Excerpt":1};const candidates=state.assets.filter((asset)=>String(asset.relatedTrackId)===String(trackId)&&asset.storageClass==="PROTECTED_PREVIEW"&&asset.status==="Ready").sort((a,b)=>(priority[b.assetType]||0)-(priority[a.assetType]||0));let ingestionRecord=null;try{const ingestion=JSON.parse(window.localStorage.getItem("beatmondo-track-ingestion-v1"));ingestionRecord=ingestion?.records?.find((item)=>String(item.trackId)===String(trackId));}catch{}if(ingestionRecord&&ingestionRecord.status!=="Published"&&!candidates.some((asset)=>asset.metadata?.protectedEditorialPreview))return{asset:null,decision:{allowed:false,code:"TRACK_UNPUBLISHED",reason:"This track is not published for preview access."}};for(const asset of candidates){const decision=canAccessAsset(asset,context,{action:"Stream"});if(decision.allowed)return{asset:clone(asset),decision};}if(candidates.length)return{asset:null,decision:canAccessAsset(candidates[0],context,{action:"Stream"})};const rights=rightsService.getByTrack(trackId);if(["Disputed","Restricted"].includes(rights?.status))return{asset:null,decision:{allowed:false,code:"RIGHTS_RESTRICTED",reason:"Preview access is unavailable while rights are under restricted review."}};const virtual={id:`asset-preview-simulated-${trackId}`,relatedTrackId:trackId,storageClass:"PROTECTED_PREVIEW",assetType:"Simulated Preview",displayName:"Protected preview",fileName:"simulated-preview",status:"Ready",metadata:{trackTitle:`Track ${trackId}`,artistName:"beatmondo catalog",trackPublished:true,watermark:false},accessPolicy:{streamAllowed:true,requiresAuthentication:false,requiredEntitlements:[]},durationSeconds:84,usageCount:0,sizeBytes:0,visibility:"Protected"};return{asset:virtual,decision:{allowed:true,code:"ALLOWED",reason:"Safe simulated preview session.",restrictions:["Preview only"]}};},
  createStreamingSession(trackId,user,sourcePage="Track Detail"){return update((state)=>{if(state.health.previewStreaming!=="Operational")return{ok:false,message:state.health.previewStreaming==="Degraded"?"Preview streaming is degraded. Please retry.":"Preview streaming is temporarily unavailable.",code:"SERVICE_UNAVAILABLE"};const playable=this.getPlayablePreviewAsset(trackId,user);const context=buildAssetContext(user);if(!playable.asset){const synthetic={id:null,relatedTrackId:trackId,displayName:"Protected preview"};log(state,synthetic,context,"Stream","Denied",playable.decision.reason,{sourcePage});return{ok:false,message:playable.decision.reason,code:playable.decision.code};}if(!state.assets.some((item)=>item.id===playable.asset.id))state.assets.push({...clone(playable.asset),fileExtension:"simulated",mimeType:"audio/simulated",checksum:`demo-${playable.asset.id}`,version:1,current:true,confidentiality:"Standard",storageReference:`storage://protected-preview/${playable.asset.id}`,uploadedBy:"System",uploadedAt:now(),processedAt:now(),expiresAt:null,archivedAt:null,environment:"Prototype",lastAccessedAt:null,sourceAssetId:null,derivedFromAssetId:null,ownerType:"Track",ownerId:`track-${trackId}`,processingInfo:{status:"Completed",warnings:["Simulated playback state"],failure:null},versions:[],notes:[]});const issuedAt=now();const session={id:uid("stream"),userId:user?.id||null,anonymousSessionId:user?null:uid("anonymous"),assetId:playable.asset.id,trackId,token:`bm_preview_${Math.random().toString(36).slice(2,10)}`,status:"Active",startedAt:issuedAt,lastActiveAt:issuedAt,expiresAt:new Date(Date.now()+30*60*1000).toISOString(),secondsStreamed:0,lastPosition:0,accessTier:context.accessTier,organizationId:user?.organizationId||null,device:"Codex Browser",approximateLocation:"India",sourcePage};state.sessions.unshift(session);playable.asset.lastAccessedAt=issuedAt;const stored=state.assets.find((item)=>item.id===playable.asset.id);if(stored){stored.lastAccessedAt=issuedAt;stored.usageCount=(stored.usageCount||0)+1;}log(state,playable.asset,context,"Stream","Allowed","Preview session created.",{sourcePage});activity(state,playable.asset,user,"Preview streamed","Short-lived preview session created.");return{ok:true,session:clone(session),asset:{id:playable.asset.id,assetType:playable.asset.assetType,durationSeconds:playable.asset.durationSeconds,watermark:playable.asset.metadata.watermark,watermarkedPreviewId:playable.asset.metadata.watermarkedPreviewId,watermarkType:playable.asset.metadata.watermarkType,watermarkPhrase:playable.asset.metadata.watermarkPhrase,watermarkPositions:playable.asset.metadata.watermarkPositions,forensicReference:playable.asset.metadata.forensicReference,policyName:playable.asset.metadata.policyName,organizationSpecific:playable.asset.metadata.organizationSpecific},message:"Protected preview session created."};});},
  updateSession(sessionId,changes,user){return update((state)=>{const session=state.sessions.find((item)=>item.id===sessionId);if(!session)return{ok:false,message:"Preview session not found."};if(session.userId&&session.userId!==user?.id&&!internal(user))return{ok:false,message:"Preview session access denied."};if(new Date(session.expiresAt)<=new Date()||session.status==="Expired")return{ok:false,message:"Preview session expired.",code:"SESSION_EXPIRED"};if(session.status==="Revoked")return{ok:false,message:"Preview access was revoked.",code:"PERMISSION_DENIED"};Object.assign(session,clone(changes),{lastActiveAt:now()});const key=user?.id||session.anonymousSessionId;const asset=state.assets.find((item)=>item.id===session.assetId);state.playbackHistory[key]=[{id:`history-${session.id}`,sessionId:session.id,trackId:session.trackId,assetId:session.assetId,track:asset?.metadata.trackTitle,artist:asset?.metadata.artistName,date:session.startedAt,lastPlayedPosition:session.lastPosition||0,sourcePage:session.sourcePage,status:session.status},...(state.playbackHistory[key]||[]).filter((item)=>item.sessionId!==session.id)].slice(0,30);return{ok:true,session:clone(session)};});},
  refreshStreamingSession(sessionId,user){const old=readStorageState().sessions.find((item)=>item.id===sessionId);return old?this.createStreamingSession(old.trackId,user,old.sourcePage):{ok:false,message:"Preview session not found."};},
  expireStreamingSession(sessionId,user){return update((state)=>{const session=state.sessions.find((item)=>item.id===sessionId);if(!session)return{ok:false,message:"Session not found."};if(!internal(user)&&session.userId!==user?.id)return{ok:false,message:"Session access denied."};session.status="Expired";session.expiresAt=now();const asset=state.assets.find((item)=>item.id===session.assetId);log(state,asset,buildAssetContext(user),"Session expiry","Expired","Demo expiry simulated.");window.dispatchEvent(new CustomEvent("beatmondo-preview-session-invalidated",{detail:{sessionId,reason:"Preview session expired."}}));return{ok:true};});},
  revokeStreamingSession(sessionId,user,reason){if(!has(user,"storage.revoke_sessions"))return{ok:false,message:"Session-revocation permission is required."};if(!reason?.trim())return{ok:false,message:"A revocation reason is required."};return update((state)=>{const session=state.sessions.find((item)=>item.id===sessionId);if(!session)return{ok:false,message:"Session not found."};session.status="Revoked";session.revokedAt=now();session.revokedBy=user.name;session.revocationReason=reason;const asset=state.assets.find((item)=>item.id===session.assetId);log(state,asset,buildAssetContext(user),"Session revoked","Revoked",reason);activity(state,asset,user,"Session revoked",reason);window.dispatchEvent(new CustomEvent("beatmondo-preview-session-invalidated",{detail:{sessionId,reason:"Preview access was revoked."}}));return{ok:true};});},
  revokeAssetSessions(assetId,user,reason){if(!has(user,"storage.revoke_sessions"))return{ok:false,message:"Session-revocation permission is required."};return update((state)=>{let count=0;state.sessions.filter((item)=>item.assetId===assetId&&["Active","Paused","Created"].includes(item.status)).forEach((session)=>{session.status="Revoked";session.revokedAt=now();session.revocationReason=reason;count++;});const asset=state.assets.find((item)=>item.id===assetId);activity(state,asset,user,"Asset sessions revoked",`${count} sessions revoked: ${reason}`);return{ok:true,count};});},
  generateMockSignedAccess(assetId,user,options={action:"Download",maxUses:1}){const asset=readStorageState().assets.find((item)=>item.id===assetId);const context=buildAssetContext(user);const decision=canAccessAsset(asset,context,{...options,action:options.action});return update((state)=>{log(state,asset,context,options.action,decision.allowed?"Allowed":"Denied",decision.reason,options);if(!decision.allowed)return{ok:false,message:decision.reason,code:decision.code};const record={accessId:uid("signed"),token:`bm_access_${Math.random().toString(36).slice(2,10)}`,assetId,action:options.action,issuedAt:now(),expiresAt:new Date(Date.now()+(options.minutes||15)*60000).toISOString(),maxUses:options.maxUses||1,uses:0,status:"Active"};state.signedAccess.unshift(record);return{ok:true,access:{...record}};});},
  accessAsset(assetId,user,request={action:"View metadata"}){return update((state)=>{const asset=state.assets.find((item)=>item.id===assetId);const context=buildAssetContext(user);const decision=canAccessAsset(asset,context,request);log(state,asset,context,request.action,decision.allowed?"Allowed":"Denied",decision.reason,request);if(decision.allowed&&asset){asset.lastAccessedAt=now();asset.usageCount=(asset.usageCount||0)+1;activity(state,asset,user,`${request.action} accessed`,decision.reason);}return{ok:decision.allowed,decision};});},
  getPlaybackHistory(user){const state=readStorageState();const key=user?.id||Object.keys(state.playbackHistory).find((item)=>item.startsWith("anonymous"))||"anonymous";return clone(state.playbackHistory[key]||[]);},
  removePlaybackHistory(user,id){return update((state)=>{const key=user?.id||"anonymous";state.playbackHistory[key]=(state.playbackHistory[key]||[]).filter((item)=>item.id!==id);return{ok:true};});},
  clearPlaybackHistory(user){return update((state)=>{state.playbackHistory[user?.id||"anonymous"]=[];return{ok:true};});},
  getAccessHistory(filters={},user){if(!has(user,"storage.view_access_logs"))return[];let logs=readStorageState().accessLogs;const query=String(filters.query||"").toLowerCase();if(query)logs=logs.filter((item)=>`${item.asset} ${item.track} ${item.user} ${item.organization} ${item.action}`.toLowerCase().includes(query));if(filters.result&&filters.result!=="All Results")logs=logs.filter((item)=>item.result===filters.result);if(filters.action&&filters.action!=="All Actions")logs=logs.filter((item)=>item.action===filters.action);return clone(logs);},
  replaceAsset(assetId,scenario,user,reason){if(!has(user,"storage.replace_assets"))return{ok:false,message:"Asset-replacement permission is required."};if(!reason?.trim())return{ok:false,message:"A replacement reason is required."};return update((state)=>{const current=state.assets.find((item)=>item.id===assetId);if(!current)return{ok:false,message:"Asset not found."};const replacement={...clone(current),id:uid("asset"),fileName:scenario.fileName||`replacement-${current.fileName}`,version:(current.version||1)+1,status:"Uploaded",current:false,sourceAssetId:current.id,uploadedBy:user.name,uploadedAt:now(),processedAt:null,checksum:uid("checksum"),storageReference:`storage://temporary-processing/${uid("replacement")}`,processingInfo:{status:"Processing",warnings:[],failure:null},replacementReason:reason,versions:[]};state.assets.unshift(replacement);activity(state,replacement,user,"Asset replacement uploaded",`Version ${replacement.version} is processing; version ${current.version} remains current.`);return{ok:true,asset:clone(replacement)};});},
  completeAssetProcessing(assetId,user){if(!has(user,"storage.manage_processing"))return{ok:false,message:"Processing-management permission is required."};return update((state)=>{const asset=state.assets.find((item)=>item.id===assetId);if(!asset)return{ok:false,message:"Asset not found."};if(!asset.sourceAssetId)return{ok:false,message:"Only a replacement version can use this review simulation."};asset.status="Ready";asset.processingInfo={status:"Completed",warnings:asset.processingInfo?.warnings||[],failure:null};asset.processedAt=now();activity(state,asset,user,"Replacement processing completed","Simulated validation completed; version is ready for activation.");return{ok:true};});},
  activateVersion(assetId,user){if(!has(user,"storage.replace_assets"))return{ok:false,message:"Version-management permission is required."};return update((state)=>{const replacement=state.assets.find((item)=>item.id===assetId);if(!replacement||!replacement.sourceAssetId)return{ok:false,message:"Replacement version not found."};if(!["Ready","Ready with Warning"].includes(replacement.status))return{ok:false,message:"Replacement must pass review before activation."};const previous=state.assets.find((item)=>item.id===replacement.sourceAssetId);if(previous){previous.current=false;previous.status="Superseded";previous.supersededAt=now();}replacement.current=true;replacement.status="Ready";replacement.processedAt=now();replacement.storageReference=`storage://${replacement.storageClass.toLowerCase().replace(/_/g,"-")}/${replacement.id}`;activity(state,replacement,user,"Version activated",`Version ${replacement.version} is current; prior version retained as Superseded.`);watermarkedPreviewService.handleSourceAssetReplacement(previous?.id,replacement.id,replacement.version,user);return{ok:true};});},
  archiveAsset(assetId,user,reason){if(!has(user,"storage.archive_assets"))return{ok:false,message:"Archive permission is required."};if(!reason?.trim())return{ok:false,message:"Archive reason is required."};return update((state)=>{const asset=state.assets.find((item)=>item.id===assetId);if(!asset)return{ok:false,message:"Asset not found."};asset.previousStorageClass=asset.storageClass;asset.previousStatus=asset.status;asset.storageClass="ARCHIVE";asset.status="Archived";asset.archivedAt=now();asset.archiveReason=reason;activity(state,asset,user,"Asset archived",reason);return{ok:true};});},
  restoreAsset(assetId,user){if(!has(user,"storage.restore_assets"))return{ok:false,message:"Restore permission is required."};return update((state)=>{const asset=state.assets.find((item)=>item.id===assetId);if(!asset||asset.status!=="Archived")return{ok:false,message:"Archived asset not found."};asset.storageClass=asset.previousStorageClass||"TEMPORARY_PROCESSING";asset.status=asset.previousStatus&&asset.previousStatus!=="Archived"?asset.previousStatus:"Ready";asset.archivedAt=null;activity(state,asset,user,"Asset restored","Archived metadata and version restored.");return{ok:true};});},
  quarantineAsset(assetId,user,reason){if(!has(user,"storage.manage_processing"))return{ok:false,message:"Processing-management permission is required."};return update((state)=>{const asset=state.assets.find((item)=>item.id===assetId);if(!asset)return{ok:false,message:"Asset not found."};asset.status="Quarantined";asset.quarantineReason=reason||"Operational review";activity(state,asset,user,"Asset quarantined",`${asset.quarantineReason}. Simulation only.`);return{ok:true};});},
  releaseAsset(assetId,user){if(!has(user,"storage.manage_processing"))return{ok:false,message:"Processing-management permission is required."};return update((state)=>{const asset=state.assets.find((item)=>item.id===assetId);if(!asset||asset.status!=="Quarantined")return{ok:false,message:"Quarantined asset not found."};asset.status=asset.preQuarantineStatus||"Uploaded";asset.quarantineReleasedAt=now();delete asset.preQuarantineStatus;activity(state,asset,user,"Asset released from quarantine","Restored to its pre-quarantine state; no real malware decision was made.");return{ok:true};});},
  runIntegrityCheck(assetId,user,outcome="verified"){if(!has(user,"storage.manage_processing"))return{ok:false,message:"Integrity-check permission is required."};return update((state)=>{const asset=state.assets.find((item)=>item.id===assetId);if(!asset)return{ok:false,message:"Asset not found."};asset.metadata.integrityStatus=outcome==="mismatch"?"Mismatch":"Verified";asset.metadata.lastIntegrityCheck=now();if(outcome==="mismatch"){asset.preQuarantineStatus=asset.status;asset.status="Quarantined";}activity(state,asset,user,"Integrity check run",`Simulated checksum result: ${asset.metadata.integrityStatus}.`);return{ok:true,status:asset.metadata.integrityStatus};});},
  getCleanupPreview(){const nowDate=new Date();return clone(readStorageState().assets.filter((asset)=>asset.storageClass==="TEMPORARY_PROCESSING"&&asset.expiresAt&&new Date(asset.expiresAt)<=new Date(nowDate.getTime()+14*86400000)));},
  runTemporaryCleanup(user){if(!has(user,"storage.manage_retention"))return{ok:false,message:"Retention-management permission is required."};return update((state)=>{const affected=state.assets.filter((asset)=>asset.storageClass==="TEMPORARY_PROCESSING"&&asset.expiresAt&&new Date(asset.expiresAt)<=new Date(Date.now()+14*86400000));affected.forEach((asset)=>{asset.previousStorageClass=asset.storageClass;asset.previousStatus=asset.status;asset.storageClass="ARCHIVE";asset.status="Archived";asset.archivedAt=now();asset.archiveReason="Temporary cleanup simulation";});state.activity.unshift({id:uid("activity"),action:"Temporary cleanup run",description:`${affected.length} temporary assets archived; no raw files were deleted.`,actor:user.name,timestamp:now(),source:"File Storage and Streaming",visibility:"Internal"});return{ok:true,count:affected.length};});},
  setHealth(service,status,user){if(!has(user,"storage.manage_processing"))return{ok:false,message:"Storage-health permission is required."};return update((state)=>{if(!(service in state.health))return{ok:false,message:"Storage service not found."};state.health[service]=status;state.activity.unshift({id:uid("activity"),action:"Storage health changed",description:`${service}: ${status}`,actor:user.name,timestamp:now(),source:"File Storage and Streaming",visibility:"Internal"});return{ok:true};});},
  calculateStorageUsage(){const assets=readStorageState().assets;return{total:calculateStorageUsage(assets),byClass:calculateStorageByClass(assets)};},
  getAnalytics(){const state=readStorageState();const usage=this.calculateStorageUsage();const sessions=state.sessions;const allowed=state.accessLogs.filter((item)=>item.result==="Allowed").length;const denied=state.accessLogs.filter((item)=>item.result==="Denied").length;return{totalAssets:state.assets.length,totalUsage:usage.total,byClass:usage.byClass,previewSessions:sessions.length,uniqueListeners:new Set(sessions.map((item)=>item.userId||item.anonymousSessionId)).size,averageCompletion:sessions.length?Math.round(sessions.reduce((sum,item)=>sum+Math.min(100,(item.secondsStreamed||0)/Math.max(1,state.assets.find((asset)=>asset.id===item.assetId)?.durationSeconds||84)*100),0)/sessions.length):0,failureRate:sessions.length?Math.round(sessions.filter((item)=>item.status==="Failed").length/sessions.length*100):0,denialRate:allowed+denied?Math.round(denied/(allowed+denied)*100):0,failedAssets:state.assets.filter((item)=>item.status==="Failed").length,expiring:state.assets.filter((item)=>item.expiresAt).length,archived:state.assets.filter((item)=>item.status==="Archived").length,restricted:state.assets.filter((item)=>["Restricted","Quarantined"].includes(item.status)).length,mostStreamed:state.assets.filter((item)=>item.storageClass==="PROTECTED_PREVIEW").sort((a,b)=>(b.usageCount||0)-(a.usageCount||0)).slice(0,5).map((item)=>({id:item.id,track:item.metadata.trackTitle,count:item.usageCount||0}))};},
  resetFileStorageStreamingDemoData(){const state=clone(DEFAULT_STORAGE_STATE);writeState(state);return clone(state);},
};

export const accessPolicyService={canAccessAsset,buildAssetContext};
export const streamingService={getPlayablePreviewAsset:(...args)=>storageService.getPlayablePreviewAsset(...args),createStreamingSession:(...args)=>storageService.createStreamingSession(...args),refreshStreamingSession:(...args)=>storageService.refreshStreamingSession(...args),expireStreamingSession:(...args)=>storageService.expireStreamingSession(...args),revokeStreamingSession:(...args)=>storageService.revokeStreamingSession(...args)};
export const assetVersionService={replaceAsset:(...args)=>storageService.replaceAsset(...args),activateVersion:(...args)=>storageService.activateVersion(...args)};
export const retentionService={runTemporaryCleanup:(...args)=>storageService.runTemporaryCleanup(...args)};
