export const PERMISSIONS_STORAGE_KEY = "beatmondo-admin-permissions-v1";
export const SELECTED_ACCESS_USER_KEY = "beatmondo-selected-access-user";
export const SELECTED_ROLE_KEY = "beatmondo-selected-role";
export const SELECTED_PERMISSION_KEY = "beatmondo-selected-permission";

const permissionSpecs = [
  [
    "access.dashboard.view",
    "Access",
    "Dashboard",
    "View",
    "Navigation",
    "Moderate",
  ],
  ["access.users.view", "Access", "Users", "View", "View", "Moderate"],
  ["access.roles.view", "Access", "Roles", "View", "View", "Moderate"],
  ["access.permissions.view", "Access", "Permissions", "View", "View", "High"],
  ["access.roles.create", "Access", "Roles", "Create", "Create", "High"],
  ["access.roles.edit", "Access", "Roles", "Edit", "Edit", "High"],
  [
    "access.roles.assign",
    "Access",
    "Roles",
    "Assign",
    "Manage Access",
    "Critical",
  ],
  [
    "access.grants.create",
    "Access",
    "Permission Grants",
    "Create",
    "Manage Access",
    "High",
  ],
  [
    "access.denials.create",
    "Access",
    "Permission Denials",
    "Create",
    "Manage Access",
    "Critical",
  ],
  ["access.requests.review", "Access", "Requests", "Review", "Approve", "High"],
  [
    "access.temporary.manage",
    "Access",
    "Temporary Elevations",
    "Manage",
    "Manage Access",
    "High",
  ],
  [
    "access.delegations.manage",
    "Access",
    "Delegations",
    "Manage",
    "Manage Access",
    "High",
  ],
  [
    "access.impersonation.request",
    "Access",
    "Impersonation",
    "Request",
    "Impersonate",
    "Critical",
  ],
  [
    "access.impersonation.approve",
    "Access",
    "Impersonation",
    "Approve",
    "Approve",
    "Critical",
  ],
  [
    "access.impersonation.start",
    "Access",
    "Impersonation",
    "Start",
    "Impersonate",
    "Critical",
  ],
  [
    "access.reviews.manage",
    "Access",
    "Access Reviews",
    "Manage",
    "Manage Access",
    "High",
  ],
  [
    "access.conflicts.manage",
    "Access",
    "Conflicts",
    "Manage",
    "Manage Security",
    "Critical",
  ],
  [
    "access.emergency.activate",
    "Access",
    "Emergency Access",
    "Activate",
    "Override",
    "Critical",
  ],
  ["access.exports.create", "Access", "Exports", "Create", "Export", "High"],
  [
    "auth.sessions.view",
    "Authentication",
    "Sessions",
    "View",
    "View",
    "Moderate",
  ],
  [
    "auth.sessions.revoke",
    "Authentication",
    "Sessions",
    "Revoke",
    "Manage Security",
    "High",
  ],
  ["users.accounts.view", "Users", "Accounts", "View", "View", "Moderate"],
  ["users.accounts.create", "Users", "Accounts", "Create", "Create", "High"],
  ["users.accounts.edit", "Users", "Accounts", "Edit", "Edit", "High"],
  [
    "users.accounts.suspend",
    "Users",
    "Accounts",
    "Suspend",
    "Manage Access",
    "High",
  ],
  [
    "users.accounts.deactivate",
    "Users",
    "Accounts",
    "Deactivate",
    "Delete",
    "Critical",
  ],
  [
    "users.roles.assign",
    "Users",
    "Roles",
    "Assign",
    "Manage Access",
    "Critical",
  ],
  [
    "users.permissions.grant",
    "Users",
    "Permissions",
    "Grant",
    "Manage Access",
    "Critical",
  ],
  [
    "users.permissions.deny",
    "Users",
    "Permissions",
    "Deny",
    "Manage Access",
    "Critical",
  ],
  [
    "users.impersonation.request",
    "Users",
    "Impersonation",
    "Request",
    "Impersonate",
    "Critical",
  ],
  [
    "users.impersonation.approve",
    "Users",
    "Impersonation",
    "Approve",
    "Approve",
    "Critical",
  ],
  [
    "verification.applications.view",
    "Buyer Verification",
    "Applications",
    "View",
    "View",
    "Moderate",
  ],
  [
    "verification.applications.review",
    "Buyer Verification",
    "Applications",
    "Review",
    "Edit",
    "High",
  ],
  [
    "verification.applications.approve",
    "Buyer Verification",
    "Applications",
    "Approve",
    "Approve",
    "High",
  ],
  [
    "verification.applications.reject",
    "Buyer Verification",
    "Applications",
    "Reject",
    "Reject",
    "High",
  ],
  [
    "verification.documents.view",
    "Buyer Verification",
    "Documents",
    "View",
    "View Sensitive Fields",
    "High",
  ],
  [
    "verification.documents.download",
    "Buyer Verification",
    "Documents",
    "Download",
    "Download",
    "Critical",
  ],
  [
    "verification.override",
    "Buyer Verification",
    "Verification",
    "Override",
    "Override",
    "Critical",
  ],
  [
    "memberships.records.view",
    "Membership",
    "Memberships",
    "View",
    "View",
    "Moderate",
  ],
  [
    "memberships.records.manage",
    "Membership",
    "Memberships",
    "Manage",
    "Manage Access",
    "High",
  ],
  [
    "membership_invoices.records.view",
    "Membership",
    "Invoices",
    "View",
    "View",
    "High",
  ],
  [
    "membership_refunds.records.issue",
    "Membership",
    "Refunds",
    "Issue",
    "Approve",
    "Critical",
  ],
  ["rights.records.view", "Rights", "Records", "View", "View", "High"],
  ["rights.records.create", "Rights", "Records", "Create", "Create", "High"],
  ["rights.records.edit", "Rights", "Records", "Edit", "Edit", "High"],
  [
    "rights.records.approve",
    "Rights",
    "Records",
    "Approve",
    "Approve",
    "Critical",
  ],
  [
    "rights.documents.view",
    "Rights",
    "Documents",
    "View",
    "View Sensitive Fields",
    "Critical",
  ],
  [
    "rights.documents.download",
    "Rights",
    "Documents",
    "Download",
    "Download",
    "Critical",
  ],
  [
    "rights.disputes.manage",
    "Rights",
    "Disputes",
    "Manage",
    "Manage Access",
    "Critical",
  ],
  [
    "rights.records.override",
    "Rights",
    "Records",
    "Override",
    "Override",
    "Critical",
  ],
  ["catalog.tracks.view", "Catalog", "Tracks", "View", "View", "Low"],
  ["catalog.tracks.edit", "Catalog", "Tracks", "Edit", "Edit", "Moderate"],
  ["catalog.tracks.publish", "Catalog", "Tracks", "Publish", "Approve", "High"],
  [
    "ingestion.submissions.view",
    "Track Ingestion",
    "Submissions",
    "View",
    "View",
    "Moderate",
  ],
  [
    "ingestion.submissions.review",
    "Track Ingestion",
    "Submissions",
    "Review",
    "Edit",
    "High",
  ],
  [
    "ingestion.assets.replace",
    "Track Ingestion",
    "Assets",
    "Replace",
    "Upload",
    "High",
  ],
  ["storage.assets.view", "Storage", "Assets", "View", "View", "Moderate"],
  [
    "storage.assets.manage",
    "Storage",
    "Assets",
    "Manage",
    "Manage Configuration",
    "High",
  ],
  [
    "storage.masters.view",
    "Storage",
    "Masters",
    "View",
    "View Sensitive Fields",
    "Critical",
  ],
  [
    "storage.stems.view",
    "Storage",
    "Stems",
    "View",
    "View Sensitive Fields",
    "Critical",
  ],
  [
    "previews.records.generate",
    "Preview",
    "Previews",
    "Generate",
    "Create",
    "High",
  ],
  [
    "previews.records.approve",
    "Preview",
    "Previews",
    "Approve",
    "Approve",
    "High",
  ],
  [
    "previews.records.revoke",
    "Preview",
    "Previews",
    "Revoke",
    "Manage Access",
    "Critical",
  ],
  [
    "quotes.calculations.create",
    "Quote",
    "Calculations",
    "Create",
    "Create",
    "Moderate",
  ],
  [
    "quotes.calculations.view_internal",
    "Quote",
    "Calculations",
    "View Internal",
    "View Sensitive Fields",
    "High",
  ],
  [
    "quotes.pricing.override",
    "Quote",
    "Pricing",
    "Override",
    "Override",
    "Critical",
  ],
  [
    "quotes.approvals.approve",
    "Quote",
    "Approvals",
    "Approve",
    "Approve",
    "High",
  ],
  [
    "contracts.records.create",
    "Contract",
    "Contracts",
    "Create",
    "Create",
    "High",
  ],
  ["contracts.records.edit", "Contract", "Contracts", "Edit", "Edit", "High"],
  [
    "contracts.records.approve",
    "Contract",
    "Contracts",
    "Approve",
    "Approve",
    "Critical",
  ],
  [
    "contracts.records.send",
    "Contract",
    "Contracts",
    "Send",
    "Manage Access",
    "High",
  ],
  [
    "signatures.records.countersign",
    "Signature",
    "Signatures",
    "Countersign",
    "Approve",
    "Critical",
  ],
  [
    "payments.transactions.view",
    "Payment",
    "Transactions",
    "View",
    "View Sensitive Fields",
    "High",
  ],
  [
    "payments.transactions.process",
    "Payment",
    "Transactions",
    "Process",
    "Edit",
    "High",
  ],
  [
    "payments.reconciliation.manage",
    "Payment",
    "Reconciliation",
    "Manage",
    "Manage Configuration",
    "Critical",
  ],
  [
    "payments.refunds.request",
    "Payment",
    "Refunds",
    "Request",
    "Create",
    "High",
  ],
  [
    "payments.refunds.approve",
    "Payment",
    "Refunds",
    "Approve",
    "Approve",
    "Critical",
  ],
  [
    "payments.refunds.issue",
    "Payment",
    "Refunds",
    "Issue",
    "Approve",
    "Critical",
  ],
  [
    "payments.credits.manage",
    "Payment",
    "Credits",
    "Manage",
    "Manage Configuration",
    "High",
  ],
  [
    "licences.records.create",
    "Licence",
    "Licences",
    "Create",
    "Create",
    "High",
  ],
  [
    "licences.records.approve",
    "Licence",
    "Licences",
    "Approve",
    "Approve",
    "Critical",
  ],
  [
    "licences.records.issue",
    "Licence",
    "Licences",
    "Issue",
    "Approve",
    "Critical",
  ],
  [
    "licences.records.suspend",
    "Licence",
    "Licences",
    "Suspend",
    "Manage Access",
    "Critical",
  ],
  [
    "licences.records.terminate",
    "Licence",
    "Licences",
    "Terminate",
    "Delete",
    "Critical",
  ],
  [
    "deliveries.packages.create",
    "Delivery",
    "Packages",
    "Create",
    "Create",
    "High",
  ],
  [
    "deliveries.packages.approve",
    "Delivery",
    "Packages",
    "Approve",
    "Approve",
    "Critical",
  ],
  [
    "deliveries.packages.activate",
    "Delivery",
    "Packages",
    "Activate",
    "Manage Access",
    "Critical",
  ],
  [
    "deliveries.packages.revoke",
    "Delivery",
    "Packages",
    "Revoke",
    "Manage Access",
    "Critical",
  ],
  [
    "temporary_access.records.generate",
    "Temporary Access",
    "Access",
    "Generate",
    "Create",
    "High",
  ],
  [
    "temporary_access.records.revoke",
    "Temporary Access",
    "Access",
    "Revoke",
    "Manage Security",
    "Critical",
  ],
  ["audit.events.view", "Audit", "Events", "View", "View", "High"],
  ["audit.events.review", "Audit", "Events", "Review", "Approve", "High"],
  ["audit.exports.create", "Audit", "Exports", "Create", "Export", "Critical"],
  [
    "audit.events.view_security",
    "Audit",
    "Security Events",
    "View",
    "View Sensitive Fields",
    "Critical",
  ],
  [
    "email.queue.manage",
    "Email",
    "Queue",
    "Manage",
    "Manage Configuration",
    "High",
  ],
  [
    "email.templates.manage",
    "Email",
    "Templates",
    "Manage",
    "Manage Configuration",
    "High",
  ],
  [
    "email.triggers.manage",
    "Email",
    "Triggers",
    "Manage",
    "Manage Configuration",
    "High",
  ],
  [
    "analytics.executive.view",
    "Analytics",
    "Executive",
    "View",
    "View",
    "Critical",
  ],
  [
    "analytics.commercial.view",
    "Analytics",
    "Commercial",
    "View",
    "View",
    "High",
  ],
  [
    "analytics.finance.view",
    "Analytics",
    "Finance",
    "View",
    "View Sensitive Fields",
    "Critical",
  ],
  [
    "analytics.catalog.view",
    "Analytics",
    "Catalog",
    "View",
    "View",
    "Moderate",
  ],
  ["analytics.search.view", "Analytics", "Search", "View", "View", "Moderate"],
  [
    "analytics.buyers.view",
    "Analytics",
    "Buyers",
    "View",
    "View Sensitive Fields",
    "High",
  ],
  [
    "analytics.artists.view",
    "Analytics",
    "Artists",
    "View",
    "View",
    "Moderate",
  ],
  [
    "analytics.rights.view",
    "Analytics",
    "Rights",
    "View",
    "View Sensitive Fields",
    "Critical",
  ],
  [
    "analytics.operations.view",
    "Analytics",
    "Operations",
    "View",
    "View",
    "High",
  ],
  [
    "analytics.security.view",
    "Analytics",
    "Security",
    "View",
    "Manage Security",
    "Critical",
  ],
  ["analytics.email.view", "Analytics", "Email", "View", "View", "High"],
  [
    "analytics.permissions.view",
    "Analytics",
    "Permissions",
    "View",
    "Manage Access",
    "Critical",
  ],
  ["reports.view", "Reports", "Library", "View", "View", "Moderate"],
  ["reports.create", "Reports", "Definitions", "Create", "Create", "High"],
  ["reports.edit", "Reports", "Definitions", "Edit", "Edit", "High"],
  ["reports.share", "Reports", "Definitions", "Share", "Manage Access", "High"],
  ["reports.archive", "Reports", "Definitions", "Archive", "Delete", "High"],
  [
    "reports.schedule",
    "Reports",
    "Schedules",
    "Manage",
    "Manage Configuration",
    "High",
  ],
  ["reports.export", "Reports", "Exports", "Create", "Export", "High"],
  [
    "reports.export_restricted",
    "Reports",
    "Restricted Exports",
    "Create",
    "Export",
    "Critical",
  ],
  [
    "reports.manage_metrics",
    "Reports",
    "Metric Registry",
    "Manage",
    "Manage Configuration",
    "Critical",
  ],
  [
    "reports.manage_alerts",
    "Reports",
    "Alerts",
    "Manage",
    "Manage Configuration",
    "Critical",
  ],
  [
    "reports.create_snapshot",
    "Reports",
    "Snapshots",
    "Create",
    "Create",
    "High",
  ],
  ["privacy.dashboard.view", "Privacy", "Dashboard", "View", "View", "High"],
  [
    "privacy.requests.view",
    "Privacy",
    "Requests",
    "View",
    "View Sensitive Fields",
    "High",
  ],
  [
    "privacy.requests.create",
    "Privacy",
    "Requests",
    "Create",
    "Create",
    "Moderate",
  ],
  [
    "privacy.requests.review",
    "Privacy",
    "Requests",
    "Review",
    "Approve",
    "High",
  ],
  [
    "privacy.requests.assign",
    "Privacy",
    "Requests",
    "Assign",
    "Manage Access",
    "High",
  ],
  [
    "privacy.requests.approve",
    "Privacy",
    "Requests",
    "Approve",
    "Approve",
    "Critical",
  ],
  [
    "privacy.requests.reject",
    "Privacy",
    "Requests",
    "Reject",
    "Approve",
    "Critical",
  ],
  [
    "privacy.requests.complete",
    "Privacy",
    "Requests",
    "Complete",
    "Edit",
    "High",
  ],
  [
    "privacy.exports.generate",
    "Privacy",
    "Exports",
    "Generate",
    "Export",
    "Critical",
  ],
  [
    "privacy.exports.approve",
    "Privacy",
    "Exports",
    "Approve",
    "Approve",
    "Critical",
  ],
  [
    "privacy.exports.download",
    "Privacy",
    "Exports",
    "Download",
    "Export",
    "High",
  ],
  [
    "privacy.deletion.plan",
    "Privacy",
    "Deletion Plans",
    "Create",
    "Delete",
    "Critical",
  ],
  [
    "privacy.deletion.approve",
    "Privacy",
    "Deletion Plans",
    "Approve",
    "Approve",
    "Critical",
  ],
  [
    "privacy.deletion.execute",
    "Privacy",
    "Deletion Plans",
    "Execute",
    "Delete",
    "Critical",
  ],
  [
    "privacy.anonymization.execute",
    "Privacy",
    "Anonymization",
    "Execute",
    "Delete",
    "Critical",
  ],
  ["privacy.notices.view", "Privacy", "Notices", "View", "View", "Moderate"],
  [
    "privacy.notices.manage",
    "Privacy",
    "Notices",
    "Manage",
    "Manage Configuration",
    "High",
  ],
  [
    "privacy.notices.approve",
    "Privacy",
    "Notices",
    "Approve",
    "Approve",
    "Critical",
  ],
  [
    "privacy.consents.view",
    "Privacy",
    "Consents",
    "View",
    "View Sensitive Fields",
    "High",
  ],
  ["privacy.consents.manage", "Privacy", "Consents", "Manage", "Edit", "High"],
  [
    "privacy.inventory.view",
    "Privacy",
    "Data Inventory",
    "View",
    "View Sensitive Fields",
    "High",
  ],
  [
    "privacy.inventory.manage",
    "Privacy",
    "Data Inventory",
    "Manage",
    "Manage Configuration",
    "Critical",
  ],
  [
    "privacy.purposes.view",
    "Privacy",
    "Processing Purposes",
    "View",
    "View",
    "High",
  ],
  [
    "privacy.purposes.manage",
    "Privacy",
    "Processing Purposes",
    "Manage",
    "Manage Configuration",
    "Critical",
  ],
  [
    "privacy.retention.view",
    "Privacy",
    "Retention",
    "View",
    "View Sensitive Fields",
    "High",
  ],
  [
    "privacy.retention.manage",
    "Privacy",
    "Retention",
    "Manage",
    "Manage Configuration",
    "Critical",
  ],
  [
    "privacy.retention.execute",
    "Privacy",
    "Retention",
    "Execute",
    "Delete",
    "Critical",
  ],
  [
    "privacy.legal_holds.view",
    "Privacy",
    "Legal Holds",
    "View",
    "View Sensitive Fields",
    "Critical",
  ],
  [
    "privacy.legal_holds.manage",
    "Privacy",
    "Legal Holds",
    "Manage",
    "Override",
    "Critical",
  ],
  [
    "privacy.vendors.view",
    "Privacy",
    "Vendors",
    "View",
    "View Sensitive Fields",
    "High",
  ],
  [
    "privacy.vendors.manage",
    "Privacy",
    "Vendors",
    "Manage",
    "Manage Configuration",
    "Critical",
  ],
  [
    "privacy.vendors.approve",
    "Privacy",
    "Vendors",
    "Approve",
    "Approve",
    "Critical",
  ],
  [
    "privacy.incidents.view",
    "Privacy",
    "Incidents",
    "View",
    "Manage Security",
    "Critical",
  ],
  [
    "privacy.incidents.manage",
    "Privacy",
    "Incidents",
    "Manage",
    "Manage Security",
    "Critical",
  ],
  [
    "privacy.incidents.resolve",
    "Privacy",
    "Incidents",
    "Resolve",
    "Approve",
    "Critical",
  ],
  [
    "privacy.assessments.view",
    "Privacy",
    "Assessments",
    "View",
    "View Sensitive Fields",
    "High",
  ],
  [
    "privacy.assessments.manage",
    "Privacy",
    "Assessments",
    "Manage",
    "Manage Configuration",
    "Critical",
  ],
  [
    "privacy.assessments.approve",
    "Privacy",
    "Assessments",
    "Approve",
    "Approve",
    "Critical",
  ],
  [
    "privacy.analytics.view",
    "Privacy",
    "Analytics",
    "View",
    "View Sensitive Fields",
    "High",
  ],
  ["privacy.override", "Privacy", "Overrides", "Use", "Override", "Critical"],
];
const incompatible = {
  "payments.refunds.request": ["payments.refunds.approve"],
  "payments.refunds.approve": ["payments.refunds.request"],
  "access.impersonation.request": ["access.impersonation.approve"],
  "access.impersonation.approve": ["access.impersonation.request"],
};
export const DEFAULT_PERMISSION_REGISTRY = permissionSpecs.map(
  ([key, module, resource, action, category, riskLevel], index) => ({
    id: `permission-${String(index + 1).padStart(3, "0")}`,
    key,
    module,
    resource,
    action,
    description: `${action} ${resource.toLowerCase()} in the ${module.toLowerCase()} module.`,
    category,
    riskLevel,
    confidentiality:
      riskLevel === "Critical"
        ? "Restricted"
        : riskLevel === "High"
          ? "Confidential"
          : "Standard",
    supportsScope: true,
    supportsTemporaryGrant: ![
      "users.permissions.grant",
      "users.permissions.deny",
    ].includes(key),
    approvalThresholdType: key.includes("refund")
      ? "Refund"
      : key.includes("quote")
        ? "Quote"
        : null,
    incompatiblePermissions: incompatible[key] || [],
    active: true,
    createdAt: "2026-07-01T09:00:00.000Z",
    updatedAt: "2026-07-16T10:00:00.000Z",
  }),
);
const p = (...keys) => keys;
export const DEFAULT_ROLES = [
  {
    id: "role-buyer",
    key: "buyer",
    name: "Buyer",
    description: "Own-account catalog and licensing access.",
    type: "External",
    status: "Active",
    permissionKeys: p(
      "catalog.tracks.view",
      "privacy.notices.view",
      "privacy.consents.manage",
      "privacy.requests.create",
      "privacy.exports.download",
    ),
    inheritedRoleIds: [],
    defaultScopes: [
      {
        type: "Self",
        ids: [],
        includeChildren: false,
        description: "Own records",
      },
    ],
    approvalLimits: {},
    systemRole: true,
    requiresApprovalToAssign: false,
  },
  {
    id: "role-buyer-org-admin",
    key: "buyer_org_admin",
    name: "Buyer Organization Administrator",
    description: "Safe organization administration.",
    type: "External",
    status: "Active",
    permissionKeys: p(
      "users.accounts.view",
      "analytics.buyers.view",
      "analytics.commercial.view",
      "analytics.finance.view",
      "analytics.operations.view",
      "reports.view",
      "privacy.notices.view",
      "privacy.consents.manage",
      "privacy.requests.create",
      "privacy.exports.download",
      "reports.export",
    ),
    inheritedRoleIds: ["role-buyer"],
    defaultScopes: [
      {
        type: "Organization",
        ids: ["org-northstar"],
        includeChildren: true,
        description: "Assigned buyer organization",
      },
    ],
    approvalLimits: {},
    systemRole: true,
    requiresApprovalToAssign: true,
  },
  {
    id: "role-artist",
    key: "artist",
    name: "Artist",
    description: "Own-track submission and review access.",
    type: "External",
    status: "Active",
    permissionKeys: p(
      "catalog.tracks.view",
      "ingestion.submissions.view",
      "analytics.artists.view",
      "analytics.catalog.view",
      "analytics.commercial.view",
      "reports.view",
    ),
    inheritedRoleIds: [],
    defaultScopes: [
      {
        type: "Artist",
        ids: ["org-smyrk"],
        includeChildren: true,
        description: "Own artist records",
      },
    ],
    approvalLimits: {},
    systemRole: true,
    requiresApprovalToAssign: false,
  },
  {
    id: "role-artist-representative",
    key: "artist_representative",
    name: "Artist Representative",
    description: "Scoped assigned-artist access.",
    type: "External",
    status: "Active",
    permissionKeys: p("ingestion.submissions.review"),
    inheritedRoleIds: ["role-artist"],
    defaultScopes: [
      {
        type: "Artist",
        ids: [],
        includeChildren: true,
        description: "Assigned artists",
      },
    ],
    approvalLimits: {},
    systemRole: true,
    requiresApprovalToAssign: true,
  },
  {
    id: "role-catalog-manager",
    key: "catalog_manager",
    name: "Catalog Manager",
    description: "Catalog, ingestion, publication, and search readiness.",
    type: "Internal",
    status: "Active",
    permissionKeys: p(
      "access.dashboard.view",
      "access.users.view",
      "access.roles.view",
      "catalog.tracks.view",
      "catalog.tracks.edit",
      "catalog.tracks.publish",
      "ingestion.submissions.view",
      "ingestion.submissions.review",
      "quotes.calculations.create",
      "analytics.catalog.view",
      "analytics.search.view",
      "analytics.artists.view",
      "reports.view",
      "reports.create",
      "reports.export",
    ),
    inheritedRoleIds: [],
    defaultScopes: [
      {
        type: "Catalog",
        ids: ["global-catalog"],
        includeChildren: true,
        description: "Global catalog",
      },
    ],
    approvalLimits: { Quote: 5000, Discount: 5 },
    systemRole: true,
    requiresApprovalToAssign: false,
  },
  {
    id: "role-media-operations",
    key: "media_operations",
    name: "Media Operations",
    description:
      "Media processing, previews, storage, and delivery preparation.",
    type: "Internal",
    status: "Active",
    permissionKeys: p(
      "access.dashboard.view",
      "storage.assets.view",
      "storage.assets.manage",
      "storage.masters.view",
      "previews.records.generate",
      "previews.records.approve",
      "ingestion.assets.replace",
      "deliveries.packages.create",
      "analytics.catalog.view",
      "analytics.operations.view",
      "reports.view",
      "reports.export",
    ),
    inheritedRoleIds: [],
    defaultScopes: [
      {
        type: "Catalog",
        ids: ["global-media"],
        includeChildren: true,
        description: "Global media processing",
      },
    ],
    approvalLimits: { Delivery: 14, DownloadLimit: 3 },
    systemRole: true,
    requiresApprovalToAssign: false,
  },
  {
    id: "role-rights-manager",
    key: "rights_manager",
    name: "Rights Manager",
    description: "Restricted rights review and eligibility.",
    type: "Internal",
    status: "Active",
    permissionKeys: p(
      "access.dashboard.view",
      "rights.records.view",
      "privacy.dashboard.view",
      "privacy.requests.view",
      "rights.records.create",
      "rights.records.edit",
      "rights.records.approve",
      "rights.documents.view",
      "rights.documents.download",
      "rights.disputes.manage",
      "analytics.rights.view",
      "analytics.artists.view",
      "privacy.requests.review",
      "privacy.retention.view",
      "reports.view",
      "reports.create",
      "reports.export",
    ),
    inheritedRoleIds: [],
    defaultScopes: [
      {
        type: "Global",
        ids: ["rights"],
        includeChildren: true,
        description: "Global rights records",
      },
    ],
    approvalLimits: { "Rights Exception": 1 },
    systemRole: true,
    requiresApprovalToAssign: true,
  },
  {
    id: "role-licensing-manager",
    key: "licensing_manager",
    name: "Licensing Manager",
    description: "Standard commercial workflow management.",
    type: "Internal",
    status: "Active",
    permissionKeys: p(
      "access.dashboard.view",
      "quotes.calculations.create",
      "quotes.calculations.view_internal",
      "quotes.approvals.approve",
      "contracts.records.create",
      "contracts.records.edit",
      "contracts.records.send",
      "licences.records.create",
      "deliveries.packages.create",
      "analytics.commercial.view",
      "analytics.buyers.view",
      "analytics.operations.view",
      "reports.view",
      "reports.create",
      "reports.edit",
      "reports.schedule",
      "reports.export",
      "reports.create_snapshot",
      "privacy.requests.review",
      "privacy.retention.view",
    ),
    inheritedRoleIds: [],
    defaultScopes: [
      {
        type: "Global",
        ids: ["licensing"],
        includeChildren: true,
        description: "Standard licensing",
      },
    ],
    approvalLimits: {
      Quote: 5000,
      Discount: 5,
      Delivery: 14,
      DownloadLimit: 3,
    },
    systemRole: true,
    requiresApprovalToAssign: false,
  },
  {
    id: "role-finance-manager",
    key: "finance_manager",
    name: "Finance Manager",
    description: "Payments, reconciliation, credits, and standard refunds.",
    type: "Internal",
    status: "Active",
    permissionKeys: p(
      "access.dashboard.view",
      "payments.transactions.view",
      "privacy.dashboard.view",
      "privacy.requests.view",
      "payments.transactions.process",
      "payments.reconciliation.manage",
      "payments.refunds.request",
      "payments.refunds.approve",
      "payments.refunds.issue",
      "payments.credits.manage",
      "membership_invoices.records.view",
      "analytics.finance.view",
      "analytics.commercial.view",
      "reports.view",
      "reports.create",
      "reports.export",
      "reports.export_restricted",
      "reports.create_snapshot",
      "privacy.requests.review",
      "privacy.retention.view",
    ),
    inheritedRoleIds: [],
    defaultScopes: [
      {
        type: "Global",
        ids: ["licensing-finance"],
        includeChildren: true,
        description: "Licensing finance",
      },
    ],
    approvalLimits: { Refund: 1000, PaymentAdjustment: 5000, Credit: 2500 },
    systemRole: true,
    requiresApprovalToAssign: true,
  },
  {
    id: "role-legal-reviewer",
    key: "legal_reviewer",
    name: "Legal Reviewer",
    description: "Legal contract and licence review.",
    type: "Internal",
    status: "Active",
    permissionKeys: p(
      "access.dashboard.view",
      "contracts.records.edit",
      "privacy.dashboard.view",
      "privacy.requests.view",
      "contracts.records.approve",
      "licences.records.approve",
      "licences.records.suspend",
      "licences.records.terminate",
      "analytics.commercial.view",
      "reports.view",
      "reports.export_restricted",
      "privacy.requests.review",
      "privacy.requests.approve",
      "privacy.exports.approve",
      "privacy.deletion.approve",
      "privacy.retention.view",
      "privacy.legal_holds.view",
      "privacy.legal_holds.manage",
      "privacy.vendors.view",
      "privacy.vendors.approve",
      "privacy.incidents.view",
      "privacy.incidents.resolve",
      "privacy.analytics.view",
    ),
    inheritedRoleIds: [],
    defaultScopes: [
      {
        type: "Global",
        ids: ["legal"],
        includeChildren: true,
        description: "Contract and licence legal scope",
      },
    ],
    approvalLimits: { Contract: 100000, Licence: 100000 },
    systemRole: true,
    requiresApprovalToAssign: true,
  },
  {
    id: "role-security-admin",
    key: "security_administrator",
    name: "Security Administrator",
    description:
      "Authentication, authorization, temporary access, and audit security.",
    type: "Internal",
    status: "Active",
    permissionKeys: p(
      "access.dashboard.view",
      "access.users.view",
      "privacy.dashboard.view",
      "privacy.requests.view",
      "access.roles.view",
      "access.permissions.view",
      "access.requests.review",
      "access.temporary.manage",
      "access.impersonation.approve",
      "access.reviews.manage",
      "access.conflicts.manage",
      "auth.sessions.view",
      "auth.sessions.revoke",
      "temporary_access.records.revoke",
      "audit.events.view",
      "audit.events.view_security",
      "analytics.security.view",
      "analytics.permissions.view",
      "reports.view",
      "reports.export_restricted",
      "reports.manage_alerts",
      "reports.create_snapshot",
      "privacy.requests.review",
      "privacy.exports.approve",
      "privacy.deletion.execute",
      "privacy.anonymization.execute",
      "privacy.incidents.view",
      "privacy.incidents.manage",
      "privacy.analytics.view",
    ),
    inheritedRoleIds: [],
    defaultScopes: [
      {
        type: "Global",
        ids: ["security"],
        includeChildren: true,
        description: "Security operations",
      },
    ],
    approvalLimits: { Impersonation: 60 },
    systemRole: true,
    requiresApprovalToAssign: true,
  },
  {
    id: "role-senior-approver",
    key: "senior_approver",
    name: "Senior Approver",
    description: "High-value and high-risk commercial approvals.",
    type: "Internal",
    status: "Active",
    permissionKeys: p(
      "access.dashboard.view",
      "quotes.approvals.approve",
      "quotes.pricing.override",
      "payments.refunds.approve",
      "contracts.records.approve",
      "licences.records.approve",
      "deliveries.packages.approve",
      "deliveries.packages.activate",
      "analytics.executive.view",
      "analytics.commercial.view",
      "analytics.finance.view",
      "reports.view",
      "reports.create",
      "reports.edit",
      "reports.share",
      "reports.schedule",
      "reports.export",
      "reports.export_restricted",
      "reports.manage_alerts",
      "reports.create_snapshot",
    ),
    inheritedRoleIds: ["role-licensing-manager"],
    defaultScopes: [
      {
        type: "Global",
        ids: ["commercial-approvals"],
        includeChildren: true,
        description: "Commercial approvals",
      },
    ],
    approvalLimits: {
      Quote: 100000,
      Discount: 25,
      Refund: 25000,
      Delivery: 60,
      DownloadLimit: 10,
    },
    systemRole: true,
    requiresApprovalToAssign: true,
  },
  {
    id: "role-support-admin",
    key: "support_administrator",
    name: "Support Administrator",
    description:
      "Safe account support and approved buyer view-only impersonation.",
    type: "Internal",
    status: "Active",
    permissionKeys: p(
      "access.dashboard.view",
      "access.users.view",
      "users.accounts.view",
      "users.impersonation.request",
      "access.impersonation.start",
      "privacy.requests.view",
      "privacy.requests.create",
    ),
    inheritedRoleIds: [],
    defaultScopes: [
      {
        type: "Global",
        ids: ["support-safe"],
        includeChildren: false,
        description: "Safe account fields",
      },
    ],
    approvalLimits: { Impersonation: 30 },
    systemRole: true,
    requiresApprovalToAssign: false,
  },
  {
    id: "role-privacy-admin",
    key: "privacy_administrator",
    name: "Privacy Administrator",
    description:
      "Privacy requests, discovery, notices, consents, retention preparation, vendors, and privacy reporting.",
    type: "Internal",
    status: "Active",
    permissionKeys: p(
      "access.dashboard.view",
      "privacy.dashboard.view",
      "privacy.requests.view",
      "privacy.requests.create",
      "privacy.requests.review",
      "privacy.requests.assign",
      "privacy.requests.complete",
      "privacy.exports.generate",
      "privacy.exports.download",
      "privacy.deletion.plan",
      "privacy.notices.view",
      "privacy.notices.manage",
      "privacy.consents.view",
      "privacy.consents.manage",
      "privacy.inventory.view",
      "privacy.inventory.manage",
      "privacy.purposes.view",
      "privacy.purposes.manage",
      "privacy.retention.view",
      "privacy.retention.manage",
      "privacy.vendors.view",
      "privacy.vendors.manage",
      "privacy.assessments.view",
      "privacy.assessments.manage",
      "privacy.analytics.view",
      "audit.events.view",
      "email.queue.manage",
    ),
    inheritedRoleIds: [],
    defaultScopes: [
      {
        type: "Global",
        ids: ["privacy-operations"],
        includeChildren: true,
        description: "Global privacy operations with approval safeguards",
      },
    ],
    approvalLimits: {},
    systemRole: true,
    requiresApprovalToAssign: true,
  },
  {
    id: "role-super-admin",
    key: "super_administrator",
    name: "Super Administrator",
    description:
      "Full prototype administration with audit and critical-action safeguards.",
    type: "Internal",
    status: "Active",
    permissionKeys: DEFAULT_PERMISSION_REGISTRY.map((item) => item.key),
    inheritedRoleIds: [],
    defaultScopes: [
      {
        type: "Global",
        ids: ["all"],
        includeChildren: true,
        description: "Global prototype",
      },
    ],
    approvalLimits: {
      Quote: 500000,
      Discount: 50,
      Refund: 100000,
      Delivery: 90,
      DownloadLimit: 20,
      Impersonation: 60,
    },
    systemRole: true,
    requiresApprovalToAssign: true,
  },
].map((role, index) => ({
  ...role,
  version: 1,
  assignableByRoleIds: ["role-super-admin"],
  createdAt: "2026-07-01T09:00:00.000Z",
  createdBy: "Beatmondo Demo Automation",
  updatedAt: "2026-07-16T10:00:00.000Z",
  updatedBy: "Preston Repenning",
  metadata: { order: index + 1 },
}));

const assignment = (id, userId, roleId, scope, overrides = {}) => ({
  id,
  userId,
  roleId,
  roleVersion: 1,
  status: "Active",
  scopeIds: scope.ids,
  scope,
  organizationId:
    scope.type === "Organization" ? scope.ids[0] : "org-beatmondo",
  assignedBy: "user-preston",
  assignedAt: "2026-07-01T10:00:00.000Z",
  approvedBy: "user-preston",
  approvedAt: "2026-07-01T10:05:00.000Z",
  validFrom: "2026-07-01T10:00:00.000Z",
  expiresAt: null,
  reason: "Seeded prototype access",
  temporary: false,
  metadata: {},
  ...overrides,
});
export const DEFAULT_ROLE_ASSIGNMENTS = [
  assignment("assignment-preston-super", "user-preston", "role-super-admin", {
    type: "Global",
    ids: ["all"],
    includeChildren: true,
  }),
  assignment(
    "assignment-jordan-catalog",
    "user-jordan",
    "role-catalog-manager",
    { type: "Catalog", ids: ["global-catalog"], includeChildren: true },
  ),
  assignment(
    "assignment-jordan-licensing",
    "user-jordan",
    "role-licensing-manager",
    { type: "Global", ids: ["standard-licensing"], includeChildren: true },
  ),
  assignment("assignment-amelia-rights", "user-amelia", "role-rights-manager", {
    type: "Global",
    ids: ["rights"],
    includeChildren: true,
  }),
  assignment("assignment-noah-media", "user-noah", "role-media-operations", {
    type: "Catalog",
    ids: ["global-media"],
    includeChildren: true,
  }),
  assignment("assignment-finance", "user-finance", "role-finance-manager", {
    type: "Global",
    ids: ["licensing-finance"],
    includeChildren: true,
  }),
  assignment("assignment-legal", "user-legal", "role-legal-reviewer", {
    type: "Global",
    ids: ["legal"],
    includeChildren: true,
  }),
  assignment("assignment-security", "user-security", "role-security-admin", {
    type: "Global",
    ids: ["security"],
    includeChildren: true,
  }),
  assignment("assignment-privacy", "user-privacy", "role-privacy-admin", {
    type: "Global",
    ids: ["privacy-operations"],
    includeChildren: true,
  }),
  assignment(
    "assignment-olivia-buyer",
    "user-olivia",
    "role-buyer-org-admin",
    { type: "Organization", ids: ["org-northstar"], includeChildren: true },
    { organizationId: "org-northstar" },
  ),
  assignment(
    "assignment-marcus-artist",
    "user-marcus",
    "role-artist",
    { type: "Artist", ids: ["org-smyrk"], includeChildren: true },
    { organizationId: "org-smyrk" },
  ),
];

export const DEFAULT_PERMISSIONS_STATE = {
  version: 1,
  permissionRegistry: DEFAULT_PERMISSION_REGISTRY,
  roles: DEFAULT_ROLES,
  roleVersions: [],
  assignments: DEFAULT_ROLE_ASSIGNMENTS,
  directGrants: [
    {
      id: "grant-jordan-audit",
      userId: "user-jordan",
      permissionKey: "audit.events.review",
      effect: "Allow",
      scope: {
        type: "Global",
        ids: ["audit-standard"],
        includeChildren: false,
      },
      status: "Active",
      validFrom: "2026-07-10T10:00:00.000Z",
      expiresAt: null,
      reason: "Operational evidence review",
      requestedBy: "user-preston",
      approvedBy: "user-preston",
      createdAt: "2026-07-10T10:00:00.000Z",
    },
  ],
  explicitDenials: [
    {
      id: "denial-finance-investigation",
      userId: "user-finance",
      permissionKey: "payments.refunds.approve",
      effect: "Deny",
      scope: {
        type: "Record",
        ids: ["refund-investigation-7"],
        includeChildren: false,
      },
      status: "Active",
      validFrom: "2026-07-12T10:00:00.000Z",
      expiresAt: "2026-08-01T10:00:00.000Z",
      reason: "Independent investigation requires alternate approver",
      requestedBy: "user-security",
      approvedBy: "user-preston",
      createdAt: "2026-07-12T10:00:00.000Z",
    },
  ],
  temporaryElevations: [
    {
      id: "elevation-jordan-quote",
      reference: "BM-ELEV-2026-0001",
      userId: "user-jordan",
      permissionKey: "quotes.approvals.approve",
      roleId: null,
      scope: {
        type: "Project",
        ids: ["project-horizon-run"],
        includeChildren: true,
      },
      requestedLimit: 10000,
      status: "Active",
      validFrom: "2026-07-15T09:00:00.000Z",
      expiresAt: "2026-07-22T18:00:00.000Z",
      reason: "Campaign coverage",
      requesterId: "user-jordan",
      approverId: "user-preston",
      ticket: "BM-CASE-410",
      emergency: false,
    },
    {
      id: "elevation-noah-delivery",
      reference: "BM-ELEV-2026-0002",
      userId: "user-noah",
      permissionKey: "deliveries.packages.approve",
      roleId: null,
      scope: {
        type: "Project",
        ids: ["project-horizon-run"],
        includeChildren: true,
      },
      status: "Active",
      validFrom: "2026-07-16T09:00:00.000Z",
      expiresAt: "2026-07-18T18:00:00.000Z",
      reason: "Project delivery coverage",
      requesterId: "user-noah",
      approverId: "user-preston",
      ticket: "BM-CASE-411",
      emergency: false,
    },
    {
      id: "elevation-expired",
      reference: "BM-ELEV-2026-0003",
      userId: "user-jordan",
      permissionKey: "payments.transactions.view",
      roleId: null,
      scope: {
        type: "Record",
        ids: ["payment-archive-1"],
        includeChildren: false,
      },
      status: "Expired",
      validFrom: "2026-06-01T09:00:00.000Z",
      expiresAt: "2026-06-02T09:00:00.000Z",
      reason: "Historical troubleshooting",
      requesterId: "user-jordan",
      approverId: "user-preston",
      ticket: "BM-CASE-350",
      emergency: false,
    },
  ],
  approvalAuthorities: [
    {
      id: "authority-jordan-quote",
      userId: "user-jordan",
      roleId: "role-licensing-manager",
      approvalType: "Quote",
      currency: "USD",
      maximumAmount: 5000,
      maximumDiscountPercentage: 5,
      maximumAccessDurationDays: 14,
      allowedRiskLevels: ["Low", "Moderate"],
      requiresCoApprovalAbove: 5000,
      active: true,
      validFrom: "2026-07-01T00:00:00.000Z",
      expiresAt: null,
    },
    {
      id: "authority-finance-refund",
      userId: "user-finance",
      roleId: "role-finance-manager",
      approvalType: "Refund",
      currency: "USD",
      maximumAmount: 1000,
      maximumDiscountPercentage: 0,
      maximumAccessDurationDays: null,
      allowedRiskLevels: ["Low", "Moderate"],
      requiresCoApprovalAbove: 1000,
      active: true,
      validFrom: "2026-07-01T00:00:00.000Z",
      expiresAt: null,
    },
    {
      id: "authority-preston",
      userId: "user-preston",
      roleId: "role-super-admin",
      approvalType: "All",
      currency: "USD",
      maximumAmount: 500000,
      maximumDiscountPercentage: 50,
      maximumAccessDurationDays: 90,
      allowedRiskLevels: ["Low", "Moderate", "High", "Critical"],
      requiresCoApprovalAbove: 100000,
      active: true,
      validFrom: "2026-07-01T00:00:00.000Z",
      expiresAt: null,
    },
  ],
  accessRequests: [
    {
      id: "request-security-role",
      reference: "BM-ACCESS-2026-0001",
      requesterId: "user-noah",
      permissionKey: null,
      roleId: "role-security-admin",
      scope: { type: "Global", ids: ["security"], includeChildren: true },
      reason: "Incident response coverage",
      risk: "Critical",
      durationHours: 8,
      urgency: "High",
      approverId: "user-preston",
      status: "Under Review",
      conflicts: [
        "Media Operations plus Security Administrator requires secondary review",
      ],
      submittedAt: "2026-07-16T09:00:00.000Z",
    },
    {
      id: "request-rejected-scope",
      reference: "BM-ACCESS-2026-0002",
      requesterId: "user-jordan",
      permissionKey: "payments.reconciliation.manage",
      roleId: null,
      scope: { type: "Global", ids: ["all-finance"], includeChildren: true },
      reason: "Broad troubleshooting",
      risk: "Critical",
      durationHours: 168,
      urgency: "Normal",
      approverId: "user-preston",
      status: "Rejected",
      conflicts: ["Scope exceeds business requirement"],
      submittedAt: "2026-07-12T09:00:00.000Z",
      decisionReason: "Excessive finance scope",
    },
  ],
  delegations: [
    {
      id: "delegation-finance",
      reference: "BM-DELGT-2026-0001",
      delegatorId: "user-finance",
      delegateId: "user-preston",
      approvalType: "Refund",
      scope: {
        type: "Global",
        ids: ["standard-refunds"],
        includeChildren: false,
      },
      limit: 1000,
      start: "2026-07-20T09:00:00.000Z",
      end: "2026-07-27T18:00:00.000Z",
      reason: "Finance coverage",
      furtherDelegationAllowed: false,
      status: "Scheduled",
    },
  ],
  impersonations: [
    {
      id: "impersonation-completed",
      reference: "BM-IMP-2026-0001",
      administratorId: "user-preston",
      targetUserId: "user-olivia",
      reason: "Reproduce buyer delivery UI issue",
      scope: "View-only buyer support",
      status: "Ended",
      requestedAt: "2026-07-14T10:00:00.000Z",
      approvedBy: "user-security",
      approvedAt: "2026-07-14T10:05:00.000Z",
      startedAt: "2026-07-14T10:06:00.000Z",
      expiresAt: "2026-07-14T10:36:00.000Z",
      endedAt: "2026-07-14T10:22:00.000Z",
      sessionId: "imp-session-1",
      actionsPerformed: ["Viewed buyer dashboard", "Viewed delivery status"],
    },
  ],
  accessReviews: [
    {
      id: "review-quarterly",
      reference: "BM-AREV-2026-0001",
      name: "Quarterly Internal Access Review",
      scope: "All internal users",
      status: "In Progress",
      reviewers: ["user-preston", "user-security"],
      userIds: ["user-jordan", "user-amelia", "user-noah", "user-finance"],
      roleIds: [],
      startedAt: "2026-07-10T09:00:00.000Z",
      dueAt: "2026-07-25T18:00:00.000Z",
      completedAt: null,
      findings: [],
      createdBy: "user-preston",
    },
    {
      id: "review-finance",
      reference: "BM-AREV-2026-0002",
      name: "Finance Privileged Access Review",
      scope: "Finance access",
      status: "Completed",
      reviewers: ["user-preston"],
      userIds: ["user-finance"],
      roleIds: ["role-finance-manager"],
      startedAt: "2026-06-01T09:00:00.000Z",
      dueAt: "2026-06-15T18:00:00.000Z",
      completedAt: "2026-06-12T15:00:00.000Z",
      findings: ["Keep standard refund authority"],
      createdBy: "user-preston",
    },
    {
      id: "review-rights",
      reference: "BM-AREV-2026-0003",
      name: "Rights Restricted Access Review",
      scope: "Rights restricted",
      status: "Overdue",
      reviewers: ["user-amelia"],
      userIds: ["user-amelia"],
      roleIds: ["role-rights-manager"],
      startedAt: "2026-07-01T09:00:00.000Z",
      dueAt: "2026-07-14T18:00:00.000Z",
      completedAt: null,
      findings: [],
      createdBy: "user-preston",
    },
  ],
  conflicts: [
    {
      id: "conflict-jordan-commercial",
      userId: "user-jordan",
      roleIds: ["role-catalog-manager", "role-licensing-manager"],
      permissionKeys: [
        "quotes.calculations.create",
        "quotes.approvals.approve",
      ],
      severity: "High",
      relatedWorkflow: "High-value quote approval",
      recommendation:
        "Require a separate senior approver above Jordan's threshold.",
      assignedReviewer: "user-preston",
      status: "Open",
    },
  ],
  systemAccounts: [
    {
      id: "system-demo-automation",
      name: "Beatmondo Demo Automation",
      permissions: ["catalog.tracks.view"],
      interactiveLogin: false,
    },
    {
      id: "system-email-queue",
      name: "Email Queue Processor",
      permissions: ["email.queue.manage"],
      interactiveLogin: false,
    },
    {
      id: "system-audit-fallback",
      name: "Audit Fallback Processor",
      permissions: ["audit.events.view"],
      interactiveLogin: false,
    },
    {
      id: "system-expiry",
      name: "Expiry Processor",
      permissions: ["temporary_access.records.revoke"],
      interactiveLogin: false,
    },
    {
      id: "system-search-index",
      name: "Search Index Synchronizer",
      permissions: ["catalog.tracks.view"],
      interactiveLogin: false,
    },
    {
      id: "system-media",
      name: "Media Processing Simulation",
      permissions: ["previews.records.generate"],
      interactiveLogin: false,
    },
  ],
  roleSequence: 14,
  requestSequence: 2,
  elevationSequence: 3,
  assignmentSequence: 10,
  grantSequence: 1,
  cache: {},
  cacheVersion: 1,
  decisionLog: [],
  notifications: [],
  lastResetAt: null,
};
