export const PAYMENT_STORAGE_KEY = "beatmondo-licensing-payments-v1";
export const SELECTED_INVOICE_KEY = "beatmondo-selected-licensing-invoice";
export const SELECTED_PAYMENT_KEY = "beatmondo-selected-licensing-payment";
export const CHECKOUT_KEY = "beatmondo-licensing-checkout";

export const PAYMENT_STATUSES = {
  Draft: { buyerLabel: "Preparing", retry: false, next: ["Pending"] },
  Pending: {
    buyerLabel: "Pending",
    retry: false,
    next: ["Processing", "Cancelled", "Expired"],
  },
  Processing: {
    buyerLabel: "Processing",
    retry: false,
    next: ["Authentication Required", "Succeeded", "Failed"],
  },
  "Authentication Required": {
    buyerLabel: "Action required",
    retry: true,
    next: ["Authorized", "Failed"],
  },
  Authorized: { buyerLabel: "Authorized", retry: false, next: ["Succeeded"] },
  Succeeded: {
    buyerLabel: "Paid",
    retry: false,
    next: ["Partially Refunded", "Refunded", "Chargeback Simulation"],
  },
  Failed: { buyerLabel: "Failed", retry: true, next: ["Pending"] },
  Declined: { buyerLabel: "Declined", retry: true, next: ["Pending"] },
  Cancelled: { buyerLabel: "Cancelled", retry: false, next: [] },
  Expired: { buyerLabel: "Expired", retry: true, next: ["Pending"] },
  "Pending Reconciliation": {
    buyerLabel: "Bank transfer under review",
    retry: false,
    next: ["Reconciled", "Failed"],
  },
  Reconciled: {
    buyerLabel: "Paid and reconciled",
    retry: false,
    next: ["Partially Refunded", "Refunded"],
  },
  "Partially Refunded": {
    buyerLabel: "Partially refunded",
    retry: false,
    next: ["Refunded"],
  },
  Refunded: { buyerLabel: "Refunded", retry: false, next: [] },
  "Chargeback Simulation": {
    buyerLabel: "Payment under review",
    retry: false,
    next: ["Disputed Simulation"],
  },
  "Disputed Simulation": {
    buyerLabel: "Dispute under review",
    retry: false,
    next: [],
  },
};
export const INVOICE_STATUSES = [
  "Draft",
  "Open",
  "Partially Paid",
  "Paid",
  "Past Due",
  "Void",
  "Cancelled",
  "Refunded",
  "Partially Refunded",
  "Uncollectible",
];

const invoice = (
  id,
  reference,
  buyer,
  organization,
  contract,
  project,
  track,
  type,
  total,
  status,
  overrides = {},
) => ({
  id,
  reference,
  invoiceType: type,
  buyerId: buyer.id,
  buyer: buyer.name,
  organizationId: organization.id,
  organization: organization.name,
  contractId: contract.id,
  contractReference: contract.reference,
  quoteId: overrides.quoteId || null,
  quoteReference: overrides.quoteReference || null,
  licenceId: overrides.licenceId || null,
  licenceReference: overrides.licenceReference || null,
  projectId: overrides.projectId || contract.projectId,
  project,
  track,
  issueDate: overrides.issueDate || "2026-07-18T00:00:00.000Z",
  dueDate: overrides.dueDate || "2026-07-25T23:59:59.000Z",
  currency: overrides.currency || "USD",
  lineItems: overrides.lineItems || [
    {
      id: `line-${id}`,
      description: type,
      quantity: 1,
      unitAmount: total,
      total,
    },
  ],
  subtotal: total,
  tax: overrides.tax ?? 0,
  taxRate: overrides.taxRate ?? 0,
  taxLabel: overrides.taxLabel || "Tax review / not calculated",
  taxJurisdiction:
    overrides.taxJurisdiction || "Buyer jurisdiction review required",
  taxRegistrationReference:
    overrides.taxRegistrationReference || "Not supplied in prototype",
  creditApplied: overrides.creditApplied || 0,
  total,
  amountPaid: overrides.amountPaid || 0,
  balanceDue:
    overrides.balanceDue ??
    Math.max(
      0,
      total - (overrides.amountPaid || 0) - (overrides.creditApplied || 0),
    ),
  status,
  paymentTerms: overrides.paymentTerms || "Due before licence generation",
  version: 1,
  createdAt: overrides.createdAt || "2026-07-18T00:00:00.000Z",
  updatedAt: overrides.updatedAt || "2026-07-18T00:00:00.000Z",
  membershipInvoice: false,
});
const tx = (
  id,
  reference,
  type,
  buyer,
  organization,
  invoiceId,
  contractId,
  projectId,
  amount,
  status,
  overrides = {},
) => ({
  id,
  reference,
  paymentType: type,
  source: overrides.source || "Licensing Checkout",
  buyerId: buyer.id,
  buyer: buyer.name,
  organizationId: organization.id,
  organization: organization.name,
  projectId,
  quoteId: overrides.quoteId || null,
  contractId,
  licenceId: overrides.licenceId || null,
  invoiceId,
  paymentMethodId: overrides.paymentMethodId || null,
  paymentMethodLabel: overrides.paymentMethodLabel || "Visa ending 4242",
  currency: overrides.currency || "USD",
  amount,
  status,
  providerReference: overrides.providerReference || `mock_provider_${id}`,
  mockAuthorizationId: overrides.mockAuthorizationId || null,
  failureCode: overrides.failureCode || null,
  failureMessage: overrides.failureMessage || null,
  authenticationRequired: status === "Authentication Required",
  authenticationStatus: overrides.authenticationStatus || null,
  initiatedAt: overrides.initiatedAt || "2026-07-18T10:00:00.000Z",
  authorizedAt: overrides.authorizedAt || null,
  capturedAt: overrides.capturedAt || null,
  failedAt: overrides.failedAt || null,
  refundedAt: overrides.refundedAt || null,
  reconciledAt: overrides.reconciledAt || null,
  createdBy: overrides.createdBy || buyer.name,
  metadata: {
    idempotencyKey: overrides.idempotencyKey || `bm_pay_idem_${id}`,
    cardLast4: overrides.cardLast4 || null,
    purchaseOrder: overrides.purchaseOrder || null,
    internalOnly: false,
    ...overrides.metadata,
  },
});
const olivia = { id: "user-olivia", name: "Olivia Bennett" },
  northstar = { id: "org-northstar", name: "Northstar Pictures" };
const sofia = { id: "user-sofia", name: "Sofia Martinez" },
  lighthouse = { id: "org-lighthouse", name: "Lighthouse Creative" };
const rachel = { id: "user-rachel", name: "Rachel Kim" },
  orbit = { id: "org-orbit", name: "Orbit Trailers" };
const daniel = { id: "user-daniel", name: "Daniel Brooks" },
  independent = { id: "org-independent", name: "Self-employed" };
const enterprise = { id: "buyer-enterprise", name: "Enterprise Studio Legal" },
  enterpriseOrg = { id: "org-enterprise", name: "Enterprise Studio Group" };
const major = { id: "buyer-major-studio", name: "Major Studio Account" },
  majorOrg = { id: "org-major-studio", name: "Major Studio" };

export const DEFAULT_LICENSING_INVOICES = [
  invoice(
    "invoice-lic-31",
    "BM-INV-LIC-2026-0031",
    olivia,
    northstar,
    {
      id: "contract-21",
      reference: "BM-C-2026-0021",
      projectId: "project-premium-hotel",
    },
    "Premium Hotel Launch Film",
    "Golden Hours",
    "Licence Deposit",
    525000,
    "Paid",
    {
      amountPaid: 525000,
      balanceDue: 0,
      paymentTerms: "50% deposit on final signature",
    },
  ),
  invoice(
    "invoice-lic-32",
    "BM-INV-LIC-2026-0032",
    olivia,
    northstar,
    {
      id: "contract-21",
      reference: "BM-C-2026-0021",
      projectId: "project-premium-hotel",
    },
    "Premium Hotel Launch Film",
    "Golden Hours",
    "Licence Balance",
    525000,
    "Open",
    { paymentTerms: "Balance due before licence generation" },
  ),
  invoice(
    "invoice-lic-33",
    "BM-INV-LIC-2026-0033",
    enterprise,
    enterpriseOrg,
    {
      id: "contract-25",
      reference: "BM-C-2026-0025",
      projectId: "project-enterprise-film",
    },
    "Feature Film End Credits",
    "Velvet Warning",
    "Full Licence Fee",
    4200000,
    "Paid",
    {
      amountPaid: 4200000,
      balanceDue: 0,
      licenceId: "licence-19",
      licenceReference: "BM-LIC-2026-0019",
      paymentTerms: "Enterprise bank-transfer terms",
    },
  ),
  invoice(
    "invoice-lic-34",
    "BM-INV-LIC-2026-0034",
    sofia,
    lighthouse,
    {
      id: "contract-19",
      reference: "BM-C-2026-0019",
      projectId: "project-quiet-city",
    },
    "Quiet City Documentary",
    "Midnight Transit",
    "Full Licence Fee",
    420000,
    "Open",
    { paymentTerms: "Payment pending verification and contract revalidation" },
  ),
  invoice(
    "invoice-lic-35",
    "BM-INV-LIC-2026-0035",
    rachel,
    orbit,
    {
      id: "contract-23",
      reference: "BM-C-2026-0023",
      projectId: "project-midnight-run",
    },
    "Midnight Run Trailer",
    "All That Remains",
    "Licence Deposit",
    850000,
    "Past Due",
    {
      dueDate: "2026-07-15T23:59:59.000Z",
      paymentTerms: "Restricted pending account resolution",
    },
  ),
  invoice(
    "invoice-lic-36",
    "BM-INV-LIC-2026-0036",
    olivia,
    northstar,
    {
      id: "contract-22",
      reference: "BM-C-2026-0022",
      projectId: "project-luxury-auto",
    },
    "Luxury Auto Campaign - Fall 2026",
    "Golden Hours",
    "Licence Deposit",
    1400000,
    "Open",
    { paymentTerms: "Due after full execution" },
  ),
  invoice(
    "invoice-lic-37",
    "BM-INV-LIC-2026-0037",
    major,
    majorOrg,
    {
      id: "contract-major-1",
      reference: "BM-C-2026-0027",
      projectId: "project-major",
    },
    "Major Studio Campaign",
    "Golden Hours",
    "Enterprise Invoice",
    2800000,
    "Open",
    { paymentTerms: "Bank transfer; finance reconciliation required" },
  ),
  invoice(
    "invoice-lic-38",
    "BM-INV-LIC-2026-0038",
    olivia,
    northstar,
    {
      id: "contract-45",
      reference: "BM-C-2026-0015",
      projectId: "project-aurora",
    },
    "Aurora Motors Campaign",
    "Meridian",
    "Contract Amendment",
    1800000,
    "Partially Refunded",
    {
      amountPaid: 1800000,
      balanceDue: 0,
      licenceId: "licence-amended-11",
      licenceReference: "BM-LIC-AMD-2026-0003",
      issueDate: "2026-07-08T00:00:00.000Z",
    },
  ),
  invoice(
    "invoice-lic-39",
    "BM-INV-LIC-2026-0039",
    daniel,
    independent,
    {
      id: "contract-18",
      reference: "BM-C-2026-0018",
      projectId: "project-independent",
    },
    "Independent Channel Package",
    "Northern Lines",
    "Full Licence Fee",
    250000,
    "Refunded",
    {
      amountPaid: 0,
      balanceDue: 0,
      licenceId: "licence-44",
      licenceReference: "BM-LIC-2025-0044",
    },
  ),
];

export const DEFAULT_OBLIGATIONS = [
  {
    id: "obligation-21-deposit",
    obligationType: "Deposit payment",
    quoteId: "quote-41",
    contractId: "contract-21",
    licenceId: null,
    invoiceId: "invoice-lic-31",
    buyerId: "user-olivia",
    organizationId: "org-northstar",
    projectId: "project-premium-hotel",
    currency: "USD",
    amountDue: 525000,
    amountPaid: 525000,
    amountRefunded: 0,
    balanceRemaining: 0,
    dueDate: "2026-07-18T23:59:59.000Z",
    paymentTerms: "50% deposit on final signature",
    depositPercentage: 50,
    depositAmount: 525000,
    balanceAmount: 525000,
    status: "Paid",
    requiredForContractEffectiveness: false,
    requiredForLicenceGeneration: true,
    requiredForDelivery: true,
    conditions: ["Balance remains due"],
    createdAt: "2026-07-18T00:00:00.000Z",
    updatedAt: "2026-07-18T12:00:00.000Z",
  },
  {
    id: "obligation-21-balance",
    obligationType: "Balance payment",
    quoteId: "quote-41",
    contractId: "contract-21",
    licenceId: null,
    invoiceId: "invoice-lic-32",
    buyerId: "user-olivia",
    organizationId: "org-northstar",
    projectId: "project-premium-hotel",
    currency: "USD",
    amountDue: 525000,
    amountPaid: 0,
    amountRefunded: 0,
    balanceRemaining: 525000,
    dueDate: "2026-07-25T23:59:59.000Z",
    paymentTerms: "Due before licence generation",
    depositPercentage: 50,
    depositAmount: 525000,
    balanceAmount: 525000,
    status: "Open",
    requiredForContractEffectiveness: false,
    requiredForLicenceGeneration: true,
    requiredForDelivery: true,
    conditions: ["Issued licence required after payment"],
    createdAt: "2026-07-18T00:00:00.000Z",
    updatedAt: "2026-07-18T00:00:00.000Z",
  },
  ...DEFAULT_LICENSING_INVOICES.filter(
    (i) => !["invoice-lic-31", "invoice-lic-32"].includes(i.id),
  ).map((i) => ({
    id: `obligation-${i.id}`,
    obligationType: i.invoiceType,
    quoteId: i.quoteId,
    contractId: i.contractId,
    licenceId: null,
    invoiceId: i.id,
    buyerId: i.buyerId,
    organizationId: i.organizationId,
    projectId: i.projectId,
    currency: i.currency,
    amountDue: i.total,
    amountPaid: i.amountPaid,
    amountRefunded: i.status.includes("Refund") ? i.total - i.amountPaid : 0,
    balanceRemaining: i.balanceDue,
    dueDate: i.dueDate,
    paymentTerms: i.paymentTerms,
    depositPercentage: null,
    depositAmount: null,
    balanceAmount: i.total,
    status:
      i.status === "Paid"
        ? "Paid"
        : i.status === "Partially Refunded"
          ? "Under Review"
          : i.status === "Refunded"
            ? "Refunded"
            : i.status,
    requiredForContractEffectiveness: false,
    requiredForLicenceGeneration: true,
    requiredForDelivery: true,
    conditions: [],
    createdAt: i.createdAt,
    updatedAt: i.updatedAt,
  })),
];

export const DEFAULT_TRANSACTIONS = [
  tx(
    "payment-61",
    "BM-PAY-2026-0061",
    "Deposit",
    olivia,
    northstar,
    "invoice-lic-31",
    "contract-21",
    "project-premium-hotel",
    525000,
    "Succeeded",
    {
      capturedAt: "2026-07-18T12:00:00.000Z",
      paymentMethodId: "pm-olivia-visa",
      cardLast4: "4242",
    },
  ),
  invoice(
    "invoice-lic-40",
    "BM-INV-LIC-2026-0040",
    olivia,
    northstar,
    {
      id: "contract-26",
      reference: "BM-C-2026-0026",
      projectId: "project-brand-film",
    },
    "Northstar Brand Film",
    "Golden Hours",
    "Full Licence Fee",
    1600000,
    "Paid",
    {
      quoteId: "quote-49",
      quoteReference: "BM-Q-2026-0049",
      amountPaid: 1600000,
      balanceDue: 0,
      paymentTerms: "Paid in full before licence generation",
    },
  ),
  tx(
    "payment-63",
    "BM-PAY-2026-0063",
    "Full licence payment",
    enterprise,
    enterpriseOrg,
    "invoice-lic-33",
    "contract-25",
    "project-enterprise-film",
    4200000,
    "Reconciled",
    {
      paymentMethodLabel: "Bank transfer",
      reconciledAt: "2026-07-19T15:00:00.000Z",
      purchaseOrder: "ESG-PO-9921",
    },
  ),
  tx(
    "payment-64",
    "BM-PAY-2026-0064",
    "Full licence payment",
    sofia,
    lighthouse,
    "invoice-lic-34",
    "contract-19",
    "project-quiet-city",
    420000,
    "Failed",
    {
      paymentMethodLabel: "Mastercard ending 4444",
      failureCode: "CARD_DECLINED",
      failureMessage: "Card declined",
      failedAt: "2026-07-19T11:00:00.000Z",
    },
  ),
  tx(
    "payment-65",
    "BM-PAY-2026-0065",
    "Deposit",
    rachel,
    orbit,
    "invoice-lic-35",
    "contract-23",
    "project-midnight-run",
    850000,
    "Failed",
    {
      failureCode: "INSUFFICIENT_FUNDS",
      failureMessage: "Insufficient funds",
      failedAt: "2026-07-19T11:30:00.000Z",
    },
  ),
  tx(
    "payment-66",
    "BM-PAY-2026-0066",
    "Deposit",
    olivia,
    northstar,
    "invoice-lic-36",
    "contract-22",
    "project-luxury-auto",
    1400000,
    "Authentication Required",
    {
      paymentMethodLabel: "Visa ending 3155",
      cardLast4: "3155",
      authenticationStatus: "Pending",
    },
  ),
  tx(
    "payment-67",
    "BM-PAY-2026-0067",
    "Enterprise payment",
    major,
    majorOrg,
    "invoice-lic-37",
    "contract-major-1",
    "project-major",
    2800000,
    "Pending Reconciliation",
    {
      paymentMethodLabel: "Bank transfer",
      purchaseOrder: "NST-PO-4417",
      metadata: {
        bankTransferStatus: "Proof Submitted",
        proofFile: "payment-proof-NST-PO-4417.pdf",
      },
    },
  ),
  tx(
    "payment-68",
    "BM-PAY-2026-0068",
    "Licence payment",
    olivia,
    northstar,
    "invoice-lic-38",
    "contract-45",
    "project-aurora",
    1800000,
    "Partially Refunded",
    {
      capturedAt: "2026-07-10T10:00:00.000Z",
      refundedAt: "2026-07-20T10:00:00.000Z",
      cardLast4: "4242",
    },
  ),
  tx(
    "payment-59",
    "BM-PAY-2026-0059",
    "Full licence payment",
    daniel,
    independent,
    "invoice-lic-39",
    "contract-18",
    "project-independent",
    250000,
    "Refunded",
    {
      capturedAt: "2026-06-10T10:00:00.000Z",
      refundedAt: "2026-06-20T10:00:00.000Z",
      cardLast4: "4242",
    },
  ),
  tx(
    "credit-application-5",
    "BM-CR-APP-2026-0005",
    "Account credit",
    olivia,
    northstar,
    "invoice-lic-38",
    "contract-45",
    "project-aurora",
    400000,
    "Succeeded",
    {
      paymentMethodLabel: "Northstar account credit",
      source: "Credit Ledger",
      capturedAt: "2026-07-20T10:00:00.000Z",
    },
  ),
  tx(
    "payment-chargeback",
    "BM-PAY-2026-0048",
    "Licence payment",
    major,
    majorOrg,
    "invoice-lic-37",
    "contract-major-1",
    "project-major",
    100000,
    "Chargeback Simulation",
    {
      paymentMethodLabel: "Visa ending 1008",
      metadata: { disputeStatus: "Evidence Required" },
    },
  ),
  tx(
    "payment-71",
    "BM-PAY-2026-0071",
    "Full licence payment",
    olivia,
    northstar,
    "invoice-lic-40",
    "contract-26",
    "project-brand-film",
    1600000,
    "Succeeded",
    {
      quoteId: "quote-49",
      capturedAt: "2026-07-15T17:00:00.000Z",
      paymentMethodId: "pm-olivia-visa",
      cardLast4: "4242",
    },
  ),
];

export const DEFAULT_CREDITS = [
  {
    id: "credit-5",
    reference: "BM-CR-2026-0005",
    organizationId: "org-northstar",
    buyerId: "user-olivia",
    currency: "USD",
    originalAmount: 125000,
    remainingAmount: 125000,
    reason: "Previous project adjustment",
    sourceTransactionId: null,
    eligibleInvoiceTypes: [
      "Licence Deposit",
      "Licence Balance",
      "Full Licence Fee",
      "Asset Preparation",
      "Contract Amendment",
      "Licence Renewal",
    ],
    createdAt: "2026-07-10T00:00:00.000Z",
    expiresAt: "2026-12-31T23:59:59.000Z",
    status: "Active",
    createdBy: "Nadia Foster",
    usageHistory: [],
  },
];
export const DEFAULT_REFUNDS = [
  {
    id: "refund-15",
    reference: "BM-REF-2026-0015",
    originalTransactionId: "payment-68",
    invoiceId: "invoice-lic-38",
    buyerId: "user-olivia",
    organizationId: "org-northstar",
    currency: "USD",
    amount: 150000,
    status: "Initiated",
    reason: "Campaign scope adjustment requested",
    buyerMessage:
      "A partial refund request is awaiting finance and contract-impact review.",
    internalNote: "Prototype refund request; no provider action taken.",
    contractImpact: "Review required",
    licenceImpact: "No automatic change",
    deliveryImpact: "No automatic change",
    approvals: [
      { type: "Finance", status: "Pending", approver: null },
      { type: "Legal", status: "Pending", approver: null },
    ],
    createdAt: "2026-07-20T11:00:00.000Z",
    completedAt: null,
  },
  {
    id: "refund-14",
    reference: "BM-REF-2026-0014",
    originalTransactionId: "payment-68",
    invoiceId: "invoice-lic-38",
    buyerId: "user-olivia",
    organizationId: "org-northstar",
    currency: "USD",
    amount: 400000,
    status: "Completed",
    reason: "Usage reduced",
    buyerMessage: "Cinema usage was removed during the contract amendment.",
    internalNote: "Finance-approved partial refund.",
    contractImpact: "Amendment terms retained",
    licenceImpact: "Review amended scope",
    deliveryImpact: "No new delivery",
    approvals: [
      { type: "Finance", status: "Approved", approver: "Nadia Foster" },
    ],
    createdAt: "2026-07-20T09:00:00.000Z",
    completedAt: "2026-07-20T10:00:00.000Z",
  },
  {
    id: "refund-daniel",
    reference: "BM-REF-2026-0012",
    originalTransactionId: "payment-59",
    invoiceId: "invoice-lic-39",
    buyerId: "user-daniel",
    organizationId: "org-independent",
    currency: "USD",
    amount: 250000,
    status: "Completed",
    reason: "Contract cancelled",
    buyerMessage: "The agreement was cancelled before effectiveness.",
    internalNote: "No licence or delivery issued.",
    contractImpact: "Cancelled",
    licenceImpact: "No licence issued",
    deliveryImpact: "No delivery",
    approvals: [
      { type: "Finance", status: "Approved", approver: "Nadia Foster" },
    ],
    createdAt: "2026-06-20T09:00:00.000Z",
    completedAt: "2026-06-20T10:00:00.000Z",
  },
];
export const DEFAULT_RECEIPTS = [
  {
    id: "receipt-58",
    reference: "BM-RCPT-2026-0058",
    paymentId: "payment-61",
    paymentReference: "BM-PAY-2026-0061",
    invoiceId: "invoice-lic-31",
    invoiceReference: "BM-INV-LIC-2026-0031",
    buyerId: "user-olivia",
    buyer: "Olivia Bennett",
    organizationId: "org-northstar",
    organization: "Northstar Pictures",
    amount: 525000,
    currency: "USD",
    method: "Visa ending 4242",
    date: "2026-07-18T12:00:00.000Z",
    contractId: "contract-21",
    contractReference: "BM-C-2026-0021",
    project: "Premium Hotel Launch Film",
    track: "Golden Hours",
    tax: 0,
    taxRate: 0,
    taxLabel: "Tax review / not calculated",
    taxJurisdiction: "Buyer jurisdiction review required",
    taxRegistrationReference: "Not supplied in prototype",
    creditApplied: 0,
    remainingBalance: 525000,
    assetId: "asset-receipt-58",
    taxInvoice: false,
  },
];
export const DEFAULT_PAYMENT_STATE = {
  version: 1,
  invoices: DEFAULT_LICENSING_INVOICES,
  obligations: DEFAULT_OBLIGATIONS,
  transactions: DEFAULT_TRANSACTIONS,
  paymentAttempts: [],
  authenticationRecords: [],
  allocations: [
    {
      id: "allocation-61",
      transactionId: "payment-61",
      invoiceId: "invoice-lic-31",
      obligationId: "obligation-21-deposit",
      amount: 525000,
      date: "2026-07-18T12:00:00.000Z",
      actor: "Payment checkout",
      reconciliationStatus: "Allocated",
    },
    {
      id: "allocation-63",
      transactionId: "payment-63",
      invoiceId: "invoice-lic-33",
      obligationId: "obligation-invoice-lic-33",
      amount: 4200000,
      date: "2026-07-19T15:00:00.000Z",
      actor: "Nadia Foster",
      reconciliationStatus: "Reconciled",
    },
  ],
  bankTransfers: [
    {
      id: "bank-transfer-67",
      transactionId: "payment-67",
      invoiceId: "invoice-lic-37",
      buyerReference: "NST-PO-4417",
      transferDate: "2026-07-19T00:00:00.000Z",
      proofFile: "payment-proof-NST-PO-4417.pdf",
      status: "Proof Submitted",
      amount: 2800000,
      currency: "USD",
      notes: [],
    },
  ],
  reconciliations: [],
  credits: DEFAULT_CREDITS,
  refunds: DEFAULT_REFUNDS,
  receipts: DEFAULT_RECEIPTS,
  notifications: [],
  analyticsEvents: [],
  activity: [],
  internalNotes: [],
  lastNumbers: { payment: 71, invoice: 40, receipt: 58, refund: 14, credit: 5 },
};
