export const INGESTION_STORAGE_KEY = "beatmondo-track-ingestion-v1";
export const SELECTED_INGESTION_KEY = "beatmondo-selected-ingestion";
export const ACTIVE_DRAFT_KEY = "beatmondo-active-ingestion-draft";

export const INGESTION_STATUSES = {
  Draft: { stage: "Submission", owner: "Submitter", publicationEligible: false, searchEligible: false },
  "Upload In Progress": { stage: "File Upload", owner: "Submitter", publicationEligible: false, searchEligible: false },
  "Files Uploaded": { stage: "File Upload", owner: "Media Operations", publicationEligible: false, searchEligible: false },
  "Files Processing": { stage: "File Processing", owner: "Media Operations", publicationEligible: false, searchEligible: false },
  "Processing Failed": { stage: "File Processing", owner: "Media Operations", publicationEligible: false, searchEligible: false },
  "Metadata Incomplete": { stage: "Metadata", owner: "Submitter", publicationEligible: false, searchEligible: false },
  "Rights Information Required": { stage: "Rights Review", owner: "Submitter", publicationEligible: false, searchEligible: false },
  "Technical Review": { stage: "Technical Review", owner: "Media Operations", publicationEligible: false, searchEligible: false },
  "Catalog Review": { stage: "Creative Review", owner: "Catalog Team", publicationEligible: false, searchEligible: false },
  "Rights Review": { stage: "Rights Review", owner: "Rights Team", publicationEligible: false, searchEligible: false },
  "Revision Requested": { stage: "Submission", owner: "Submitter", publicationEligible: false, searchEligible: false },
  Resubmitted: { stage: "File Processing", owner: "Media Operations", publicationEligible: false, searchEligible: false },
  "Awaiting Approval": { stage: "Final Approval", owner: "Senior Approver", publicationEligible: false, searchEligible: true },
  Approved: { stage: "Final Approval", owner: "Catalog Team", publicationEligible: true, searchEligible: true },
  Scheduled: { stage: "Publication", owner: "Catalog Team", publicationEligible: true, searchEligible: true },
  Published: { stage: "Publication", owner: "Catalog Team", publicationEligible: true, searchEligible: true },
  Unpublished: { stage: "Publication", owner: "Catalog Team", publicationEligible: true, searchEligible: false },
  Rejected: { stage: "Final Approval", owner: "Catalog Team", publicationEligible: false, searchEligible: false },
  Withdrawn: { stage: "Submission", owner: "Submitter", publicationEligible: false, searchEligible: false },
  Archived: { stage: "Publication", owner: "Administrator", publicationEligible: false, searchEligible: false },
};

export const INGESTION_STAGES = ["Submission", "File Upload", "File Processing", "Metadata", "Creative Review", "Technical Review", "Rights Review", "Preview Preparation", "Search Preparation", "Final Approval", "Publication"];

export const INGESTION_TRANSITIONS = {
  Draft: ["Upload In Progress", "Withdrawn"],
  "Upload In Progress": ["Files Uploaded", "Draft", "Withdrawn"],
  "Files Uploaded": ["Files Processing", "Metadata Incomplete"],
  "Files Processing": ["Technical Review", "Processing Failed", "Metadata Incomplete"],
  "Processing Failed": ["Files Processing", "Revision Requested", "Archived"],
  "Metadata Incomplete": ["Technical Review", "Revision Requested", "Withdrawn"],
  "Rights Information Required": ["Rights Review", "Revision Requested", "Withdrawn"],
  "Technical Review": ["Catalog Review", "Revision Requested", "Processing Failed"],
  "Catalog Review": ["Rights Review", "Revision Requested", "Rejected"],
  "Rights Review": ["Awaiting Approval", "Revision Requested", "Rejected"],
  "Revision Requested": ["Resubmitted", "Withdrawn"],
  Resubmitted: ["Files Processing", "Metadata Incomplete"],
  "Awaiting Approval": ["Approved", "Revision Requested", "Rejected"],
  Approved: ["Scheduled", "Published"],
  Scheduled: ["Published", "Approved"],
  Published: ["Unpublished"],
  Unpublished: ["Published", "Archived"],
  Rejected: ["Archived"],
  Withdrawn: ["Archived"],
  Archived: ["Unpublished"],
};

export const REVIEWERS = [
  { id: "reviewer-jordan", name: "Jordan Lee", team: "Catalog Operations" },
  { id: "reviewer-amelia", name: "Amelia Grant", team: "Rights and Compliance" },
  { id: "reviewer-maya", name: "Maya Thompson", team: "Buyer and Licensing Review" },
  { id: "user-preston", name: "Preston Repenning", team: "Senior Approval" },
  { id: "reviewer-noah", name: "Noah Pierce", team: "Media Operations" },
];

export const FILE_SCENARIOS = {
  "Valid WAV": { fileName: "track-master-v1.wav", assetType: "WAV Master", extension: "wav", mimeType: "audio/wav", sizeMb: 82.4, duration: "3:12", sampleRate: 48000, bitDepth: 24, channels: 2, validation: "Valid", warnings: [] },
  "Valid MP3": { fileName: "track-preview-v1.mp3", assetType: "Preview MP3", extension: "mp3", mimeType: "audio/mpeg", sizeMb: 7.8, duration: "3:12", sampleRate: 44100, bitDepth: null, channels: 2, validation: "Valid", warnings: [] },
  "Valid artwork": { fileName: "track-artwork.webp", assetType: "Artwork", extension: "webp", mimeType: "image/webp", sizeMb: 2.4, width: 2400, height: 2400, validation: "Valid", warnings: [] },
  "Corrupted WAV": { fileName: "corrupted-master.wav", assetType: "WAV Master", extension: "wav", mimeType: "audio/wav", sizeMb: 0.4, duration: null, sampleRate: null, bitDepth: null, channels: null, validation: "Invalid", error: "Invalid or unreadable audio header" },
  "Oversized file": { fileName: "oversized-master.wav", assetType: "WAV Master", extension: "wav", mimeType: "audio/wav", sizeMb: 3200, duration: "7:44", sampleRate: 96000, bitDepth: 24, channels: 2, validation: "Invalid", error: "File exceeds the 2 GB prototype limit" },
  "Unsupported FLAC": { fileName: "master.flac", assetType: "WAV Master", extension: "flac", mimeType: "audio/flac", sizeMb: 42, validation: "Invalid", error: "Master audio must be WAV or AIFF" },
  "Mono master warning": { fileName: "mono-master.wav", assetType: "WAV Master", extension: "wav", mimeType: "audio/wav", sizeMb: 58, duration: "2:49", sampleRate: 48000, bitDepth: 24, channels: 1, validation: "Warning", warnings: ["Mono source requires technical approval"] },
  "16-bit master warning": { fileName: "16-bit-master.wav", assetType: "WAV Master", extension: "wav", mimeType: "audio/wav", sizeMb: 48, duration: "2:49", sampleRate: 44100, bitDepth: 16, channels: 2, validation: "Warning", warnings: ["16-bit source is accepted but 24-bit is preferred"] },
  "Low-resolution artwork": { fileName: "small-artwork.jpg", assetType: "Artwork", extension: "jpg", mimeType: "image/jpeg", sizeMb: 0.3, width: 800, height: 800, validation: "Warning", warnings: ["Artwork is below the preferred 1600 × 1600 resolution"] },
  "Incomplete stems ZIP": { fileName: "stems-incomplete.zip", assetType: "Stems ZIP", extension: "zip", mimeType: "application/zip", sizeMb: 640, validation: "Warning", warnings: ["Stems archive is missing expected instrument groups"] },
};

const baseChecklist = { fileOpens: false, formatAcceptable: false, durationValid: false, sampleRateAcceptable: false, bitDepthAcceptable: false, channelsApproved: false, noClipping: false, noUnintendedSilence: false, noCorruption: false, metadataMatches: false, previewSourceSelected: false, stemsReadable: false, filenameAcceptable: false };
const catalogChecklist = { artistConfirmed: false, titleConfirmed: false, catalogFit: false, productionQuality: false, metadataQuality: false, genre: false, mood: false, usage: false, artwork: false, lyrics: false, explicitState: false, similarTracks: false, editorialDescription: false, buyerRelevance: false, duplicateCheck: false };
const activity = (action, description, actor = "System") => ({ id: `activity-${Math.random().toString(36).slice(2)}`, action, description, actor, timestamp: "2026-07-16T10:00:00.000Z", visibility: "Internal", source: "Track Ingestion" });
const asset = (id, assetType, fileName, status = "Approved", overrides = {}) => ({ id, assetType, fileName, fileType: fileName.split(".").pop().toUpperCase(), fileSize: "82.4 MB", duration: "3:12", sampleRate: "48 kHz", bitDepth: "24-bit", channels: "Stereo", uploadStatus: "Uploaded", processingStatus: "Completed", qualityStatus: status, storageReference: `mock://private/${id}`, version: 1, checksum: `demo-${id}-checksum`, current: true, uploadedAt: "2026-06-18T10:00:00.000Z", uploadedBy: "Marcus Hale", versions: [], ...overrides });
const jobs = (prefix, processing = false, failed = false) => ["Malware scan simulation", "Audio validation", "Metadata extraction", "Waveform generation", "Preview conversion", "Watermark preparation", "Loudness analysis", "Artwork optimization", "Stems validation", "Search-document preparation"].map((jobType, index) => ({ id: `${prefix}-job-${index + 1}`, jobType, status: failed && index === 1 ? "Failed" : processing && index >= 3 ? (index === 3 ? "Processing" : "Queued") : "Completed", progress: failed && index === 1 ? 18 : processing && index === 3 ? 62 : processing && index > 3 ? 0 : 100, failureCode: failed && index === 1 ? "AUDIO_HEADER_INVALID" : null, failureMessage: failed && index === 1 ? "Invalid or unreadable audio header" : null, retryCount: 0, result: index === 3 ? "Fixed-value prototype waveform" : "Demo job result" }));

export const DEFAULT_INGESTION_RECORDS = [
  { id: "ingestion-1", reference: "BM-ING-2026-0001", trackId: 1, artistId: "artist-lennox", trackTitle: "Golden Hours", artistName: "Lennox", submissionId: "submission-1", source: "Internal Catalog", submittedBy: "Jordan Lee", submittedByUserId: "reviewer-jordan", organizationId: "org-beatmondo", status: "Published", priority: "Standard", currentStage: "Publication", assignedCatalogReviewer: "reviewer-jordan", assignedRightsReviewer: "reviewer-amelia", assignedAudioReviewer: "reviewer-noah", metadata: { title: "Golden Hours", artist: "Lennox", primaryGenre: "Cinematic", moods: ["Reflective", "Warm"], duration: "2:34", vocalType: "Instrumental", intendedUsage: ["Feature Film", "Luxury"], shortDescription: "Warm cinematic restraint for premium storytelling.", explicit: "Clean", bpm: 72, key: "C# Major", instrumentation: "Felt piano, bowed guitar, analog pads", completeness: 100 }, assets: [asset("asset-1-master", "WAV Master", "golden-hours-master.wav"), asset("asset-1-preview", "Preview MP3", "golden-hours-preview.mp3"), asset("asset-1-stems", "Stems ZIP", "golden-hours-stems.zip"), asset("asset-1-art", "Artwork", "golden-hours-artwork.webp")], processingJobs: jobs("ing1"), qualityControl: { status: "Passed", checklist: Object.fromEntries(Object.keys(baseChecklist).map((key) => [key, true])), warnings: [] }, catalogReview: { status: "Approved", checklist: Object.fromEntries(Object.keys(catalogChecklist).map((key) => [key, true])), decision: "Approve" }, rightsReadiness: { status: "Fully Verified", blockers: [], rightsRecordId: "rights-1" }, searchReadiness: { status: "Indexed", missing: [] }, artwork: { status: "Approved", fileName: "golden-hours-artwork.webp", width: 2400, height: 2400 }, lyrics: { status: "Instrumental", text: "" }, deliveryAssets: { master: "Approved", instrumental: "Approved", clean: "Not applicable", stems: "Approved", acapella: "Not available", alternateMix: "Approved" }, contributors: [], declarations: { authorized: true, accurate: true, disclosed: true, reviewAllowed: true, noGuarantee: true, additionalInfo: true, privateUntilApproved: true }, revisionRequests: [], restrictions: [], internalNotes: [], artistMessages: [], activity: [activity("Track published", "Published after catalog, technical, rights, and search approval.", "Jordan Lee")], createdAt: "2026-06-05T09:00:00.000Z", updatedAt: "2026-06-22T14:00:00.000Z", submittedAt: "2026-06-08T09:00:00.000Z", approvedAt: "2026-06-21T09:00:00.000Z", publishedAt: "2026-06-22T14:00:00.000Z" },
  { id: "ingestion-2", reference: "BM-ING-2026-0002", trackId: 16, artistId: "artist-arco", trackTitle: "Northern Lines", artistName: "Arco North", source: "Artist Portal", submittedBy: "Jon Arco", submittedByUserId: "user-arco", organizationId: "org-arco", status: "Files Processing", priority: "High", currentStage: "File Processing", assignedCatalogReviewer: "reviewer-jordan", assignedRightsReviewer: "reviewer-amelia", assignedAudioReviewer: "reviewer-noah", metadata: { title: "Northern Lines", artist: "Arco North", primaryGenre: "Indie Rock", moods: ["Uplifting", "Hopeful"], duration: "2:42", vocalType: "Instrumental", intendedUsage: ["Automotive", "Advertising"], shortDescription: "Driving guitar energy for open-road brand stories.", explicit: "Clean", bpm: 122, completeness: 92 }, assets: [asset("asset-2-master", "WAV Master", "northern-lines-master.wav", "Under Review"), asset("asset-2-art", "Artwork", "northern-lines-artwork.jpg", "Under Review")], processingJobs: jobs("ing2", true), qualityControl: { status: "In Review", checklist: baseChecklist, warnings: [] }, catalogReview: { status: "Not Started", checklist: catalogChecklist }, rightsReadiness: { status: "Partially Verified", blockers: ["Publishing confirmation remains under review"] }, searchReadiness: { status: "Pending", missing: [] }, artwork: { status: "Uploaded", fileName: "northern-lines-artwork.jpg", width: 2000, height: 2000 }, lyrics: { status: "Instrumental", text: "" }, deliveryAssets: { master: "Under review", instrumental: "Provided", clean: "Not applicable", stems: "Can be prepared" }, contributors: [], declarations: { authorized: true, accurate: true, disclosed: true }, revisionRequests: [], restrictions: [], internalNotes: [], artistMessages: [], activity: [activity("Processing started", "Waveform processing is active.")], createdAt: "2026-07-12T09:00:00.000Z", updatedAt: "2026-07-16T08:30:00.000Z", submittedAt: "2026-07-13T09:00:00.000Z" },
  { id: "ingestion-3", reference: "BM-ING-2026-0003", trackId: 18, artistId: "artist-soren", trackTitle: "Quiet Machines", artistName: "Soren", source: "Artist Portal", submittedBy: "Soren Ivers", submittedByUserId: "user-soren", organizationId: "org-soren", status: "Metadata Incomplete", priority: "Standard", currentStage: "Metadata", assignedCatalogReviewer: "reviewer-jordan", assignedRightsReviewer: "reviewer-amelia", assignedAudioReviewer: "reviewer-noah", metadata: { title: "Quiet Machines", artist: "Soren", primaryGenre: "", moods: ["Mysterious"], duration: "2:18", vocalType: "Instrumental", intendedUsage: ["Technology"], shortDescription: "", explicit: "Clean", bpm: "", completeness: 58 }, assets: [asset("asset-3-master", "WAV Master", "quiet-machines-master.wav")], processingJobs: jobs("ing3"), qualityControl: { status: "Passed", checklist: Object.fromEntries(Object.keys(baseChecklist).map((key) => [key, true])), warnings: [] }, catalogReview: { status: "Not Started", checklist: catalogChecklist }, rightsReadiness: { status: "Documents Requested", blockers: ["Writer contribution confirmation required"] }, searchReadiness: { status: "Not Created", missing: ["Primary genre", "Second mood", "Short description"] }, artwork: { status: "Not Uploaded" }, lyrics: { status: "Instrumental", text: "" }, deliveryAssets: { master: "Approved", instrumental: "Provided" }, contributors: [], declarations: {}, revisionRequests: [], restrictions: [], internalNotes: [], artistMessages: [], activity: [activity("Metadata blocker", "Required discovery metadata remains incomplete.")], createdAt: "2026-07-11T09:00:00.000Z", updatedAt: "2026-07-15T08:30:00.000Z" },
  { id: "ingestion-4", reference: "BM-ING-2026-0004", trackId: 19, artistId: "artist-jade", trackTitle: "Velvet Warning", artistName: "Jade Montague", source: "Artist Portal", submittedBy: "Jade Montague", submittedByUserId: "user-jade", organizationId: "org-jade", status: "Revision Requested", priority: "Urgent", currentStage: "Submission", assignedCatalogReviewer: "reviewer-jordan", assignedRightsReviewer: "reviewer-amelia", assignedAudioReviewer: "reviewer-noah", metadata: { title: "Velvet Warning", artist: "Jade Montague", primaryGenre: "R&B", moods: ["Dark", "Sensual"], duration: "2:55", vocalType: "Female Vocal", intendedUsage: ["Luxury", "Advertising"], shortDescription: "Intimate nocturnal R&B for premium campaigns.", explicit: "Clean", bpm: 88, completeness: 94 }, assets: [asset("asset-4-master", "WAV Master", "velvet-warning-master.wav"), asset("asset-4-art", "Artwork", "velvet-warning-artwork-small.jpg", "Revision Requested", { width: 800, height: 800 })], processingJobs: jobs("ing4"), qualityControl: { status: "Passed", checklist: Object.fromEntries(Object.keys(baseChecklist).map((key) => [key, true])), warnings: [] }, catalogReview: { status: "Revision Requested", checklist: catalogChecklist, decision: "Request Revision" }, rightsReadiness: { status: "Restricted", blockers: ["Sample declaration incomplete"] }, searchReadiness: { status: "Ready", missing: [] }, artwork: { status: "Revision Requested", fileName: "velvet-warning-artwork-small.jpg", width: 800, height: 800 }, lyrics: { status: "Approved", text: "Lyrics supplied in the protected submission workspace." }, deliveryAssets: { master: "Approved", instrumental: "Not available", clean: "Missing", stems: "Under review" }, contributors: [], declarations: { authorized: true, accurate: true }, revisionRequests: [{ id: "revision-1", title: "Complete delivery and declaration package", requestedChanges: "Upload higher-resolution artwork, add a clean version, and clarify sample use.", affectedSections: ["Artwork and Lyrics", "Delivery Assets", "Rights Declaration"], requiredFiles: ["Artwork", "Clean version"], artistMessage: "Please replace the artwork, add a clean version, and complete the sample declaration.", internalNotes: "Required before final approval.", dueDate: "2026-07-28", priority: "Urgent", assignedRespondent: "Jade Montague", status: "Open", createdAt: "2026-07-14T10:00:00.000Z" }], restrictions: ["Manual licence review"], internalNotes: [], artistMessages: [], activity: [activity("Revision requested", "Artwork, clean version, and sample declaration require updates.", "Jordan Lee")], createdAt: "2026-07-02T09:00:00.000Z", updatedAt: "2026-07-14T10:00:00.000Z" },
  { id: "ingestion-5", reference: "BM-ING-2026-0005", trackId: 20, artistId: "artist-vespera", trackTitle: "The Long Arrival", artistName: "Vespera", source: "Internal Catalog", submittedBy: "Jordan Lee", submittedByUserId: "reviewer-jordan", organizationId: "org-beatmondo", status: "Processing Failed", priority: "Critical", currentStage: "File Processing", assignedCatalogReviewer: "reviewer-jordan", assignedRightsReviewer: "reviewer-amelia", assignedAudioReviewer: "reviewer-noah", metadata: { title: "The Long Arrival", artist: "Vespera", primaryGenre: "Orchestral", moods: ["Emotional", "Melancholic"], duration: "4:36", vocalType: "Instrumental", intendedUsage: ["Feature Film", "Documentary"], shortDescription: "Archive orchestral movement for patient emotional scenes.", explicit: "Clean", bpm: 66, completeness: 96 }, assets: [asset("asset-5-master", "WAV Master", "long-arrival-corrupted.wav", "Failed", { processingStatus: "Failed" })], processingJobs: jobs("ing5", false, true), qualityControl: { status: "Failed", checklist: baseChecklist, warnings: ["Invalid or unreadable audio header"] }, catalogReview: { status: "Not Started", checklist: catalogChecklist }, rightsReadiness: { status: "Disputed", blockers: ["Active rights dispute blocks publication"] }, searchReadiness: { status: "Disabled", missing: [] }, artwork: { status: "Uploaded", fileName: "long-arrival-artwork.jpg", width: 2200, height: 2200 }, lyrics: { status: "Instrumental", text: "" }, deliveryAssets: { master: "Failed", instrumental: "Not available" }, contributors: [], declarations: {}, revisionRequests: [], restrictions: [], internalNotes: [], artistMessages: [], activity: [activity("Processing failed", "The master has an invalid or unreadable audio header.", "Noah Pierce")], createdAt: "2026-07-09T09:00:00.000Z", updatedAt: "2026-07-16T07:30:00.000Z" },
  { id: "ingestion-6", reference: "BM-ING-2026-0006", trackId: 17, artistId: "artist-hollow-skies", trackTitle: "Heavy Weather", artistName: "Hollow Skies", source: "Artist Portal", submittedBy: "Nate Calder", submittedByUserId: "user-hollow", organizationId: "org-hollow", status: "Awaiting Approval", priority: "High", currentStage: "Final Approval", assignedCatalogReviewer: "reviewer-jordan", assignedRightsReviewer: "reviewer-amelia", assignedAudioReviewer: "reviewer-noah", metadata: { title: "Heavy Weather", artist: "Hollow Skies", primaryGenre: "Alternative", moods: ["Triumphant", "Energetic"], duration: "2:26", vocalType: "Female Vocal", intendedUsage: ["Trailer", "Sports"], shortDescription: "Explosive alternative lift for trailers and sports campaigns.", explicit: "Clean", bpm: 138, completeness: 100 }, assets: [asset("asset-6-master", "WAV Master", "heavy-weather-master.wav"), asset("asset-6-preview", "Preview MP3", "heavy-weather-preview.mp3"), asset("asset-6-art", "Artwork", "heavy-weather-artwork.webp")], processingJobs: jobs("ing6"), qualityControl: { status: "Passed", checklist: Object.fromEntries(Object.keys(baseChecklist).map((key) => [key, true])), warnings: [] }, catalogReview: { status: "Approved", checklist: Object.fromEntries(Object.keys(catalogChecklist).map((key) => [key, true])), decision: "Approve" }, rightsReadiness: { status: "Manual Review Required", blockers: [], warnings: ["Per-project approval remains required"] }, searchReadiness: { status: "Ready", missing: [] }, artwork: { status: "Approved", fileName: "heavy-weather-artwork.webp", width: 2400, height: 2400 }, lyrics: { status: "Approved", text: "Lyrics supplied and reviewed." }, deliveryAssets: { master: "Approved", instrumental: "Provided", clean: "Provided", stems: "Provided" }, contributors: [], declarations: { authorized: true, accurate: true, disclosed: true, reviewAllowed: true, noGuarantee: true, additionalInfo: true, privateUntilApproved: true }, revisionRequests: [], restrictions: ["Manual licence review"], internalNotes: [], artistMessages: [], activity: [activity("Final approval required", "Technical, catalog, and search reviews are ready.")], createdAt: "2026-06-28T09:00:00.000Z", updatedAt: "2026-07-16T09:30:00.000Z", submittedAt: "2026-07-01T09:00:00.000Z" },
  { id: "ingestion-7", reference: "BM-ING-2026-0007", trackId: null, artistId: "artist-applicant", trackTitle: "City Heat Demo", artistName: "New Applicant", source: "Artist Portal", submittedBy: "New Applicant", submittedByUserId: "user-applicant", organizationId: "org-applicant", status: "Rejected", priority: "Standard", currentStage: "Final Approval", assignedCatalogReviewer: "reviewer-jordan", assignedRightsReviewer: "reviewer-amelia", assignedAudioReviewer: "reviewer-noah", metadata: { title: "City Heat Demo", artist: "New Applicant", primaryGenre: "Electronic", moods: ["Energetic", "Urban"], duration: "2:08", vocalType: "Instrumental", intendedUsage: ["Advertising"], shortDescription: "Applicant demo retained for review history.", explicit: "Clean", completeness: 76 }, assets: [asset("asset-7-master", "WAV Master", "city-heat-demo.wav", "Rejected")], processingJobs: jobs("ing7"), qualityControl: { status: "Failed", checklist: baseChecklist, warnings: ["Poor source-audio quality"] }, catalogReview: { status: "Rejected", checklist: catalogChecklist, decision: "Reject" }, rightsReadiness: { status: "Documents Requested", blockers: ["Incomplete ownership evidence"] }, searchReadiness: { status: "Not Created", missing: [] }, artwork: { status: "Not Uploaded" }, lyrics: { status: "Instrumental", text: "" }, deliveryAssets: { master: "Rejected" }, contributors: [], declarations: {}, revisionRequests: [], restrictions: [], internalNotes: [{ id: "note-7", author: "Jordan Lee", content: "Poor source quality, incomplete ownership evidence, and catalog fit not approved.", visibility: "Internal", timestamp: "2026-07-13T10:00:00.000Z" }], artistMessages: [{ id: "message-7", content: "The submission does not currently meet beatmondo’s catalog and delivery requirements.", timestamp: "2026-07-13T10:00:00.000Z" }], activity: [activity("Submission rejected", "Record retained for audit history.", "Jordan Lee")], createdAt: "2026-07-08T09:00:00.000Z", updatedAt: "2026-07-13T10:00:00.000Z" },
  { id: "ingestion-8", reference: "BM-ING-2026-0008", trackId: 15, artistId: "artist-smyrk", trackTitle: "The End of Jason Todd", artistName: "The SMYRK", source: "Artist Portal", submittedBy: "Marcus Hale", submittedByUserId: "user-marcus", organizationId: "org-smyrk", status: "Rights Information Required", priority: "High", currentStage: "Rights Review", assignedCatalogReviewer: "reviewer-jordan", assignedRightsReviewer: "reviewer-amelia", assignedAudioReviewer: "reviewer-noah", metadata: { title: "The End of Jason Todd", artist: "The SMYRK", primaryGenre: "Alternative", moods: ["Intense", "Dark"], duration: "2:49", vocalType: "Male Vocal", intendedUsage: ["Feature Film", "Television"], shortDescription: "Cinematic alternative rock with sharp dynamic turns.", explicit: "Undeclared", bpm: 132, completeness: 78 }, assets: [asset("asset-8-master", "WAV Master", "the-end-of-jason-todd-protected-source.wav", "Locked", { storageReference: "mock://protected/source-master", processingStatus: "Private Review" }), asset("asset-8-preview", "Preview AAC", "the-end-of-jason-todd-preview.m4a", "Approved")], processingJobs: jobs("ing8"), qualityControl: { status: "Passed with Warnings", checklist: { ...baseChecklist, fileOpens: true, formatAcceptable: true, durationValid: true, sampleRateAcceptable: true, bitDepthAcceptable: true, channelsApproved: true, noCorruption: true, previewSourceSelected: true, filenameAcceptable: true }, warnings: ["Exact session and ownership documentation remains pending"] }, catalogReview: { status: "In Review", checklist: catalogChecklist }, rightsReadiness: { status: "Draft declaration", blockers: ["Master ownership documentation required", "Writer and publisher information required", "Licensing authority not confirmed"], rightsRecordId: "rights-15" }, searchReadiness: { status: "Hidden", missing: ["Rights eligibility"] }, artwork: { status: "Approved", fileName: "d-hoppin-card.webp", width: 1600, height: 1600 }, lyrics: { status: "Unavailable", text: "" }, deliveryAssets: { master: "Locked", instrumental: "Not declared", clean: "Not declared", stems: "Not declared" }, contributors: [], declarations: { authorized: false, accurate: false, disclosed: false }, revisionRequests: [], restrictions: ["Protected preview only", "Original master locked"], internalNotes: [], artistMessages: [{ id: "message-8", content: "Please provide ownership and publishing documentation. The original protected source master remains locked.", timestamp: "2026-07-15T10:00:00.000Z" }], activity: [activity("Rights information requested", "Ownership and publishing evidence is required.", "Amelia Grant")], createdAt: "2026-06-20T09:00:00.000Z", updatedAt: "2026-07-15T10:00:00.000Z" },
];

export const DEFAULT_INGESTION_STATE = { version: 1, records: DEFAULT_INGESTION_RECORDS, drafts: [], notifications: [], demoMessages: [], globalActivity: [], cms: { introduction: "Submit protected music for structured human review.", acceptedFormats: "WAV or AIFF masters; MP3, AAC, or M4A previews; ZIP stems; JPG, PNG, or WEBP artwork.", audioGuidance: "24-bit stereo at 44.1 or 48 kHz is preferred.", artworkRequirements: "Square artwork of at least 1600 × 1600 is preferred.", rightsCopy: "Declarations begin a rights review; they do not verify ownership.", termsVersion: "INGESTION-DEMO-2026.1", support: "catalog@beatmondo.example" } };
