// DEMO ONLY — remove before production release.
// Plaintext passwords are present solely so the frontend prototype can demonstrate
// authentication. Production credentials must be hashed and verified server-side.

export const AUTH_STORAGE_KEY = "beatmondo-auth-demo-v1";
export const AUTH_SESSION_KEY = "beatmondo-auth-session-v1";
export const AUTH_PENDING_MFA_KEY = "beatmondo-auth-pending-mfa-v1";

const BUYER_LICENCE_PERMISSIONS = [
  "licences.view_own",
  "licences.view_document_own",
  "licences.view_delivery_authorization_own",
  "licences.request_amendment_own",
  "licences.request_renewal_own",
];
const LICENCE_OPERATIONS_PERMISSIONS = [
  "licences.view",
  "licences.create",
  "licences.request_approval",
  "licences.approve_licensing",
  "licences.approve_rights",
  "licences.approve_finance",
  "licences.generate",
  "licences.issue",
  "licences.manage_status",
  "licences.view_internal_notes",
  "licences.view_analytics",
];
const BUYER_DELIVERY_PERMISSIONS = [
  "deliveries.view_own",
  "deliveries.request_extension_own",
  "deliveries.report_issue_own",
  "downloads.create_session",
  "downloads.complete",
  "downloads.retry",
  "manifests.view_own",
];
const DELIVERY_OPERATIONS_PERMISSIONS = [
  "deliveries.view",
  "deliveries.create",
  "deliveries.calculate_readiness",
  "deliveries.edit",
  "deliveries.approve",
  "deliveries.activate",
  "deliveries.manage_assets",
  "deliveries.manage_users",
  "deliveries.manage_expiry",
  "deliveries.manage_download_limits",
  "deliveries.replace_assets",
  "deliveries.suspend",
  "deliveries.restore",
  "deliveries.revoke",
  "deliveries.confirm_payment",
  "deliveries.view_download_history",
  "deliveries.view_internal_notes",
  "deliveries.view_analytics",
  "downloads.create_session",
  "downloads.complete",
  "downloads.retry",
  "downloads.revoke_session",
  "downloads.override_limit",
  "manifests.generate",
];
const BUYER_TEMPORARY_ACCESS_PERMISSIONS = [
  "expiring_access.generate_own",
  "expiring_access.refresh",
  "expiring_access.extend",
  "temporary_stream.generate",
  "temporary_download.generate",
  "temporary_document.generate",
];
const EXPIRING_ACCESS_OPERATIONS_PERMISSIONS = [
  "expiring_access.view",
  "expiring_access.generate",
  "expiring_access.refresh",
  "expiring_access.extend",
  "expiring_access.revoke",
  "expiring_access.bulk_revoke",
  "expiring_access.manage_policies",
  "expiring_access.view_attempts",
  "expiring_access.view_security",
  "expiring_access.resolve_security",
  "expiring_access.override",
  "temporary_upload.generate",
  "temporary_upload.revoke",
  "temporary_download.generate",
  "temporary_stream.generate",
  "temporary_document.generate",
];
const AUDIT_OPERATIONS_PERMISSIONS = [
  "audit.view",
  "audit.view_internal",
  "audit.review",
  "audit.assign",
  "audit.export",
  "audit.view_integrity",
  "audit.view_analytics",
];
const AUDIT_ADMIN_PERMISSIONS = [
  ...AUDIT_OPERATIONS_PERMISSIONS,
  "audit.view_finance",
  "audit.view_rights",
  "audit.view_legal",
  "audit.view_security",
  "audit.export_restricted",
  "audit.manage_retention",
  "audit.manage_health",
];
const EMAIL_OPERATIONS_PERMISSIONS = [
  "email.view",
  "email.view_internal",
  "email.view_confidential",
  "email.create_manual",
  "email.cancel",
  "email.retry",
  "email.view_failures",
  "email.view_analytics",
];
const EMAIL_ADMIN_PERMISSIONS = [
  ...EMAIL_OPERATIONS_PERMISSIONS,
  "email.process_queue",
  "email.pause_queue",
  "email.manage_templates",
  "email.approve_templates",
  "email.manage_triggers",
  "email.manage_sender_profiles",
  "email.manage_preferences",
  "email.override",
];

export const ROLE_PERMISSIONS = {
  discovery_buyer: [
    "email.view_own",
    "audit.view_own",
    ...BUYER_TEMPORARY_ACCESS_PERMISSIONS,
    ...BUYER_LICENCE_PERMISSIONS,
    ...BUYER_DELIVERY_PERMISSIONS,
    "payments.view_own",
    "payments.process_own",
    "payments.retry_own",
    "payments.submit_bank_transfer_own",
    "invoices.view_licensing_own",
    "receipts.view_own",
    "contracts.view_own",
    "contracts.request_changes_own",
    "signatures.sign",
    "quotes.view_own",
    "quotes.respond_own",
    "previews.play_public",
    "storage.view_public",
    "storage.view_previews",
    "stream.preview",
    "search.public",
    "search.discovery",
    "search.saved.manage",
    "catalog.view",
    "content.view",
    "profile.manage",
    "security.manage",
    "membership.view",
    "buyers.verification.own",
    "privacy.notices.view",
    "privacy.requests.create",
    "privacy.consents.view",
  ],
  professional_buyer: [
    "email.view_own",
    "audit.view_own",
    ...BUYER_TEMPORARY_ACCESS_PERMISSIONS,
    ...BUYER_LICENCE_PERMISSIONS,
    ...BUYER_DELIVERY_PERMISSIONS,
    "payments.view_own",
    "payments.process_own",
    "payments.retry_own",
    "payments.submit_bank_transfer_own",
    "invoices.view_licensing_own",
    "receipts.view_own",
    "contracts.view_own",
    "contracts.request_changes_own",
    "signatures.sign",
    "quotes.view_own",
    "quotes.respond_own",
    "previews.play_public",
    "previews.play_professional",
    "storage.view_public",
    "storage.view_previews",
    "stream.preview",
    "search.public",
    "search.discovery",
    "search.professional",
    "search.projects",
    "search.saved.manage",
    "catalog.view",
    "content.view",
    "projects.view",
    "quotes.view",
    "contracts.view",
    "payments.view",
    "delivery.view",
    "profile.manage",
    "security.manage",
    "membership.view",
    "buyers.verification.own",
    "privacy.notices.view",
    "privacy.requests.create",
    "privacy.consents.view",
  ],
  vip_buyer: [
    "email.view_own",
    "audit.view_own",
    ...BUYER_TEMPORARY_ACCESS_PERMISSIONS,
    ...BUYER_LICENCE_PERMISSIONS,
    ...BUYER_DELIVERY_PERMISSIONS,
    "payments.view_own",
    "payments.process_own",
    "payments.retry_own",
    "payments.submit_bank_transfer_own",
    "invoices.view_licensing_own",
    "receipts.view_own",
    "contracts.view_own",
    "contracts.request_changes_own",
    "signatures.sign",
    "quotes.view_own",
    "quotes.respond_own",
    "previews.play_public",
    "previews.play_professional",
    "previews.play_vip",
    "previews.private.view",
    "storage.view_public",
    "storage.view_previews",
    "stream.preview",
    "search.public",
    "search.discovery",
    "search.professional",
    "search.vip",
    "search.projects",
    "search.saved.manage",
    "catalog.view",
    "catalog.vip",
    "content.view",
    "projects.view",
    "quotes.view",
    "contracts.view",
    "payments.view",
    "delivery.view",
    "delivery.vip",
    "concierge.request",
    "profile.manage",
    "security.manage",
    "membership.view",
    "buyers.verification.own",
    "privacy.notices.view",
    "privacy.requests.create",
    "privacy.consents.view",
  ],
  artist: [
    "email.view_own",
    "audit.view_own",
    "expiring_access.generate_own",
    "expiring_access.refresh",
    "temporary_upload.generate",
    "previews.own.view",
    "previews.own.request_changes",
    "storage.view_public",
    "storage.view_previews",
    "stream.preview",
    "ingestion.view",
    "ingestion.create",
    "ingestion.edit_metadata",
    "ingestion.upload_assets",
    "ingestion.replace_assets",
    "search.public",
    "search.discovery",
    "catalog.own.view",
    "submissions.view",
    "submissions.create",
    "rights.own.view",
    "documents.own.view",
    "rights.documents.own.upload",
    "rights.corrections.own.submit",
    "profile.manage",
    "privacy.notices.view",
    "privacy.requests.create",
    "privacy.consents.view",
    "security.manage",
    "content.view",
  ],
  licensing_manager: [
    ...EMAIL_OPERATIONS_PERMISSIONS,
    ...AUDIT_OPERATIONS_PERMISSIONS,
    "audit.view_rights",
    "audit.view_legal",
    "expiring_access.view",
    "expiring_access.generate",
    "expiring_access.refresh",
    "expiring_access.revoke",
    "expiring_access.view_attempts",
    "expiring_access.view_security",
    "temporary_document.generate",
    "deliveries.view",
    "deliveries.calculate_readiness",
    "deliveries.suspend",
    "deliveries.restore",
    "deliveries.view_download_history",
    "deliveries.view_internal_notes",
    "licences.view",
    "licences.approve_rights",
    "licences.view_internal_notes",
    "payments.view",
    "payments.create",
    "payments.allocate",
    "invoices.view_licensing",
    "invoices.create_licensing",
    "receipts.view",
    "contracts.create",
    "contracts.generate",
    "contracts.edit",
    "contracts.request_review",
    "contracts.approve_rights",
    "contracts.send",
    "contracts.manage_signers",
    "contracts.resend_signature",
    "contracts.replace_signer",
    "contracts.cancel",
    "contracts.create_amendment",
    "contracts.create_renewal",
    "contracts.view_internal_notes",
    "contracts.view_analytics",
    "signatures.view_records",
    "quotes.create",
    "quotes.edit",
    "quotes.request_approval",
    "quotes.approve_rights",
    "quotes.send",
    "quotes.negotiate",
    "previews.view",
    "previews.create",
    "previews.configure",
    "previews.generate",
    "previews.review",
    "previews.regenerate",
    "previews.revoke",
    "previews.manage_buyer_specific",
    "previews.view_sessions",
    "previews.revoke_sessions",
    "previews.view_analytics",
    "storage.view",
    "storage.view_previews",
    "storage.view_documents",
    "storage.view_access_logs",
    "stream.internal",
    "ingestion.view",
    "ingestion.request_revision",
    "ingestion.view_internal_notes",
    "search.internal",
    "search.rights",
    "search.buyers",
    "search.projects",
    "search.analytics.view",
    "catalog.view",
    "buyers.view",
    "buyers.verify",
    "projects.view",
    "quotes.view",
    "quotes.manage",
    "contracts.view",
    "contracts.manage",
    "payments.view",
    "delivery.view",
    "delivery.manage",
    "analytics.view",
    "audit.view",
    "profile.manage",
    "security.manage",
    "buyers.assign",
    "buyers.request_information",
    "buyers.view_documents",
    "buyers.review_documents",
    "buyers.manage_internal_notes",
    "memberships.view",
    "billing.view",
    "billing.view_invoices",
    "rights.view",
    "rights.request_review",
  ],
  catalog_manager: [
    ...EMAIL_OPERATIONS_PERMISSIONS,
    ...AUDIT_OPERATIONS_PERMISSIONS,
    "audit.view_rights",
    ...EXPIRING_ACCESS_OPERATIONS_PERMISSIONS,
    ...DELIVERY_OPERATIONS_PERMISSIONS,
    ...LICENCE_OPERATIONS_PERMISSIONS,
    "payments.view",
    "payments.create",
    "payments.allocate",
    "invoices.view_licensing",
    "invoices.create_licensing",
    "receipts.view",
    "contracts.view",
    "contracts.create",
    "contracts.generate",
    "contracts.edit",
    "contracts.request_review",
    "contracts.approve_licensing",
    "contracts.send",
    "contracts.manage_signers",
    "contracts.resend_signature",
    "contracts.replace_signer",
    "contracts.cancel",
    "contracts.create_amendment",
    "contracts.create_renewal",
    "contracts.view_internal_notes",
    "contracts.view_analytics",
    "signatures.view_records",
    "quotes.view",
    "quotes.create",
    "quotes.edit",
    "quotes.request_approval",
    "quotes.approve_licensing",
    "quotes.send",
    "quotes.negotiate",
    "quotes.analytics",
    "previews.view",
    "previews.create",
    "previews.configure",
    "previews.generate",
    "previews.review",
    "previews.approve",
    "previews.reject",
    "previews.regenerate",
    "previews.revoke",
    "previews.view_sessions",
    "previews.view_analytics",
    "storage.view",
    "storage.view_public",
    "storage.view_previews",
    "storage.manage_assets",
    "storage.replace_assets",
    "storage.archive_assets",
    "storage.restore_assets",
    "storage.view_usage",
    "stream.internal",
    "ingestion.view",
    "ingestion.create",
    "ingestion.edit_metadata",
    "ingestion.upload_assets",
    "ingestion.replace_assets",
    "ingestion.review_catalog",
    "ingestion.request_revision",
    "ingestion.approve",
    "ingestion.reject",
    "ingestion.assign_reviewers",
    "ingestion.view_internal_notes",
    "ingestion.view_all_artists",
    "search.internal",
    "search.rights",
    "search.collections.manage",
    "search.synonyms.manage",
    "search.ranking.manage",
    "search.index.manage",
    "search.analytics.view",
    "catalog.view",
    "catalog.manage",
    "tracks.create",
    "tracks.edit",
    "tracks.publish",
    "rights.view",
    "rights.manage",
    "rights.create",
    "rights.edit",
    "rights.verify_master",
    "rights.verify_publishing",
    "rights.verify_samples",
    "rights.manage_parties",
    "rights.manage_documents",
    "rights.manage_contracts",
    "rights.manage_restrictions",
    "rights.manage_territories",
    "rights.create_version",
    "rights.assign_reviewers",
    "artists.view",
    "submissions.view",
    "content.view",
    "audit.view",
    "profile.manage",
    "security.manage",
  ],
  administrator: [
    ...EMAIL_ADMIN_PERMISSIONS,
    ...AUDIT_ADMIN_PERMISSIONS,
    ...EXPIRING_ACCESS_OPERATIONS_PERMISSIONS,
    ...DELIVERY_OPERATIONS_PERMISSIONS,
    ...LICENCE_OPERATIONS_PERMISSIONS,
    "payments.view",
    "payments.create",
    "payments.process",
    "payments.retry",
    "payments.record_manual",
    "payments.reconcile",
    "payments.allocate",
    "payments.view_methods",
    "payments.manage_methods",
    "payments.view_internal_notes",
    "payments.manage_credits",
    "payments.request_refund",
    "payments.approve_refund",
    "payments.issue_refund",
    "payments.manage_disputes",
    "payments.override",
    "payments.view_analytics",
    "invoices.view_licensing",
    "invoices.create_licensing",
    "invoices.edit_licensing",
    "invoices.void_licensing",
    "receipts.view",
    "receipts.generate",
    "contracts.view",
    "contracts.create",
    "contracts.generate",
    "contracts.edit",
    "contracts.manage_clauses",
    "contracts.manage_templates",
    "contracts.request_review",
    "contracts.approve_licensing",
    "contracts.approve_rights",
    "contracts.approve_finance",
    "contracts.approve_legal",
    "contracts.approve_senior",
    "contracts.send",
    "contracts.manage_signers",
    "contracts.resend_signature",
    "contracts.replace_signer",
    "contracts.cancel",
    "contracts.terminate",
    "contracts.create_amendment",
    "contracts.create_renewal",
    "contracts.view_internal_notes",
    "contracts.view_legal_notes",
    "contracts.view_analytics",
    "signatures.sign",
    "signatures.countersign",
    "signatures.view_records",
    "signatures.override",
    "quotes.view",
    "quotes.create",
    "quotes.edit",
    "quotes.request_approval",
    "quotes.approve_licensing",
    "quotes.approve_rights",
    "quotes.approve_finance",
    "quotes.approve_senior",
    "quotes.send",
    "quotes.negotiate",
    "quotes.analytics",
    "quotes.manage_pricing",
    "previews.view",
    "previews.create",
    "previews.configure",
    "previews.generate",
    "previews.review",
    "previews.approve",
    "previews.reject",
    "previews.regenerate",
    "previews.revoke",
    "previews.manage_buyer_specific",
    "previews.manage_policies",
    "previews.manage_voice_profiles",
    "previews.view_sessions",
    "previews.revoke_sessions",
    "previews.view_analytics",
    "previews.override",
    "storage.view",
    "storage.view_public",
    "storage.view_previews",
    "storage.view_masters",
    "storage.view_stems",
    "storage.view_documents",
    "storage.manage_assets",
    "storage.replace_assets",
    "storage.archive_assets",
    "storage.restore_assets",
    "storage.manage_access",
    "storage.revoke_sessions",
    "storage.manage_processing",
    "storage.manage_retention",
    "storage.view_usage",
    "storage.view_access_logs",
    "stream.internal",
    "download.master",
    "download.stems",
    "download.documents",
    "ingestion.view",
    "ingestion.create",
    "ingestion.edit_metadata",
    "ingestion.upload_assets",
    "ingestion.replace_assets",
    "ingestion.review_technical",
    "ingestion.review_catalog",
    "ingestion.request_revision",
    "ingestion.approve",
    "ingestion.reject",
    "ingestion.publish",
    "ingestion.unpublish",
    "ingestion.archive",
    "ingestion.assign_reviewers",
    "ingestion.manage_jobs",
    "ingestion.view_internal_notes",
    "ingestion.view_all_artists",
    "search.internal",
    "search.rights",
    "search.buyers",
    "search.projects",
    "search.saved.manage",
    "search.collections.manage",
    "search.synonyms.manage",
    "search.ranking.manage",
    "search.index.manage",
    "search.analytics.view",
    "catalog.view",
    "catalog.manage",
    "tracks.create",
    "tracks.edit",
    "tracks.publish",
    "rights.view",
    "rights.manage",
    "buyers.view",
    "buyers.verify",
    "quotes.view",
    "quotes.manage",
    "contracts.view",
    "contracts.manage",
    "payments.view",
    "delivery.view",
    "delivery.manage",
    "analytics.view",
    "content.view",
    "content.manage",
    "users.view",
    "audit.view",
    "settings.manage",
    "profile.manage",
    "security.manage",
    "buyers.assign",
    "buyers.request_information",
    "buyers.approve",
    "buyers.reject",
    "buyers.suspend",
    "buyers.reinstate",
    "buyers.manage_reverification",
    "buyers.view_documents",
    "buyers.review_documents",
    "buyers.view_internal_notes",
    "buyers.manage_internal_notes",
    "buyers.manage_risk",
    "buyers.manage_access",
    "memberships.view",
    "memberships.create",
    "memberships.change_plan",
    "memberships.cancel",
    "memberships.pause",
    "memberships.reactivate",
    "billing.view",
    "billing.manage_payment_methods",
    "billing.view_invoices",
    "billing.manage_invoices",
    "billing.record_manual_payment",
    "billing.manage_tax",
    "rights.create",
    "rights.edit",
    "rights.verify_master",
    "rights.verify_publishing",
    "rights.verify_samples",
    "rights.verify_final",
    "rights.manage_parties",
    "rights.manage_documents",
    "rights.manage_contracts",
    "rights.manage_restrictions",
    "rights.manage_territories",
    "rights.manage_disputes",
    "rights.view_internal_notes",
    "rights.view_legal_notes",
    "rights.create_version",
    "rights.assign_reviewers",
    "rights.trigger_reverification",
  ],
  super_administrator: ["*"],
  finance_manager: [
    ...EMAIL_OPERATIONS_PERMISSIONS,
    "email.manage_templates",
    "email.approve_templates",
    ...AUDIT_OPERATIONS_PERMISSIONS,
    "audit.view_finance",
    "audit.export_restricted",
    "expiring_access.view",
    "expiring_access.generate",
    "expiring_access.revoke",
    "expiring_access.view_attempts",
    "temporary_document.generate",
    "temporary_upload.generate",
    "deliveries.view",
    "deliveries.calculate_readiness",
    "deliveries.confirm_payment",
    "deliveries.view_download_history",
    "deliveries.view_analytics",
    "licences.view",
    "licences.approve_finance",
    "licences.view_analytics",
    "payments.view",
    "payments.create",
    "payments.process",
    "payments.retry",
    "payments.record_manual",
    "payments.reconcile",
    "payments.allocate",
    "payments.view_methods",
    "payments.view_internal_notes",
    "payments.manage_credits",
    "payments.request_refund",
    "payments.approve_refund",
    "payments.issue_refund",
    "payments.view_analytics",
    "invoices.view_licensing",
    "invoices.create_licensing",
    "invoices.edit_licensing",
    "invoices.void_licensing",
    "receipts.view",
    "receipts.generate",
    "contracts.view",
    "contracts.approve_finance",
    "contracts.view_analytics",
    "contracts.view_internal_notes",
    "signatures.view_records",
    "quotes.view",
    "quotes.edit",
    "quotes.approve_finance",
    "quotes.analytics",
    "quotes.manage_pricing",
    "billing.view",
    "billing.view_invoices",
    "payments.view",
    "profile.manage",
    "security.manage",
  ],
  media_operations: [
    ...EMAIL_OPERATIONS_PERMISSIONS,
    ...AUDIT_OPERATIONS_PERMISSIONS,
    "expiring_access.view",
    "expiring_access.generate",
    "expiring_access.refresh",
    "expiring_access.revoke",
    "expiring_access.view_attempts",
    "temporary_upload.generate",
    "temporary_download.generate",
    "deliveries.view",
    "deliveries.calculate_readiness",
    "deliveries.manage_assets",
    "deliveries.replace_assets",
    "deliveries.view_download_history",
    "downloads.retry",
    "downloads.revoke_session",
    "manifests.generate",
    "previews.view",
    "previews.create",
    "previews.configure",
    "previews.generate",
    "previews.review",
    "previews.regenerate",
    "previews.view_sessions",
    "previews.view_analytics",
    "storage.view",
    "storage.view_public",
    "storage.view_previews",
    "storage.view_masters",
    "storage.manage_assets",
    "storage.replace_assets",
    "storage.archive_assets",
    "storage.restore_assets",
    "storage.manage_processing",
    "storage.view_usage",
    "storage.view_access_logs",
    "stream.internal",
    "catalog.view",
    "ingestion.view",
    "ingestion.upload_assets",
    "ingestion.replace_assets",
    "ingestion.review_technical",
    "ingestion.manage_jobs",
    "profile.manage",
    "security.manage",
  ],
  legal_reviewer: [
    ...EMAIL_OPERATIONS_PERMISSIONS,
    ...AUDIT_OPERATIONS_PERMISSIONS,
    ...LICENCE_OPERATIONS_PERMISSIONS,
    "contracts.view",
    "contracts.edit",
    "contracts.approve_legal",
    "contracts.view_internal_notes",
    "signatures.view_records",
    "rights.view",
    "rights.view_legal_notes",
    "profile.manage",
    "security.manage",
  ],
  security_administrator: [
    ...EMAIL_ADMIN_PERMISSIONS,
    ...AUDIT_ADMIN_PERMISSIONS,
    ...EXPIRING_ACCESS_OPERATIONS_PERMISSIONS,
    "users.manage",
    "auth.sessions.view",
    "auth.sessions.revoke",
    "profile.manage",
    "security.manage",
  ],
  support_administrator: [
    "email.view",
    "email.view_internal",
    "users.manage",
    "buyers.view",
    "profile.manage",
    "security.manage",
  ],
  privacy_administrator: [
    ...EMAIL_OPERATIONS_PERMISSIONS,
    ...AUDIT_OPERATIONS_PERMISSIONS,
    "privacy.dashboard.view",
    "privacy.requests.view",
    "privacy.requests.create",
    "privacy.requests.review",
    "privacy.requests.assign",
    "privacy.requests.complete",
    "privacy.exports.generate",
    "privacy.exports.download",
    "privacy.deletion.plan",
    "privacy.notices.view",
    "privacy.notices.manage",
    "privacy.consents.view",
    "privacy.consents.manage",
    "privacy.inventory.view",
    "privacy.inventory.manage",
    "privacy.purposes.view",
    "privacy.purposes.manage",
    "privacy.retention.view",
    "privacy.retention.manage",
    "privacy.vendors.view",
    "privacy.vendors.manage",
    "privacy.assessments.view",
    "privacy.assessments.manage",
    "privacy.analytics.view",
    "profile.manage",
    "security.manage",
  ],
  senior_approver: [
    ...EMAIL_OPERATIONS_PERMISSIONS,
    ...AUDIT_OPERATIONS_PERMISSIONS,
    ...DELIVERY_OPERATIONS_PERMISSIONS,
    ...LICENCE_OPERATIONS_PERMISSIONS,
    "quotes.view",
    "quotes.approve_licensing",
    "quotes.approve_finance",
    "contracts.view",
    "contracts.approve_licensing",
    "payments.view",
    "payments.approve_refund",
    "profile.manage",
    "security.manage",
  ],
};

export const ORGANIZATIONS = [
  { id: "org-northstar", name: "Northstar Pictures", type: "Studio" },
  { id: "org-smyrk", name: "The SMYRK", type: "Artist / Rightsholder" },
  { id: "org-beatmondo", name: "beatmondo", type: "Platform" },
  { id: "org-brightframe", name: "BrightFrame Agency", type: "Agency" },
  { id: "org-samplemedia", name: "Sample Media", type: "Production company" },
  {
    id: "org-lighthouse",
    name: "Lighthouse Creative",
    type: "Independent professional",
  },
  {
    id: "org-independent",
    name: "Self-employed",
    type: "Independent professional",
  },
  { id: "org-orbit", name: "Orbit Trailers", type: "Trailer house" },
];

const defaultSessions = (userId) => [
  {
    id: `${userId}-current`,
    device: "MacBook Pro",
    browser: "Codex Browser",
    location: "India",
    lastActive: "Now",
    current: true,
    trusted: false,
  },
  {
    id: `${userId}-windows`,
    device: "Windows workstation",
    browser: "Chrome",
    location: "New York",
    lastActive: "2 days ago",
    current: false,
    trusted: false,
  },
  {
    id: `${userId}-iphone`,
    device: "iPhone",
    browser: "Safari",
    location: "Los Angeles",
    lastActive: "6 days ago",
    current: false,
    trusted: true,
  },
];

const baseUser = {
  phone: "",
  country: "United States",
  website: "",
  bio: "",
  notificationPreferences: {
    security: true,
    licensing: true,
    editorial: false,
  },
  failedLoginAttempts: 0,
  lockedUntil: null,
  trustedDevices: [],
  securityFlags: [],
  createdAt: "2026-07-01T09:00:00.000Z",
};

export const DEFAULT_USERS = [
  {
    ...baseUser,
    id: "user-olivia",
    name: "Olivia Bennett",
    email: "olivia@northstarpictures.com",
    password: "Beatmondo@123",
    avatar: "OB",
    organizationId: "org-northstar",
    organization: "Northstar Pictures",
    jobTitle: "Senior Music Supervisor",
    userType: "buyer",
    role: "vip_buyer",
    roleLabel: "VIP Buyer",
    permissions: ROLE_PERMISSIONS.vip_buyer,
    accountStatus: "active",
    emailVerified: true,
    verificationStatus: "approved",
    membershipTier: "VIP Sync Access",
    mfaEnabled: false,
    profileCompletion: 100,
    preApprovedTerms: true,
    lastLoginAt: "2026-07-15T17:42:00.000Z",
  },
  {
    ...baseUser,
    id: "user-marcus",
    name: "Marcus Hale",
    email: "marcus@thesmyrk.com",
    password: "Artist@123",
    avatar: "MH",
    organizationId: "org-smyrk",
    organization: "The SMYRK",
    jobTitle: "Artist Representative",
    userType: "artist",
    role: "artist",
    roleLabel: "Artist / Rightsholder",
    permissions: ROLE_PERMISSIONS.artist,
    accountStatus: "active",
    emailVerified: true,
    verificationStatus: "approved",
    membershipTier: "Artist Workspace",
    mfaEnabled: false,
    profileCompletion: 85,
    submissionAccess: true,
    lastLoginAt: "2026-07-14T12:18:00.000Z",
  },
  {
    ...baseUser,
    id: "user-preston",
    name: "Preston Repenning",
    email: "admin@beatmondo.com",
    password: "Admin@123",
    avatar: "PR",
    organizationId: "org-beatmondo",
    organization: "beatmondo",
    jobTitle: "Platform Administrator",
    userType: "internal",
    role: "super_administrator",
    roleLabel: "Super Administrator",
    permissions: ROLE_PERMISSIONS.super_administrator,
    accountStatus: "active",
    emailVerified: true,
    verificationStatus: "approved",
    membershipTier: "Internal",
    mfaEnabled: true,
    profileCompletion: 100,
    lastLoginAt: "2026-07-16T08:30:00.000Z",
  },
  {
    ...baseUser,
    id: "user-jordan",
    name: "Jordan Lee",
    email: "jordan@beatmondo.com",
    password: "Catalog@123",
    avatar: "JL",
    organizationId: "org-beatmondo",
    organization: "beatmondo",
    jobTitle: "Catalog Operations Manager",
    userType: "internal",
    role: "catalog_manager",
    roleLabel: "Catalog Manager",
    permissions: ROLE_PERMISSIONS.catalog_manager,
    accountStatus: "active",
    emailVerified: true,
    verificationStatus: "approved",
    membershipTier: "Internal",
    mfaEnabled: false,
    profileCompletion: 100,
  },
  {
    ...baseUser,
    id: "user-amelia",
    name: "Amelia Grant",
    email: "amelia@beatmondo.com",
    password: "Rights@123",
    avatar: "AG",
    organizationId: "org-beatmondo",
    organization: "beatmondo",
    jobTitle: "Rights and Compliance Manager",
    userType: "internal",
    role: "licensing_manager",
    roleLabel: "Rights Manager",
    permissions: ROLE_PERMISSIONS.licensing_manager,
    accountStatus: "active",
    emailVerified: true,
    verificationStatus: "approved",
    membershipTier: "Internal",
    mfaEnabled: false,
    profileCompletion: 100,
  },
  {
    ...baseUser,
    id: "user-noah",
    name: "Noah Pierce",
    email: "noah@beatmondo.com",
    password: "Media@123",
    avatar: "NP",
    organizationId: "org-beatmondo",
    organization: "beatmondo",
    jobTitle: "Media Operations",
    userType: "internal",
    role: "media_operations",
    roleLabel: "Media Operations",
    permissions: ROLE_PERMISSIONS.media_operations,
    accountStatus: "active",
    emailVerified: true,
    verificationStatus: "approved",
    membershipTier: "Internal",
    mfaEnabled: false,
    profileCompletion: 100,
  },
  {
    ...baseUser,
    id: "user-finance",
    name: "Nadia Foster",
    email: "finance@beatmondo.com",
    password: "Finance@123",
    avatar: "NF",
    organizationId: "org-beatmondo",
    organization: "beatmondo",
    jobTitle: "Commercial Finance Manager",
    userType: "internal",
    role: "finance_manager",
    roleLabel: "Finance Manager",
    permissions: ROLE_PERMISSIONS.finance_manager,
    accountStatus: "active",
    emailVerified: true,
    verificationStatus: "approved",
    membershipTier: "Internal",
    mfaEnabled: false,
    profileCompletion: 100,
  },
  {
    ...baseUser,
    id: "user-ethan",
    name: "Ethan Cole",
    email: "ethan@brightframeagency.com",
    password: "Buyer@123",
    avatar: "EC",
    organizationId: "org-brightframe",
    organization: "BrightFrame Agency",
    jobTitle: "Creative Producer",
    userType: "buyer",
    role: "discovery_buyer",
    roleLabel: "Discovery Buyer",
    permissions: ROLE_PERMISSIONS.discovery_buyer,
    accountStatus: "active",
    emailVerified: true,
    verificationStatus: "under_review",
    membershipTier: "Discovery Access",
    mfaEnabled: false,
    profileCompletion: 70,
    preApprovedTerms: false,
    lastLoginAt: "2026-07-12T15:04:00.000Z",
  },
  {
    ...baseUser,
    id: "user-laura",
    name: "Laura Reed",
    email: "laura@samplemedia.com",
    password: "Suspended@123",
    avatar: "LR",
    organizationId: "org-samplemedia",
    organization: "Sample Media",
    jobTitle: "Producer",
    userType: "buyer",
    role: "professional_buyer",
    roleLabel: "Professional Buyer",
    permissions: ROLE_PERMISSIONS.professional_buyer,
    accountStatus: "suspended",
    suspensionReason: "Account review required",
    emailVerified: true,
    verificationStatus: "approved",
    membershipTier: "Professional Buyer",
    mfaEnabled: false,
    profileCompletion: 90,
    lastLoginAt: "2026-06-28T11:25:00.000Z",
  },
  {
    ...baseUser,
    id: "user-sofia",
    name: "Sofia Martinez",
    email: "sofia@lighthousecreative.co",
    password: "Sofia@123",
    avatar: "SM",
    organizationId: "org-lighthouse",
    organization: "Lighthouse Creative",
    jobTitle: "Freelance Music Supervisor",
    userType: "buyer",
    role: "professional_buyer",
    roleLabel: "Professional Buyer",
    permissions: ROLE_PERMISSIONS.professional_buyer,
    accountStatus: "active",
    emailVerified: true,
    verificationStatus: "additional_information_required",
    membershipTier: "Professional Buyer",
    mfaEnabled: false,
    profileCompletion: 78,
    preApprovedTerms: false,
    lastLoginAt: "2026-07-15T10:12:00.000Z",
  },
  {
    ...baseUser,
    id: "user-daniel",
    name: "Daniel Brooks",
    email: "daniel@independentmail.com",
    password: "Daniel@123",
    avatar: "DB",
    organizationId: "org-independent",
    organization: "Self-employed",
    jobTitle: "Content Creator",
    userType: "buyer",
    role: "discovery_buyer",
    roleLabel: "Discovery Buyer",
    permissions: ROLE_PERMISSIONS.discovery_buyer,
    accountStatus: "active",
    emailVerified: true,
    verificationStatus: "rejected",
    membershipTier: "Professional Buyer",
    mfaEnabled: false,
    profileCompletion: 66,
    preApprovedTerms: false,
    lastLoginAt: "2026-07-08T14:06:00.000Z",
  },
  {
    ...baseUser,
    id: "user-rachel",
    name: "Rachel Kim",
    email: "rachel@orbittrailers.com",
    password: "Rachel@123",
    avatar: "RK",
    organizationId: "org-orbit",
    organization: "Orbit Trailers",
    jobTitle: "Music Coordinator",
    userType: "buyer",
    role: "professional_buyer",
    roleLabel: "Professional Buyer",
    permissions: ROLE_PERMISSIONS.professional_buyer,
    accountStatus: "active",
    emailVerified: true,
    verificationStatus: "suspended",
    membershipTier: "Professional Buyer",
    mfaEnabled: false,
    profileCompletion: 92,
    preApprovedTerms: false,
    lastLoginAt: "2026-07-09T16:40:00.000Z",
    securityFlags: ["verification-suspended"],
  },
  {
    ...baseUser,
    id: "user-privacy",
    name: "Priya Nair",
    email: "privacy@beatmondo.com",
    password: "Privacy@123",
    avatar: "PN",
    organizationId: "org-beatmondo",
    organization: "beatmondo",
    jobTitle: "Privacy Administrator",
    userType: "internal",
    role: "privacy_administrator",
    roleLabel: "Privacy Administrator",
    permissions: ROLE_PERMISSIONS.privacy_administrator,
    accountStatus: "active",
    emailVerified: true,
    verificationStatus: "approved",
    membershipTier: "Internal",
    mfaEnabled: true,
    profileCompletion: 100,
    lastLoginAt: "2026-07-15T08:30:00.000Z",
  },
  {
    ...baseUser,
    id: "user-legal",
    name: "Eleanor Shaw",
    email: "legal@beatmondo.com",
    password: "Legal@123",
    avatar: "ES",
    organizationId: "org-beatmondo",
    organization: "beatmondo",
    jobTitle: "Legal Reviewer",
    userType: "internal",
    role: "legal_reviewer",
    roleLabel: "Legal Reviewer",
    permissions: ROLE_PERMISSIONS.legal_reviewer,
    accountStatus: "active",
    emailVerified: true,
    verificationStatus: "approved",
    membershipTier: "Internal",
    mfaEnabled: true,
    profileCompletion: 100,
    lastLoginAt: "2026-07-11T12:00:00.000Z",
  },
  {
    ...baseUser,
    id: "user-security",
    name: "Aman Verma",
    email: "security@beatmondo.com",
    password: "Security@123",
    avatar: "AV",
    organizationId: "org-beatmondo",
    organization: "beatmondo",
    jobTitle: "Security Administrator",
    userType: "internal",
    role: "security_administrator",
    roleLabel: "Security Administrator",
    permissions: ROLE_PERMISSIONS.security_administrator,
    accountStatus: "active",
    emailVerified: true,
    verificationStatus: "approved",
    membershipTier: "Internal",
    mfaEnabled: true,
    profileCompletion: 100,
    lastLoginAt: "2026-07-16T07:45:00.000Z",
  },

  {
    ...baseUser,
    id: "user-operations",
    name: "Sam Okonkwo",
    email: "operations@beatmondo.com",
    password: "Operations@123",
    avatar: "SO",
    organizationId: "org-beatmondo",
    organization: "beatmondo",
    jobTitle: "Platform Operations Lead",
    userType: "internal",
    role: "administrator",
    roleLabel: "Platform Administrator",
    permissions: ROLE_PERMISSIONS.administrator,
    accountStatus: "active",
    emailVerified: true,
    verificationStatus: "approved",
    membershipTier: "Internal",
    mfaEnabled: false,
    profileCompletion: 100,
    lastLoginAt: "2026-07-16T09:15:00.000Z",
  },
  {
    ...baseUser,
    id: "user-support",
    name: "Casey Nguyen",
    email: "support@beatmondo.com",
    password: "Support@123",
    avatar: "CN",
    organizationId: "org-beatmondo",
    organization: "beatmondo",
    jobTitle: "Support Administrator",
    userType: "internal",
    role: "support_administrator",
    roleLabel: "Support Administrator",
    permissions: ROLE_PERMISSIONS.support_administrator,
    accountStatus: "active",
    emailVerified: true,
    verificationStatus: "approved",
    membershipTier: "Internal",
    mfaEnabled: false,
    profileCompletion: 100,
    lastLoginAt: "2026-07-15T14:20:00.000Z",
  },

];

export const DEMO_ACCOUNTS = [
  {
    id: "vip",
    label: "VIP Buyer — Olivia Bennett",
    email: "olivia@northstarpictures.com",
    password: "Beatmondo@123",
    destination: "Buyer Dashboard",
  },
  {
    id: "artist",
    label: "Artist — Marcus Hale",
    email: "marcus@thesmyrk.com",
    password: "Artist@123",
    destination: "Artist Dashboard",
  },
  {
    id: "admin",
    label: "Super Admin — Preston (MFA 246810)",
    email: "admin@beatmondo.com",
    password: "Admin@123",
    destination: "Admin + MFA",
  },
  {
    id: "catalog",
    label: "Catalog Manager — Jordan Lee",
    email: "jordan@beatmondo.com",
    password: "Catalog@123",
    destination: "Admin",
  },
  {
    id: "rights",
    label: "Rights Manager — Amelia Grant",
    email: "amelia@beatmondo.com",
    password: "Rights@123",
    destination: "Admin",
  },
  {
    id: "media",
    label: "Media Ops — Noah Pierce",
    email: "noah@beatmondo.com",
    password: "Media@123",
    destination: "Admin",
  },
  {
    id: "finance",
    label: "Finance — Nadia Foster",
    email: "finance@beatmondo.com",
    password: "Finance@123",
    destination: "Admin",
  },
  {
    id: "legal",
    label: "Legal — Eleanor Shaw (MFA 246810)",
    email: "legal@beatmondo.com",
    password: "Legal@123",
    destination: "Admin + MFA",
  },
  {
    id: "security",
    label: "Security — Aman Verma (MFA 246810)",
    email: "security@beatmondo.com",
    password: "Security@123",
    destination: "Admin + MFA",
  },
  {
    id: "privacy",
    label: "Privacy — Priya Nair (MFA 246810)",
    email: "privacy@beatmondo.com",
    password: "Privacy@123",
    destination: "Admin + MFA",
  },
  {
    id: "operations",
    label: "Platform Ops — Sam Okonkwo",
    email: "operations@beatmondo.com",
    password: "Operations@123",
    destination: "Admin",
  },
  {
    id: "support",
    label: "Support — Casey Nguyen",
    email: "support@beatmondo.com",
    password: "Support@123",
    destination: "Admin",
  },
  {
    id: "pending",
    label: "Discovery Buyer — Ethan Cole",
    email: "ethan@brightframeagency.com",
    password: "Buyer@123",
    destination: "Limited Buyer Dashboard",
  },
  {
    id: "information",
    label: "Pro Buyer / Info Required — Sofia",
    email: "sofia@lighthousecreative.co",
    password: "Sofia@123",
    destination: "Verification Response",
  },
  {
    id: "rejected",
    label: "Rejected / Cancelling — Daniel",
    email: "daniel@independentmail.com",
    password: "Daniel@123",
    destination: "Limited Buyer Dashboard",
  },
  {
    id: "verification-suspended",
    label: "Verification Suspended — Rachel",
    email: "rachel@orbittrailers.com",
    password: "Rachel@123",
    destination: "Limited Buyer Dashboard",
  },
  {
    id: "account-suspended",
    label: "Account Suspended — Laura Reed",
    email: "laura@samplemedia.com",
    password: "Suspended@123",
    destination: "Account Suspended",
  },
];

export const DEFAULT_AUTH_STATE = {
  version: 1,
  users: DEFAULT_USERS,
  organizations: ORGANIZATIONS,
  sessions: DEFAULT_USERS.flatMap((user) => defaultSessions(user.id)),
  resetTokens: [],
  verificationTokens: [],
  loginHistory: [],
  securityEvents: [
    {
      id: "event-seed-1",
      type: "security.baseline",
      userId: "user-preston",
      timestamp: "2026-07-16T08:30:00.000Z",
      device: "MacBook Pro",
      location: "India",
      status: "success",
      description: "Authentication demo data initialized.",
    },
  ],
  messages: [
    {
      id: "message-welcome",
      userId: "user-olivia",
      type: "security",
      title: "New login detected",
      body: "A new browser session was created for your beatmondo workspace.",
      createdAt: "2026-07-15T17:42:00.000Z",
      read: false,
      action: "security",
    },
    {
      id: "message-delivery",
      userId: "user-olivia",
      type: "licensing",
      title: "Secure delivery approved",
      body: "A protected WAV master is ready in your buyer workspace.",
      createdAt: "2026-07-15T14:10:00.000Z",
      read: false,
      action: "buyer",
    },
    {
      id: "message-rights",
      userId: "user-marcus",
      type: "artist",
      title: "Rights document requested",
      body: "The catalog team requested one additional ownership document for The End of Jason Todd.",
      createdAt: "2026-07-14T09:20:00.000Z",
      read: false,
      action: "artist-dashboard",
    },
  ],
};

export const defaultDestinationFor = (user) => {
  if (!user) return "home";
  if (user.role === "artist") return "artist-dashboard";
  if (
    [
      "licensing_manager",
      "catalog_manager",
      "media_operations",
      "finance_manager",
      "privacy_administrator",
      "legal_reviewer",
      "security_administrator",
      "support_administrator",
      "senior_approver",
      "administrator",
      "super_administrator",
    ].includes(user.role)
  )
    return "admin";
  return "buyer";
};

export const roleHasPermission = (user, permission) =>
  Boolean(
    user?.permissions?.includes("*") || user?.permissions?.includes(permission),
  );
